Repository elastic/eui, pull requests merged in 2018-02, with the labels that each got.

#375 Horizontal & Complex Steps
  CHANGELOG.md
  src-docs/src/views/steps/steps.js
  src-docs/src/views/steps/steps_complex.js
  src-docs/src/views/steps/steps_example.js
  src-docs/src/views/steps/steps_horizontal.js
  src/components/index.js
  src/components/steps/__snapshots__/steps_horizontal.test.js.snap
  src/components/steps/__snapshots__/sub_steps.test.js.snap
  src/components/steps/_index.scss
  src/components/steps/_steps.scss
  src/components/steps/_steps_horizontal.scss
  src/components/steps/_sub_steps.scss
  src/components/steps/index.js
  src/components/steps/step_horizontal.js
  src/components/steps/steps_horizontal.js
  src/components/steps/steps_horizontal.test.js
  src/components/steps/sub_steps.js
  src/components/steps/sub_steps.test.js
  src/global_styling/mixins/_index.scss
  src/global_styling/mixins/_states.scss
  src/global_styling/mixins/_typography.scss
Labels: feature request

#380 Slimmer pagination look / feel
  CHANGELOG.md
  src-docs/src/views/pagination/compressed.js
  src-docs/src/views/pagination/pagination_example.js
  src/components/button/button_empty/_button_empty.scss
  src/components/index.js
  src/components/pagination/__snapshots__/pagination.test.js.snap
  src/components/pagination/__snapshots__/pagination_button.test.js.snap
  src/components/pagination/_pagination_button.scss
  src/components/pagination/index.js
  src/components/pagination/pagination.js
  src/components/pagination/pagination_button.js
  src/components/table/table_pagination/__snapshots__/table_pagination.test.js.snap
Labels: style only, work in progress

#387 Better docs for our various tables
  CHANGELOG.md
  src-docs/src/routes.js
  src-docs/src/views/basic_table/basic/basic_section.js
  src-docs/src/views/basic_table/basic_table_example.js
  src-docs/src/views/partials.js
  src-docs/src/views/table/table_example.js
  src-docs/src/views/table_of_records/table_of_records_example.js
  src-docs/src/views/tables/actions/actions.js
  src-docs/src/views/tables/actions/actions_section.js
  src-docs/src/views/tables/actions/index.js
  src-docs/src/views/tables/basic/basic.js
  src-docs/src/views/tables/basic/basic_section.js
  src-docs/src/views/tables/basic/index.js
  src-docs/src/views/tables/basic/props_info.js
  src-docs/src/views/tables/custom/compressed.js
  src-docs/src/views/tables/custom/custom.js
  src-docs/src/views/tables/custom/custom_section.js
  src-docs/src/views/tables/custom/index.js
  src-docs/src/views/tables/data_store.js
  src-docs/src/views/tables/paginated/index.js
  src-docs/src/views/tables/paginated/paginated.js
  src-docs/src/views/tables/paginated/paginated_section.js
  src-docs/src/views/tables/selection/index.js
  src-docs/src/views/tables/selection/selection.js
  src-docs/src/views/tables/selection/selection_section.js
  src-docs/src/views/tables/sorting/index.js
  src-docs/src/views/tables/sorting/sorting.js
  src-docs/src/views/tables/sorting/sorting_section.js
  src-docs/src/views/tables/tables_example.js
  src-docs/src/views/text/text.js
  src/components/text/_text.scss
Labels: chore, documentation

#391 Adding `readOnly` prop styles to form inputs
  CHANGELOG.md
  src-docs/src/views/form/form_controls_readonly.js
  src-docs/src/views/form/form_example.js
  src/components/form/_index.scss
Labels: style only

#385 EuiCards
  CHANGELOG.md
  src-docs/src/routes.js
  src-docs/src/views/card/card.js
  src-docs/src/views/card/card_example.js
  src-docs/src/views/card/card_footer.js
  src-docs/src/views/card/card_image.js
  src-docs/src/views/panel/panel_example.js
  src-docs/src/views/panel/panel_hover.js
  src/components/card/__snapshots__/card.test.js.snap
  src/components/card/_card.scss
  src/components/card/_index.scss
  src/components/card/card.js
  src/components/card/card.test.js
  src/components/card/index.js
  src/components/index.js
  src/components/index.scss
  src/components/panel/_panel.scss
  src/components/panel/panel.js
Labels: feature request

#381 Bolder, smaller badges with onclick events and custom colors
  CHANGELOG.md
  src-docs/src/views/badge/badge.js
  src-docs/src/views/badge/badge_button.js
  src-docs/src/views/badge/badge_example.js
  src-docs/src/views/badge/badge_with_icon.js
  src/components/badge/__snapshots__/badge.test.js.snap
  src/components/badge/_badge.scss
  src/components/badge/badge.js
  src/global_styling/variables/_colors.scss
  src/services/color/hex_to_rgb.js
  src/services/color/index.js
Labels: style only

#396 Using tintOrShade for subStep background color
  CHANGELOG.md
  src/components/steps/_sub_steps.scss
Labels: style only

#404 Reorder selectors to fix fixed progress bar in Firefox
  CHANGELOG.md
  src/components/progress/_progress.scss
Labels: style only

#407 New Radio & Checkbox styles
  CHANGELOG.md
  src/components/accessibility/_screen_reader.scss
  src/components/form/_index.scss
  src/components/form/checkbox/__snapshots__/checkbox.test.js.snap
  src/components/form/checkbox/_checkbox.scss
  src/components/form/checkbox/_index.scss
  src/components/form/checkbox/checkbox.js
  src/components/form/radio/__snapshots__/radio.test.js.snap
  src/components/form/radio/__snapshots__/radio_group.test.js.snap
  src/components/form/radio/_index.scss
  src/components/form/radio/_radio.scss
  src/components/form/radio/radio.js
  src/components/form/range/_index.scss
  src/components/form/range/_range.scss
  src/components/form/switch/_index.scss
  src/components/form/switch/_switch.scss
  src/global_styling/mixins/_helpers.scss
  src/global_styling/mixins/_icons.scss
  src/global_styling/mixins/_index.scss
  src/global_styling/mixins/_states.scss
Labels: style only

#402 Filepicker form element
  CHANGELOG.md
  src-docs/src/routes.js
  src-docs/src/views/file_picker/file_picker.js
  src-docs/src/views/file_picker/file_picker_example.js
  src-docs/src/views/form/disabled.js
  src-docs/src/views/form/form_controls.js
  src-docs/src/views/form/form_rows.js
  src/components/form/_index.scss
  src/components/form/file_picker/__snapshots__/file_picker.test.js.snap
  src/components/form/file_picker/_file_picker.scss
  src/components/form/file_picker/_index.scss
  src/components/form/file_picker/file_picker.js
  src/components/form/file_picker/file_picker.test.js
  src/components/form/file_picker/index.js
  src/components/form/index.js
  src/components/index.js
Labels: feature request

#436 Fix error stemming from `selected` prop on `EuiSelect`
  CHANGELOG.md
  src-docs/src/views/form/form_rows.js
  src/components/form/select/select.js
Labels: bug
