Repository elastic/eui, pull requests merged in 2018-04, with the labels that each got.

#608 Apply more specificity to fix disabled states
  src/components/button/_button.scss
Labels: bug, style only

#611 Update EuiComboBox to match options list width to the input width.
  CHANGELOG.md
  src/components/combo_box/combo_box.js
  src/components/combo_box/combo_box_options_list/combo_box_options_list.js
Labels: bug

#626 Add guidelines and fix inconsistencies in Callout
  src-docs/src/views/call_out/call_out_example.js
Labels: documentation

#642 Export scss vars as json during compilation
  CHANGELOG.md
  package.json
  scripts/compile-scss.js
  src/components/key_pad_menu/_index.scss
  src/index.d.ts
  src/themes/index.d.ts
  wiki/consuming.md
  yarn.lock
Labels: platform

#644 Feature/datepicker
  CHANGELOG.md
  package.json
  src-docs/src/components/guide_components.scss
  src-docs/src/routes.js
  src-docs/src/views/date_picker/classes.js
  src-docs/src/views/date_picker/custom_input.js
  src-docs/src/views/date_picker/date_picker.js
  src-docs/src/views/date_picker/date_picker_example.js
  src-docs/src/views/date_picker/inline.js
  src-docs/src/views/date_picker/locale.js
  src-docs/src/views/date_picker/min_max.js
  src-docs/src/views/date_picker/open_to_date.js
  src-docs/src/views/date_picker/range.js
  src-docs/src/views/date_picker/states.js
  src-docs/src/views/date_picker/time_select.js
  src-docs/src/views/date_picker/utc.js
  src/components/date_picker/__snapshots__/date_picker.test.js.snap
  src/components/date_picker/_date_picker.scss
  src/components/date_picker/_index.scss
  src/components/date_picker/date_picker.js
  src/components/date_picker/date_picker.test.js
  src/components/date_picker/index.js
  src/components/form/field_text/_field_text.scss
  src/components/index.js
  src/components/index.scss
  src/global_styling/mixins/_shadow.scss
  yarn.lock
Labels: feature request

#673 Step status props
  CHANGELOG.md
  src-docs/src/views/steps/status.js
  src-docs/src/views/steps/steps_example.js
  src/components/index.js
  src/components/steps/__snapshots__/step.test.js.snap
  src/components/steps/__snapshots__/steps.test.js.snap
  src/components/steps/_steps.scss
  src/components/steps/index.js
  src/components/steps/step.js
  src/components/steps/steps.js
Labels: feature request

#701 Adds paddingSize prop to EuiAccordion
  CHANGELOG.md
  src-docs/src/views/accordion/accordion.js
  src-docs/src/views/accordion/accordion_example.js
  src-docs/src/views/accordion/accordion_extra.js
  src-docs/src/views/accordion/accordion_form.js
  src-docs/src/views/accordion/accordion_grow.js
  src-docs/src/views/accordion/accordion_open.js
  src/components/accordion/__snapshots__/accordion.test.js.snap
  src/components/accordion/_accordion.scss
  src/components/accordion/_accordion_form.scss
  src/components/accordion/accordion.js
Labels: bug

#702 Fix inherited line-height of inputs
  CHANGELOG.md
  src/global_styling/reset/_reset.scss
Labels: bug

#703 Reduced EuiToast title to “xs” title size
  CHANGELOG.md
  src/components/toast/_toast.scss
Labels: style only

#704 Card theme title parity and margin fix
  CHANGELOG.md
  src/components/card/__snapshots__/card.test.js.snap
  src/components/card/_card.scss
  src/components/card/card.js
Labels: bug, style only
