Repository elastic/eui, pull requests merged in 2018-09, with the labels that each got.

#1163 fix EuiToolTip from setting state on unmounted component
  CHANGELOG.md
  src/components/tool_tip/tool_tip.js
Labels: bug

#1181 Accessibility/tables
  CHANGELOG.md
  src/components/basic_table/__snapshots__/basic_table.test.js.snap
  src/components/basic_table/__snapshots__/in_memory_table.test.js.snap
  src/components/basic_table/basic_table.js
  src/components/search_bar/search_box.js
Labels: accessibility

#1190 IE11 doesn't support document.contains()
  CHANGELOG.md
  src/components/tool_tip/tool_tip.js
Labels: bug

#1188 Another fixer PR
  CHANGELOG.md
  src-docs/src/views/bottom_bar/bottom_bar.js
  src-docs/src/views/icon/icons.js
  src/components/form/_mixins.scss
  src/components/icon/__snapshots__/icon.test.js.snap
  src/components/icon/assets/tag.svg
  src/components/icon/icon.js
  src/components/icon/index.d.ts
  src/components/modal/_modal.scss
  src/components/modal/confirm_modal.js
  src/components/modal/index.d.ts
  src/global_styling/mixins/_helpers.scss
  src/global_styling/mixins/_states.scss
  src/global_styling/mixins/_typography.scss
  src/global_styling/utility/_animations.scss
  src/global_styling/utility/_index.scss
  src/global_styling/variables/_animations.scss
  src/global_styling/variables/_z_index.scss
Labels: style only

#1192 Fix combobox list z-index
  CHANGELOG.md
  src/components/combo_box/_combo_box.scss
  src/components/combo_box/combo_box_options_list/_combo_box_options_list.scss
  src/global_styling/variables/_z_index.scss
Labels: bug, style only

#1196 Add direction prop for EuiFlexGroup typing
  CHANGELOG.md
  src/components/flex/flex_group.js
  src/components/flex/index.d.ts
Labels: typescript

#1206 Make EuiBasicTable rows keyboard-accessible when they are clickable.
  CHANGELOG.md
  src/components/basic_table/__snapshots__/basic_table.test.js.snap
  src/components/basic_table/basic_table.js
  src/components/flex/_flex_item.scss
  src/components/table/_table.scss
  src/components/table/_variables.scss
  src/components/table/table_row.js
Labels: accessibility

#1213 Use pointer cursor when a EuiTable row is clickable.
  CHANGELOG.md
  src/components/table/_table.scss
Labels: chore

#1215 Add lockOpoen icon
  CHANGELOG.md
  src-docs/src/views/icon/icons.js
  src/components/icon/__snapshots__/icon.test.js.snap
  src/components/icon/assets/lock.svg
  src/components/icon/assets/lockOpen.svg
  src/components/icon/icon.js
  src/components/icon/index.d.ts
Labels: assign:designer
