Repository elastic/eui, pull requests merged in 2018-12, with the labels that each got.

#1344 Add props to EuiFormRowProps
  src/components/form/form_row/index.d.ts
Labels: typescript

#1346 Better breadcrumb truncation
  CHANGELOG.md
  src-docs/src/views/breadcrumbs/breadcrumbs_example.js
  src-docs/src/views/breadcrumbs/responsive.js
  src-docs/src/views/breadcrumbs/truncate.js
  src-docs/src/views/header/header.js
  src/components/breadcrumbs/__snapshots__/breadcrumbs.test.js.snap
  src/components/breadcrumbs/_breadcrumbs.scss
  src/components/breadcrumbs/_index.scss
  src/components/breadcrumbs/_variables.scss
  src/components/breadcrumbs/breadcrumbs.js
  src/components/breadcrumbs/breadcrumbs.test.js
  src/components/breadcrumbs/max.js
  src/components/header/header_breadcrumbs/_header_breadcrumbs.scss
  src/components/header/header_breadcrumbs/header_breadcrumbs.js
  src/components/header/header_section/__snapshots__/header_section.test.js.snap
  src/components/header/header_section/_header_section.scss
  src/components/header/header_section/header_section.js
  src/components/header/header_section/header_section.test.js
Labels: design decision

#1353 `EuiComboBox` converts entered text into a custom option on blur
  CHANGELOG.md
  src/components/combo_box/combo_box.js
Labels: feature request

#1355 Convert EuiIcon to TypeScript
  CHANGELOG.md
  package.json
  src/components/badge/index.d.ts
  src/components/button/index.d.ts
  src/components/call_out/index.d.ts
  src/components/common.ts
  src/components/empty_prompt/index.d.ts
  src/components/form/field_number/index.d.ts
  src/components/health/index.d.ts
  src/components/icon/__snapshots__/icon.test.tsx.snap
  src/components/icon/icon.test.tsx
  src/components/icon/icon.tsx
  src/components/icon/index.d.ts
  src/components/icon/index.ts
  src/components/index.d.ts
  src/components/key_pad_menu/index.d.ts
  src/components/table/index.d.ts
  src/components/toast/index.d.ts
  src/components/token/index.d.ts
  src/custom_typings/index.d.ts
  tsconfig.json
Labels: icons, typescript

#1363 Revert combobox onblur pill creation in #1353
  CHANGELOG.md
  src/components/combo_box/combo_box.js
Labels: bug

#1369 fix EuiSuperSelect from accessing ref when unmounted
  CHANGELOG.md
  src/components/form/super_select/super_select.js
Labels: bug

#1368 Convert EuiExpression to TS
  CHANGELOG.md
  scripts/babel/proptypes-from-ts-props/index.js
  scripts/babel/proptypes-from-ts-props/index.test.js
  src-docs/src/views/card/card_beta.js
  src-docs/src/views/expression/colors.tsx
  src-docs/src/views/expression/expression.js
  src-docs/src/views/expression/expression_example.js
  src-docs/src/views/expression/stringing.tsx
  src/components/common.ts
  src/components/expression/__snapshots__/expression.test.js.snap
  src/components/expression/__snapshots__/expression.test.tsx.snap
  src/components/expression/__snapshots__/expression_button.test.js.snap
  src/components/expression/_expression.scss
  src/components/expression/_index.scss
  src/components/expression/_variables.scss
  src/components/expression/expression.js
  src/components/expression/expression.test.js
  src/components/expression/expression.test.tsx
  src/components/expression/expression.tsx
  src/components/expression/expression_button.js
  src/components/expression/expression_button.test.js
  src/components/expression/index.js
  src/components/expression/index.ts
  src/components/index.js
Labels: breaking change, typescript

#1395 Exclude `custom_typings` from `eui.d.ts`
  CHANGELOG.md
  scripts/dtsgenerator.js
Labels: typescript
