Repository elastic/eui, pull requests merged in 2018-07, with the labels that each got.

#932 More sliders
  CHANGELOG.md
  src-docs/src/views/form_controls/form_controls_example.js
  src-docs/src/views/form_controls/range.js
  src/components/button/_button.scss
  src/components/form/range/__snapshots__/range.test.js.snap
  src/components/form/range/_index.scss
  src/components/form/range/_mixins.scss
  src/components/form/range/_range.scss
  src/components/form/range/_variables.scss
  src/components/form/range/range.js
  src/components/form/range/range.test.js
  src/global_styling/mixins/_shadow.scss
Labels: feature request

#962 Added word-break fallback for FF & IE in table cell
  CHANGELOG.md
  src/components/table/_table.scss
Labels: bug

#989 Fixed euiScrollBar
  CHANGELOG.md
  src-docs/src/components/guide_components.scss
  src/global_styling/mixins/_helpers.scss
Labels: style only

#988 Add typings for keyCodes
  CHANGELOG.md
  src/services/index.d.ts
  src/services/key_codes.d.ts
Labels: typescript

#1017 Make the `Omit` type compatible with TS 2.9+
  CHANGELOG.md
  src/components/common.d.ts
Labels: typescript

#779 Make switch use a random id if none is provided
  CHANGELOG.md
  src-docs/src/views/form_controls/switch.js
  src/components/form/switch/switch.js
  src/components/form/switch/switch.test.js
Labels: accessibility, bug

#1026 Global date picker
  CHANGELOG.md
  package.json
  src-docs/src/views/date_picker/date_picker_example.js
  src-docs/src/views/date_picker/global_date_picker.js
  src/components/date_picker/_date_picker_range.scss
  src/components/date_picker/date_picker_range.js
  src/components/flex/__snapshots__/flex_grid.test.js.snap
  src/components/flex/_flex_item.scss
  src/components/flex/flex_grid.js
  src/components/flex/flex_grid.test.js
  src/components/popover/_popover.scss
  src/components/tabs/__snapshots__/tabs.test.js.snap
  src/components/tabs/_tabs.scss
  src/components/tabs/tabbed_content/__snapshots__/tabbed_content.test.js.snap
  src/components/tabs/tabbed_content/tabbed_content.js
  src/components/tabs/tabs.js
  src/components/tabs/tabs.test.js
  yarn.lock
Labels: feature request

#1034 Add typings for EuiBadge
  CHANGELOG.md
  src/components/badge/index.d.ts
  src/components/index.d.ts
Labels: typescript

#1044 Fixed regressions from Global Time Picker
  CHANGELOG.md
  src-docs/src/views/date_picker/global_date_picker.js
  src-docs/src/views/flex/direction.js
  src-docs/src/views/flex/flex_example.js
  src/components/flex/_flex_item.scss
  src/components/popover/_popover.scss
Labels: bug

#1041 Make EUIXYChart responsive using ResizeObserver
  CHANGELOG.md
  package.json
  src-docs/src/views/xy_chart/responsive_chart.js
  src-docs/src/views/xy_chart/xy_chart_example.js
  src-docs/src/views/xy_chart_area/area_example.js
  src-docs/src/views/xy_chart_axis/xy_axis_example.js
  src-docs/src/views/xy_chart_bar/bar_example.js
  src-docs/src/views/xy_chart_histogram/histogram_example.js
  src-docs/src/views/xy_chart_histogram/time_histogram_series.js
  src-docs/src/views/xy_chart_line/line_example.js
  src/components/xy_chart/_xy_chart.scss
  src/components/xy_chart/axis/__snapshots__/default_axis.test.js.snap
  src/components/xy_chart/axis/__snapshots__/horizontal_grid.test.js.snap
  src/components/xy_chart/axis/__snapshots__/vertical_grid.test.js.snap
  src/components/xy_chart/axis/__snapshots__/x_axis.test.js.snap
  src/components/xy_chart/axis/__snapshots__/y_axis.test.js.snap
  src/components/xy_chart/crosshairs/__snapshots__/crosshair_x.test.js.snap
  src/components/xy_chart/crosshairs/__snapshots__/crosshair_y.test.js.snap
  src/components/xy_chart/series/__snapshots__/area_series.test.js.snap
  src/components/xy_chart/series/__snapshots__/horizontal_bar_series.test.js.snap
  src/components/xy_chart/series/__snapshots__/horizontal_rect_series.test.js.snap
  src/components/xy_chart/series/__snapshots__/line_series.test.js.snap
  src/components/xy_chart/series/__snapshots__/vertical_bar_series.test.js.snap
  src/components/xy_chart/series/__snapshots__/vertical_rect_series.test.js.snap
  src/components/xy_chart/utils/flexible.js
  src/components/xy_chart/xy_chart.js
  yarn.lock
Labels: bug
