Repository elastic/eui, pull requests merged in 2018-03, with the labels that each got.

#457 Fix broken links in docs
  src-docs/src/views/flex/flex_example.js
  src-docs/src/views/panel/panel_example.js
  src-docs/src/views/table_of_records/table_of_records_example.js
Labels: documentation

#430 update readme instructions to use yarn
  README.md
  wiki/component-development.md
Labels: documentation

#479 Fix all table rows showing on page 1 for paginated table examples
  src-docs/src/views/tables/data_store.js
Labels: documentation

#371 Button and toast guidelines
  CHANGELOG.md
  package-lock.json
  src-docs/src/components/guide_page/guide_page_chrome.js
  src-docs/src/components/guide_rule/_guide_rule_example.scss
  src-docs/src/components/guide_rule/guide_rule_example.js
  src-docs/src/routes.js
  src-docs/src/views/guidelines/button.js
  src-docs/src/views/guidelines/modals.js
  src-docs/src/views/guidelines/toasts.js
  src-docs/src/views/guidelines/writing.js
  src-docs/src/views/toast/success.js
Labels: documentation

#484 Refactor EuiToolTip, add EuiPortal
  CHANGELOG.md
  src-docs/src/routes.js
  src-docs/src/views/portal/portal.js
  src-docs/src/views/portal/portal_example.js
  src-docs/src/views/tool_tip/tool_tip.js
  src-docs/src/views/tool_tip/tool_tip_example.js
  src-docs/src/views/tooltip/examples.js
  src-docs/src/views/tooltip/tooltip_example.js
  src/components/index.js
  src/components/index.scss
  src/components/portal/__snapshots__/portal.test.js.snap
  src/components/portal/index.js
  src/components/portal/portal.js
  src/components/portal/portal.test.js
  src/components/tool_tip/__snapshots__/tool_tip.test.js.snap
  src/components/tool_tip/__snapshots__/tool_tip_popover.test.js.snap
  src/components/tool_tip/_index.scss
  src/components/tool_tip/_tool_tip.scss
  src/components/tool_tip/index.js
  src/components/tool_tip/tool_tip.js
  src/components/tool_tip/tool_tip.test.js
  src/components/tool_tip/tool_tip_popover.js
  src/components/tool_tip/tool_tip_popover.test.js
  src/components/tooltip/_index.scss
  src/components/tooltip/_mixins.scss
  src/components/tooltip/_tooltip.scss
  src/components/tooltip/index.js
  src/components/tooltip/tooltip.js
  src/components/tooltip/tooltip_constants.js
  src/components/tooltip/tooltip_trigger.js
  src/services/index.js
  src/services/overflow/index.js
  src/services/overflow/no_overflow_placement.js
  src/services/popover/index.js
  src/services/popover/popover_calculate_position.js
  src/services/popover/popover_calculate_styles.js
Labels: breaking change, feature request

#487 Misc. small fixes against outstanding issues
  CHANGELOG.md
  src-docs/src/views/pagination/customizable_pagination.js
  src/components/bottom_bar/bottom_bar.js
  src/components/bottom_bar/bottom_bar.test.js
  src/components/button/_index.scss
Labels: bug

#492 Clear search, reset nav display on nav item clicks
  src-docs/src/components/guide_page/guide_page_chrome.js
Labels: documentation

#494 Docs homepage rework, colors guideline + misc fixes
  CHANGELOG.md
  package.json
  src-docs/src/components/guide_components.scss
  src-docs/src/routes.js
  src-docs/src/views/guidelines/button.js
  src-docs/src/views/guidelines/colors.js
  src-docs/src/views/guidelines/index.scss
  src-docs/src/views/guidelines/modals.js
  src-docs/src/views/guidelines/toasts.js
  src-docs/src/views/guidelines/writing.js
  src-docs/src/views/home/home_view.js
  src-docs/src/views/icon/logos.js
  src-docs/src/views/image/image.js
  src-docs/src/views/image/image_size.js
  src-docs/src/views/image/image_zoom.js
  src/components/badge/__snapshots__/badge.test.js.snap
  src/components/badge/badge.js
  src/components/card/card.js
  src/components/flex/_flex_item.scss
  src/components/icon/__snapshots__/icon.test.js.snap
  src/components/icon/assets/logo_github.svg
  src/components/icon/assets/logo_sketch.svg
  src/components/icon/icon.js
  src/global_styling/variables/_colors.scss
  src/services/color/index.js
  src/services/color/luminance_and_contrast.js
  src/services/color/rgb_to_hex.js
  src/services/index.js
  yarn.lock
Labels: documentation

#513 Fix FlexGrid responsiveness
  CHANGELOG.md
  src-docs/src/views/home/home_view.js
  src/components/card/card.js
  src/components/flex/_flex_item.scss
Labels: bug

#512 Modal responsive refactor
  CHANGELOG.md
  src-docs/src/views/modal/modal_example.js
  src-docs/src/views/modal/overflow_test.js
  src/components/modal/__snapshots__/confirm_modal.test.js.snap
  src/components/modal/__snapshots__/modal.test.js.snap
  src/components/modal/_modal.scss
  src/components/modal/modal.js
Labels: bug

#524 Adding local images for home page and updating look
  src-docs/src/images/buttons.svg
  src-docs/src/images/cards.svg
  src-docs/src/images/flexgrid.svg
  src-docs/src/images/forms.svg
  src-docs/src/images/icons.jpg
  src-docs/src/images/tables.svg
  src-docs/src/views/home/home_view.js
Labels: documentation, style only

#527 Fix EuiPageContent centering
  CHANGELOG.md
  src/components/page/page_content/_page_content.scss
Labels: bug

#530 EuiHealth responsive fix
  CHANGELOG.md
  src/components/health/__snapshots__/health.test.js.snap
  src/components/health/health.js
Labels: bug

#565 Improve EuiBasicTable cell configuration and EuiTable cell content CSS
  CHANGELOG.md
  src-docs/src/views/tables/actions/actions.js
  src-docs/src/views/tables/basic/basic.js
  src-docs/src/views/tables/custom/custom.js
  src-docs/src/views/tables/data_store.js
  src-docs/src/views/tables/in_memory/in_memory.js
  src-docs/src/views/tables/in_memory/in_memory_search.js
  src-docs/src/views/tables/in_memory/in_memory_search_callback.js
  src-docs/src/views/tables/in_memory/in_memory_selection.js
  src-docs/src/views/tables/paginated/paginated.js
  src-docs/src/views/tables/selection/selection.js
  src-docs/src/views/tables/sorting/sorting.js
  src/components/basic_table/basic_table.js
  src/components/table/_table.scss
Labels: bug

#574 Tweaking Documentation styles
  src-docs/src/components/guide_components.scss
  src-docs/src/components/guide_rule/_guide_rule.scss
  src-docs/src/components/guide_rule/_guide_rule_description.scss
  src-docs/src/components/guide_rule/_guide_rule_title.scss
  src-docs/src/components/guide_rule/guide_rule.js
  src-docs/src/components/guide_section/_guide_section.scss
  src-docs/src/views/guidelines/button.js
  src-docs/src/views/guidelines/colors.js
  src-docs/src/views/guidelines/modals.js
  src-docs/src/views/guidelines/toasts.js
  src-docs/src/views/guidelines/writing.js
  src/components/text/_text.scss
Labels: documentation, style only

#578 Removing HR comps from guideline pages
  src-docs/src/views/guidelines/button.js
  src-docs/src/views/guidelines/toasts.js
Labels: bug, documentation

#523 Modals guidelines
  src-docs/src/routes.js
  src-docs/src/views/guidelines/modals.js
  src-docs/src/views/guidelines/writing.js
  src-docs/src/views/home/home_view.js
  src/components/modal/_modal.scss
Labels: documentation

#593 Add warning in EuiPortal about inability to render immediately.
  src/components/portal/portal.js
Labels: chore

#596 Font weight fix for k6
  CHANGELOG.md
  docs/index.html
  src-docs/src/index.html
  src/global_styling/variables/_typography.scss
  src/themes/k6/k6_globals.scss
Labels: bug, style only
