Repository elastic/eui, pull requests merged in 2018-06, with the labels that each got.

#901 Fixed column not showing up on large screens
  src-docs/src/views/guidelines/button.js
Labels: documentation

#904 Fixing form layout icon vertical alignment
  src/components/form/form_control_layout/__snapshots__/form_control_layout.test.js.snap
  src/components/form/form_control_layout/_form_control_layout_custom_icon.scss
  src/components/form/form_control_layout/form_control_layout_custom_icon.js
Labels: style only

#909 Responsive refactors and addition of helpers
  CHANGELOG.md
  src-docs/src/components/guide_components.scss
  src-docs/src/routes.js
  src-docs/src/views/responsive/responsive.js
  src-docs/src/views/responsive/responsive_example.js
  src-docs/src/views/utility_classes/utility_classes.js
  src/components/breadcrumbs/_breadcrumbs.scss
  src/components/button/button_group/_button_group.scss
  src/components/date_picker/_date_picker.scss
  src/components/flex/_flex_group.scss
  src/components/flex/_flex_item.scss
  src/components/flyout/_flyout.scss
  src/components/form/described_form_group/_described_form_group.scss
  src/components/header/_header_logo.scss
  src/components/header/header_links/_header_links.scss
  src/components/index.js
  src/components/modal/_modal.scss
  src/components/page/page_body/_page_body.scss
  src/components/page/page_content/_page_content.scss
  src/components/page/page_content/_page_content_header.scss
  src/components/page/page_content/_page_content_header_section.scss
  src/components/page/page_header/_page_header.scss
  src/components/page/page_header/_page_header_section.scss
  src/components/page/page_side_bar/_page_side_bar.scss
  src/components/pagination/_pagination_button.scss
  src/components/responsive/__snapshots__/hide_from.test.js.snap
  src/components/responsive/__snapshots__/show_for.test.js.snap
  src/components/responsive/hide_from.js
  src/components/responsive/hide_from.test.js
  src/components/responsive/index.js
  src/components/responsive/show_for.js
  src/components/responsive/show_for.test.js
  src/components/side_nav/_side_nav.scss
  src/components/steps/_steps_horizontal.scss
  src/components/table/_responsive.scss
  src/components/table/_table.scss
  src/components/table/mobile/_mobile.scss
  src/components/toast/_global_toast_list.scss
  src/global_styling/mixins/_responsive.scss
  src/global_styling/utility/_utility.scss
  src/global_styling/variables/_responsive.scss
  yarn.lock
Labels: feature request, style only

#916 Added role='dialog' to EuiFlyout and documented correct way to make it announce itself with aria attributes
  CHANGELOG.md
  src-docs/src/views/flyout/flyout.js
  src-docs/src/views/flyout/flyout_complicated.js
  src-docs/src/views/flyout/flyout_example.js
  src-docs/src/views/flyout/flyout_size.js
  src/components/flyout/__snapshots__/flyout.test.js.snap
  src/components/flyout/flyout.js
Labels: accessibility

#918 EuiComboBox now gives focus to the search input when the user clicks the clear button
  CHANGELOG.md
  src/components/combo_box/__snapshots__/combo_box.test.js.snap
  src/components/combo_box/combo_box.js
  src/components/combo_box/combo_box.test.js
  src/components/combo_box/combo_box_input/combo_box_input.js
Labels: accessibility

#926 Fix bug where users could tab away from EuiComboBox while navigating the options list
  src/components/combo_box/combo_box.js
  src/components/combo_box/combo_box.test.js
Labels: accessibility

#928 Fixing size of inputs via box-shadow
  CHANGELOG.md
  src/components/combo_box/_combo_box.scss
  src/components/combo_box/combo_box_options_list/_combo_box_options_list.scss
  src/components/form/_mixins.scss
  src/components/form/file_picker/_file_picker.scss
Labels: style only

#945 Altering the avatars a bit
  CHANGELOG.md
  src/components/avatar/_avatar.scss
Labels: style only

#947 add MutationObserver to accordion to trigger setChildContentHeight when children change
  CHANGELOG.md
  src-docs/src/views/accordion/accordion_grow.js
  src/components/accordion/accordion.js
  src/components/accordion/accordion.test.js
Labels: bug

#954 Simplifying form control styles
  CHANGELOG.md
  src/components/combo_box/_combo_box.scss
  src/components/form/_mixins.scss
  src/components/form/_variables.scss
  src/components/form/file_picker/_file_picker.scss
  src/components/form/select/_select.scss
Labels: style only
