Repository elastic/eui, pull requests merged in 2019-01, with the labels that each got.

#1410 Adds initialFocus prop typedefs
  CHANGELOG.md
  src/components/modal/index.d.ts
  src/components/popover/index.d.ts
Labels: typescript

#1413 Update GIS app icon
  CHANGELOG.md
  src-docs/src/views/icon/apps.js
  src/components/icon/__snapshots__/icon.test.tsx.snap
  src/components/icon/_icon.scss
  src/components/icon/assets/app_gis.svg
Labels: icons

#1416 Fix broken docs links
  src-docs/src/views/badge/badge_example.js
  src-docs/src/views/button/button_example.js
  src-docs/src/views/form_controls/form_controls_example.js
  src-docs/src/views/guidelines/colors.js
  src-docs/src/views/guidelines/sass.js
  src-docs/src/views/home/home_view.js
  src-docs/src/views/list_group/list_group_links.js
  src-docs/src/views/toggle/toggle_example.js
  wiki/documentation-guidelines.md
Labels: documentation

#1408 Migrate remaining accessibility files to TS
  CHANGELOG.md
  src/components/accessibility/__snapshots__/keyboard_accessible.test.tsx.snap
  src/components/accessibility/index.ts
  src/components/accessibility/keyboard_accessible.test.js
  src/components/accessibility/keyboard_accessible.test.tsx
  src/components/accessibility/keyboard_accessible.ts
  src/components/accessibility/screen_reader.tsx
Labels: typescript

#1422 Propagate className in EuiCodeBlock in fullscreen mode
  CHANGELOG.md
  src/components/code/_code_block.js
Labels: bug

#1444 Button group fixes
  CHANGELOG.md
  src-docs/src/views/button/button_example.js
  src-docs/src/views/button/button_group.js
  src/components/button/button_group/__snapshots__/button_group.test.js.snap
  src/components/button/button_group/button_group.js
  src/components/form/switch/_mixins.scss
  src/global_styling/reset/_reset.scss
Labels: accessibility, bug

#1402 Inter UI Font Family
  CHANGELOG.md
  src-docs/src/theme_dark.scss
  src-docs/src/theme_light.scss
  src-docs/src/views/guidelines/colors.js
  src-docs/src/views/guidelines/index.scss
  src-docs/src/views/guidelines/sass.js
  src/components/badge/_badge.scss
  src/components/button/_mixins.scss
  src/components/code/_code_block.scss
  src/components/combo_box/_combo_box.scss
  src/components/combo_box/combo_box_input/_combo_box_pill.scss
  src/components/date_picker/_date_picker.scss
  src/components/expression/_expression.scss
  src/components/form/_mixins.scss
  src/components/key_pad_menu/_key_pad_menu.scss
  src/components/table/_table.scss
  src/components/text/_text.scss
  src/components/toast/_toast.scss
  src/global_styling/mixins/_typography.scss
  src/global_styling/reset/_reset.scss
  src/global_styling/variables/_colors.scss
  src/global_styling/variables/_shadows.scss
  src/global_styling/variables/_typography.scss
  src/themes/eui/eui_colors_dark.scss
  src/themes/k6/k6_colors_dark.scss
  src/themes/k6/k6_globals.scss
  wiki/consuming.md
Labels: design decision, style only

#1455 Fix EuiFilterGroupButton bolding with notification and...
  CHANGELOG.md
  src/components/badge/badge.js
  src/components/badge/notification_badge/_notification_badge.scss
  src/components/button/button.js
  src/components/button/button_empty/button_empty.js
  src/components/filter_group/_filter_button.scss
  src/components/filter_group/filter_button.js
Labels: bug

#1445 Added snowflake icon
  CHANGELOG.md
  src-docs/src/views/icon/icons.js
  src/components/icon/__snapshots__/icon.test.tsx.snap
  src/components/icon/assets/snowflake.svg
  src/components/icon/icon.tsx
Labels: icons

#1447 Add new bell icon
  CHANGELOG.md
  src-docs/src/views/icon/icons.js
  src/components/icon/__snapshots__/icon.test.tsx.snap
  src/components/icon/assets/bell.svg
  src/components/icon/icon.tsx
Labels: icons

#1465 Fix font stack for monospace font
  CHANGELOG.md
  src/global_styling/variables/_typography.scss
Labels: bug

#1481 Don’t add the variant font family
  CHANGELOG.md
  src/global_styling/mixins/_typography.scss
  src/global_styling/variables/_typography.scss
  src/themes/k6/k6_globals.scss
Labels: style only

#1480 Don’t reduce header at at mobile size
  CHANGELOG.md
  src/components/header/_header_logo.scss
  src/components/header/_variables.scss
  src/components/header/header_section/_header_section_item.scss
  src/components/nav_drawer/_nav_drawer.scss
  src/components/nav_drawer/_variables.scss
Labels: style only

#1487 [EuiText] Add 'align' property
  CHANGELOG.md
  src/components/text/index.d.ts
Labels: chore, typescript
