Repository elastic/eui, pull requests merged in 2019-07, with the labels that each got.

#2084 [Icons] Updated APM app and solution logos
  CHANGELOG.md
  src/components/icon/__snapshots__/icon.test.tsx.snap
  src/components/icon/assets/app_apm.js
  src/components/icon/assets/app_apm.svg
  src/components/icon/assets/logo_apm.js
  src/components/icon/assets/logo_apm.svg
Labels: icons

#1820 React datepicker better responsive handling when inline
  CHANGELOG.md
  src-docs/src/views/date_picker/time_select.js
  src/components/date_picker/__snapshots__/date_picker.test.js.snap
  src/components/date_picker/_date_picker.scss
  src/components/date_picker/_index.scss
  src/components/date_picker/_variables.scss
  src/components/date_picker/date_picker.js
  src/components/date_picker/super_date_picker/date_popover/_date_popover_content.scss
Labels: bug

#2086 Convert form control layout to ts
  CHANGELOG.md
  src/components/date_picker/__snapshots__/date_picker.test.js.snap
  src/components/date_picker/super_date_picker/__snapshots__/super_date_picker.test.js.snap
  src/components/form/form_control_layout/__snapshots__/form_control_layout.test.tsx.snap
  src/components/form/form_control_layout/form_control_layout.js
  src/components/form/form_control_layout/form_control_layout.test.tsx
  src/components/form/form_control_layout/form_control_layout.tsx
  src/components/form/form_control_layout/form_control_layout_clear_button.tsx
  src/components/form/form_control_layout/form_control_layout_custom_icon.tsx
  src/components/form/form_control_layout/form_control_layout_icons.tsx
  src/components/form/form_control_layout/index.d.ts
  src/components/form/form_control_layout/index.js
  src/components/form/form_control_layout/index.ts
  src/components/form/index.d.ts
Labels: chore, typescript

#2088 Use `mask-image` for overflow shadows
  CHANGELOG.md
  src-docs/src/views/guidelines/index.scss
  src-docs/src/views/guidelines/sass.js
  src-docs/src/views/utility_classes/utility_classes.js
  src/components/flyout/_flyout_body.scss
  src/components/modal/_modal.scss
  src/components/selectable/selectable_list/__snapshots__/selectable_list.test.tsx.snap
  src/components/selectable/selectable_list/_selectable_list.scss
  src/components/selectable/selectable_list/selectable_list.tsx
  src/global_styling/mixins/_helpers.scss
  src/global_styling/mixins/_shadow.scss
  src/global_styling/utility/_utility.scss
Labels: style only

#2113 Fixed placeholder text color for more browsers
  CHANGELOG.md
  src/components/form/_mixins.scss
Labels: style only

#2114 [Feature branch] Updated form control border color
  src/components/form/_mixins.scss
  src/components/form/_variables.scss
Labels: style only

#2102 Add new icons
  CHANGELOG.md
  src-docs/src/views/icon/icons.js
  src/components/icon/__snapshots__/icon.test.tsx.snap
  src/components/icon/assets/cloudDrizzle.js
  src/components/icon/assets/cloudDrizzle.svg
  src/components/icon/assets/cloudStormy.js
  src/components/icon/assets/cloudStormy.svg
  src/components/icon/assets/cloudSunny.js
  src/components/icon/assets/cloudSunny.svg
  src/components/icon/assets/documentEdit.js
  src/components/icon/assets/documentEdit.svg
  src/components/icon/assets/documents.js
  src/components/icon/assets/documents.svg
  src/components/icon/assets/training.js
  src/components/icon/assets/training.svg
  src/components/icon/assets/videoPlayer.js
  src/components/icon/assets/videoPlayer.svg
  src/components/icon/icon.tsx
Labels: icons

#2135 Fixed EuiComboBox padding on the right
  CHANGELOG.md
  src/components/combo_box/_combo_box.scss
Labels: bug, style only

#2144 Update docs on how to test local EUI in Kibana
  wiki/component-development.md
Labels: documentation

#2146 Fix typo in icon docs
  src-docs/src/views/icon/icon_example.js
Labels: documentation

#2151 Upgrade sidenav search to include sub-section titles
  src-docs/src/components/guide_components.scss
  src-docs/src/components/guide_page/guide_page_chrome.js
Labels: documentation

#2154 Relative `href` values in `EuiNavDrawer` example
  src-docs/src/views/nav_drawer/nav_drawer.js
Labels: documentation

#2152 Added `partial` glyph to EuiIcon
  CHANGELOG.md
  src-docs/src/views/icon/icons.js
  src/components/icon/__snapshots__/icon.test.tsx.snap
  src/components/icon/assets/partial.js
  src/components/icon/assets/partial.svg
  src/components/icon/icon.tsx
Labels: icons

#2157 Fix text wrapping utilities
  CHANGELOG.md
  src-docs/src/views/guidelines/sass.js
  src-docs/src/views/utility_classes/utility_classes.js
  src/global_styling/utility/_utility.scss
Labels: deprecations, style only

#2170 Add 'Creating icons' section to the wiki
  CONTRIBUTING.md
  wiki/creating-icons.md
Labels: documentation
