Repository elastic/eui, pull requests merged in 2019-09, with the labels that each got.

#2299 Fix some typoes in documentation/comments
  packages/react-datepicker/test/datepicker_test.js
  src/components/avatar/_avatar.scss
  src/components/badge/_badge.scss
  src/components/badge/notification_badge/_notification_badge.scss
  src/components/card/_card.scss
  src/components/filter_group/filter_button.js
  src/components/form/_mixins.scss
  src/components/form/file_picker/_file_picker.scss
  src/components/icon/_icon.scss
  src/components/image/_image.scss
  src/components/loading/_loading_spinner.scss
  src/components/modal/_modal.scss
  src/components/nav_drawer/_nav_drawer_group.scss
  src/components/table/_responsive.scss
  src/components/text/_text.scss
  src/components/tool_tip/_tool_tip.scss
  src/global_styling/functions/_colors.scss
Labels: chore

#2291 EuiFilterSelect add missing TS def
  CHANGELOG.md
  src/components/filter_group/filter_select_item.js
  src/components/filter_group/index.d.ts
Labels: documentation, typescript

#2327 Compressed switch styling
  CHANGELOG.md
  src-docs/src/views/form_compressed/form_compressed.js
  src-docs/src/views/form_compressed/form_horizontal.js
  src-docs/src/views/form_controls/switch.js
  src/components/form/_mixins.scss
  src/components/form/_variables.scss
  src/components/form/switch/_switch.scss
  src/components/form/switch/switch.js
Labels: bug

#2328 Migrate EuiBottomBar, EuiHealth and EuiImage to TS
  CHANGELOG.md
  src-docs/src/i18ntokens.json
  src/components/bottom_bar/__snapshots__/bottom_bar.test.tsx.snap
  src/components/bottom_bar/bottom_bar.test.tsx
  src/components/bottom_bar/bottom_bar.tsx
  src/components/bottom_bar/index.ts
  src/components/health/__snapshots__/health.test.tsx.snap
  src/components/health/health.test.tsx
  src/components/health/health.tsx
  src/components/health/index.d.ts
  src/components/health/index.ts
  src/components/image/__snapshots__/image.test.tsx.snap
  src/components/image/image.test.tsx
  src/components/image/image.tsx
  src/components/image/index.ts
  src/components/index.d.ts
Labels: typescript

#2333 Added disabled state to EuiCard and EuiKeypadMenuItem
  CHANGELOG.md
  src-docs/src/views/card/card.js
  src-docs/src/views/key_pad_menu/key_pad_menu.js
  src-docs/src/views/key_pad_menu/key_pad_menu_item_button.js
  src/components/card/_card.scss
  src/components/card/card.js
  src/components/key_pad_menu/_key_pad_menu.scss
  src/components/key_pad_menu/key_pad_menu_item.js
Labels: prop request

#2354 Apply same top padding to EuiFormErrorText as EuiFormHelpText
  CHANGELOG.md
  src/components/form/form_error_text/_form_error_text.scss
Labels: style only

#2375 Adjusted style of beta badge on EuiKeyPadMenuItem
  CHANGELOG.md
  src-docs/src/views/key_pad_menu/key_pad_beta.js
  src/components/key_pad_menu/_key_pad_menu.scss
Labels: style only

#2382 Migrate `EuiFacetGroup`, `EuiKeyPadMenu` and `EuiCallOut` to TS
  CHANGELOG.md
  src/components/call_out/__snapshots__/call_out.test.tsx.snap
  src/components/call_out/call_out.test.tsx
  src/components/call_out/call_out.tsx
  src/components/call_out/index.d.ts
  src/components/call_out/index.js
  src/components/call_out/index.ts
  src/components/facet/__snapshots__/facet_group.test.tsx.snap
  src/components/facet/facet_group.test.tsx
  src/components/facet/facet_group.tsx
  src/components/facet/index.d.ts
  src/components/facet/index.js
  src/components/facet/index.ts
  src/components/index.d.ts
  src/components/key_pad_menu/__snapshots__/key_pad_menu.test.tsx.snap
  src/components/key_pad_menu/__snapshots__/key_pad_menu_item.test.tsx.snap
  src/components/key_pad_menu/index.d.ts
  src/components/key_pad_menu/index.ts
  src/components/key_pad_menu/key_pad_menu.js
  src/components/key_pad_menu/key_pad_menu.test.tsx
  src/components/key_pad_menu/key_pad_menu.tsx
  src/components/key_pad_menu/key_pad_menu_item.test.tsx
  src/components/key_pad_menu/key_pad_menu_item.tsx
Labels: chore, typescript

#2387 Migrate `EuiEmptyPrompt`and `EuiCard` to TS
  CHANGELOG.md
  src/components/button/button_empty/button_empty.tsx
  src/components/button/button_empty/index.ts
  src/components/card/__snapshots__/card.test.tsx.snap
  src/components/card/__snapshots__/card_select.test.tsx.snap
  src/components/card/card.test.tsx
  src/components/card/card.tsx
  src/components/card/card_select.test.tsx
  src/components/card/card_select.tsx
  src/components/card/index.d.ts
  src/components/card/index.ts
  src/components/empty_prompt/__snapshots__/empty_prompt.test.tsx.snap
  src/components/empty_prompt/empty_prompt.test.tsx
  src/components/empty_prompt/empty_prompt.tsx
  src/components/empty_prompt/index.d.ts
  src/components/empty_prompt/index.js
  src/components/empty_prompt/index.ts
  src/components/icon/icon.tsx
  src/components/icon/index.ts
  src/components/index.d.ts
  src/components/title/title.tsx
Labels: typescript

#2388 Made EuiKeyPadMenuItem beta badge smaller
  CHANGELOG.md
  src/components/badge/beta_badge/_beta_badge.scss
  src/components/key_pad_menu/_index.scss
  src/components/key_pad_menu/_key_pad_menu.scss
  src/components/key_pad_menu/_variables.scss
Labels: style only
