Repository elastic/eui, pull requests merged in 2019-10, with the labels that each got.

#2397 Change `render` signature to function from property
  src/components/filter_group/index.d.ts
Labels: typescript

#2391 EuiBreadcrumbs, EuiHeader and children, and EuiLink to TS
  CHANGELOG.md
  src/components/breadcrumbs/__snapshots__/breadcrumbs.test.tsx.snap
  src/components/breadcrumbs/breadcrumbs.test.tsx
  src/components/breadcrumbs/breadcrumbs.tsx
  src/components/breadcrumbs/index.js
  src/components/breadcrumbs/index.ts
  src/components/button/button_empty/button_empty.tsx
  src/components/filter_group/index.d.ts
  src/components/header/__snapshots__/header.test.tsx.snap
  src/components/header/header.js
  src/components/header/header.test.tsx
  src/components/header/header.tsx
  src/components/header/header_alert/__snapshots__/header_alert.test.tsx.snap
  src/components/header/header_alert/header_alert.test.tsx
  src/components/header/header_alert/header_alert.tsx
  src/components/header/header_alert/index.js
  src/components/header/header_alert/index.ts
  src/components/header/header_breadcrumbs/__snapshots__/header_breadcrumbs.test.tsx.snap
  src/components/header/header_breadcrumbs/header_breadcrumbs.js
  src/components/header/header_breadcrumbs/header_breadcrumbs.test.tsx
  src/components/header/header_breadcrumbs/header_breadcrumbs.tsx
  src/components/header/header_breadcrumbs/index.ts
  src/components/header/header_links/__snapshots__/header_link.test.tsx.snap
  src/components/header/header_links/__snapshots__/header_links.test.tsx.snap
  src/components/header/header_links/header_link.js
  src/components/header/header_links/header_link.test.tsx
  src/components/header/header_links/header_link.tsx
  src/components/header/header_links/header_links.test.tsx
  src/components/header/header_links/header_links.tsx
  src/components/header/header_links/index.ts
  src/components/header/header_logo.tsx
  src/components/header/header_section/__snapshots__/header_section.test.tsx.snap
  src/components/header/header_section/__snapshots__/header_section_item.test.tsx.snap
  src/components/header/header_section/__snapshots__/header_section_item_button.test.tsx.snap
  src/components/header/header_section/header_section.test.tsx
  src/components/header/header_section/header_section.tsx
  src/components/header/header_section/header_section_item.test.tsx
  src/components/header/header_section/header_section_item.tsx
  src/components/header/header_section/header_section_item_button.test.tsx
  src/components/header/header_section/header_section_item_button.tsx
  src/components/header/header_section/index.ts
  src/components/header/index.d.ts
  src/components/header/index.ts
  src/components/index.d.ts
  src/components/link/__snapshots__/link.test.tsx.snap
  src/components/link/index.d.ts
  src/components/link/index.js
  src/components/link/index.ts
  src/components/link/link.js
  src/components/link/link.test.tsx
  src/components/link/link.tsx
  src/components/pagination/pagination_button.tsx
Labels: typescript

#2411 Fixes several a11y issues manifesting in Kibana
  CHANGELOG.md
  src-docs/src/views/form_layouts/form_rows.js
  src/components/code_editor/__snapshots__/code_editor.test.js.snap
  src/components/code_editor/code_editor.js
  src/components/code_editor/code_editor.test.js
  src/components/date_picker/super_date_picker/date_popover/relative_tab.js
  src/components/date_picker/super_date_picker/quick_select_popover/__snapshots__/quick_select.test.js.snap
  src/components/date_picker/super_date_picker/quick_select_popover/_commonly_used_time_ranges.scss
  src/components/date_picker/super_date_picker/quick_select_popover/_index.scss
  src/components/date_picker/super_date_picker/quick_select_popover/_quick_select.scss
  src/components/date_picker/super_date_picker/quick_select_popover/_quick_select_popover.scss
  src/components/date_picker/super_date_picker/quick_select_popover/commonly_used_time_ranges.js
  src/components/date_picker/super_date_picker/quick_select_popover/quick_select.js
  src/components/date_picker/super_date_picker/quick_select_popover/quick_select.test.js
  src/components/date_picker/super_date_picker/quick_select_popover/refresh_interval.js
  src/components/flex/__snapshots__/flex_item.test.tsx.snap
  src/components/flex/flex_grid.tsx
  src/components/flex/flex_item.test.tsx
  src/components/flex/flex_item.tsx
  src/components/form/described_form_group/__snapshots__/described_form_group.test.js.snap
  src/components/form/form_row/__snapshots__/form_row.test.js.snap
  src/components/form/form_row/form_row.js
Labels: accessibility

#2417 Improve a11y in EuiNavDrawer
  CHANGELOG.md
  src-docs/src/views/nav_drawer/nav_drawer.js
  src/components/nav_drawer/_nav_drawer.scss
  src/components/nav_drawer/nav_drawer.js
Labels: accessibility

#2426 Cleanup around EuiSuperDatePicker quick select a11y
  CHANGELOG.md
  src/components/date_picker/super_date_picker/quick_select_popover/__snapshots__/quick_select.test.js.snap
  src/components/date_picker/super_date_picker/quick_select_popover/quick_select.js
Labels: accessibility

#2429 remove menubar role from EuiSideNav
  CHANGELOG.md
  src/components/side_nav/__snapshots__/side_nav.test.js.snap
  src/components/side_nav/__snapshots__/side_nav_item.test.js.snap
  src/components/side_nav/side_nav.js
  src/components/side_nav/side_nav_item.js
Labels: accessibility

#2430 [Icon] Update Observability app icons
  CHANGELOG.md
  src-docs/src/views/icon/apps.js
  src-docs/src/views/nav_drawer/nav_drawer.js
  src/components/icon/__snapshots__/icon.test.tsx.snap
  src/components/icon/assets/app_infra.js
  src/components/icon/assets/app_infra.svg
  src/components/icon/assets/app_logging.js
  src/components/icon/assets/app_logging.svg
  src/components/icon/assets/app_logs.js
  src/components/icon/assets/app_logs.svg
  src/components/icon/assets/app_metrics.js
  src/components/icon/assets/app_metrics.svg
  src/components/icon/icon.tsx
Labels: icons

#2448 Memoize EuiIcon
  CHANGELOG.md
  src/components/icon/icon.tsx
Labels: icons
