Repository elastic/eui, pull requests merged in 2019-04, with the labels that each got.

#1699 [WIP] EuiSelectable
  CHANGELOG.md
  src-docs/src/components/guide_page/guide_page.js
  src-docs/src/routes.js
  src-docs/src/views/header/header_spaces_menu.js
  src-docs/src/views/selectable/data.ts
  src-docs/src/views/selectable/selectable.tsx
  src-docs/src/views/selectable/selectable_custom_render.js
  src-docs/src/views/selectable/selectable_example.js
  src-docs/src/views/selectable/selectable_exclusion.tsx
  src-docs/src/views/selectable/selectable_messages.js
  src-docs/src/views/selectable/selectable_popover.js
  src-docs/src/views/selectable/selectable_search.tsx
  src-docs/src/views/selectable/selectable_single.tsx
  src/components/combo_box/combo_box_options_list/combo_box_options_list.js
  src/components/filter_group/__snapshots__/filter_select_item.test.js.snap
  src/components/filter_group/_filter_select_item.scss
  src/components/filter_group/filter_select_item.js
  src/components/form/field_search/field_search.js
  src/components/index.js
  src/components/index.scss
  src/components/selectable/__snapshots__/selectable.test.tsx.snap
  src/components/selectable/_index.scss
  src/components/selectable/_selectable.scss
  src/components/selectable/index.ts
  src/components/selectable/matching_options.ts
  src/components/selectable/selectable.test.tsx
  src/components/selectable/selectable.tsx
  src/components/selectable/selectable_list/__snapshots__/selectable_list.test.tsx.snap
  src/components/selectable/selectable_list/__snapshots__/selectable_list_item.test.tsx.snap
  src/components/selectable/selectable_list/_index.scss
  src/components/selectable/selectable_list/_selectable_list.scss
  src/components/selectable/selectable_list/_selectable_list_item.scss
  src/components/selectable/selectable_list/_variables.scss
  src/components/selectable/selectable_list/index.ts
  src/components/selectable/selectable_list/selectable_list.test.tsx
  src/components/selectable/selectable_list/selectable_list.tsx
  src/components/selectable/selectable_list/selectable_list_item.test.tsx
  src/components/selectable/selectable_list/selectable_list_item.tsx
  src/components/selectable/selectable_message/__snapshots__/selectable_message.test.tsx.snap
  src/components/selectable/selectable_message/_index.scss
  src/components/selectable/selectable_message/_selectable_message.scss
  src/components/selectable/selectable_message/index.ts
  src/components/selectable/selectable_message/selectable_message.test.tsx
  src/components/selectable/selectable_message/selectable_message.tsx
  src/components/selectable/selectable_search/__snapshots__/selectable_search.test.tsx.snap
  src/components/selectable/selectable_search/_index.scss
  src/components/selectable/selectable_search/_selectable_search.scss
  src/components/selectable/selectable_search/index.ts
  src/components/selectable/selectable_search/selectable_search.test.tsx
  src/components/selectable/selectable_search/selectable_search.tsx
  src/components/selectable/types.tsx
  src/global_styling/mixins/_helpers.scss
  src/global_styling/mixins/_shadow.scss
  src/global_styling/variables/_size.scss
Labels: work in progress

#1797 Added `menuLeft` and `menuRight` icons
  CHANGELOG.md
  src-docs/src/views/icon/icons.js
  src/components/icon/__snapshots__/icon.test.tsx.snap
  src/components/icon/assets/menuLeft.svg
  src/components/icon/assets/menuRight.svg
  src/components/icon/icon.tsx
  src/components/nav_drawer/nav_drawer.js
Labels: icons

#1802 Adds cut icon
  CHANGELOG.md
  src-docs/src/views/icon/icons.js
  src/components/icon/__snapshots__/icon.test.tsx.snap
  src/components/icon/assets/cut.svg
  src/components/icon/icon.tsx
Labels: icons

#1803 Small accessibility fixes to toasts and combo box
  CHANGELOG.md
  src/components/combo_box/combo_box_input/combo_box_input.js
  src/components/toast/_toast.scss
  src/components/toast/global_toast_list.js
Labels: accessibility, bug

#1831 Add snippets to accordion docs
  src-docs/src/views/accordion/accordion.js
  src-docs/src/views/accordion/accordion_example.js
  src-docs/src/views/accordion/accordion_multiple.js
Labels: documentation

#1829 Better overflow shadows and some mobile modal fixes
  CHANGELOG.md
  src-docs/src/views/guidelines/index.scss
  src-docs/src/views/guidelines/sass.js
  src-docs/src/views/modal/overflow_test.js
  src/components/flyout/__snapshots__/flyout_body.test.tsx.snap
  src/components/flyout/_flyout_body.scss
  src/components/flyout/_flyout_footer.scss
  src/components/flyout/_flyout_header.scss
  src/components/flyout/flyout_body.tsx
  src/components/modal/__snapshots__/confirm_modal.test.js.snap
  src/components/modal/__snapshots__/modal_body.test.tsx.snap
  src/components/modal/_modal.scss
  src/components/modal/confirm_modal.js
  src/components/modal/confirm_modal.test.js
  src/components/modal/index.d.ts
  src/components/modal/modal_body.tsx
  src/global_styling/mixins/_shadow.scss
Labels: deprecations

#1814 Remove `keyOfStringsOnly` option from tsconfig.json
  CHANGELOG.md
  scripts/compile-eui.js
  src/components/badge/index.d.ts
  src/components/badge/notification_badge/badge_notification.tsx
  src/components/drag_and_drop/drag_drop_context.tsx
  src/components/flex/flex_grid.tsx
  src/components/icon/icon.tsx
  src/services/format/format_date.ts
  src/services/predicate/common_predicates.ts
  src/services/predicate/lodash_predicates.ts
  tsconfig.json
Labels: breaking change, typescript

#1791 Convert EuiText, EuiTextColor and EuiTextAlign to TS
  CHANGELOG.md
  src/components/form/described_form_group/__snapshots__/described_form_group.test.js.snap
  src/components/index.d.ts
  src/components/selectable/selectable_message/selectable_message.tsx
  src/components/text/__snapshots__/text.test.tsx.snap
  src/components/text/__snapshots__/text_align.test.tsx.snap
  src/components/text/__snapshots__/text_color.test.tsx.snap
  src/components/text/index.d.ts
  src/components/text/index.js
  src/components/text/index.ts
  src/components/text/text.js
  src/components/text/text.test.tsx
  src/components/text/text.tsx
  src/components/text/text_align.js
  src/components/text/text_align.test.tsx
  src/components/text/text_align.tsx
  src/components/text/text_color.js
  src/components/text/text_color.test.tsx
  src/components/text/text_color.tsx
Labels: typescript

#1842 [IconColor] Distinguish between named and arbitrary colors
  CHANGELOG.md
  src/components/icon/icon.test.tsx
  src/components/icon/icon.tsx
Labels: typescript

#1841 Use cache-loader to speed up development docs site builds
  .gitignore
  .npmignore
  CHANGELOG.md
  package.json
  src-docs/webpack.config.js
  yarn.lock
Labels: documentation

#1845 Use span for loaders and set width to kibana loader
  CHANGELOG.md
  src/components/button/__snapshots__/button.test.js.snap
  src/components/facet/__snapshots__/facet_button.test.js.snap
  src/components/form/form_control_layout/__snapshots__/form_control_layout.test.js.snap
  src/components/form/super_select/__snapshots__/super_select_control.test.js.snap
  src/components/loading/__snapshots__/loading_chart.test.tsx.snap
  src/components/loading/__snapshots__/loading_content.test.tsx.snap
  src/components/loading/__snapshots__/loading_kibana.test.tsx.snap
  src/components/loading/__snapshots__/loading_spinner.test.tsx.snap
  src/components/loading/_loading_chart.scss
  src/components/loading/_loading_content.scss
  src/components/loading/_loading_kibana.scss
  src/components/loading/loading_chart.tsx
  src/components/loading/loading_content.tsx
  src/components/loading/loading_kibana.tsx
  src/components/loading/loading_spinner.tsx
Labels: bug

#1859 Adding Azure and moon logos.
  CHANGELOG.md
  src-docs/src/views/icon/icons.js
  src-docs/src/views/icon/logos_third.js
  src/components/icon/__snapshots__/icon.test.tsx.snap
  src/components/icon/assets/logo_azure.svg
  src/components/icon/assets/logo_azure_mono.svg
  src/components/icon/assets/moon.svg
  src/components/icon/icon.tsx
Labels: icons

#1887 Adds bug, flag, and heart icons. Updates alert icon.
  CHANGELOG.md
  src-docs/src/views/icon/icons.js
  src/components/form/form_control_layout/__snapshots__/form_control_layout.test.js.snap
  src/components/header/__snapshots__/header_logo.test.js.snap
  src/components/icon/__snapshots__/icon.test.tsx.snap
  src/components/icon/assets/alert.svg
  src/components/icon/assets/bug.svg
  src/components/icon/assets/flag.svg
  src/components/icon/assets/heart.svg
  src/components/icon/icon.tsx
  src/components/steps/__snapshots__/step_number.test.js.snap
  src/components/toast/__snapshots__/global_toast_list.test.js.snap
  src/components/tool_tip/__snapshots__/icon_tip.test.js.snap
Labels: icons

#1902 Fix overflow of EuiModals in Chrome and Safari
  CHANGELOG.md
  src/components/modal/_modal.scss
Labels: :urgent:, bug, style only
