Repository elastic/eui, pull requests merged in 2019-08, with the labels that each got.

#2192 Fixed the TS defs for EuiFilterSelectItem
  CHANGELOG.md
  src/components/filter_group/index.d.ts
Labels: bug, typescript

#2193 Aligning switch semantics with aria role
  CHANGELOG.md
  src-docs/src/views/form_controls/switch.js
  src/components/form/_variables.scss
  src/components/form/switch/__snapshots__/switch.test.js.snap
  src/components/form/switch/_switch.scss
  src/components/form/switch/index.d.ts
  src/components/form/switch/switch.js
  src/global_styling/reset/_reset.scss
Labels: accessibility

#2246 Center align logos
  CHANGELOG.md
  src/components/icon/__snapshots__/icon.test.tsx.snap
  src/components/icon/assets/logo_cloud_ece.js
  src/components/icon/assets/logo_cloud_ece.svg
  src/components/icon/assets/logo_logging.js
  src/components/icon/assets/logo_logging.svg
  src/components/icon/assets/logo_security.js
  src/components/icon/assets/logo_security.svg
Labels: icons

#2236 Offset negative margin for max width inside container for super date picker
  CHANGELOG.md
  src/components/date_picker/super_date_picker/_super_date_picker.scss
Labels: style only
