Repository elastic/eui, pull requests merged in 2020-02, with the labels that each got.

#2810 Convert EuiDescribedFormGroup to typeScript
  CHANGELOG.md
  src/components/flex/flex_group.tsx
  src/components/flex/index.ts
  src/components/form/described_form_group/__snapshots__/described_form_group.test.tsx.snap
  src/components/form/described_form_group/described_form_group.js
  src/components/form/described_form_group/described_form_group.test.tsx
  src/components/form/described_form_group/described_form_group.tsx
  src/components/form/described_form_group/index.js
  src/components/form/described_form_group/index.ts
  src/components/title/index.ts
Labels: typescript

#2758 Adjusting EuiToken for use as ES field types
  src-docs/src/views/datagrid/datagrid_example.js
  src-docs/src/views/icon/icon_example.js
  src-docs/src/views/icon/tokens.js
  src/components/datagrid/column_sorting.tsx
  src/components/datagrid/column_sorting_draggable.tsx
  src/components/datagrid/data_grid_schema.tsx
  src/components/icon/__snapshots__/icon.test.tsx.snap
  src/components/icon/assets/document.js
  src/components/icon/assets/document.svg
  src/components/icon/assets/tokens/tokenAlias.js
  src/components/icon/assets/tokens/tokenAlias.svg
  src/components/icon/assets/tokens/tokenBoolean.js
  src/components/icon/assets/tokens/tokenBoolean.svg
  src/components/icon/assets/tokens/tokenDate.js
  src/components/icon/assets/tokens/tokenDate.svg
  src/components/icon/assets/tokens/tokenGeo.js
  src/components/icon/assets/tokens/tokenGeo.svg
  src/components/icon/assets/tokens/tokenIP.js
  src/components/icon/assets/tokens/tokenIP.svg
  src/components/icon/assets/tokens/tokenNested.js
  src/components/icon/assets/tokens/tokenNested.svg
  src/components/icon/assets/tokens/tokenRange.js
  src/components/icon/assets/tokens/tokenRange.svg
  src/components/icon/assets/tokens/tokenShape.js
  src/components/icon/assets/tokens/tokenShape.svg
  src/components/icon/icon.tsx
  src/components/token/__snapshots__/token.test.tsx.snap
  src/components/token/_index.scss
  src/components/token/_token.scss
  src/components/token/_variables.scss
  src/components/token/token.test.tsx
  src/components/token/token.tsx
  src/components/token/token_map.ts
  src/components/tree_view/tree_view.scss
  src/global_styling/variables/_colors.scss
Labels: breaking change

#2829 Update elastic charts to v17.x
  package.json
  src-docs/src/views/elastic_charts/shared.js
  src-docs/src/views/elastic_charts/sparklines.js
  src-docs/src/views/elastic_charts/theming.js
  src-docs/src/views/elastic_charts/theming_categorical.js
  yarn.lock
Labels: dependencies

#2830 Export select option type
  CHANGELOG.md
  src/components/form/select/index.ts
  src/components/form/select/select.tsx
Labels: typescript

#2846 Add control columns to EuiDataGrid
  CHANGELOG.md
  src-docs/src/routes.js
  src-docs/src/views/datagrid/control_columns.js
  src-docs/src/views/datagrid/datagrid.js
  src-docs/src/views/datagrid/datagrid_controlcolumns_example.js
  src-docs/src/views/datagrid/datagrid_example.js
  src-docs/src/views/datagrid/props.tsx
  src-docs/src/views/tables/in_memory/in_memory_selection.js
  src/components/datagrid/__snapshots__/data_grid.test.tsx.snap
  src/components/datagrid/_data_grid_data_row.scss
  src/components/datagrid/_data_grid_header_row.scss
  src/components/datagrid/data_grid.test.tsx
  src/components/datagrid/data_grid.tsx
  src/components/datagrid/data_grid_body.tsx
  src/components/datagrid/data_grid_cell.tsx
  src/components/datagrid/data_grid_control_header_cell.tsx
  src/components/datagrid/data_grid_data_row.tsx
  src/components/datagrid/data_grid_header_cell.tsx
  src/components/datagrid/data_grid_header_row.tsx
  src/components/datagrid/data_grid_types.ts
  src/components/datagrid/index.ts
Labels: data grid

#2872 Prevent EuiDataGrid from auto-focusing
  CHANGELOG.md
  src/components/datagrid/__snapshots__/data_grid.test.tsx.snap
  src/components/datagrid/data_grid.test.tsx
  src/components/datagrid/data_grid.tsx
  src/components/datagrid/data_grid_body.tsx
  src/components/datagrid/data_grid_control_header_cell.tsx
  src/components/datagrid/data_grid_header_cell.tsx
  src/components/datagrid/data_grid_header_row.tsx
Labels: data grid

#2887 Fix typos in urls in datagrid docs
  src-docs/src/views/datagrid/datagrid_example.js
Labels: documentation

#2908 Fixes #2217 : removed duplicate icons
  CHANGELOG.md
  src-docs/src/views/icon/icons.js
  src/components/icon/__snapshots__/icon.test.tsx.snap
  src/components/icon/assets/vis_controls.js
  src/components/icon/assets/vis_controls.svg
  src/components/icon/assets/vis_heatmap.js
  src/components/icon/assets/vis_heatmap.svg
  src/components/icon/icon.tsx
Labels: breaking change

#2861 Improving a11y of BottomBar and ControlBar
  CHANGELOG.md
  src/components/bottom_bar/__snapshots__/bottom_bar.test.tsx.snap
  src/components/bottom_bar/bottom_bar.tsx
  src/components/control_bar/__snapshots__/control_bar.test.tsx.snap
  src/components/control_bar/control_bar.tsx
Labels: accessibility

#2873 [Amsterdam] Saturating colors and providing contrast mixin for text.
  CHANGELOG.md
  src-docs/src/components/guide_rule/_guide_rule_example.scss
  src-docs/src/views/guidelines/colors.js
  src-docs/src/views/guidelines/index.scss
  src-docs/src/views/guidelines/sass.js
  src/components/badge/notification_badge/_notification_badge.scss
  src/components/expression/_variables.scss
  src/components/icon/_icon.scss
  src/components/icon/_variables.scss
  src/components/link/_link.scss
  src/components/stat/_stat.scss
  src/components/toast/_toast.scss
  src/global_styling/functions/_colors.scss
  src/global_styling/variables/_colors.scss
  src/themes/eui-amsterdam/eui_amsterdam_colors_dark.scss
  src/themes/eui-amsterdam/eui_amsterdam_colors_light.scss
  src/themes/eui/eui_colors_dark.scss
Labels: Amsterdam, style only

#2914 Adding more props to EuiHeaderSectionItemButton, EuiFieldSearch, and EuiAccordion
  CHANGELOG.md
  src-docs/src/views/accordion/accordion_arrow.js
  src-docs/src/views/accordion/accordion_example.js
  src-docs/src/views/form_controls/display_toggles.js
  src-docs/src/views/form_controls/field_search.js
  src-docs/src/views/header/header_app_menu.js
  src-docs/src/views/header/header_updates.js
  src/components/accordion/__snapshots__/accordion.test.tsx.snap
  src/components/accordion/_accordion.scss
  src/components/accordion/accordion.test.tsx
  src/components/accordion/accordion.tsx
  src/components/color_picker/color_picker.tsx
  src/components/flyout/flyout.test.tsx
  src/components/flyout/flyout.tsx
  src/components/form/field_number/field_number.tsx
  src/components/form/field_search/__snapshots__/field_search.test.tsx.snap
  src/components/form/field_search/field_search.test.tsx
  src/components/form/field_search/field_search.tsx
  src/components/form/field_text/field_text.tsx
  src/components/form/form_control_layout/form_control_layout.tsx
  src/components/form/range/dual_range.tsx
  src/components/form/select/select.tsx
  src/components/header/header_section/__snapshots__/header_section_item_button.test.tsx.snap
  src/components/header/header_section/_header_section_item.scss
  src/components/header/header_section/header_section_item_button.test.tsx
  src/components/header/header_section/header_section_item_button.tsx
Labels: deprecations

#2857 [Docs only] Adds a ThemeContext context to docs
  src-docs/src/actions/action_types.js
  src-docs/src/actions/index.js
  src-docs/src/actions/theme_actions.js
  src-docs/src/components/guide_page/guide_page_chrome.js
  src-docs/src/components/guide_section/guide_section.js
  src-docs/src/components/guide_section/guide_section_container.js
  src-docs/src/components/guide_theme_selector/guide_theme_selector.js
  src-docs/src/components/index.js
  src-docs/src/components/with_theme/index.js
  src-docs/src/components/with_theme/index.ts
  src-docs/src/components/with_theme/theme_context.tsx
  src-docs/src/components/with_theme/with_theme.js
  src-docs/src/views/app_container.js
  src-docs/src/views/app_view.js
  src-docs/src/views/elastic_charts/category_chart.js
  src-docs/src/views/elastic_charts/sizes.js
  src-docs/src/views/elastic_charts/sparklines.js
  src-docs/src/views/elastic_charts/theming.js
  src-docs/src/views/elastic_charts/theming_categorical.js
  src-docs/src/views/elastic_charts/time_chart.js
  src/index.js
  src/themes/index.ts
  src/themes/themes.ts
Labels: documentation
