Repository elastic/eui, pull requests merged in 2020-10, with the labels that each got.

#4062 Major version dependency upgrades, pt. III; Docker bonus
  .babelrc.js
  CHANGELOG.md
  package.json
  scripts/docker-puppeteer/Dockerfile
  scripts/docker-puppeteer/README.md
  scripts/jenkins_run_visual_regression_tests.sh
  scripts/jest/config.json
  scripts/jest/setup/mocks.js
  scripts/run-visual-tests.js
  scripts/test-docker.js
  src-docs/src/index.js
  src/components/combo_box/__snapshots__/combo_box.test.tsx.snap
  src/components/empty_prompt/empty_prompt.tsx
  src/components/form/field_number/field_number.test.tsx
  src/components/form/field_text/field_text.test.tsx
  src/components/icon/icon.test.tsx
  test/README.md
  test/failure-screenshots/.keep
  test/spec/components/card/card.spec.js
  test/spec/components/table/table.spec.js
  test/spec/components/toast/toast.spec.js
  test/spec/screenshots/baseline/.keep
  test/spec/screenshots/diff/.keep
  test/spec/screenshots/screen/.keep
  test/wdio.conf.js
  wiki/automated-accessibility-testing.md
  yarn.lock
Labels: dependencies

#4133 [Amsterdam] Tighten title line-heights
  CHANGELOG.md
  src/themes/eui-amsterdam/global_styling/variables/_typography.scss
Labels: Amsterdam

#4056 Fix EuiButtonGroup a11y and remove EuiToggle/EuiButtonToggle
  CHANGELOG.md
  packages/eslint-plugin/rules/href_or_on_click.js
  src-docs/src/routes.js
  src-docs/src/views/button/button_example.js
  src-docs/src/views/button/button_ghost.js
  src-docs/src/views/button/button_group.js
  src-docs/src/views/button/button_toggle.js
  src-docs/src/views/button/playground.js
  src-docs/src/views/collapsible_nav/collapsible_nav.tsx
  src-docs/src/views/markdown_editor/markdown_editor.js
  src-docs/src/views/markdown_editor/markdown_editor_errors.js
  src-docs/src/views/markdown_editor/markdown_editor_with_plugins.js
  src-docs/src/views/toggle/playground.js
  src-docs/src/views/toggle/toggle.js
  src-docs/src/views/toggle/toggle_example.js
  src/components/accessibility/__snapshots__/skip_link.test.tsx.snap
  src/components/button/__snapshots__/button.test.tsx.snap
  src/components/button/_button.scss
  src/components/button/_index.scss
  src/components/button/button.test.tsx
  src/components/button/button.tsx
  src/components/button/button_content.tsx
  src/components/button/button_empty/__snapshots__/button_empty.test.tsx.snap
  src/components/button/button_empty/button_empty.test.tsx
  src/components/button/button_empty/button_empty.tsx
  src/components/button/button_group/__snapshots__/button_group.test.tsx.snap
  src/components/button/button_group/_button_group.scss
  src/components/button/button_group/_button_group_button.scss
  src/components/button/button_group/_index.scss
  src/components/button/button_group/button_group.test.tsx
  src/components/button/button_group/button_group.tsx
  src/components/button/button_group/button_group_button.tsx
  src/components/button/button_group/index.ts
  src/components/button/button_icon/__snapshots__/button_icon.test.tsx.snap
  src/components/button/button_icon/button_icon.test.tsx
  src/components/button/button_icon/button_icon.tsx
  src/components/button/button_toggle/__snapshots__/button_toggle.test.tsx.snap
  src/components/button/button_toggle/_button_toggle.scss
  src/components/button/button_toggle/_index.scss
  src/components/button/button_toggle/_mixins.scss
  src/components/button/button_toggle/button_toggle.test.tsx
  src/components/button/button_toggle/button_toggle.tsx
  src/components/button/button_toggle/index.ts
  src/components/button/index.ts
  src/components/control_bar/__snapshots__/control_bar.test.tsx.snap
  src/components/datagrid/column_sorting_draggable.tsx
  src/components/datagrid/data_grid.test.tsx
  src/components/index.js
  src/components/index.scss
  src/components/toggle/__snapshots__/toggle.test.tsx.snap
  src/components/toggle/_index.scss
  src/components/toggle/_toggle.scss
  src/components/toggle/index.ts
  src/components/toggle/toggle.test.tsx
  src/components/toggle/toggle.tsx
  src/global_styling/mixins/_button.scss
  src/global_styling/variables/_buttons.scss
  src/themes/eui-amsterdam/global_styling/mixins/_button.scss
  src/themes/eui-amsterdam/overrides/_button.scss
  src/themes/eui-amsterdam/overrides/_button_group.scss
Labels: accessibility, breaking change

#4151 [EuiFilterGroup] and [EuiFilterButton] Fix styling for Amsterdam
  CHANGELOG.md
  src/components/filter_group/_filter_group.scss
  src/themes/eui-amsterdam/overrides/_filter_group.scss
Labels: Amsterdam, style only

#4124 Major version dependency upgrades, pt. V
  CHANGELOG.md
  package.json
  src/components/markdown_editor/markdown_editor.tsx
  src/components/markdown_editor/markdown_format.tsx
  src/components/markdown_editor/plugins/markdown_default_plugins.tsx
  src/components/markdown_editor/unified-plugins.d.ts
  yarn.lock
Labels: dependencies

#4135 Deprecating EuiKeyboardAccessible
  CHANGELOG.md
  src-docs/src/views/accessibility/accessibility_example.js
  src-docs/src/views/steps/steps_horizontal.js
  src/components/code_editor/__snapshots__/code_editor.test.tsx.snap
  src/components/code_editor/_code_editor.scss
  src/components/code_editor/code_editor.tsx
  src/components/steps/__snapshots__/step.test.tsx.snap
  src/components/steps/__snapshots__/step_horizontal.test.tsx.snap
  src/components/steps/__snapshots__/step_number.test.tsx.snap
  src/components/steps/__snapshots__/steps.test.tsx.snap
  src/components/steps/__snapshots__/steps_horizontal.test.tsx.snap
  src/components/steps/_steps_horizontal.scss
  src/components/steps/step.tsx
  src/components/steps/step_horizontal.tsx
  src/components/steps/step_number.tsx
  src/components/steps/step_strings.tsx
  src/components/steps/steps_horizontal.tsx
Labels: accessibility, deprecations

#4028 [Docs] Update alert and console interactions
  src-docs/src/views/accordion/accordion_callback.js
  src-docs/src/views/badge/badge_button.js
  src-docs/src/views/badge/badge_href.js
  src-docs/src/views/badge/playground.js
  src-docs/src/views/breadcrumbs/breadcrumbs.js
  src-docs/src/views/button/button.js
  src-docs/src/views/button/button_empty.js
  src-docs/src/views/button/button_ghost.js
  src-docs/src/views/button/button_icon.js
  src-docs/src/views/button/button_with_icon.js
  src-docs/src/views/button/guidelines.js
  src-docs/src/views/card/card.js
  src-docs/src/views/card/card_beta.js
  src-docs/src/views/card/card_layout.js
  src-docs/src/views/card/card_selectable.js
  src-docs/src/views/code_editor/code_editor.js
  src-docs/src/views/context_menu/context_menu.js
  src-docs/src/views/context_menu/context_menu_with_content.js
  src-docs/src/views/context_menu/single_panel.js
  src-docs/src/views/control_bar/controls.js
  src-docs/src/views/control_bar/tabs.js
  src-docs/src/views/datagrid/additional_controls.js
  src-docs/src/views/datagrid/column_actions.js
  src-docs/src/views/datagrid/control_columns.js
  src-docs/src/views/datagrid/datagrid.js
  src-docs/src/views/datagrid/datagrid_styling_example.js
  src-docs/src/views/datagrid/focus.js
  src-docs/src/views/drag_and_drop/drag_and_drop_bare.js
  src-docs/src/views/drag_and_drop/drag_and_drop_disable_blocking.js
  src-docs/src/views/flex/component_span.tsx
  src-docs/src/views/focus_trap/focus_trap.js
  src-docs/src/views/key_pad_menu/key_pad_menu_item_button.js
  src-docs/src/views/link/link.js
  src-docs/src/views/link/link_disable.js
  src-docs/src/views/list_group/list_group.js
  src-docs/src/views/list_group/list_group_extra.js
  src-docs/src/views/list_group/list_group_link_actions.js
  src-docs/src/views/list_group/pinnable_list_group.tsx
  src-docs/src/views/pagination/customizable_pagination.js
  src-docs/src/views/panel/panel_badge.js
  src-docs/src/views/panel/panel_hover.js
  src-docs/src/views/selectable/search.tsx
  src-docs/src/views/side_nav/side_nav.js
  src-docs/src/views/steps/steps_horizontal.js
  src-docs/src/views/suggest/global_filter_form.js
  src-docs/src/views/suggest/global_filter_item.js
  src-docs/src/views/suggest/saved_queries.js
  src-docs/src/views/suggest/suggest.js
  src-docs/src/views/tables/auto/auto.js
  src-docs/src/views/tables/basic/basic.js
  src-docs/src/views/toast/default.js
  src-docs/src/views/toast/info.js
  src-docs/src/views/tool_tip/tool_tip.js
  src-docs/src/views/tour/tour_example.js
  src-docs/src/views/tree_view/tree_view.js
Labels: documentation

#3668 [Data Grid] Allow adding custom actions to DataGridCells and cell popover
  CHANGELOG.md
  src-docs/src/views/datagrid/column_cell_actions.js
  src-docs/src/views/datagrid/datagrid.js
  src-docs/src/views/datagrid/datagrid_example.js
  src-docs/src/views/datagrid/datagrid_styling_example.js
  src/components/datagrid/__snapshots__/data_grid.test.tsx.snap
  src/components/datagrid/_data_grid_data_row.scss
  src/components/datagrid/data_grid.test.tsx
  src/components/datagrid/data_grid_cell.tsx
  src/components/datagrid/data_grid_cell_buttons.tsx
  src/components/datagrid/data_grid_cell_popover.tsx
  src/components/datagrid/data_grid_data_row.tsx
  src/components/datagrid/data_grid_types.ts
Labels: data grid

#4162 [EuiComboBox] Fix issue with duplicate checkmarks
  CHANGELOG.md
  src/components/combo_box/combo_box.test.tsx
  src/components/combo_box/combo_box_options_list/combo_box_options_list.tsx
Labels: bug

#4169 Table width mobile options
  CHANGELOG.md
  src-docs/src/views/tables/mobile/mobile.js
  src-docs/src/views/tables/mobile/mobile_section.js
  src-docs/src/views/tables/mobile/props_info.js
  src/components/table/table_row_cell.tsx
  src/services/hooks/index.ts
  src/services/hooks/useIsWithinBreakpoints.ts
  src/services/index.ts
Labels: hacktoberfest-accepted

#4178 [Docs] filter_group_multi: update multi select example to be functional
  src-docs/src/views/filter_group/filter_group_multi.js
Labels: hacktoberfest-accepted

#4172 Adds 'opens in new target' text for links for screen readers
  CHANGELOG.md
  src-docs/src/views/link/link.js
  src/components/link/__snapshots__/link.test.tsx.snap
  src/components/link/link.test.tsx
  src/components/link/link.tsx
Labels: accessibility, discussion
