Repository elastic/eui, pull requests merged in 2020-09, with the labels that each got.

#3970 Fix SSR for breadcrumbs and collapsible-nav
  CHANGELOG.md
  src/components/breadcrumbs/breadcrumbs.tsx
  src/components/collapsible_nav/collapsible_nav.tsx
  src/services/breakpoint.ts
Labels: bug

#3994 [Icons] Adding `fold` and `unfold` glyphs to `EuiIcon`
  CHANGELOG.md
  src-docs/src/views/icon/icons.js
  src/components/icon/__snapshots__/icon.test.tsx.snap
  src/components/icon/assets/fold.js
  src/components/icon/assets/fold.svg
  src/components/icon/assets/unfold.js
  src/components/icon/assets/unfold.svg
  src/components/icon/icon.tsx
Labels: icons

#3986 [Docs] Fix link to toast usage guidelines
  src-docs/src/views/toast/toast_example.js
Labels: documentation

#3967 Minor and patch dependencies version updates
  .babelrc.js
  package.json
  src/components/color_picker/color_palette_picker/__snapshots__/color_palette_picker.test.tsx.snap
  src/components/color_picker/utils.test.ts
  src/components/form/super_select/__snapshots__/super_select.test.tsx.snap
  src/components/form/super_select/__snapshots__/super_select_control.test.tsx.snap
  src/components/form/super_select/super_select_control.tsx
  src/services/accessibility/html_id_generator.ts
  yarn.lock
Labels: dependencies

#3991 Fix incorrect variable usage in SCSS
  CHANGELOG.md
  src/components/code/_code_block.scss
Labels: bug

#4002 Fixes docs page navbar showing only in homepage in mobile
  src/components/side_nav/_side_nav.scss
Labels: documentation

#3987 Major version dependency upgrades, pt. I
  package.json
  scripts/release.js
  yarn.lock
Labels: dependencies

#3741 Updates form controls to use the Amsterdam border radius.
  CHANGELOG.md
  src/components/date_picker/super_date_picker/_super_date_picker.scss
  src/components/form/file_picker/_file_picker.scss
  src/components/suggest/__snapshots__/suggest.test.tsx.snap
  src/components/suggest/__snapshots__/suggest_input.test.tsx.snap
  src/components/suggest/_suggest_input.scss
  src/components/suggest/suggest_input.tsx
  src/global_styling/mixins/_form.scss
  src/global_styling/variables/_form.scss
  src/themes/eui-amsterdam/global_styling/mixins/_form.scss
  src/themes/eui-amsterdam/global_styling/mixins/_index.scss
  src/themes/eui-amsterdam/global_styling/variables/_form.scss
  src/themes/eui-amsterdam/global_styling/variables/_index.scss
  src/themes/eui-amsterdam/overrides/_form_control_layout.scss
  src/themes/eui-amsterdam/overrides/_form_control_layout_delimited.scss
  src/themes/eui-amsterdam/overrides/_index.scss
Labels: Amsterdam, style only

#4006 EuiBadge health status docs
  src-docs/src/views/badge/badge_example.js
  src-docs/src/views/badge/badge_health.js
  src-docs/src/views/tables/custom/custom.js
Labels: documentation

#4022 Major version dependency upgrades, pt. II
  .babelrc.js
  .browserslistrc
  CHANGELOG.md
  package.json
  postcss.config.js
  scripts/compile-eui.js
  scripts/dtsgenerator.js
  src-docs/src/components/guide_components.scss
  src-docs/webpack.config.js
  src/webpack.config.js
  yarn.lock
Labels: dependencies

#4008 Updates to EuiSelectableTemplateSitewide and some other fixes for the new header
  CHANGELOG.md
  src-docs/src/components/guide_section/guide_section.js
  src-docs/src/views/header/header_dark.tsx
  src-docs/src/views/header/header_elastic_pattern.js
  src-docs/src/views/header/header_example.js
  src-docs/src/views/header/header_updates.js
  src-docs/src/views/responsive/responsive.js
  src-docs/src/views/responsive/responsive_example.js
  src-docs/src/views/selectable/search.tsx
  src-docs/src/views/selectable/selectable_example.js
  src/components/badge/notification_badge/badge_notification.tsx
  src/components/bottom_bar/_bottom_bar.scss
  src/components/header/_mixins.scss
  src/components/header/header_links/__snapshots__/header_link.test.tsx.snap
  src/components/header/header_links/header_link.test.tsx
  src/components/header/header_links/header_link.tsx
  src/components/header/header_section/__snapshots__/header_section_item_button.test.tsx.snap
  src/components/header/header_section/_header_section_item.scss
  src/components/header/header_section/header_section_item_button.test.tsx
  src/components/header/header_section/header_section_item_button.tsx
  src/components/responsive/__snapshots__/hide_for.test.tsx.snap
  src/components/responsive/__snapshots__/show_for.test.tsx.snap
  src/components/responsive/hide_for.test.tsx
  src/components/responsive/hide_for.tsx
  src/components/responsive/show_for.test.tsx
  src/components/responsive/show_for.tsx
  src/components/selectable/selectable_list/selectable_list.tsx
  src/components/selectable/selectable_templates/__snapshots__/selectable_template_sitewide.test.tsx.snap
  src/components/selectable/selectable_templates/__snapshots__/selectable_template_sitewide_option.test.tsx.snap
  src/components/selectable/selectable_templates/_selectable_template_sitewide.scss
  src/components/selectable/selectable_templates/selectable_template_sitewide.test.tsx
  src/components/selectable/selectable_templates/selectable_template_sitewide.tsx
  src/components/selectable/selectable_templates/selectable_template_sitewide_option.tsx
  src/services/breakpoint.test.ts
  src/services/breakpoint.ts
  src/services/index.ts
  src/themes/eui-amsterdam/overrides/_header.scss
Labels: breaking change

#4045 clean up raw-loader imports in a few places
  src-docs/src/components/codesandbox/link.js
  src-docs/src/views/code/code_block.js
  src-docs/src/views/code/playground.js
  src-docs/src/views/package/changelog.js
Labels: bug, documentation

#3770 [EuiDataGrid] Add footer row
  CHANGELOG.md
  src-docs/src/routes.js
  src-docs/src/views/datagrid/datagrid_footer_row_example.js
  src-docs/src/views/datagrid/datagrid_styling_example.js
  src-docs/src/views/datagrid/footer_row.js
  src-docs/src/views/datagrid/styling.js
  src/components/datagrid/__snapshots__/data_grid.test.tsx.snap
  src/components/datagrid/_data_grid.scss
  src/components/datagrid/_data_grid_footer_row.scss
  src/components/datagrid/_data_grid_header_row.scss
  src/components/datagrid/_index.scss
  src/components/datagrid/_mixins.scss
  src/components/datagrid/data_grid.tsx
  src/components/datagrid/data_grid_body.tsx
  src/components/datagrid/data_grid_footer_row.tsx
  src/components/datagrid/data_grid_header_cell.tsx
  src/components/datagrid/data_grid_header_row.tsx
  src/components/datagrid/data_grid_types.ts
  src/components/datagrid/style_selector.tsx
Labels: data grid

#4038 Add controlled pagination props to EuiInMemoryTable
  CHANGELOG.md
  src-docs/src/views/tables/in_memory/in_memory_controlled_pagination.js
  src-docs/src/views/tables/in_memory/in_memory_controlled_pagination_section.js
  src-docs/src/views/tables/in_memory/index.js
  src-docs/src/views/tables/in_memory/props_info.js
  src-docs/src/views/tables/tables_in_memory_example.js
  src/components/basic_table/in_memory_table.test.tsx
  src/components/basic_table/in_memory_table.tsx
Labels: tables

#3087 [DATA GRID] Column header menu
  CHANGELOG.md
  src-docs/src/views/datagrid/column_actions.js
  src-docs/src/views/datagrid/datagrid.js
  src-docs/src/views/datagrid/datagrid_example.js
  src-docs/src/views/datagrid/datagrid_schema_example.js
  src-docs/src/views/datagrid/datagrid_styling_example.js
  src-docs/src/views/datagrid/focus.js
  src/components/datagrid/__snapshots__/data_grid.test.tsx.snap
  src/components/datagrid/_data_grid_data_row.scss
  src/components/datagrid/_data_grid_header_row.scss
  src/components/datagrid/_mixins.scss
  src/components/datagrid/column_actions.tsx
  src/components/datagrid/column_selector.tsx
  src/components/datagrid/data_grid.test.tsx
  src/components/datagrid/data_grid.tsx
  src/components/datagrid/data_grid_header_cell.tsx
  src/components/datagrid/data_grid_header_row.tsx
  src/components/datagrid/data_grid_types.ts
Labels: data grid, feature request

#4009 Update docgen info in dev server when files change
  scripts/babel/react-docgen-typescript.js
Labels: documentation, typescript

#4050 Bump misc. deps
  packages/react-datepicker.js
  packages/react-datepicker/package.json
  packages/react-datepicker/yarn.lock
  yarn.lock
Labels: dependencies

#4066 [EuiCallout] Remove border radius from Amsterdam
  CHANGELOG.md
  src/themes/eui-amsterdam/overrides/_call_out.scss
Labels: Amsterdam

#4076 Amsterdam toast update
  CHANGELOG.md
  src/components/toast/_toast.scss
  src/themes/eui-amsterdam/overrides/_index.scss
  src/themes/eui-amsterdam/overrides/_toast.scss
Labels: Amsterdam, style only

#4064 [Docs] Swap secondary color for success color
  src-docs/src/views/guidelines/colors.js
  src-docs/src/views/guidelines/colors/_utilities.js
Labels: documentation

#4079 Fix EuiTitle lineheight
  CHANGELOG.md
  src/themes/eui-amsterdam/global_styling/variables/_typography.scss
Labels: Amsterdam, style only
