Repository elastic/eui, pull requests merged in 2021-05, with the labels that each got.

#4785 [i18n] EuiTourStepIndicator to use EuiI18n following the standard way
  CHANGELOG.md
  i18ntokens.json
  src/components/tour/tour_step_indicator.tsx
Labels: bug

#4794 Updating Stale workflow to exclude...
  .github/workflows/stale_issues.yml
Labels: skip-changelog

#4808 Bump dependencies
  package.json
  packages/react-datepicker.js
  packages/react-datepicker/docs-site/bundle.js
  packages/react-datepicker/yarn.lock
  src/components/date_picker/__snapshots__/date_picker.test.tsx.snap
  yarn.lock
Labels: skip-changelog

#4834 [Deps] Add `mdast-util-to-hast`
  package.json
Labels: skip-changelog

#4798 [EuiBetaBadge] Add color and size props and support for click event
  CHANGELOG.md
  src-docs/src/views/badge/badge_example.js
  src-docs/src/views/badge/beta_badge.js
  src-docs/src/views/card/card_beta.js
  src/components/badge/beta_badge/__snapshots__/beta_badge.test.tsx.snap
  src/components/badge/beta_badge/_beta_badge.scss
  src/components/badge/beta_badge/beta_badge.test.tsx
  src/components/badge/beta_badge/beta_badge.tsx
  src/components/badge/notification_badge/_notification_badge.scss
  src/components/card/__snapshots__/card.test.tsx.snap
  src/components/card/_card.scss
  src/components/card/card.test.tsx
  src/components/card/card.tsx
  src/global_styling/mixins/_beta_badge.scss
Labels: deprecations

#4839 Removing text transform from EuiTour.
  CHANGELOG.md
  src/components/tour/_tour.scss
Labels: style only
