Repository elastic/eui, pull requests merged in 2021-08, with the labels that each got.

#4999 [Docs] Fixed exit full screen link back
  src-docs/src/services/routing/routing.ts
Labels: documentation, skip-changelog

#5028 Update component-development.md
  wiki/component-development.md
Labels: documentation, skip-changelog

#5021 [EuiSelectable] Fix logic to detect the blur event coming from child popover
  CHANGELOG.md
  src/components/selectable/__snapshots__/selectable.test.tsx.snap
  src/components/selectable/selectable.test.tsx
  src/components/selectable/selectable.tsx
Labels: bug

#5035 Minor wiki docs fixes
  wiki/automated-accessibility-testing.md
  wiki/component-design.md
  wiki/component-development.md
  wiki/consuming.md
  wiki/documentation-guidelines.md
  wiki/react-router.md
Labels: documentation, skip-changelog

#5036 Wiki documentation suggestions for Component development > Tests
  wiki/component-development.md
Labels: documentation, skip-changelog

#5039 Wiki changelog skip suggestion
  wiki/documentation-guidelines.md
Labels: skip-changelog

#5041 Remove Sketch references from Creating icons wiki
  wiki/creating-icons.md
Labels: skip-changelog

#5051 [Docs only] Fix type error in EuiDataGrid props table
  src-docs/src/views/datagrid/datagrid_example.js
Labels: skip-changelog

#5000 [EuiDatePicker] Update styles for Amsterdam
  .sass-lint.yml
  CHANGELOG.md
  src-docs/src/views/icon/icon_example.js
  src/components/date_picker/__snapshots__/date_picker.test.tsx.snap
  src/components/date_picker/__snapshots__/date_picker_range.test.tsx.snap
  src/components/date_picker/_date_picker_range.scss
  src/components/date_picker/_index.scss
  src/components/date_picker/date_picker.tsx
  src/components/date_picker/date_picker_range.tsx
  src/global_styling/functions/_colors.scss
  src/global_styling/index.scss
  src/global_styling/react_date_picker/_date_picker.scss
  src/global_styling/react_date_picker/_index.scss
  src/global_styling/react_date_picker/_variables.scss
  src/themes/eui-amsterdam/global_styling/index.scss
  src/themes/eui-amsterdam/global_styling/mixins/_button.scss
  src/themes/eui-amsterdam/global_styling/react_date_picker/_date_picker.scss
  src/themes/eui-amsterdam/global_styling/react_date_picker/_date_picker_days.scss
  src/themes/eui-amsterdam/global_styling/react_date_picker/_date_picker_month_year.scss
  src/themes/eui-amsterdam/global_styling/react_date_picker/_date_picker_navigation.scss
  src/themes/eui-amsterdam/global_styling/react_date_picker/_date_picker_times.scss
  src/themes/eui-amsterdam/global_styling/react_date_picker/_index.scss
  src/themes/eui-amsterdam/global_styling/react_date_picker/_mixins.scss
  src/themes/eui-amsterdam/global_styling/react_date_picker/_variables.scss
Labels: style only, Amsterdam

#5045 [Tech debt] Update various linter ignore files
  .eslintignore
  .stylelintrc
  src-docs/src/views/icon/icon_example.js
Labels: skip-changelog

#5054 [euiHeaderAffordForFixed] Don't apply offset styles to EuiOverlayMask or EuiFlyout when EuiDataGrid is full screen
  CHANGELOG.md
  src-docs/src/views/datagrid/datagrid.js
  src/components/datagrid/_data_grid.scss
  src/components/datagrid/_variables.scss
  src/global_styling/mixins/_header.scss
Labels: bug, !urgent!

#5062 [Linting] Fix Prettier linting issue in master
  src-docs/src/views/icon/icon_example.js
Labels: skip-changelog

#5064 [Docs only] Fix EuiFilePicker example file list on Firefox
  src-docs/src/views/form_controls/file_picker.js
Labels: skip-changelog

#5075 [Tech debt/docs] Unit test updates
  scripts/jest/config.json
  wiki/component-development.md
  wiki/testing.md
Labels: skip-changelog

#5093 Updating releasing-versions.md
  wiki/releasing-versions.md
Labels: chore, platform, skip-changelog

#5103 Update documentation for service imports
  src-docs/src/components/guide_section/_utils.js
  src-docs/src/services/string/clean_imports.js
  wiki/consuming.md
Labels: documentation, skip-changelog

#5011 [EuiFlyout] Fix prop table; refactor
  src/components/common.ts
  src/components/flyout/flyout.tsx
Labels: skip-changelog

#5065 [Docs] Upgrading EUI in Kibana
  wiki/upgrading-kibana.md
Labels: skip-changelog
