Repository elastic/eui, pull requests merged in 2021-07, with the labels that each got.

#4934 Replaced HTML with XHTML in EuiText
  src-docs/src/views/text/text_example.js
Labels: skip-changelog

#4937 docs: fix a broken link in the EuiMarkdownFormat section
  src-docs/src/views/markdown_editor/mardown_format_example.js
Labels: documentation, skip-changelog

#4927 Define set of i18n tokens via TypeScript
  CHANGELOG.md
  scripts/dtsgenerator.js
Labels: platform, typescript

#4886 [EuiColorPicker] a11y polish
  CHANGELOG.md
  src/components/color_picker/__snapshots__/color_picker.test.tsx.snap
  src/components/color_picker/__snapshots__/saturation.test.tsx.snap
  src/components/color_picker/_color_picker.scss
  src/components/color_picker/color_picker.test.tsx
  src/components/color_picker/color_picker.tsx
  src/components/color_picker/color_picker_swatch.tsx
  src/components/color_picker/saturation.tsx
  src/components/popover/popover.tsx
Labels: accessibility

#4945 [EuiCodeBlock] Added inline code samples to support CodeSandbox
  src-docs/src/views/code/code_block.js
  src-docs/src/views/code/code_examples/example.js
  src-docs/src/views/code/code_examples/example.sql
  src-docs/src/views/code/playground.js
Labels: documentation, skip-changelog

#4946 [Docs] Organizing the docs' main Sass
  src-docs/src/components/_index.scss
  src-docs/src/components/guide_components.scss
  src-docs/src/components/guide_page/_guide_page.scss
  src-docs/src/components/guide_page/guide_page_header.tsx
  src-docs/src/components/guide_section/_guide_section.scss
  src-docs/src/theme_amsterdam_dark.scss
  src-docs/src/theme_amsterdam_light.scss
  src-docs/src/theme_dark.scss
  src-docs/src/theme_light.scss
  src-docs/src/views/_index.scss
  src-docs/src/views/datagrid/_datagrid.scss
  src-docs/src/views/date_picker/_date_picker.scss
  src-docs/src/views/date_picker/classes.js
  src-docs/src/views/elastic_charts/_index.scss
  src-docs/src/views/elastic_charts/_theming_categorical.scss
  src-docs/src/views/elastic_charts/theming_categorical.js
  src-docs/src/views/flex/_flex.scss
  src-docs/src/views/guidelines/_index.scss
  src-docs/src/views/home/_home.scss
  src-docs/src/views/horizontal_rule/_horizontal_rule.scss
  src-docs/src/views/markdown_editor/markdown_editor_height.js
  src-docs/src/views/notification_event/_notification_event.scss
  src-docs/src/views/notification_event/notification_event_props_methods.js
  src-docs/src/views/page/_page.scss
  src-docs/src/views/selectable/_search.scss
  src-docs/src/views/spacer/_spacer.scss
  src-docs/src/views/suggest/_global_filter_group.scss
  src-docs/src/views/suggest/_index.scss
  src-docs/src/views/text_scaling/_text_scaling.scss
  src-docs/src/views/tree_view/_tree_view.scss
  src-docs/src/views/tree_view/compressed.js
Labels: documentation, skip-changelog

#4955 [EuiDataGrid] Fix initial alignment of cells and expand button on multi-line cells
  CHANGELOG.md
  src-docs/src/views/datagrid/datagrid_height_options_example.js
  src-docs/src/views/datagrid/row_height_options.js
  src/components/datagrid/__snapshots__/data_grid.test.tsx.snap
  src/components/datagrid/_data_grid_data_row.scss
  src/components/datagrid/data_grid_cell.tsx
  src/components/datagrid/row_height_utils.ts
Labels: bug

#4962 [EuiDataGrid] Adding a docs section about nesting in a flex item
  src-docs/src/views/datagrid/container.js
  src-docs/src/views/datagrid/datagrid_styling_example.js
  src-docs/src/views/datagrid/flex.js
Labels: skip-changelog

#4751 [Docs] Added section on (accessible) form labels
  src-docs/src/views/form_layouts/accessible_labels.js
  src-docs/src/views/form_layouts/described_form_group.js
  src-docs/src/views/form_layouts/difficult_accessibility_labels.js
  src-docs/src/views/form_layouts/form_layouts_example.js
  src-docs/src/views/form_layouts/form_rows.js
  src-docs/src/views/form_layouts/implicit_titles.js
  src-docs/src/views/guidelines/accessibility.js
Labels: skip-changelog

#4965 [EuiButton] Fixed up docs page and a couple component fixes
  CHANGELOG.md
  src-docs/src/components/guide_section/guide_section.tsx
  src-docs/src/views/button/button.js
  src-docs/src/views/button/button_as_link.js
  src-docs/src/views/button/button_empty.js
  src-docs/src/views/button/button_empty_flush.js
  src-docs/src/views/button/button_example.js
  src-docs/src/views/button/button_group_compressed.js
  src-docs/src/views/button/button_icon.js
  src-docs/src/views/button/button_loading.js
  src-docs/src/views/button/button_toggle.js
  src-docs/src/views/button/button_toggle_aria.js
  src-docs/src/views/button/button_with_icon.js
  src-docs/src/views/button/playground.js
  src-docs/src/views/button/split_button.js
  src/components/button/button_content.tsx
  src/components/button/button_empty/__snapshots__/button_empty.test.tsx.snap
  src/components/button/button_empty/button_empty.tsx
Labels: breaking change

#4916 docs(elastic charts docs): elastic-chart a11y features into eui docs
  package.json
  scripts/babel/react-docgen-typescript.js
  src-docs/src/routes.js
  src-docs/src/views/elastic_charts/accessibility_bullet.js
  src-docs/src/views/elastic_charts/accessibility_example.js
  src-docs/src/views/elastic_charts/accessibility_sunburst.js
  src-docs/src/views/elastic_charts/data.js
  src-docs/src/views/elastic_charts/goal.js
  src-docs/src/views/elastic_charts/pie.js
  src-docs/src/views/elastic_charts/texture.js
  src-docs/src/views/elastic_charts/texture_props.tsx
  src/themes/charts/themes.ts
  yarn.lock
Labels: Elastic Charts, accessibility, documentation, skip-changelog

#4985 [Deps] Bump `url-parse`
  package.json
  yarn.lock
Labels: skip-changelog

#4763 [EuiBreadcrumbs] a11y polish
  CHANGELOG.md
  src-docs/src/views/breadcrumbs/breadcrumbs.js
  src/components/breadcrumbs/__snapshots__/breadcrumbs.test.tsx.snap
  src/components/breadcrumbs/_breadcrumbs.scss
  src/components/breadcrumbs/breadcrumbs.test.tsx
  src/components/breadcrumbs/breadcrumbs.tsx
  src/components/control_bar/__snapshots__/control_bar.test.tsx.snap
  src/components/control_bar/_control_bar.scss
  src/components/header/__snapshots__/header.test.tsx.snap
  src/components/header/header_breadcrumbs/__snapshots__/header_breadcrumbs.test.tsx.snap
  src/components/header/header_breadcrumbs/_header_breadcrumbs.scss
  src/components/link/_link.scss
  src/global_styling/mixins/_link.scss
  src/themes/eui-amsterdam/global_styling/mixins/_link.scss
  src/themes/eui-amsterdam/overrides/_breadcrumbs.scss
  src/themes/eui-amsterdam/overrides/_header.scss
  src/themes/eui-amsterdam/overrides/_header_breadcrumbs.scss
  src/themes/eui-amsterdam/overrides/_index.scss
Labels: accessibility

#4988 Update component-development.md
  wiki/component-development.md
Labels: documentation, skip-changelog

#4991 Remove EuiKeyboardAccessible
  CHANGELOG.md
  src-docs/src/views/accessibility/accessibility_example.js
  src-docs/src/views/accessibility/keyboard_accessible.js
  src/components/accessibility/__snapshots__/keyboard_accessible.test.tsx.snap
  src/components/accessibility/index.ts
  src/components/accessibility/keyboard_accessible.test.tsx
  src/components/accessibility/keyboard_accessible.ts
  src/components/basic_table/__snapshots__/basic_table.test.tsx.snap
  src/components/basic_table/basic_table.tsx
  src/components/index.js
  src/components/table/table_row.tsx
Labels: breaking change
