Repository elastic/eui, pull requests merged in 2021-12, with the labels that each got.

#5434 [Docs] Add `@emotion/react` to codesandbox `dependecies`
  src-docs/src/components/codesandbox/link.js
Labels: skip-changelog

#5437 [EuiPopover] Fix removeEventListener with mismatched capture flag
  CHANGELOG.md
  src/components/popover/popover.tsx
Labels: bug

#5443 [Docs] Fix broken TSX demos/CodeSandbox links
  src-docs/src/components/guide_section/guide_section_parts/guide_section_code.tsx
Labels: skip-changelog

#5444 [Docs] Use `<meta>` tag for global style insertion point
  src-docs/src/index.html
  src-docs/src/views/app_context.js
Labels: skip-changelog

#5441 [EuiDatePicker] Better handle `onBlur` callback
  CHANGELOG.md
  src/components/date_picker/__snapshots__/date_picker.test.tsx.snap
  src/components/date_picker/react-datepicker/src/calendar.js
  src/components/date_picker/react-datepicker/src/index.js
  src/components/tool_tip/tool_tip.tsx
Labels: !urgent!

#5445 [Cypress] Attempt to harden flaking EuiContextMenuPanel specs
  src/components/context_menu/context_menu_panel.spec.tsx
Labels: skip-changelog

#5383 [EuiSuperDatePicker] Fixes for width and auto refresh
  CHANGELOG.md
  src-docs/src/routes.js
  src-docs/src/views/auto_refresh/auto_refresh_button.tsx
  src-docs/src/views/auto_refresh/auto_refresh_example.js
  src-docs/src/views/auto_refresh/auto_refresh_input.tsx
  src-docs/src/views/auto_refresh/auto_refresh_interval.tsx
  src-docs/src/views/auto_refresh/playground.js
  src-docs/src/views/form_controls/form_control_layout.js
  src-docs/src/views/icon/icons.js
  src-docs/src/views/suggest/saved_queries.js
  src-docs/src/views/super_date_picker/auto_refresh.tsx
  src-docs/src/views/super_date_picker/auto_refresh_only.tsx
  src-docs/src/views/super_date_picker/playground.js
  src-docs/src/views/super_date_picker/props.tsx
  src-docs/src/views/super_date_picker/super_date_picker.js
  src-docs/src/views/super_date_picker/super_date_picker.tsx
  src-docs/src/views/super_date_picker/super_date_picker_config.js
  src-docs/src/views/super_date_picker/super_date_picker_config.tsx
  src-docs/src/views/super_date_picker/super_date_picker_custom_quick_select.js
  src-docs/src/views/super_date_picker/super_date_picker_custom_quick_select.tsx
  src-docs/src/views/super_date_picker/super_date_picker_example.js
  src-docs/src/views/super_date_picker/super_date_picker_pattern.tsx
  src-docs/src/views/super_date_picker/super_date_picker_width.tsx
  src-docs/src/views/super_date_picker/super_date_picker_width_example.tsx
  src/components/date_picker/auto_refresh/__snapshots__/auto_refresh.test.tsx.snap
  src/components/date_picker/auto_refresh/auto_refresh.test.tsx
  src/components/date_picker/auto_refresh/auto_refresh.tsx
  src/components/date_picker/auto_refresh/index.ts
  src/components/date_picker/auto_refresh/refresh_interval.tsx
  src/components/date_picker/index.ts
  src/components/date_picker/super_date_picker/__snapshots__/super_date_picker.test.tsx.snap
  src/components/date_picker/super_date_picker/__snapshots__/super_update_button.test.tsx.snap
  src/components/date_picker/super_date_picker/_index.scss
  src/components/date_picker/super_date_picker/_super_date_picker.scss
  src/components/date_picker/super_date_picker/_super_update_button.scss
  src/components/date_picker/super_date_picker/date_popover/_date_popover_button.scss
  src/components/date_picker/super_date_picker/date_popover/date_popover_button.tsx
  src/components/date_picker/super_date_picker/date_popover/relative_tab.tsx
  src/components/date_picker/super_date_picker/pretty_interval.test.ts
  src/components/date_picker/super_date_picker/pretty_interval.ts
  src/components/date_picker/super_date_picker/quick_select_popover/__snapshots__/quick_select.test.tsx.snap
  src/components/date_picker/super_date_picker/quick_select_popover/__snapshots__/quick_select_popover.test.tsx.snap
  src/components/date_picker/super_date_picker/quick_select_popover/commonly_used_time_ranges.tsx
  src/components/date_picker/super_date_picker/quick_select_popover/quick_select.tsx
  src/components/date_picker/super_date_picker/quick_select_popover/quick_select_popover.test.tsx
  src/components/date_picker/super_date_picker/quick_select_popover/quick_select_popover.tsx
  src/components/date_picker/super_date_picker/quick_select_popover/recently_used.tsx
  src/components/date_picker/super_date_picker/super_date_picker.test.tsx
  src/components/date_picker/super_date_picker/super_date_picker.tsx
  src/components/date_picker/super_date_picker/super_update_button.test.tsx
  src/components/date_picker/super_date_picker/super_update_button.tsx
  src/components/form/form_control_layout/_form_control_layout.scss
  src/components/icon/__snapshots__/icon.test.tsx.snap
  src/components/icon/assets/timeRefresh.tsx
  src/components/icon/icon.tsx
  src/components/icon/svgs/timeRefresh.svg
  src/global_styling/variables/_form.scss
  src/themes/amsterdam/overrides/_date_picker.scss
Labels: breaking change

#5449 [Cypress] Fix missing reset styles
  cypress/support/commands.js
  cypress/support/index.d.ts
  cypress/support/index.js
  src/components/context_menu/context_menu_panel.spec.tsx
  src/components/datagrid/data_grid.spec.tsx
  src/components/focus_trap/focus_trap.spec.tsx
Labels: test, skip-changelog

#5452 [Global reset] Fix reset of `button` styles
  CHANGELOG.md
  src/global_styling/reset/global_styles.tsx
  src/global_styling/reset/reset.ts
Labels: bug, !urgent!

#5448 [Docs] Update to reflect `<meta>`; codesandbox link
  src-docs/src/components/codesandbox/link.js
  src-docs/src/views/provider/provider.md
Labels: skip-changelog

#5457 Remove duplicate entry in `i18ntokens_changelog.json`
  i18ntokens_changelog.json
Labels: skip-changelog

#5446 Upgrade to Node 16
  .nvmrc
  package.json
  scripts/deploy/build_docs
  scripts/deploy/deploy_docs
  scripts/docker-ci/Dockerfile
  scripts/docker-ci/README.md
  scripts/test-docker.js
  yarn.lock
Labels: skip-changelog, tech debt

#5459 Upgrade Cypress to latest
  .ci/jobs/elastic+eui+pull-request-test.yml
  package.json
  src/components/context_menu/__snapshots__/context_menu_panel.test.tsx.snap
  yarn.lock
Labels: skip-changelog, tech debt

#5466 Adding unique IDs to `EuiDatePicker` Time component options.
  CHANGELOG.md
  src/components/date_picker/react-datepicker/src/time.js
Labels: accessibility, WCAG A, accessibility - automated

#5469 [EuiSuperDatePicker] Small unit test clean up
  src/components/date_picker/super_date_picker/async_interval.test.ts
Labels: skip-changelog

#5467 [EuiDataGrid] Added focus management cypress tests for data grid
  cypress/support/index.js
  package.json
  src/components/datagrid/body/data_grid_cell_popover.test.tsx
  src/components/datagrid/body/data_grid_cell_popover.tsx
  src/components/datagrid/data_grid.spec.tsx
  yarn.lock
Labels: data grid, skip-changelog

#5475 [Docs][Proposal] Enable react-refresh in docs development
  package.json
  src-docs/webpack.config.js
  yarn.lock
Labels: documentation, skip-changelog

#5492 Update elastic-charts to v41.0.1
  CHANGELOG.md
  package.json
  src-docs/src/views/elastic_charts/accessibility_sunburst.js
  src-docs/src/views/elastic_charts/pie.js
  src-docs/src/views/elastic_charts/pie_example.js
  src-docs/src/views/elastic_charts/pie_slices.js
  src-docs/src/views/elastic_charts/treemap.js
  src/themes/charts/themes.ts
  yarn.lock
Labels: dependencies, Elastic Charts

#5494 [EuiModal] Wrapping header in H1 if a string is returned
  CHANGELOG.md
  src/components/modal/__snapshots__/confirm_modal.test.tsx.snap
  src/components/modal/__snapshots__/modal_header_title.test.tsx.snap
  src/components/modal/modal_header_title.tsx
Labels: accessibility, accessibility - cognition

#5501 [EuiDatePicker] Update ARIA and role attributes for better screen reader accessibility
  CHANGELOG.md
  src/components/date_picker/__snapshots__/date_picker.test.tsx.snap
  src/components/date_picker/react-datepicker/src/day.js
  src/components/date_picker/react-datepicker/src/month.js
  src/components/date_picker/react-datepicker/src/time.js
Labels: accessibility, accessibility - screen reader

#5509 [EuiDatePicker] Moved `Time` component tabindex to UL
  CHANGELOG.md
  src/components/date_picker/react-datepicker/src/time.js
Labels: accessibility, accessibility - screen reader, accessibility - cognition
