Repository elastic/eui, pull requests merged in 2021-09, with the labels that each got.

#5119 [EuiSwitch] Add guidelines around labelling
  src-docs/src/views/form_controls/form_controls_example.js
  src-docs/src/views/form_controls/switch.js
  src-docs/src/views/form_controls/switch_label.tsx
Labels: documentation, skip-changelog

#5123 Revert temporary docs change
  src-docs/src/views/selectable/data.ts
  src-docs/src/views/selectable/selectable_popover.js
Labels: skip-changelog

#5125 [EuiDataGrid] Add unit tests for body/ components + minor refactors
  src/components/datagrid/body/__snapshots__/data_grid_body.test.tsx.snap
  src/components/datagrid/body/__snapshots__/data_grid_cell.test.tsx.snap
  src/components/datagrid/body/data_grid_body.test.tsx
  src/components/datagrid/body/data_grid_body.tsx
  src/components/datagrid/body/data_grid_cell.test.tsx
  src/components/datagrid/body/data_grid_cell.tsx
  src/components/datagrid/body/data_grid_cell_buttons.test.tsx
  src/components/datagrid/body/data_grid_cell_popover.test.tsx
  src/components/datagrid/body/data_grid_footer_row.test.tsx
  src/components/datagrid/body/data_grid_footer_row.tsx
  src/components/datagrid/body/popover_utils.test.tsx
  src/components/datagrid/body/popover_utils.tsx
  src/components/datagrid/data_grid_schema.tsx
  src/components/datagrid/data_grid_types.ts
  src/components/observer/resize_observer/resize_observer.tsx
Labels: skip-changelog, tech debt

#5096 [Docs] Moved Playground to a flyout
  src-docs/src/components/guide_section/_guide_section.scss
  src-docs/src/components/guide_section/guide_section.tsx
  src-docs/src/components/guide_section/guide_section_parts/guide_section_props_description.tsx
  src-docs/src/components/guide_section/guide_section_parts/guide_section_tabs.tsx
  src-docs/src/services/playground/_playground_compiler.scss
  src-docs/src/services/playground/knobs.js
  src-docs/src/services/playground/markdown_format/index.js
  src-docs/src/services/playground/markdown_format/plugin_list.js
  src-docs/src/services/playground/markdown_format/props_link_plugin.js
  src-docs/src/services/playground/playground.js
  src-docs/src/views/aspect_ratio/aspect_ratio_example.js
  src-docs/src/views/avatar/avatar_example.js
  src-docs/src/views/badge/badge_example.js
  src-docs/src/views/bottom_bar/playground.js
  src-docs/src/views/call_out/call_out_example.js
  src-docs/src/views/color_picker/color_picker_example.js
  src-docs/src/views/color_picker/playground.js
  src-docs/src/views/comment/comment_example.js
  src-docs/src/views/expression/expression_example.js
  src-docs/src/views/image/image_example.js
  src-docs/src/views/page/_page.scss
  src-docs/src/views/page/playground.js
  src-docs/src/views/panel/playground.js
  src-docs/src/views/progress/progress_example.js
  src-docs/src/views/range/range_example.js
  src-docs/src/views/stat/stat_example.js
  src-docs/src/views/tabs/tabs_example.js
  src-docs/src/views/text/text_example.js
  src-docs/src/views/title/title_example.js
  src-docs/src/views/toast/toast_example.js
Labels: documentation, skip-changelog

#5153 [Misc] Fix typo in PR template
  .github/pull_request_template.md
Labels: skip-changelog

#5135 [EuiTabs] Consolidated styling options for Amsterdam and updated usage in EuiPageHeader
  CHANGELOG.md
  src-docs/src/components/guide_section/_guide_section.scss
  src-docs/src/views/page_header/page_header.js
  src-docs/src/views/page_header/page_header.tsx
  src-docs/src/views/page_header/page_header_custom.tsx
  src-docs/src/views/page_header/page_header_example.js
  src-docs/src/views/page_header/page_header_tabs.js
  src-docs/src/views/page_header/page_header_tabs.tsx
  src-docs/src/views/page_header/page_header_tabs_title.tsx
  src-docs/src/views/page_header/playground.js
  src-docs/src/views/tabs/controlled.tsx
  src-docs/src/views/tabs/playground.js
  src-docs/src/views/tabs/tabbed_content.js
  src-docs/src/views/tabs/tabbed_content.tsx
  src-docs/src/views/tabs/tabs.js
  src-docs/src/views/tabs/tabs.tsx
  src-docs/src/views/tabs/tabs_condensed.js
  src-docs/src/views/tabs/tabs_example.js
  src-docs/src/views/tabs/tabs_flyout.tsx
  src-docs/src/views/tabs/tabs_small.tsx
  src/components/page/__snapshots__/page_template.test.tsx.snap
  src/components/page/page_body/_page_body.scss
  src/components/page/page_header/__snapshots__/page_header.test.tsx.snap
  src/components/page/page_header/__snapshots__/page_header_content.test.tsx.snap
  src/components/page/page_header/_page_header.scss
  src/components/page/page_header/page_header.test.tsx
  src/components/page/page_header/page_header.tsx
  src/components/page/page_header/page_header_content.test.tsx
  src/components/page/page_header/page_header_content.tsx
  src/components/tabs/__snapshots__/tab.test.tsx.snap
  src/components/tabs/__snapshots__/tabs.test.tsx.snap
  src/components/tabs/_index.scss
  src/components/tabs/_tabs.scss
  src/components/tabs/_variables.scss
  src/components/tabs/tab.test.tsx
  src/components/tabs/tab.tsx
  src/components/tabs/tabbed_content/__snapshots__/tabbed_content.test.tsx.snap
  src/components/tabs/tabbed_content/tabbed_content.test.tsx
  src/components/tabs/tabbed_content/tabbed_content.tsx
  src/components/tabs/tabs.tsx
  src/themes/eui-amsterdam/overrides/_notification_badge.scss
  src/themes/eui-amsterdam/overrides/_tabs.scss
Labels: deprecations

#5161 [Deps] Bump `caniuse-lite`
  yarn.lock
Labels: skip-changelog

#5160 [Docs] Add support for `.tsx` CodeSandbox demos
  src-docs/src/components/codesandbox/link.js
  src-docs/src/components/guide_section/guide_section.tsx
  src-docs/src/components/guide_section/guide_section_parts/guide_section_code.tsx
  src-docs/src/components/guide_section/guide_section_parts/guide_section_tabs.tsx
  src-docs/src/components/guide_section/guide_section_types.tsx
  src-docs/src/views/tabs/tabs_example.js
Labels: skip-changelog

#5163 [EuiDataGrid] Actually fix calls to tabbable instead of moving the issue to a different part of the code
  CHANGELOG.md
  src/components/datagrid/body/data_grid_body.test.tsx
  src/components/datagrid/body/data_grid_body.tsx
Labels: !urgent!, data grid, performance

#5182 Bump typescript version to ~4.1.3
  CHANGELOG.md
  package.json
  src/components/icon/icon.test.tsx
  src/components/selectable/selectable_templates/selectable_template_sitewide.tsx
  yarn.lock
Labels: platform, breaking change, typescript

#5152 [EuiScreenReaderOnly] Add `clip` property to fix scrolling bug
  CHANGELOG.md
  src-docs/src/views/accessibility/accessibility_example.js
  src-docs/src/views/accessibility/screen_reader.tsx
  src-docs/src/views/accessibility/screen_reader_focus.tsx
  src-docs/src/views/accessibility/skip_link.tsx
  src/components/form/checkbox/_checkbox.scss
  src/components/form/radio/_radio.scss
  src/components/link/_link.scss
  src/global_styling/mixins/_helpers.scss
Labels: breaking change, accessibility

#5187 [Docs] Writing styles with Emotion
  CONTRIBUTING.md
  wiki/writing-styles-with-emotion.md
Labels: skip-changelog

#5184 [EuiDataGrid] Refactor + write unit tests for body/header/column_actions
  src/components/datagrid/body/header/column_actions.test.tsx
  src/components/datagrid/body/header/column_actions.tsx
  src/components/datagrid/body/header/data_grid_header_cell.tsx
Labels: test, skip-changelog, tech debt

#5192 [EuiDataGrid] Refactor + write unit tests for header cell components
  src/components/datagrid/body/__snapshots__/data_grid_body.test.tsx.snap
  src/components/datagrid/body/data_grid_body.test.tsx
  src/components/datagrid/body/header/__snapshots__/data_grid_header_cell.test.tsx.snap
  src/components/datagrid/body/header/data_grid_control_header_cell.test.tsx
  src/components/datagrid/body/header/data_grid_control_header_cell.tsx
  src/components/datagrid/body/header/data_grid_header_cell.test.tsx
  src/components/datagrid/body/header/data_grid_header_cell.tsx
  src/components/datagrid/body/header/data_grid_header_cell_wrapper.test.tsx
  src/components/datagrid/body/header/data_grid_header_cell_wrapper.tsx
  src/components/datagrid/body/header/data_grid_header_row.tsx
  src/components/datagrid/data_grid_types.ts
Labels: test, skip-changelog, tech debt

#5193 [EuiDataGrid] Add remaining header unit tests
  src/components/datagrid/body/header/data_grid_column_resizer.test.tsx
  src/components/datagrid/body/header/data_grid_header_row.test.tsx
Labels: test, skip-changelog

#5197 [EuiSuperSelect] Fix regenerating and missing IDs
  src/components/color_picker/color_palette_picker/__snapshots__/color_palette_picker.test.tsx.snap
  src/components/form/super_select/__snapshots__/super_select.test.tsx.snap
  src/components/form/super_select/__snapshots__/super_select_control.test.tsx.snap
  src/components/form/super_select/super_select_control.tsx
Labels: skip-changelog, tech debt

#5177 [Amsterdam] Fixed EuiButtonGroup's border-radius and font-weight, and Fixed EuiButton's text color for text colors
  CHANGELOG.md
  src/themes/eui-amsterdam/overrides/_button.scss
  src/themes/eui-amsterdam/overrides/_button_group.scss
Labels: style only, Amsterdam

#5200 [EuiSuperDatePicker] Fix multiple IDs regenerating on rerender
  src/components/date_picker/super_date_picker/date_popover/relative_tab.tsx
  src/components/date_picker/super_date_picker/quick_select_popover/commonly_used_time_ranges.tsx
  src/components/date_picker/super_date_picker/quick_select_popover/quick_select.tsx
  src/components/date_picker/super_date_picker/quick_select_popover/recently_used.tsx
  src/components/date_picker/super_date_picker/quick_select_popover/refresh_interval.tsx
Labels: skip-changelog, tech debt

#5201 Fix multiple class components to not regenerate IDs on rerender
  src/components/accordion/accordion.tsx
  src/components/combo_box/combo_box_input/combo_box_input.tsx
  src/components/form/file_picker/__snapshots__/file_picker.test.tsx.snap
  src/components/form/file_picker/file_picker.tsx
  src/components/popover/popover.tsx
  src/components/side_nav/__snapshots__/side_nav.test.tsx.snap
  src/components/side_nav/side_nav.tsx
Labels: skip-changelog, tech debt

#5195 Update multiple functional components to useGeneratedHtmlId hook
  CHANGELOG.md
  src/components/button/button_group/button_group.tsx
  src/components/button/button_group/button_group_button.tsx
  src/components/card/card.tsx
  src/components/form/switch/switch.tsx
  src/components/header/header_alert/header_alert.tsx
  src/components/key_pad_menu/key_pad_menu_item.tsx
  src/components/markdown_editor/markdown_editor.tsx
  src/components/markdown_editor/plugins/markdown_checkbox/renderer.tsx
  src/components/notification/notification_event.tsx
  src/components/notification/notification_event_messages.tsx
  src/components/notification/notification_event_meta.tsx
  src/components/resizable_container/resizable_button.tsx
  src/components/resizable_container/resizable_panel.tsx
  src/components/tour/tour_step.tsx
Labels: tech debt

#5204 Fix icons/logos with static SVG IDs to use generated IDs
  CHANGELOG.md
  scripts/compile-icons.js
  src/components/icon/__snapshots__/icon.test.tsx.snap
  src/components/icon/assets/logo_apache.js
  src/components/icon/assets/logo_dropwizard.js
  src/components/icon/assets/logo_dropwizard.svg
  src/components/icon/assets/logo_gcp.js
  src/components/icon/assets/logo_google_g.js
  src/components/icon/assets/logo_haproxy.js
  src/components/icon/assets/logo_ibm.js
  src/components/icon/assets/logo_memcached.js
  src/components/icon/assets/logo_php.js
  src/components/icon/assets/stop_slash.js
  src/components/icon/assets/stop_slash.svg
Labels: accessibility

#5217 [Docs] Backporting documentation improvements
  wiki/releasing-versions.md
Labels: skip-changelog

#5219 [Docs] Revert temporary change
  src-docs/src/views/code/virtualized.js
Labels: skip-changelog

#5218 [Docs] Add wiki documentation for EUI deprecations
  .stylelintrc
  wiki/deprecations.md
Labels: documentation, skip-changelog

#5223 [EuiSuperSelect] Update jest test for `popoverProps` to simulate click first
  src/components/form/super_select/__snapshots__/super_select.test.tsx.snap
  src/components/form/super_select/super_select.test.tsx
Labels: skip-changelog

#5225 [EuiTour] Style and a11y fixes
  CHANGELOG.md
  src-docs/src/views/tour/step.js
  src/components/tour/__snapshots__/tour_step.test.tsx.snap
  src/components/tour/_tour.scss
  src/components/tour/tour_step.test.tsx
  src/components/tour/tour_step.tsx
Labels: breaking change
