Repository elastic/eui, pull requests merged in 2021-04, with the labels that each got.

#4662 [EuiPageLayout] Add `bottomBar` & [EuiBottomBar] Add more position props
  .eslintrc.js
  CHANGELOG.md
  scripts/a11y-testing.js
  src-docs/src/components/guide_page/guide_page.js
  src-docs/src/components/guide_page/guide_page_chrome.js
  src-docs/src/components/guide_section/guide_section.tsx
  src-docs/src/views/app_view.js
  src-docs/src/views/bottom_bar/bottom_bar_example.js
  src-docs/src/views/bottom_bar/bottom_bar_position.js
  src-docs/src/views/bottom_bar/playground.js
  src-docs/src/views/breadcrumbs/breadcrumbs.js
  src-docs/src/views/elastic_charts/sizes.js
  src-docs/src/views/home/home_view.js
  src-docs/src/views/page/_page_demo.tsx
  src-docs/src/views/page/page_bottom_bar.js
  src-docs/src/views/page/page_bottom_bar_template.js
  src-docs/src/views/page/page_example.js
  src-docs/src/views/page/page_template.js
  src-docs/src/views/page/playground.js
  src-docs/src/views/text_scaling/text_scaling.js
  src/components/bottom_bar/__snapshots__/bottom_bar.test.tsx.snap
  src/components/bottom_bar/_bottom_bar.scss
  src/components/bottom_bar/bottom_bar.test.tsx
  src/components/bottom_bar/bottom_bar.tsx
  src/components/header/_header.scss
  src/components/page/__snapshots__/page_template.test.tsx.snap
  src/components/page/page_body/_page_body.scss
  src/components/page/page_content/__snapshots__/page_content.test.tsx.snap
  src/components/page/page_content/page_content.test.tsx
  src/components/page/page_content/page_content.tsx
  src/components/page/page_header/_page_header.scss
  src/components/page/page_header/page_header.tsx
  src/components/page/page_template.test.tsx
  src/components/page/page_template.tsx
  src/components/panel/panel.tsx
  src/global_styling/variables/_header.scss
Labels: breaking change

#4680 [DOCS] Add writing advice for button labels
  src-docs/src/views/guidelines/writing.js
Labels: documentation, skip-changelog

#4683 [Docs] EuiCodeEditor - Removed examples and added deprecation notice
  src-docs/src/views/code_editor/code_editor_example.js
Labels: documentation, skip-changelog

#4704 [Docs] Fixing up Icons page
  src-docs/src/components/guide_components.scss
  src-docs/src/components/with_theme/theme_context.tsx
  src-docs/src/services/playground/iconValidator.js
  src-docs/src/views/icon/accessibility.js
  src-docs/src/views/icon/apps.js
  src-docs/src/views/icon/custom_tokens.js
  src-docs/src/views/icon/editor.js
  src-docs/src/views/icon/icon_colors.js
  src-docs/src/views/icon/icon_colors_apps.js
  src-docs/src/views/icon/icon_example.js
  src-docs/src/views/icon/icon_sizes.js
  src-docs/src/views/icon/icon_types.js
  src-docs/src/views/icon/icons.js
  src-docs/src/views/icon/logos.js
  src-docs/src/views/icon/logos_third.js
  src-docs/src/views/icon/ml.js
  src-docs/src/views/icon/playground.js
  src-docs/src/views/icon/tokens.js
Labels: documentation, skip-changelog

#4697 Added a11y tests for some pages
  scripts/a11y-testing.js
  src-docs/src/views/drag_and_drop/drag_and_drop_custom_handle.js
  src-docs/src/views/form_compressed/complex_example.js
  src-docs/src/views/suggest/hashtag_popover.js
  src-docs/src/views/suggest/saved_queries.js
Labels: skip-changelog

#4708 Enable incremental typescript runs
  tsconfig.json
Labels: platform, skip-changelog

#4706 [EuiDataGrid] bug fixes
  CHANGELOG.md
  src-docs/src/views/datagrid/column_actions.js
  src-docs/src/views/datagrid/column_widths.js
  src-docs/src/views/datagrid/styling.js
  src/components/datagrid/__snapshots__/data_grid.test.tsx.snap
  src/components/datagrid/_data_grid_header_row.scss
  src/components/datagrid/data_grid.tsx
  src/components/datagrid/data_grid_body.tsx
  src/components/datagrid/data_grid_header_cell.tsx
Labels: data grid

#4722 [Docs] Add `euiBorderRadius` to sass guidelines
  src-docs/src/views/guidelines/index.scss
  src-docs/src/views/guidelines/sass.js
Labels: documentation, skip-changelog

#4732 [Docs] Fixed broken link of grid styling
  src-docs/src/views/datagrid/datagrid_example.js
Labels: documentation, skip-changelog

#4734 Updated EuiForm examples
  src-docs/src/views/accordion/accordion_form.js
  src-docs/src/views/flyout/flyout_complicated.js
  src-docs/src/views/flyout/flyout_max_width.js
  src-docs/src/views/form_layouts/described_form_group.js
  src-docs/src/views/form_layouts/inline_popover.js
  src-docs/src/views/form_validation/validation.js
  src-docs/src/views/markdown_editor/markdown_editor_with_plugins.js
  src-docs/src/views/modal/modal_example.js
  src-docs/src/views/modal/modal_form.js
  src-docs/src/views/tour/managed.js
  src-docs/src/views/tour/managed_hook.js
  src-docs/src/views/tour/tour.js
Labels: skip-changelog

#4727 [Docs] Rebrand
  package.json
  src-docs/src/components/guide_components.scss
  src-docs/src/components/guide_page/guide_page_header.tsx
  src-docs/src/components/guide_theme_selector/guide_figma_link.tsx
  src-docs/src/favicon.ico
  src-docs/src/images/favicon/dev/favicon-16x16.png
  src-docs/src/images/favicon/dev/favicon-32x32.png
  src-docs/src/images/favicon/dev/favicon-96x96.png
  src-docs/src/images/favicon/prod/favicon-16x16.png
  src-docs/src/images/favicon/prod/favicon-32x32.png
  src-docs/src/images/favicon/prod/favicon-96x96.png
  src-docs/src/images/illustration-eui-hero-500-darkmode-shadow.svg
  src-docs/src/images/illustration-eui-hero-500-shadow.svg
  src-docs/src/images/logo-eui.svg
  src-docs/src/index.html
  src-docs/src/views/app_view.js
  src-docs/src/views/home/home_footer_elastic_logo.tsx
  src-docs/src/views/home/home_illustration.tsx
  src-docs/src/views/home/home_illustration_parts/illustration_bg.tsx
  src-docs/src/views/home/home_illustration_parts/illustration_components.tsx
  src-docs/src/views/home/home_illustration_parts/illustration_dots.tsx
  src-docs/src/views/home/home_view.js
  src-docs/webpack.config.js
  yarn.lock
Labels: skip-changelog

#4743 [Docs] [EuiStat] Incorrect reference to `size` property in example, should be `titleSize` (#4742).
  src-docs/src/views/stat/stat_example.js
  src-docs/src/views/stat/stat_size.js
Labels: documentation, skip-changelog

#4746 [EuiMarkdowEditor] export intermediary type
  src/components/markdown_editor/plugins/markdown_default_plugins.tsx
Labels: skip-changelog

#4744 [EuiComboBox] Matching placeholder color to other form elements
  CHANGELOG.md
  src/components/combo_box/combo_box_input/_combo_box_placeholder.scss
  src/components/combo_box/combo_box_options_list/_combo_box_options_list.scss
  src/components/date_picker/_date_picker.scss
  src/global_styling/mixins/_form.scss
  src/global_styling/variables/_form.scss
Labels: accessibility, bug
