Repository elastic/eui, pull requests merged in 2021-03, with the labels that each got.

#4591 [Docs] Removed all `isNew` declarations on components over 6 months old
  src-docs/src/views/collapsible_nav/collapsible_nav_example.js
  src-docs/src/views/comment/comment_example.js
  src-docs/src/views/elastic_charts/pie_example.js
  src-docs/src/views/markdown_editor/mardown_editor_example.js
  src-docs/src/views/markdown_editor/mardown_format_example.js
  src-docs/src/views/markdown_editor/markdown_plugin_example.js
  src-docs/src/views/resizable_container/resizable_container_example.js
  src-docs/src/views/text_diff/text_diff_example.js
  src-docs/src/views/tour/tour_example.js
Labels: documentation, skip-changelog

#4589 [EuiDataGrid] Update jest environment rendering to include all cells
  src/components/datagrid/__snapshots__/data_grid.test.tsx.snap
  src/components/datagrid/data_grid.test.tsx
  src/components/datagrid/data_grid_body.tsx
Labels: skip-changelog

#4592 Prevent the changelog check from running on commits to master
  .github/workflows/changelog.yml
Labels: skip-changelog

#4598 Fix spelling of deprecated in warnings
  src/themes/eui-amsterdam/global_styling/mixins/_shadow.scss
Labels: skip-changelog

#4551 [EuiPopover] Default to ownFocus
  CHANGELOG.md
  src-docs/src/views/color_picker/color_palette_display.js
  src-docs/src/views/color_picker/containers.js
  src-docs/src/views/combo_box/containers.js
  src-docs/src/views/datagrid/control_columns.js
  src-docs/src/views/datagrid/datagrid.js
  src-docs/src/views/expression/columns.js
  src-docs/src/views/expression/expression.js
  src-docs/src/views/filter_group/filter_group.js
  src-docs/src/views/filter_group/filter_group_multi.js
  src-docs/src/views/flyout/flyout_complicated.js
  src-docs/src/views/form_layouts/inline_popover.js
  src-docs/src/views/header/header.js
  src-docs/src/views/header/header_alert.js
  src-docs/src/views/header/header_elastic_pattern.js
  src-docs/src/views/popover/popover.js
  src-docs/src/views/popover/popover_anchor_position.js
  src-docs/src/views/popover/popover_block.js
  src-docs/src/views/popover/popover_container.js
  src-docs/src/views/popover/popover_example.js
  src-docs/src/views/popover/popover_fixed.js
  src-docs/src/views/popover/popover_htmlelement_anchor.js
  src-docs/src/views/popover/popover_panel_class_name.js
  src-docs/src/views/popover/popover_with_title.js
  src-docs/src/views/popover/popover_with_title_padding.js
  src-docs/src/views/popover/trap_focus.js
  src/components/basic_table/__snapshots__/collapsed_item_actions.test.tsx.snap
  src/components/basic_table/__snapshots__/in_memory_table.test.tsx.snap
  src/components/datagrid/column_selector.tsx
  src/components/datagrid/column_sorting.tsx
  src/components/datagrid/data_grid_cell_popover.tsx
  src/components/datagrid/data_grid_header_cell.tsx
  src/components/datagrid/style_selector.tsx
  src/components/date_picker/super_date_picker/date_popover/date_popover_button.tsx
  src/components/date_picker/super_date_picker/quick_select_popover/quick_select_popover.tsx
  src/components/header/header_links/header_links.tsx
  src/components/popover/__snapshots__/popover.test.tsx.snap
  src/components/popover/popover.test.tsx
  src/components/popover/popover.tsx
  src/components/search_bar/filters/field_value_selection_filter.tsx
  src/components/table/mobile/table_sort_mobile.tsx
  src/components/tour/tour_step.tsx
Labels: !urgent!

#4605 [EuiToolTip, useInnerText] Use jest.useFakeTimers for flaky tests
  src/components/inner_text/inner_text.test.tsx
  src/components/tool_tip/tool_tip.test.tsx
Labels: skip-changelog

#4614 [EuiColorStops] Fixed: Standard, Random & Fixed Examples are using same state
  src-docs/src/views/color_picker/color_stops.js
Labels: skip-changelog

#4616 [DOCS] Fix demo for "Sizes" and "With single panel" for Context menu
  src-docs/src/views/context_menu/context_menu_example.js
Labels: documentation, skip-changelog

#4625 Stale issue/pr action
  .github/workflows/stale_issues.yml
  CONTRIBUTING.md
Labels: platform, skip-changelog

#4630 Turn on stale issue/pr action
  .github/workflows/stale_issues.yml
Labels: skip-changelog

#4618 Disable file watching in CI build
  scripts/babel/react-docgen-typescript.js
  src-docs/webpack.config.js
Labels: skip-changelog

#4632 Bump `caniuse-lite`
  yarn.lock
Labels: dependencies, skip-changelog

#4628 [webpack] Fail on missing export
  src/webpack.config.js
Labels: skip-changelog

#4639 Tweak the stale issue action's cron setup
  .github/workflows/stale_issues.yml
Labels: platform, skip-changelog

#4610 [DOCS] Coverted some examples to functional component
  src-docs/src/views/datagrid/schema.js
  src-docs/src/views/datagrid/styling.js
  src-docs/src/views/form_controls/display_toggles.js
Labels: skip-changelog

#4647 Bump lodash, url-parse
  package.json
  yarn.lock
Labels: dependencies, skip-changelog

#4617 [EuiInMemoryTable] Added documentation for `itemId` prop and improved props table
  src-docs/src/views/tables/in_memory/in_memory_selection_section.js
Labels: skip-changelog

#4652 [Docs] Add missing wiki file and fix links
  README.md
  wiki/consuming.md
Labels: documentation, skip-changelog

#4658 [Docs] Fix "badge with onClick events" snippets
  src-docs/src/views/badge/badge_example.js
Labels: documentation, skip-changelog

#4659 [Docs] Show all `HTMLAttributes` types
  src-docs/src/components/guide_section/guide_section_parts/guide_section_props_description.tsx
Labels: documentation, skip-changelog

#4657 Use generated IDs in EuiButtonGroup Buttons
  CHANGELOG.md
  src-docs/src/views/datagrid/styling.js
  src/components/button/button_group/__snapshots__/button_group.test.tsx.snap
  src/components/button/button_group/button_group_button.tsx
Labels: bug, documentation

#4649 [EuiCard] Refactored to use EuiPanel
  CHANGELOG.md
  src-docs/src/components/guide_section/guide_section_parts/guide_section_example.tsx
  src-docs/src/services/playground/knobs.js
  src-docs/src/views/card/card_checkable.js
  src-docs/src/views/card/card_checkable_checkbox.js
  src-docs/src/views/card/card_display.js
  src-docs/src/views/card/card_example.js
  src-docs/src/views/card/playground.js
  src-docs/src/views/modal/modal_example.js
  src-docs/src/views/panel/guidelines.js
  src-docs/src/views/panel/panel_badge.js
  src-docs/src/views/panel/panel_example.js
  src/components/card/__snapshots__/card.test.tsx.snap
  src/components/card/_card.scss
  src/components/card/card.test.tsx
  src/components/card/card.tsx
  src/components/card/checkable_card/__snapshots__/checkable_card.test.tsx.snap
  src/components/card/checkable_card/_checkable_card.scss
  src/components/card/checkable_card/checkable_card.test.tsx
  src/components/card/checkable_card/checkable_card.tsx
  src/components/panel/_panel.scss
  src/components/panel/panel.tsx
  src/components/panel/split_panel/_split_panel.scss
  src/components/panel/split_panel/split_panel.tsx
  src/global_styling/mixins/_beta_badge.scss
  src/global_styling/mixins/_panel.scss
  src/themes/eui-amsterdam/global_styling/mixins/_panel.scss
  wiki/component-development.md
Labels: breaking change

#4667 [Props] Explicit import of `Component` and `FunctionComponent`
  src/components/button/button.tsx
  src/components/context/context.tsx
  src/components/form/described_form_group/described_form_group.tsx
  src/components/i18n/i18n_number.tsx
  src/components/portal/portal.tsx
  src/components/selectable/selectable_message/selectable_message.tsx
Labels: skip-changelog

#4673 Update stale_issues.yml
  .github/workflows/stale_issues.yml
Labels: skip-changelog

#4633 forwardRef documentation, forwardRef tests for EuiHeaderSectionItemButton
  src/components/header/header_section/header_section_item_button.test.tsx
  wiki/component-development.md
Labels: skip-changelog

#4678 Update EuiHeaderSectionItemButton to avoid re-renders
  src/components/header/header_section/header_section_item_button.tsx
Labels: skip-changelog
