Repository elastic/eui, pull requests merged in 2021-01, with the labels that each got.

#4406 Spacing issue resolved #4263
  CHANGELOG.md
  src/components/date_picker/super_date_picker/_super_date_picker.scss
Labels: bug

#4245 [EuiMarkdownEditor] Better support to extend to full height
  CHANGELOG.md
  src-docs/src/views/markdown_editor/mardown_editor_example.js
  src-docs/src/views/markdown_editor/markdown_editor_height.js
  src/components/markdown_editor/__snapshots__/markdown_editor.test.tsx.snap
  src/components/markdown_editor/_index.scss
  src/components/markdown_editor/_markdown_editor.scss
  src/components/markdown_editor/_markdown_editor_drop_zone.scss
  src/components/markdown_editor/_markdown_editor_preview.scss
  src/components/markdown_editor/_markdown_editor_text_area.scss
  src/components/markdown_editor/_variables.scss
  src/components/markdown_editor/markdown_editor.test.tsx
  src/components/markdown_editor/markdown_editor.tsx
  src/components/markdown_editor/markdown_editor_drop_zone.tsx
  src/components/markdown_editor/markdown_editor_footer.tsx
  src/components/markdown_editor/markdown_editor_text_area.tsx
  src/components/markdown_editor/markdown_editor_toolbar.tsx
Labels: markdown editor

#4435 adding more pages to a11y testing
  CHANGELOG.md
  package.json
  scripts/a11y-testing.js
  src-docs/src/views/button/button_ghost.js
  src-docs/src/views/button/button_group.js
  src-docs/src/views/side_nav/side_nav.js
  src-docs/src/views/side_nav/side_nav_complex.js
  src-docs/src/views/side_nav/side_nav_force_open.js
  src-docs/src/views/utility_classes/utility_classes.js
  src/components/tabs/__snapshots__/tabs.test.tsx.snap
  src/components/tabs/tabs.test.tsx
  src/components/tabs/tabs.tsx
  src/components/tree_view/__snapshots__/tree_view.test.tsx.snap
  src/components/tree_view/tree_view.tsx
  yarn.lock
Labels: accessibility
