Repository elastic/eui, pull requests merged in 2021-11, with the labels that each got.

#5340 [EuiMarkdownEditor] Fix react-dropzone taking over all drop events on the page
  CHANGELOG.md
  src/components/markdown_editor/markdown_editor_drop_zone.tsx
Labels: bug

#5345 [Breaking] Remove Sass vars `$euiColorSecondary` and `$euiColorSecondaryText`
  CHANGELOG.md
  src/components/button/button_empty/_button_empty.scss
  src/components/call_out/_variables.scss
  src/components/drag_and_drop/_droppable.scss
  src/components/toast/_toast.scss
  src/global_styling/react_date_picker/_date_picker.scss
  src/global_styling/variables/_colors.scss
  src/themes/eui-amsterdam/eui_amsterdam_colors_dark.scss
  src/themes/eui-amsterdam/eui_amsterdam_colors_light.scss
  src/themes/eui/eui_colors_dark.scss
Labels: breaking change

#5348 Fix filenames and paths for components and routes
  wiki/creating-components-manually.md
  wiki/creating-components-yeoman.md
  wiki/react-router.md
  wiki/testing.md
Labels: documentation, skip-changelog

#5284 [EuiDataGrid] Refactor row height calculations to no longer need computed styles on grid init
  CHANGELOG.md
  src/components/datagrid/__mocks__/row_height_utils.ts
  src/components/datagrid/_data_grid_data_row.scss
  src/components/datagrid/body/__snapshots__/data_grid_cell.test.tsx.snap
  src/components/datagrid/body/data_grid_body.tsx
  src/components/datagrid/body/data_grid_cell.test.tsx
  src/components/datagrid/body/data_grid_cell.tsx
  src/components/datagrid/body/data_grid_footer_row.tsx
  src/components/datagrid/data_grid.test.tsx
  src/components/datagrid/data_grid.tsx
  src/components/datagrid/row_height_utils.ts
Labels: bug

#5349 [Docs] Add new "Theming / More" page
  src-docs/src/routes.js
  src-docs/src/views/guidelines/_index.scss
  src-docs/src/views/guidelines/colors/_color_section.scss
  src-docs/src/views/guidelines/sass.js
  src-docs/src/views/guidelines/sass/animation.tsx
  src-docs/src/views/guidelines/sass/core.tsx
  src-docs/src/views/guidelines/sass/shadow.tsx
  src-docs/src/views/page/page_example.js
  src-docs/src/views/theme/_animation.js
  src-docs/src/views/theme/customizing/_animation.js
  src-docs/src/views/theme/other/_animation_js.tsx
  src-docs/src/views/theme/other/_animation_sass.tsx
  src-docs/src/views/theme/other/_levels_sass.tsx
  src-docs/src/views/theme/other/_shadow_sass.tsx
  src-docs/src/views/theme/other/other.tsx
  src-docs/src/views/theme/values.js
  src/components/button/button_icon/button_icon.tsx
  src/global_styling/variables/_colors.ts
Labels: documentation, skip-changelog

#5311 [Docs] Update props global filter pattern to pass axe check
  src-docs/src/views/suggest/global_filter_item.js
  src/components/icon/icon.tsx
Labels: skip-changelog, accessibility - automated

#5350 [Guidelines] Add `EuiTour`
  src-docs/src/components/guide_rule/guide_rule.js
  src-docs/src/components/guide_rule/guide_rule_description.js
  src-docs/src/components/guide_section/guide_section.tsx
  src-docs/src/components/guide_section/guide_section_parts/guide_section_text.tsx
  src-docs/src/images/tour_1_do.svg
  src-docs/src/images/tour_1_dont.svg
  src-docs/src/images/tour_6.gif
  src-docs/src/views/tour/guidelines.js
  src-docs/src/views/tour/tour_example.js
Labels: documentation, skip-changelog

#5354 [EuiDataGrid] Reorganize & add unit tests for row height utils
  src/components/datagrid/row_height_utils.test.ts
  src/components/datagrid/row_height_utils.ts
Labels: skip-changelog, tech debt

#5369 [EuiDataGrid] Fix full screen display bug
  src/components/datagrid/_data_grid.scss
Labels: bug, skip-changelog

#5374 [CSS-in-JS] Theme exports
  src/services/theme/hooks.tsx
  src/services/theme/index.ts
  src/services/theme/types.ts
  src/themes/index.ts
Labels: skip-changelog

#5376 [EuiDataGrid] Fix grids that set a `defaultHeight` with `lineCount` and `rowHeights` overrides with `lineCount`
  CHANGELOG.md
  src-docs/src/views/datagrid/datagrid_height_options_example.js
  src-docs/src/views/datagrid/row_height_auto.tsx
  src/components/datagrid/__mocks__/row_height_utils.ts
  src/components/datagrid/body/__snapshots__/data_grid_cell.test.tsx.snap
  src/components/datagrid/body/data_grid_body.tsx
  src/components/datagrid/body/data_grid_cell.test.tsx
  src/components/datagrid/body/data_grid_cell.tsx
  src/components/datagrid/row_height_utils.test.ts
  src/components/datagrid/row_height_utils.ts
Labels: bug, data grid

#5364 [EuiSuperSelect] Adding generated IDs to create accessible label and description
  CHANGELOG.md
  src-docs/src/views/form_compressed/complex_example.js
  src/components/color_picker/color_palette_display/__snapshots__/color_palette_display.test.tsx.snap
  src/components/color_picker/color_palette_display/color_palette_display_fixed.tsx
  src/components/color_picker/color_palette_display/color_palette_display_gradient.tsx
  src/components/color_picker/color_palette_picker/__snapshots__/color_palette_picker.test.tsx.snap
  src/components/color_picker/color_palette_picker/color_palette_picker.tsx
  src/components/form/super_select/__snapshots__/super_select.test.tsx.snap
  src/components/form/super_select/__snapshots__/super_select_control.test.tsx.snap
  src/components/form/super_select/super_select.tsx
  src/components/form/super_select/super_select_control.tsx
Labels: accessibility, accessibility - automated

#5371 [Cypress] Add EUI's styles to test environment
  cypress/plugins/webpack.config.js
  cypress/support/index.js
  package.json
  scripts/compile-scss.js
  scripts/cypress.js
  src/components/focus_trap/focus_trap.spec.tsx
  wiki/cypress-testing.md
  yarn.lock
Labels: platform, skip-changelog

#5392 [Deps] `ansi-regex` to v5.0.1
  yarn.lock
Labels: skip-changelog

#5400 [EuiDataGrid] Fix paginated & height-limited datagrids becoming unscrollable on `rowCount` change
  CHANGELOG.md
  src/components/datagrid/body/data_grid_body.tsx
Labels: bug, data grid

#5401 Update yeoman docs generator
  generator-eui/documentation/index.js
  generator-eui/documentation/templates/documentation_page.js
  generator-eui/documentation/templates/documentation_page_demo.tsx
Labels: skip-changelog

#4720 [Guidelines] Add writing examples page
  src-docs/src/components/guide_page/guide_page_chrome.js
  src-docs/src/components/guide_rule/_guide_rule_example.scss
  src-docs/src/components/guide_rule/guide_rule_example.js
  src-docs/src/components/guide_tabbed_page/guide_tabbed_page.tsx
  src-docs/src/components/guide_tabbed_page/index.ts
  src-docs/src/routes.js
  src-docs/src/views/guidelines/writing.js
  src-docs/src/views/guidelines/writing_examples.js
  src-docs/src/views/guidelines/writing_guidelines.js
Labels: documentation, skip-changelog

#5389 [Cypress] Allow theme selection in tests
  cypress/plugins/webpack.config.js
  cypress/support/index.js
  package.json
  scripts/cypress.js
  wiki/cypress-testing.md
Labels: platform, skip-changelog

#5405 Fixes typo in EuiPageHeader docs
  src/components/page/page_header/page_header_content.tsx
Labels: skip-changelog

#5412 Exclude mocks and Cypress specs from eui.d.ts
  CHANGELOG.md
  scripts/dtsgenerator.js
Labels: !urgent!

#5413 [EuiCodeBlock] Fix HTML attributes not being accepted as props
  src/components/code/code.tsx
  src/components/code/utils.tsx
Labels: skip-changelog

#5372 [EuiDataGrid] Add rowHeightSwitcher logic + API change
  CHANGELOG.md
  cypress/support/index.js
  src-docs/src/views/datagrid/datagrid_example.js
  src-docs/src/views/datagrid/datagrid_height_options_example.js
  src-docs/src/views/datagrid/datagrid_styling_example.js
  src-docs/src/views/datagrid/row_height_fixed.tsx
  src-docs/src/views/datagrid/styling.js
  src/components/datagrid/__snapshots__/data_grid.test.tsx.snap
  src/components/datagrid/_data_grid_data_row.scss
  src/components/datagrid/_mixins.scss
  src/components/datagrid/body/__snapshots__/data_grid_cell.test.tsx.snap
  src/components/datagrid/body/data_grid_cell.test.tsx
  src/components/datagrid/body/data_grid_cell.tsx
  src/components/datagrid/controls/__snapshots__/display_selector.test.tsx.snap
  src/components/datagrid/controls/column_selector.test.tsx
  src/components/datagrid/controls/column_selector.tsx
  src/components/datagrid/controls/data_grid_toolbar.test.tsx
  src/components/datagrid/controls/data_grid_toolbar.tsx
  src/components/datagrid/controls/display_selector.test.tsx
  src/components/datagrid/controls/display_selector.tsx
  src/components/datagrid/controls/index.ts
  src/components/datagrid/controls/style_selector.test.tsx
  src/components/datagrid/controls/style_selector.tsx
  src/components/datagrid/data_grid.test.tsx
  src/components/datagrid/data_grid.tsx
  src/components/datagrid/data_grid_types.ts
  src/components/datagrid/index.ts
Labels: data grid

#5414 [EuiIcon] Added `payment` glyph
  CHANGELOG.md
  src-docs/src/views/icon/icons.js
  src/components/icon/__snapshots__/icon.test.tsx.snap
  src/components/icon/assets/payment.tsx
  src/components/icon/icon.tsx
  src/components/icon/svgs/payment.svg
Labels: icons

#5402 [EuiTableFieldDataColumnType] improve autocomplete suggestions for `field` property
  src/components/basic_table/table_types.ts
Labels: skip-changelog

#5420 [Docs] Fix Sass `border-radius` snippet in theming borders
  src-docs/src/views/theme/borders/_border_sass.tsx
Labels: documentation, skip-changelog

#5423 [EuiAvatar] Adding conditional`role` attribute to EuiAvatar container DIV
  CHANGELOG.md
  src/components/avatar/__snapshots__/avatar.test.tsx.snap
  src/components/avatar/avatar.tsx
  src/components/comment_list/__snapshots__/comment.test.tsx.snap
  src/components/comment_list/__snapshots__/comment_timeline.test.tsx.snap
Labels: accessibility, WCAG A, accessibility - automated
