Repository elastic/eui, pull requests merged in 2022-09, with the labels that each got.

#6201 [CSS-in-JS] Remove `euiCallOutColor` Sass mixin
  src/components/call_out/_index.scss
  src/components/call_out/_mixins.scss
  src/components/call_out/_variables.scss
  src/components/index.scss
  upcoming_changelogs/6201.md
Labels: breaking change

#6209 Update upgrading kibana wiki
  wiki/upgrading-kibana.md
Labels: skip-changelog

#6104 [EuiToolTip] Convert to Emotion styling
  src/components/badge/beta_badge/__snapshots__/beta_badge.test.tsx.snap
  src/components/basic_table/__snapshots__/collapsed_item_actions.test.tsx.snap
  src/components/code/__snapshots__/code_block.test.tsx.snap
  src/components/datagrid/__snapshots__/data_grid.test.tsx.snap
  src/components/date_picker/super_date_picker/super_update_button.tsx
  src/components/index.scss
  src/components/key_pad_menu/__snapshots__/key_pad_menu_item.test.tsx.snap
  src/components/markdown_editor/__snapshots__/markdown_editor.test.tsx.snap
  src/components/suggest/__snapshots__/suggest.test.tsx.snap
  src/components/tool_tip/__snapshots__/icon_tip.test.tsx.snap
  src/components/tool_tip/__snapshots__/tool_tip.test.tsx.snap
  src/components/tool_tip/__snapshots__/tool_tip_popover.test.tsx.snap
  src/components/tool_tip/_index.scss
  src/components/tool_tip/_tool_tip.scss
  src/components/tool_tip/index.ts
  src/components/tool_tip/tool_tip.styles.ts
  src/components/tool_tip/tool_tip.test.tsx
  src/components/tool_tip/tool_tip.tsx
  src/components/tool_tip/tool_tip_anchor.tsx
  src/components/tool_tip/tool_tip_arrow.tsx
  src/components/tool_tip/tool_tip_popover.tsx
  src/global_styling/mixins/_tool_tip.scss
  src/themes/amsterdam/overrides/_index.scss
  src/themes/amsterdam/overrides/_tooltip.scss
  upcoming_changelogs/6104.md
Labels: emotion

#6215 [Docs] Remove `console.log`
  src-docs/src/index.js
Labels: skip-changelog

#6212 Upgrade Cypress to v10
  cypress.config.ts
  cypress.json
  cypress/plugins/index.js
  cypress/support/a11y/defaultAxeConfig.ts
  cypress/support/commands.js
  cypress/support/commands.ts
  cypress/support/component-index.html
  cypress/support/component.tsx
  cypress/support/index.d.ts
  cypress/support/index.js
  cypress/webpack.config.js
  nyc.config.js
  package.json
  scripts/cypress.js
  src-docs/src/index.html
  src/components/datagrid/body/data_grid_footer_row.spec.tsx
  yarn.lock
Labels: test, skip-changelog

#6220 [SearchBar] Use bool query instead of match bool logic
  src/components/search_bar/query/__snapshots__/ast_to_es_query_dsl.test.ts.snap
  src/components/search_bar/query/ast_to_es_query_dsl.ts
  upcoming_changelogs/6220.md
Labels: bug

#6221 [Emotion] Remove misc unnecessary args from Emotion style functions
  src/components/button/button.tsx
  src/components/button/button_display/_button_display.styles.ts
  src/components/button/button_display/_button_display.tsx
  src/components/card/card.styles.ts
  src/components/card/card.tsx
  src/components/datagrid/controls/__snapshots__/column_selector.test.tsx.snap
  src/components/date_picker/super_date_picker/quick_select_popover/__snapshots__/quick_select.test.tsx.snap
  src/components/popover/__snapshots__/popover_title.test.tsx.snap
  src/components/popover/popover_title.styles.ts
  src/components/popover/popover_title.tsx
  src/components/tour/__snapshots__/tour_step.test.tsx.snap
Labels: skip-changelog

#6224 [Emotion] Convert EuiBadge
  src-docs/src/views/badge/badge.tsx
  src-docs/src/views/badge/badge_button.tsx
  src-docs/src/views/badge/badge_health.tsx
  src-docs/src/views/badge/badge_href.tsx
  src-docs/src/views/badge/badge_truncate.tsx
  src-docs/src/views/badge/badge_with_icon.tsx
  src/components/badge/__snapshots__/badge.test.tsx.snap
  src/components/badge/_badge.scss
  src/components/badge/_index.scss
  src/components/badge/badge.styles.ts
  src/components/badge/badge.test.tsx
  src/components/badge/badge.tsx
  src/components/badge/badge_group/__snapshots__/badge_group.test.tsx.snap
  src/components/notification/__snapshots__/notification_event.test.tsx.snap
  src/components/notification/__snapshots__/notification_event_meta.test.tsx.snap
  src/components/selectable/selectable_list/__snapshots__/selectable_list.test.tsx.snap
  src/components/selectable/selectable_list/__snapshots__/selectable_list_item.test.tsx.snap
  src/services/color/contrast.ts
  src/services/index.ts
  upcoming_changelogs/6224.md
Labels: emotion

#6234 [EuiDatePicker] Fix CodeSandbox locale examples and add dev note for explicit imports
  src-docs/src/views/date_picker/date_picker_example.js
  src-docs/src/views/date_picker/locale.js
Labels: skip-changelog

#6231 [Emotion] Add utility for performing math on numbers with CSS units
  src/components/badge/badge.styles.ts
  src/components/breadcrumbs/breadcrumb.styles.ts
  src/components/expression/expression.styles.ts
  src/components/markdown_editor/markdown_format.styles.ts
  src/components/pagination/pagination_button.styles.ts
  src/components/text/text.styles.ts
  src/components/tool_tip/tool_tip.styles.ts
  src/components/tour/tour.styles.ts
  src/global_styling/functions/index.ts
  src/global_styling/functions/math.test.ts
  src/global_styling/functions/math.ts
Labels: skip-changelog, emotion

#6237 Fix EuiButtonIcon snapshots
  src/components/accordion/__snapshots__/accordion.test.tsx.snap
  src/components/basic_table/__snapshots__/collapsed_item_actions.test.tsx.snap
  src/components/basic_table/__snapshots__/in_memory_table.test.tsx.snap
  src/components/button/button_icon/__snapshots__/button_icon.test.tsx.snap
  src/components/button/button_icon/button_icon.tsx
  src/components/code/__snapshots__/code_block.test.tsx.snap
  src/components/collapsible_nav/__snapshots__/collapsible_nav.test.tsx.snap
  src/components/collapsible_nav/collapsible_nav_group/__snapshots__/collapsible_nav_group.test.tsx.snap
  src/components/datagrid/__snapshots__/data_grid.test.tsx.snap
  src/components/datagrid/controls/__snapshots__/column_sorting.test.tsx.snap
  src/components/flyout/__snapshots__/flyout.test.tsx.snap
  src/components/form/field_password/__snapshots__/field_password.test.tsx.snap
  src/components/list_group/__snapshots__/list_group.test.tsx.snap
  src/components/list_group/__snapshots__/list_group_item.test.tsx.snap
  src/components/list_group/pinnable_list_group/__snapshots__/pinnable_list_group.test.tsx.snap
  src/components/markdown_editor/__snapshots__/markdown_editor.test.tsx.snap
  src/components/modal/__snapshots__/confirm_modal.test.tsx.snap
  src/components/modal/__snapshots__/modal.test.tsx.snap
  src/components/notification/__snapshots__/notification_event.test.tsx.snap
  src/components/notification/__snapshots__/notification_event_read_button.test.tsx.snap
  src/components/pagination/__snapshots__/pagination.test.tsx.snap
  src/components/table/table_pagination/__snapshots__/table_pagination.test.tsx.snap
  src/components/toast/__snapshots__/global_toast_list.test.tsx.snap
Labels: skip-changelog, emotion

#6238 Fix internal test mocks of `useIsWithin*Breakpoint` hooks
  scripts/jest/setup/mocks.js
  src/components/collapsible_nav/__snapshots__/collapsible_nav.test.tsx.snap
  src/components/flyout/__snapshots__/flyout.test.tsx.snap
  src/components/page/__snapshots__/page_template.test.tsx.snap
  src/components/panel/split_panel/__snapshots__/split_panel.test.tsx.snap
Labels: skip-changelog

#6242 [EuiSearchBar docs] Updated placeholder example to align with forms guidelines
  src-docs/src/views/search_bar/controlled_search_bar.js
  src-docs/src/views/search_bar/search_bar.js
  src-docs/src/views/search_bar/search_bar_filters.js
Labels: documentation, skip-changelog

#6207 [Emotion] Convert `EuiListGroup`
  src-docs/src/views/collapsible_nav/collapsible_nav_all.tsx
  src-docs/src/views/collapsible_nav/collapsible_nav_list.tsx
  src-docs/src/views/list_group/list_group.tsx
  src-docs/src/views/list_group/list_group_example.js
  src-docs/src/views/list_group/list_group_extra.tsx
  src-docs/src/views/list_group/list_group_item_color.tsx
  src-docs/src/views/list_group/list_group_link_actions.tsx
  src-docs/src/views/list_group/list_group_links.tsx
  src-docs/src/views/list_group/pinnable_list_group.tsx
  src-docs/src/views/list_group/props.tsx
  src/components/datagrid/__snapshots__/data_grid.test.tsx.snap
  src/components/datagrid/data_grid.test.tsx
  src/components/flyout/flyout.styles.ts
  src/components/form/form.styles.ts
  src/components/index.scss
  src/components/list_group/__snapshots__/list_group.test.tsx.snap
  src/components/list_group/__snapshots__/list_group_item.test.tsx.snap
  src/components/list_group/__snapshots__/list_group_item_extra_action.test.tsx.snap
  src/components/list_group/_index.scss
  src/components/list_group/_list_group.scss
  src/components/list_group/_list_group_item.scss
  src/components/list_group/_variables.scss
  src/components/list_group/index.ts
  src/components/list_group/list_group.styles.ts
  src/components/list_group/list_group.test.tsx
  src/components/list_group/list_group.tsx
  src/components/list_group/list_group_item.styles.ts
  src/components/list_group/list_group_item.test.tsx
  src/components/list_group/list_group_item.tsx
  src/components/list_group/list_group_item_extra_action.styles.ts
  src/components/list_group/list_group_item_extra_action.test.tsx
  src/components/list_group/list_group_item_extra_action.tsx
  src/components/list_group/pinnable_list_group/__snapshots__/pinnable_list_group.test.tsx.snap
  src/components/list_group/pinnable_list_group/_index.scss
  src/components/list_group/pinnable_list_group/_pinnable_list_group.scss
  src/components/list_group/pinnable_list_group/pinnable_list_group.styles.ts
  src/components/list_group/pinnable_list_group/pinnable_list_group.test.tsx
  src/components/list_group/pinnable_list_group/pinnable_list_group.tsx
  src/components/popover/input_popover.tsx
  src/themes/amsterdam/overrides/_index.scss
  src/themes/amsterdam/overrides/_list_group_item.scss
  upcoming_changelogs/6207.md
Labels: breaking change, emotion

#6254 [Emotion] Pre-emptively fix/regression test form components with tricky `className`/`css` locations
  src/components/basic_table/__snapshots__/basic_table.test.tsx.snap
  src/components/card/checkable_card/__snapshots__/checkable_card.test.tsx.snap
  src/components/datagrid/controls/__snapshots__/column_selector.test.tsx.snap
  src/components/form/checkbox/__snapshots__/checkbox.test.tsx.snap
  src/components/form/checkbox/checkbox.test.tsx
  src/components/form/checkbox/checkbox.tsx
  src/components/form/range/__snapshots__/dual_range.test.tsx.snap
  src/components/form/range/dual_range.test.tsx
  src/components/form/range/dual_range.tsx
  src/components/form/switch/__snapshots__/switch.test.tsx.snap
  src/components/form/switch/switch.test.tsx
  src/components/form/switch/switch.tsx
  src/components/key_pad_menu/__snapshots__/key_pad_menu_item.test.tsx.snap
Labels: skip-changelog

#6259 VS Code snippet for component styles.
  wiki/writing-styles-with-emotion.md
Labels: skip-changelog, emotion

#6258 [Emotion] Convert EuiBadgeGroup, EuiBetaBadge, and EuiNotificationBadge
  src-docs/src/views/badge/badge_example.js
  src-docs/src/views/badge/beta_badge.js
  src-docs/src/views/badge/beta_badge.tsx
  src/components/badge/_index.scss
  src/components/badge/badge_group/__snapshots__/badge_group.test.tsx.snap
  src/components/badge/badge_group/_badge_group.scss
  src/components/badge/badge_group/_index.scss
  src/components/badge/badge_group/badge_group.styles.ts
  src/components/badge/badge_group/badge_group.test.tsx
  src/components/badge/badge_group/badge_group.tsx
  src/components/badge/beta_badge/__snapshots__/beta_badge.test.tsx.snap
  src/components/badge/beta_badge/_beta_badge.scss
  src/components/badge/beta_badge/_index.scss
  src/components/badge/beta_badge/beta_badge.styles.ts
  src/components/badge/beta_badge/beta_badge.test.tsx
  src/components/badge/beta_badge/beta_badge.tsx
  src/components/badge/notification_badge/__snapshots__/badge_notification.test.tsx.snap
  src/components/badge/notification_badge/_index.scss
  src/components/badge/notification_badge/_notification_badge.scss
  src/components/badge/notification_badge/badge_notification.styles.ts
  src/components/badge/notification_badge/badge_notification.test.tsx
  src/components/badge/notification_badge/badge_notification.tsx
  src/components/card/__snapshots__/card.test.tsx.snap
  src/components/facet/__snapshots__/facet_button.test.tsx.snap
  src/components/filter_group/__snapshots__/filter_button.test.tsx.snap
  src/components/header/header_section/__snapshots__/header_section_item_button.test.tsx.snap
  src/components/index.scss
  src/components/key_pad_menu/__snapshots__/key_pad_menu_item.test.tsx.snap
  src/themes/amsterdam/overrides/_index.scss
  src/themes/amsterdam/overrides/_notification_badge.scss
  upcoming_changelogs/6258.md
Labels: emotion

#6247 [EuiPortal docs] Add custom flyout example
  src-docs/src/views/portal/complex/custom_flyout.tsx
  src-docs/src/views/portal/portal_complex.tsx
  src-docs/src/views/portal/portal_example.js
  src/components/flyout/flyout.styles.ts
  src/components/flyout/index.ts
Labels: documentation, skip-changelog

#6262 [EuiPopover docs] Update examples to align with product assistance guidelines
  src-docs/src/views/popover/initial_focus.tsx
  src-docs/src/views/popover/popover.tsx
  src-docs/src/views/popover/popover_anchor_position.tsx
  src-docs/src/views/popover/popover_container.js
  src-docs/src/views/popover/popover_example.js
  src-docs/src/views/popover/popover_fixed.tsx
  src-docs/src/views/popover/popover_htmlelement_anchor.js
  src-docs/src/views/popover/popover_panel_class_name.tsx
  src-docs/src/views/popover/popover_with_title.tsx
  src-docs/src/views/popover/popover_with_title_padding.tsx
  src-docs/src/views/popover/trap_focus.tsx
Labels: documentation, skip-changelog

#6256 [Emotion] Add form variables and mixins
  src/components/form/form.styles.test.tsx
  src/components/form/form.styles.ts
  src/global_styling/mixins/_form.scss
  src/global_styling/variables/_borders.scss
  src/global_styling/variables/_form.scss
  src/services/color/manipulation.ts
  src/services/index.ts
  src/themes/amsterdam/global_styling/mixins/_form.scss
  src/themes/amsterdam/global_styling/mixins/_index.scss
  src/themes/amsterdam/global_styling/variables/_borders.scss
  src/themes/amsterdam/global_styling/variables/_form.scss
  src/themes/amsterdam/global_styling/variables/_index.scss
Labels: skip-changelog, emotion

#6266 [CI] Skip a11y testing to stop CI from hanging
  scripts/test-docker.js
Labels: skip-changelog

#6264 Upgrade Node to v16.17.1
  .ci/jobs/elastic+eui+pull-request-test.yml
  .nvmrc
  package.json
  scripts/deploy/build_docs
  scripts/deploy/deploy_docs
  scripts/docker-ci/Dockerfile
  scripts/test-docker.js
Labels: skip-changelog

#6193 [Platform] Upgrade to webpack 5
  .eslintrc.js
  .eslintwebpack.config.js
  cypress/webpack.config.js
  package.json
  scripts/babel/react-docgen-typescript.js
  scripts/compile-eui.js
  scripts/loaders/prop-loader.js
  src-docs/src/views/elastic_charts/shared.js
  src-docs/webpack.config.js
  src/themes/charts/webpack.config.js
  yarn.lock
Labels: platform, skip-changelog

#6257 ESLint rule to validate `css` props are declared before`{...spread}` props
  .eslintplugin.js
  .eslintrc.js
  scripts/eslint-plugin/css_before_spread_props.js
  scripts/eslint-plugin/css_before_spread_props.test.js
  src/components/flyout/flyout_body.tsx
  src/components/flyout/flyout_footer.tsx
  src/components/flyout/flyout_header.tsx
  src/components/image/image_fullscreen_wrapper.tsx
  src/components/page/page_section/page_section.tsx
  src/components/pagination/pagination.tsx
  src/components/tool_tip/tool_tip_anchor.tsx
  src/services/theme/clone_element.test.tsx
Labels: test, skip-changelog
