Repository elastic/eui, pull requests merged in 2022-06, with the labels that each got.

#5950 [Docs] Fix link in CSS utility classes page
  src-docs/src/views/utility_classes/utility_classes_example.js
Labels: documentation, skip-changelog

#5946 [EuiText docs] Add callout with usage instructions
  src-docs/src/views/avatar/avatar_example.js
  src-docs/src/views/badge/badge_example.js
  src-docs/src/views/button/button_example.js
  src-docs/src/views/call_out/call_out_example.js
  src-docs/src/views/card/card_example.js
  src-docs/src/views/color_palette/color_palette_example.js
  src-docs/src/views/context_menu/context_menu_example.js
  src-docs/src/views/control_bar/control_bar_example.js
  src-docs/src/views/date_picker/date_picker_example.js
  src-docs/src/views/description_list/description_list_example.js
  src-docs/src/views/expression/expression_example.js
  src-docs/src/views/image/image_example.js
  src-docs/src/views/overlay_mask/overlay_mask_example.js
  src-docs/src/views/page/page_template_example.js
  src-docs/src/views/progress/progress_example.js
  src-docs/src/views/resizable_container/resizable_container_example.js
  src-docs/src/views/search_bar/search_bar_example.js
  src-docs/src/views/steps/steps_example.js
  src-docs/src/views/super_select/super_select_example.js
  src-docs/src/views/text/text_example.js
  src-docs/src/views/toast/toast_example.js
  src-docs/src/views/tree_view/tree_view_example.js
  src-docs/src/views/window_event/window_event_example.js
Labels: documentation, skip-changelog

#5910 Writing guidelines for form controls and validation
  src-docs/src/views/form_controls/form_controls_example.js
  src-docs/src/views/form_controls/guidelines.js
  src-docs/src/views/form_validation/form_validation_example.js
  src-docs/src/views/form_validation/guidelines.js
Labels: documentation, skip-changelog

#5957 [EuiSkipLink] Add `overrideLinkBehavior` prop for SPA/hash routers
  src-docs/src/views/app_view.js
  src/components/accessibility/skip_link/__snapshots__/skip_link.test.tsx.snap
  src/components/accessibility/skip_link/skip_link.styles.ts
  src/components/accessibility/skip_link/skip_link.test.tsx
  src/components/accessibility/skip_link/skip_link.tsx
  upcoming_changelogs/5957.md
Labels: accessibility

#5968 [Emotion] Convert EuiStat
  src-docs/src/views/stat/playground.js
  src/components/index.scss
  src/components/stat/__snapshots__/stat.test.tsx.snap
  src/components/stat/_index.scss
  src/components/stat/_stat.scss
  src/components/stat/stat.styles.ts
  src/components/stat/stat.test.tsx
  src/components/stat/stat.tsx
  upcoming_changelogs/5968.md
Labels: emotion

#5955 Add `gutterSize` prop to `EuiTimeline`
  src-docs/src/views/timeline/timeline_example.js
  src-docs/src/views/timeline/timeline_item.tsx
  src/components/timeline/__snapshots__/timeline.test.tsx.snap
  src/components/timeline/__snapshots__/timeline_item.test.tsx.snap
  src/components/timeline/timeline.styles.ts
  src/components/timeline/timeline.test.tsx
  src/components/timeline/timeline.tsx
  src/components/timeline/timeline_item.styles.ts
  src/components/timeline/timeline_item.tsx
  src/components/timeline/timeline_item_icon.styles.ts
  src/global_styling/functions/__snapshots__/logicals.test.ts.snap
  src/global_styling/functions/logicals.ts
  upcoming_changelogs/5955.md
Labels: breaking change

#5853 [CSS-in-JS] Granular insertion; Utility component for classes
  src-docs/src/index.html
  src-docs/src/views/app_context.js
  src-docs/src/views/provider/provider_example.js
  src-docs/src/views/provider/provider_styles.tsx
  src-docs/webpack.config.js
  src/components/provider/__snapshots__/provider.test.tsx.snap
  src/components/provider/cache/__snapshots__/cache_provider.test.tsx.snap
  src/components/provider/cache/cache_provider.test.tsx
  src/components/provider/cache/cache_provider.tsx
  src/components/provider/cache/index.ts
  src/components/provider/provider.test.tsx
  src/components/provider/provider.tsx
  src/global_styling/utility/utility.tsx
  src/services/theme/hooks.tsx
  src/services/theme/provider.tsx
  upcoming_changelogs/5853.md
Labels: emotion

#5986 [Emotion] Convert EuiProgress
  src-docs/src/views/progress/playground.js
  src-docs/src/views/theme/_json/eui_theme_dark.json
  src-docs/src/views/theme/_json/eui_theme_light.json
  src/components/index.scss
  src/components/progress/__snapshots__/progress.styles.test.ts.snap
  src/components/progress/__snapshots__/progress.test.tsx.snap
  src/components/progress/_index.scss
  src/components/progress/_progress.scss
  src/components/progress/_variables.scss
  src/components/progress/progress.styles.test.ts
  src/components/progress/progress.styles.ts
  src/components/progress/progress.test.tsx
  src/components/progress/progress.tsx
  src/themes/amsterdam/overrides/_index.scss
  src/themes/amsterdam/overrides/_progress.scss
  upcoming_changelogs/5986.md
Labels: emotion

#5994 [EuiProgress docs] Removing callout and other fixes
  src-docs/src/views/progress/progress_example.js
  src-docs/src/views/theme/color/_color_js.tsx
  src-docs/src/views/theme/color/_color_sass.tsx
  src-docs/src/views/theme/color/tokens.tsx
Labels: documentation, skip-changelog

#6000 [docs] Increased support for TS types -> props table/docgen
  scripts/loaders/prop-loader.js
Labels: skip-changelog

#5974 [Docs] `EuiAccordion` props table
  src/components/accordion/accordion.tsx
  src/services/theme/hooks.tsx
  upcoming_changelogs/5974.md
Labels: skip-changelog

#5995 Update `EuiScreenReaderLive` and use it in EUI Docs to announce page loads to screen readers
  src-docs/src/components/scroll_to_hash.tsx
  src-docs/src/views/accessibility/accessibility_example.js
  src-docs/src/views/accessibility/screen_reader_live_focus.tsx
  src-docs/src/views/app_view.js
  src/components/accessibility/screen_reader_live/__snapshots__/screen_reader_live.test.tsx.snap
  src/components/accessibility/screen_reader_live/screen_reader_live.test.tsx
  src/components/accessibility/screen_reader_live/screen_reader_live.tsx
  src/components/selectable/__snapshots__/selectable.test.tsx.snap
  upcoming_changelogs/5995.md
Labels: documentation, accessibility, accessibility - screen reader
