Repository elastic/eui, pull requests merged in 2022-03, with the labels that each got.

#5664 Force bump known-css-properties package to 0.24.0
  package.json
  src/themes/amsterdam/global_styling/react_date_picker/_date_picker_times.scss
  yarn.lock
Labels: skip-changelog

#5678 [EuiEmptyPrompt Docs] Fix text inconsistencies
  src-docs/src/views/empty_prompt/_types_of_use_cases.tsx
  src-docs/src/views/empty_prompt/custom.tsx
  src-docs/src/views/empty_prompt/empty_prompt.tsx
  src-docs/src/views/empty_prompt/empty_prompt_layout.tsx
  src-docs/src/views/empty_prompt/empty_prompt_multiple_types.tsx
  src-docs/src/views/empty_prompt/empty_prompt_page_template.tsx
  src-docs/src/views/empty_prompt/empty_prompt_panel.tsx
  src-docs/src/views/empty_prompt/playground.js
  src-docs/src/views/empty_prompt/prompt_types/complex.tsx
  src-docs/src/views/empty_prompt/prompt_types/license_upgrade.tsx
  src-docs/src/views/empty_prompt/prompt_types/no_permission.tsx
  src-docs/src/views/empty_prompt/prompt_types/page_not_found.tsx
Labels: documentation, skip-changelog

#5663 [EuiEmptyPrompt] Allow horizontal image to be smaller than 50% and added a `gap`
  CHANGELOG.md
  src/components/empty_prompt/_empty_prompt.scss
Labels: style only

#5679 [EuiSelectableListItem] Revert layout changes and add `textWrap` option
  CHANGELOG.md
  src-docs/src/views/selectable/selectable_example.js
  src-docs/src/views/suggest/suggest_example.js
  src/components/selectable/__snapshots__/selectable.test.tsx.snap
  src/components/selectable/selectable_list/__snapshots__/selectable_list.test.tsx.snap
  src/components/selectable/selectable_list/__snapshots__/selectable_list_item.test.tsx.snap
  src/components/selectable/selectable_list/_selectable_list_item.scss
  src/components/selectable/selectable_list/selectable_list.test.tsx
  src/components/selectable/selectable_list/selectable_list.tsx
  src/components/selectable/selectable_list/selectable_list_item.test.tsx
  src/components/selectable/selectable_list/selectable_list_item.tsx
  src/components/suggest/__snapshots__/suggest.test.tsx.snap
  src/components/suggest/suggest.tsx
Labels: bug

#5658 [EuiSuggest][EuiSelectable] Allow controlled search `value` prop
  CHANGELOG.md
  src-docs/src/views/selectable/search.tsx
  src-docs/src/views/suggest/playground.js
  src-docs/src/views/suggest/suggest.tsx
  src-docs/src/views/suggest/suggest_example.js
  src-docs/src/views/suggest/suggest_item.tsx
  src/components/form/field_search/field_search.tsx
  src/components/selectable/__snapshots__/selectable.test.tsx.snap
  src/components/selectable/selectable.test.tsx
  src/components/selectable/selectable.tsx
  src/components/selectable/selectable_search/__snapshots__/selectable_search.test.tsx.snap
  src/components/selectable/selectable_search/selectable_search.test.tsx
  src/components/selectable/selectable_search/selectable_search.tsx
  src/components/suggest/__snapshots__/suggest.test.tsx.snap
  src/components/suggest/suggest.spec.tsx
  src/components/suggest/suggest.test.tsx
  src/components/suggest/suggest.tsx
Labels: breaking change

#5661 [Pagination Guidelines] Fixed auto-focus on context menu panel by removing the panel
  src-docs/src/views/pagination/guidelines.js
Labels: documentation, skip-changelog

#5684 [Docs] Add `copyToClipboard` utility function docs
  src-docs/src/views/copy/copy_example.js
  src-docs/src/views/copy/copy_to_clipboard.js
Labels: documentation, skip-changelog

#5693 [EuiSuggest] Fire `onItemClick` callback on Enter key presses; [EuiSelectable] Fix Enter and Space key to select items on non-searchable listboxes
  CHANGELOG.md
  src/components/selectable/selectable.spec.tsx
  src/components/selectable/selectable.tsx
  src/components/suggest/__snapshots__/suggest.test.tsx.snap
  src/components/suggest/suggest.spec.tsx
  src/components/suggest/suggest.test.tsx
  src/components/suggest/suggest.tsx
Labels: bug, !urgent!

#5699 [EuiBasicTable][EuiInMemoryTable][EuiDataGrid] Revert page size `number | 'all'` type to just `number`
  CHANGELOG.md
  src-docs/src/views/datagrid/in_memory_pagination.js
  src-docs/src/views/pagination/paginated_table.js
  src-docs/src/views/pagination/pagination_example.js
  src-docs/src/views/pagination/table_pagination.tsx
  src-docs/src/views/tables/data_store.js
  src-docs/src/views/tables/in_memory/in_memory_controlled_pagination.js
  src-docs/src/views/tables/paginated/paginated.js
  src/components/basic_table/__snapshots__/pagination_bar.test.tsx.snap
  src/components/basic_table/basic_table.test.tsx
  src/components/basic_table/basic_table.tsx
  src/components/basic_table/in_memory_table.test.tsx
  src/components/basic_table/in_memory_table.tsx
  src/components/basic_table/pagination_bar.test.tsx
  src/components/basic_table/pagination_bar.tsx
  src/components/datagrid/data_grid.tsx
  src/components/datagrid/data_grid_types.ts
  src/components/datagrid/utils/data_grid_pagination.test.tsx
  src/components/datagrid/utils/data_grid_pagination.tsx
  src/components/datagrid/utils/focus.ts
  src/components/datagrid/utils/grid_height_width.ts
  src/components/datagrid/utils/ref.ts
  src/components/datagrid/utils/row_count.ts
  src/components/table/table_pagination/table_pagination.test.tsx
  src/components/table/table_pagination/table_pagination.tsx
Labels: breaking change

#5718 Added a Figma specific PR checklist item
  .github/pull_request_template.md
Labels: skip-changelog

#5711 [Docs] Improve Import Statements for Elastic Charts Code Samples
  src-docs/src/components/guide_section/_utils.js
  src-docs/src/components/guide_section/_utils.test.js
Labels: skip-changelog

#5717 [EuiFilterGroup] Add `compressed` prop
  CHANGELOG.md
  src-docs/src/views/filter_group/filter_group_simple.js
  src/components/filter_group/__snapshots__/filter_button.test.tsx.snap
  src/components/filter_group/__snapshots__/filter_group.test.tsx.snap
  src/components/filter_group/filter_button.tsx
  src/components/filter_group/filter_group.test.tsx
  src/components/filter_group/filter_group.tsx
  src/themes/amsterdam/overrides/_filter_group.scss
Labels: breaking change

#5724 [EuiSelectableTemplateSitewide] Increase contrast of text when in dark header
  CHANGELOG.md
  src/components/selectable/selectable_templates/_selectable_template_sitewide.scss
Labels: style only

#5729 [Tech debt] Delete upcoming changelogs on release
  generator-eui/changelog/templates/changelog.md
  scripts/update-changelog.js
Labels: skip-changelog

#5719 [EuiContextMenu] Fix tab keypress requiring two presses to work correctly
  src/components/context_menu/context_menu_panel.spec.tsx
  src/components/context_menu/context_menu_panel.tsx
  upcoming_changelogs/5719.md
Labels: bug

#5652 [Docs] Add form controls examples docs
  src-docs/src/views/form_controls/form_controls_example.js
Labels: documentation, skip-changelog

#5707 [Docs] Add writing guidelines to selection controls
  src-docs/src/views/selection_controls/guidelines.js
  src-docs/src/views/selection_controls/selection_controls_example.js
Labels: documentation, skip-changelog

#5722 [CSS-in-JS] Emotion snapshot serializer
  scripts/compile-eui.js
  scripts/jest/config.json
  src/components/accordion/__snapshots__/accordion.test.tsx.snap
  src/components/basic_table/__snapshots__/expanded_item_actions.test.tsx.snap
  src/components/datagrid/__snapshots__/data_grid.test.tsx.snap
  src/components/datagrid/body/data_grid_cell_popover.test.tsx
  src/components/datagrid/body/header/header_is_interactive.test.ts
  src/components/datagrid/controls/__snapshots__/column_sorting.test.tsx.snap
  src/components/datagrid/controls/display_selector.test.tsx
  src/components/datagrid/controls/fullscreen_selector.test.tsx
  src/components/datagrid/utils/col_widths.test.ts
  src/components/datagrid/utils/focus.test.tsx
  src/components/datagrid/utils/ref.test.ts
  src/components/datagrid/utils/row_heights.test.ts
  src/components/datagrid/utils/scrolling.test.tsx
  src/components/highlight/__snapshots__/highlight.test.tsx.snap
  src/components/mark/__snapshots__/mark.test.tsx.snap
  src/components/mark/mark.test.tsx
  src/components/selectable/selectable_list/__snapshots__/selectable_list.test.tsx.snap
  src/test/internal/index.ts
  src/test/internal/render_with_styles.ts
  src/test/internal/test_custom_hook.tsx
  wiki/testing.md
Labels: skip-changelog

#5746 [Wiki] Update old references to manual CHANGELOG.md updates
  wiki/documentation-guidelines.md
  wiki/releasing-versions.md
Labels: skip-changelog

#5743 [EuiSuperDatePicker] i18n all remaining static copy + convert prettyDuration to hook/component
  src-docs/src/views/pretty_duration/pretty_duration.js
  src-docs/src/views/pretty_duration/pretty_duration_example.js
  src-docs/src/views/super_date_picker/super_date_picker_custom_quick_select.tsx
  src-docs/src/views/super_date_picker/super_date_picker_pattern.tsx
  src/components/date_picker/auto_refresh/auto_refresh.tsx
  src/components/date_picker/auto_refresh/refresh_interval.tsx
  src/components/date_picker/super_date_picker/__snapshots__/super_date_picker.test.tsx.snap
  src/components/date_picker/super_date_picker/date_popover/absolute_tab.tsx
  src/components/date_picker/super_date_picker/date_popover/date_popover_button.tsx
  src/components/date_picker/super_date_picker/date_popover/date_popover_content.tsx
  src/components/date_picker/super_date_picker/date_popover/relative_tab.tsx
  src/components/date_picker/super_date_picker/index.ts
  src/components/date_picker/super_date_picker/pretty_duration.test.tsx
  src/components/date_picker/super_date_picker/pretty_duration.ts
  src/components/date_picker/super_date_picker/pretty_duration.tsx
  src/components/date_picker/super_date_picker/pretty_interval.test.ts
  src/components/date_picker/super_date_picker/pretty_interval.ts
  src/components/date_picker/super_date_picker/quick_select_popover/__snapshots__/quick_select.test.tsx.snap
  src/components/date_picker/super_date_picker/quick_select_popover/__snapshots__/quick_select_popover.test.tsx.snap
  src/components/date_picker/super_date_picker/quick_select_popover/quick_select.test.tsx
  src/components/date_picker/super_date_picker/quick_select_popover/quick_select.tsx
  src/components/date_picker/super_date_picker/quick_select_popover/quick_select_popover.test.tsx
  src/components/date_picker/super_date_picker/quick_select_popover/quick_select_popover.tsx
  src/components/date_picker/super_date_picker/quick_select_popover/quick_select_utils.ts
  src/components/date_picker/super_date_picker/quick_select_popover/recently_used.tsx
  src/components/date_picker/super_date_picker/relative_options.test.ts
  src/components/date_picker/super_date_picker/relative_options.ts
  src/components/date_picker/super_date_picker/relative_utils.ts
  src/components/date_picker/super_date_picker/super_date_picker.test.tsx
  src/components/date_picker/super_date_picker/super_date_picker.tsx
  src/components/date_picker/super_date_picker/time_options.test.tsx
  src/components/date_picker/super_date_picker/time_options.tsx
  src/components/date_picker/super_date_picker/time_units.ts
  src/components/date_picker/types.ts
  upcoming_changelogs/5743.md
Labels: breaking change, !urgent!, i18n

#5748 [EuiI18n] Fixed `EuiContext.i18n`'s `mappingFunc` not being called for `EuiI18n` with multiple tokens and function callbacks
  src-docs/src/views/i18n/i18n_interpolation.js
  src/components/i18n/__snapshots__/i18n.test.tsx.snap
  src/components/i18n/i18n.test.tsx
  src/components/i18n/i18n.tsx
  upcoming_changelogs/5748.md
Labels: bug

#5747 Adding Cypress test for selectable in popover.
  src/components/selectable/selectable.spec.tsx
Labels: test, skip-changelog, accessibility - automated

#5749 [Tech debt] Upgrade Node.js version to 16.14.2 to match Kibana
  .ci/jobs/elastic+eui+pull-request-test.yml
  .nvmrc
  package.json
  scripts/deploy/build_docs
  scripts/deploy/deploy_docs
  scripts/docker-ci/Dockerfile
  scripts/docker-ci/README.md
  scripts/test-docker.js
Labels: skip-changelog, tech debt

#5632 [Docs] New Templates section
  scripts/a11y-testing.js
  src-docs/src/routes.js
  src-docs/src/views/auto_refresh/auto_refresh_example.js
  src-docs/src/views/bottom_bar/bottom_bar_example.js
  src-docs/src/views/datagrid/_row_auto_height_data.json
  src-docs/src/views/empty_prompt/empty_prompt_example.js
  src-docs/src/views/home/home_view.js
  src-docs/src/views/page/page_template_example.js
  src-docs/src/views/page_header/page_header_example.js
  src-docs/src/views/panel/panel_example.js
  src-docs/src/views/selectable/selectable_example.js
  src-docs/src/views/selectable/selectable_sitewide_template_example.js
  src-docs/src/views/tabs/tabs_example.js
Labels: documentation, skip-changelog
