Repository elastic/eui, pull requests merged in 2022-12, with the labels that each got.

#6444 Remove `sass-vars-to-js-loader` dependency
  .gitattributes
  package.json
  src-docs/src/views/theme/typography/_typography_sass.tsx
  src-docs/src/views/theme/typography/values.tsx
  src/themes/charts/themes.ts
  yarn.lock
Labels: skip-changelog

#6450 Update RenovateBot owners of elastic/charts
  renovate.json
Labels: skip-changelog

#6426 [CSS-in-JS] Add utility for converting `style` to logical properties
  src/components/code/__snapshots__/code_block.test.tsx.snap
  src/components/code/code_block_virtualized.tsx
  src/global_styling/functions/__snapshots__/logicals.test.ts.snap
  src/global_styling/functions/logicals.test.ts
  src/global_styling/functions/logicals.ts
  upcoming_changelogs/6426.md
Labels: emotion

#6449 Adding a11y tests for Control Bar, Drag and Drop, Card.
  cypress/support/index.d.ts
  src/components/breadcrumbs/breadcrumbs.a11y.tsx
  src/components/card/card.a11y.tsx
  src/components/control_bar/control_bar.a11y.tsx
  src/components/drag_and_drop/drag_and_drop.a11y.tsx
Labels: skip-changelog, accessibility - automated

#6432 [Feature] Range sliders QA fixes
  src-docs/src/views/range/input.tsx
  src-docs/src/views/range/input_only.tsx
  src-docs/src/views/range/levels.tsx
  src-docs/src/views/range/range.tsx
  src-docs/src/views/range/range_example.js
  src-docs/src/views/range/states.tsx
  src-docs/src/views/range/ticks.tsx
  src/components/color_picker/color_stops/__snapshots__/color_stops.test.tsx.snap
  src/components/form/range/__snapshots__/dual_range.test.tsx.snap
  src/components/form/range/__snapshots__/range.test.tsx.snap
  src/components/form/range/__snapshots__/range_levels.test.tsx.snap
  src/components/form/range/__snapshots__/range_track.test.tsx.snap
  src/components/form/range/dual_range.styles.ts
  src/components/form/range/dual_range.test.tsx
  src/components/form/range/dual_range.tsx
  src/components/form/range/range.styles.ts
  src/components/form/range/range.test.tsx
  src/components/form/range/range.tsx
  src/components/form/range/range_draggable.styles.ts
  src/components/form/range/range_draggable.tsx
  src/components/form/range/range_highlight.styles.ts
  src/components/form/range/range_highlight.tsx
  src/components/form/range/range_input.styles.ts
  src/components/form/range/range_input.tsx
  src/components/form/range/range_label.styles.ts
  src/components/form/range/range_label.tsx
  src/components/form/range/range_levels.styles.ts
  src/components/form/range/range_levels.test.tsx
  src/components/form/range/range_levels.tsx
  src/components/form/range/range_slider.styles.ts
  src/components/form/range/range_slider.tsx
  src/components/form/range/range_thumb.styles.ts
  src/components/form/range/range_thumb.tsx
  src/components/form/range/range_ticks.styles.ts
  src/components/form/range/range_ticks.tsx
  src/components/form/range/range_tooltip.styles.ts
  src/components/form/range/range_tooltip.tsx
  src/components/form/range/range_track.styles.ts
  src/components/form/range/range_track.tsx
  src/components/form/range/range_wrapper.styles.ts
  src/components/form/range/range_wrapper.tsx
Labels: skip-changelog

#6452 Another attempt to fix failing PR → Project action
  .github/workflows/add_issues_to_project.yml
  .github/workflows/add_pr_to_project.yml
Labels: skip-changelog

#6453 Add renovate bot to jenkins white-list
  .ci/jobs/elastic+eui+pull-request.yml
Labels: skip-changelog

#6455 Removes PRs from the actions workflow
  .github/workflows/add_issues_to_project.yml
Labels: skip-changelog

#6454 [EuiBasicTable] Fix incorrect props documentation
  src/components/basic_table/in_memory_table.tsx
Labels: skip-changelog

#6461 Adding a11y tests for EuiColorPicker, EuiComboBox, and EuiCopy
  src/components/breadcrumbs/breadcrumbs.a11y.tsx
  src/components/color_picker/color_picker.a11y.tsx
  src/components/combo_box/combo_box.a11y.tsx
  src/components/control_bar/control_bar.a11y.tsx
  src/components/copy/copy.a11y.tsx
  src/components/modal/modal.a11y.tsx
  src/components/side_nav/side_nav.a11y.tsx
Labels: skip-changelog, accessibility - automated

#6467 [EuiDualRange] Add regression test for Kibana use of `ref` prop
  src/components/form/range/dual_range.test.tsx
Labels: test, skip-changelog

#6464 [Docs] Add EUI error messaging to playground errors
  src-docs/src/services/playground/playground.js
  src/components/error_boundary/error_boundary.tsx
Labels: documentation, skip-changelog

#6466 A11y specs for EuiDataGrid, EuiDatePicker, EuiDelayRender, EuiEmptyPrompt
  src/components/datagrid/data_grid.a11y.tsx
  src/components/date_picker/date_picker.a11y.tsx
  src/components/delay_hide/delay_hide.a11y.tsx
  src/components/delay_render/delay_render.a11y.tsx
  src/components/empty_prompt/empty_prompt.a11y.tsx
Labels: skip-changelog, accessibility - automated

#6471 Remove `nodegit` dependency
  package.json
  scripts/postinstall.js
  scripts/release.js
  scripts/update-token-changelog.js
  wiki/releasing-versions.md
  yarn.lock
Labels: skip-changelog

#6475 Fixes issue assignment action.
  .github/workflows/add_issues_to_project.yml
  .github/workflows/moves_assigned_card.yml
Labels: skip-changelog

#6473 Improve release script
  package.json
  scripts/release.js
  yarn.lock
Labels: skip-changelog

#6474 Remove `node-sass` in favor of dart `sass`
  README.md
  package.json
  scripts/compile-scss.js
  src-docs/webpack.config.js
  src/global_styling/mixins/_header.scss
  yarn.lock
Labels: skip-changelog

#6472 Added Cypress a11y tests for EuiErrorBoundary, EuiExpression, and EuiFilterGroup.
  src/components/error_boundary/error_boundary.a11y.tsx
  src/components/expression/expression.a11y.tsx
  src/components/filter_group/filter_group.a11y.tsx
Labels: skip-changelog, accessibility - automated

#6483 Remove unnecessary `known-css-properties` resolution
  package.json
  yarn.lock
Labels: dependencies, skip-changelog

#6482 Replace `remark-parse` with `remark-parse-no-trim`
  package.json
  src-docs/src/services/props/markdown_format/plugin_list.js
  src/components/markdown_editor/markdown_types.ts
  src/components/markdown_editor/plugins/markdown_default_plugins/parsing_plugins.ts
  upcoming_changelogs/6482.md
  yarn.lock
Labels: dependencies, tech debt

#6486 Added a11y and keyboard specs for EuiFocusTrap, EuiHeader, EuiIcon.
  src/components/focus_trap/focus_trap.a11y.tsx
  src/components/header/header.a11y.tsx
  src/components/icon/icon_ML.a11y.tsx
  src/components/icon/icon_apps.a11y.tsx
  src/components/icon/icon_editor.a11y.tsx
  src/components/icon/icon_elastic.a11y.tsx
  src/components/icon/icon_glyphs.a11y.tsx
  src/components/icon/icon_tokens.a11y.tsx
Labels: skip-changelog, accessibility - automated

#6489 [Emotion ] Convert `EuiColorStops`
  src-docs/src/views/color_picker/color_stops.tsx
  src/components/color_picker/_index.scss
  src/components/color_picker/color_picker.styles.ts
  src/components/color_picker/color_stops/__snapshots__/color_stop_thumb.test.tsx.snap
  src/components/color_picker/color_stops/__snapshots__/color_stops.test.tsx.snap
  src/components/color_picker/color_stops/_color_stops.scss
  src/components/color_picker/color_stops/_index.scss
  src/components/color_picker/color_stops/color_stop_thumb.styles.ts
  src/components/color_picker/color_stops/color_stop_thumb.tsx
  src/components/color_picker/color_stops/color_stops.styles.ts
  src/components/color_picker/color_stops/color_stops.test.tsx
  src/components/color_picker/color_stops/color_stops.tsx
  src/components/form/range/__snapshots__/range_track.test.tsx.snap
  src/components/form/range/range_highlight.styles.ts
  src/components/form/range/range_levels.styles.ts
  src/components/form/range/range_track.tsx
  src/services/color/manipulation.ts
  src/services/index.ts
  src/themes/amsterdam/overrides/_color_stops.scss
  src/themes/amsterdam/overrides/_index.scss
  upcoming_changelogs/6489.md
Labels: emotion
