Repository elastic/eui, pull requests merged in 2022-11, with the labels that each got.

#6334 Add more helpful tips to the Upgrading Kibana wiki
  wiki/upgrading-kibana.md
Labels: documentation, skip-changelog

#6331 Splitting Cypress tests for component function and axe (a11y) checks
  cypress.config.ts
  package.json
  scripts/cypress.js
  src/components/accordion/accordion.a11y.tsx
  src/components/accordion/accordion.spec.tsx
  src/components/context_menu/context_menu_panel.a11y.tsx
  src/components/context_menu/context_menu_panel.spec.tsx
  src/components/selectable/selectable.a11y.tsx
  src/components/selectable/selectable.spec.tsx
  tsconfig-cypress.json
  tsconfig.json
  wiki/cypress-testing.md
Labels: accessibility, skip-changelog, accessibility - automated

#6344 Adding Cypress a11y tests for five components.
  package.json
  src/components/date_picker/super_date_picker/super_date_picker.a11y.tsx
  src/components/modal/modal.a11y.tsx
  src/components/modal/modal.spec.tsx
  src/components/popover/popover.a11y.tsx
  src/components/tabs/tabs.a11y.tsx
  src/components/tabs/tabs.spec.tsx
  src/components/tree_view/tree_view.a11y.tsx
  src/components/tree_view/tree_view.spec.tsx
  yarn.lock
Labels: skip-changelog, accessibility - automated

#6340 Adding a Docker script and prompt for Cypress a11y tests in CI.
  package.json
  scripts/test-a11y-docker.js
Labels: skip-changelog, accessibility - automated

#6355 [EuiSkipLink] Allow consumer `onClick`s to be called even if no valid destination or fallback destination exists
  src/components/accessibility/skip_link/skip_link.test.tsx
  src/components/accessibility/skip_link/skip_link.tsx
  upcoming_changelogs/6355.md
Labels: accessibility

#6359 Adding an a11y spec for EuiFlyout.
  src/components/flyout/flyout.a11y.tsx
Labels: accessibility, skip-changelog, accessibility - automated

#6371 Bumping Node to 16.18.1 in Docker.
  .ci/jobs/elastic+eui+pull-request-test.yml
  .nvmrc
  package.json
  scripts/deploy/build_docs
  scripts/deploy/deploy_docs
  scripts/docker-ci/Dockerfile
  scripts/test-a11y-docker.js
  scripts/test-docker.js
Labels: platform, skip-changelog

#6374 [Emotion] Fix overly large scroll shadow gradients
  src/components/flyout/__snapshots__/flyout_body.test.tsx.snap
  src/global_styling/mixins/_helpers.ts
  src/global_styling/utility/__snapshots__/utility.test.tsx.snap
  upcoming_changelogs/6374.md
Labels: bug

#6372 Moving report only smoke test to a11y namespace.
  src/test/internal/axe_report_only.a11y.tsx
Labels: skip-changelog, accessibility - automated

#6377 [EuiCard] Fix bug with vertical cards not growing 100% in width
  src/components/card/card.styles.ts
  upcoming_changelogs/6377.md
Labels: bug

#6380 [EuiSuperDatePicker] Fix incorrect button margins in quick select popover
  src/components/date_picker/super_date_picker/_super_date_picker.scss
  src/components/date_picker/super_date_picker/quick_select_popover/_quick_select_popover.scss
  src/components/date_picker/super_date_picker/quick_select_popover/quick_select_popover.tsx
  src/components/date_picker/super_date_picker/quick_select_popover/recently_used.tsx
  upcoming_changelogs/6380.md
Labels: bug

#6381 [EuiFlex] Fix responsive selector missed in Emotion conversion
  src/components/flex/flex_group.styles.ts
  upcoming_changelogs/6381.md
Labels: bug

#6379 [Docs] Convert `DisplayToggles` to `*.TS`
  src-docs/src/components/codesandbox/link.js
  src-docs/src/services/string/clean_imports.js
  src-docs/src/views/date_picker/range.tsx
  src-docs/src/views/form_controls/display_toggles.tsx
Labels: documentation, skip-changelog

#6321 [Emotion] Convert `EuiModal`
  src-docs/src/views/modal/confirm_modal.tsx
  src-docs/src/views/modal/confirm_modal_loading.tsx
  src-docs/src/views/modal/modal.tsx
  src-docs/src/views/modal/modal_example.js
  src-docs/src/views/modal/modal_form.tsx
  src-docs/src/views/modal/modal_width.tsx
  src/components/image/image_fullscreen_wrapper.styles.ts
  src/components/index.scss
  src/components/modal/__snapshots__/confirm_modal.test.tsx.snap
  src/components/modal/__snapshots__/modal.test.tsx.snap
  src/components/modal/__snapshots__/modal_body.test.tsx.snap
  src/components/modal/__snapshots__/modal_footer.test.tsx.snap
  src/components/modal/__snapshots__/modal_header.test.tsx.snap
  src/components/modal/__snapshots__/modal_header_title.test.tsx.snap
  src/components/modal/_index.scss
  src/components/modal/_modal.scss
  src/components/modal/confirm_modal.test.tsx
  src/components/modal/confirm_modal.tsx
  src/components/modal/modal.styles.ts
  src/components/modal/modal.test.tsx
  src/components/modal/modal.tsx
  src/components/modal/modal_body.styles.ts
  src/components/modal/modal_body.test.tsx
  src/components/modal/modal_body.tsx
  src/components/modal/modal_footer.styles.ts
  src/components/modal/modal_footer.test.tsx
  src/components/modal/modal_footer.tsx
  src/components/modal/modal_header.styles.ts
  src/components/modal/modal_header.test.tsx
  src/components/modal/modal_header.tsx
  src/components/modal/modal_header_title.test.tsx
  src/components/modal/modal_header_title.tsx
  src/global_styling/utility/animations.ts
  src/themes/amsterdam/overrides/_index.scss
  src/themes/amsterdam/overrides/_modal.scss
  upcoming_changelogs/6321.md
Labels: emotion

#6421 Changing label in `upgrading-kibana.md`
  wiki/upgrading-kibana.md
Labels: documentation, skip-changelog

#6409 Specify the operator option when generating term queries.
  src/components/search_bar/query/__snapshots__/ast_to_es_query_dsl.test.ts.snap
  src/components/search_bar/query/ast_to_es_query_dsl.ts
  upcoming_changelogs/6409.md
Labels: bug

#6425 Empty prompt and content updates
  src-docs/src/images/empty-prompt/accessDenied--dark.png
  src-docs/src/images/empty-prompt/accessDenied--light.png
  src-docs/src/views/empty_prompt/prompt_types/no_permission.tsx
  src-docs/src/views/empty_prompt/prompt_types/page_not_found.tsx
Labels: documentation, skip-changelog

#6431 [CSS-in-JS] Fix EUI media queries to more flexibly account for custom breakpoints
  src-docs/src/views/theme/breakpoints/_breakpoints_js.tsx
  src/components/description_list/description_list.styles.ts
  src/components/description_list/description_list_description.styles.ts
  src/components/description_list/description_list_description.tsx
  src/components/description_list/description_list_title.styles.ts
  src/components/flex/flex_grid.styles.ts
  src/components/flex/flex_group.styles.ts
  src/components/flyout/flyout.styles.ts
  src/components/image/image_wrapper.styles.ts
  src/components/modal/modal.styles.ts
  src/components/modal/modal_body.styles.ts
  src/components/modal/modal_footer.styles.ts
  src/components/page/page.styles.ts
  src/components/toast/global_toast_list.styles.ts
  src/global_styling/mixins/__snapshots__/_responsive.test.ts.snap
  src/global_styling/mixins/_responsive.test.ts
  src/global_styling/mixins/_responsive.ts
  upcoming_changelogs/6431.md
Labels: emotion

#6383 Adding a11y specs for three navigation patterns.
  src/components/breadcrumbs/breadcrumbs.a11y.tsx
  src/components/pagination/pagination.a11y.tsx
  src/components/side_nav/side_nav.a11y.tsx
Labels: skip-changelog, accessibility - automated

#6427 Adds actions for EUI Team project.
  .github/workflows/add_issues_to_project.yml
  .github/workflows/moves_assigned_card.yml
Labels: skip-changelog

#6438 [Wiki] Remove `main` changelog update step from Kibana patch/backports docs
  wiki/releasing-versions.md
Labels: documentation, skip-changelog

#6434 [Icons] Discuss and Issue icons added
  src-docs/src/views/icon/icons.js
  src/components/icon/__snapshots__/icon.test.tsx.snap
  src/components/icon/assets/discuss.tsx
  src/components/icon/assets/dotInCircle.tsx
  src/components/icon/assets/issue.tsx
  src/components/icon/icon_map.ts
  src/components/icon/svgs/discuss.svg
  src/components/icon/svgs/dotInCircle.svg
  upcoming_changelogs/6434.md
Labels: icons

#6445 Cleanup refactor for Breadcrumbs Emotion conversion
  src-docs/src/views/breadcrumbs/breadcrumbs.tsx
  src-docs/src/views/breadcrumbs/breadcrumbs_example.js
  src-docs/src/views/breadcrumbs/max.tsx
  src-docs/src/views/breadcrumbs/responsive.tsx
  src-docs/src/views/breadcrumbs/responsive_custom.tsx
  src-docs/src/views/breadcrumbs/truncate.tsx
  src-docs/src/views/breadcrumbs/truncate_single.tsx
  src-docs/src/views/header/header.tsx
  src-docs/src/views/header/header_alert.tsx
  src-docs/src/views/header/header_animate.tsx
  src-docs/src/views/header/header_dark.tsx
  src-docs/src/views/header/header_elastic_pattern.tsx
  src-docs/src/views/header/header_example.js
  src-docs/src/views/header/header_links.tsx
  src-docs/src/views/header/header_position.tsx
  src-docs/src/views/header/header_sections.tsx
  src-docs/src/views/header/header_stacked.tsx
  src/components/breadcrumbs/__snapshots__/breadcrumbs.test.tsx.snap
  src/components/breadcrumbs/breadcrumb.tsx
  src/components/breadcrumbs/breadcrumbs.test.tsx
  src/components/control_bar/__snapshots__/control_bar.test.tsx.snap
  src/components/header/__snapshots__/header.test.tsx.snap
  src/components/header/header_breadcrumbs/__snapshots__/header_breadcrumbs.test.tsx.snap
  src/components/header/header_breadcrumbs/header_breadcrumbs.test.tsx
  src/components/page/page_header/__snapshots__/page_header.test.tsx.snap
  src/components/page/page_header/__snapshots__/page_header_content.test.tsx.snap
  src/themes/amsterdam/overrides/_breadcrumbs.scss
Labels: documentation, skip-changelog, emotion

#6429 [CSS-in-JS] Add `logicalShorthandCSS` util + lint rule
  scripts/eslint-plugin/css_logical_properties.js
  scripts/eslint-plugin/css_logical_properties.test.js
  src-docs/src/views/comment/comment_props.tsx
  src-docs/src/views/theme/borders/_border_sass.tsx
  src-docs/src/views/theme/sizing/_sizing_js.tsx
  src/components/badge/badge.styles.ts
  src/components/breadcrumbs/breadcrumb.styles.ts
  src/components/button/button_display/_button_display.styles.ts
  src/components/code/code.styles.ts
  src/components/expression/expression.styles.ts
  src/components/list_group/list_group_item.styles.ts
  src/components/loading/loading_spinner.styles.ts
  src/components/markdown_editor/__snapshots__/markdown_format.styles.test.ts.snap
  src/components/markdown_editor/markdown_format.styles.ts
  src/components/modal/modal_header.styles.ts
  src/components/popover/popover_footer.styles.ts
  src/components/popover/popover_title.styles.ts
  src/components/text/text.styles.ts
  src/components/token/token.styles.ts
  src/components/tool_tip/tool_tip.styles.ts
  src/global_styling/functions/index.ts
  src/global_styling/functions/logical_shorthands.test.ts
  src/global_styling/functions/logical_shorthands.ts
  src/global_styling/functions/logicals.json
  src/global_styling/functions/logicals.ts
  upcoming_changelogs/6429.md
Labels: emotion
