Repository elastic/eui, pull requests merged in 2022-04, with the labels that each got.

#5758 Update renovate configuration to include @elastic/charts
  renovate.json
Labels: skip-changelog

#5734 [EuiDataGrid] Deprecate the `closePopover` callback passed to `cellActions` in favor of `closeCellPopover` ref API
  src-docs/src/views/datagrid/cells_popovers/datagrid_cells_example.js
  src/components/datagrid/body/data_grid_cell.test.tsx
  src/components/datagrid/body/data_grid_cell.tsx
  src/components/datagrid/body/data_grid_cell_actions.test.tsx
  src/components/datagrid/body/data_grid_cell_actions.tsx
  src/components/datagrid/data_grid_types.ts
  upcoming_changelogs/5734.md
Labels: breaking change

#5764 [CSS-in-JS] Configure snapshot serializer `includeStyles` option
  package.json
  scripts/jest/config.json
  scripts/jest/setup/emotion.js
  src/components/accordion/__snapshots__/accordion.test.tsx.snap
  src/components/basic_table/__snapshots__/expanded_item_actions.test.tsx.snap
  src/components/datagrid/__snapshots__/data_grid.test.tsx.snap
  src/components/datagrid/controls/__snapshots__/column_sorting.test.tsx.snap
  yarn.lock
Labels: skip-changelog

#5772 Reducing the snapshot output of EuiMark unit tests.
  scripts/jest/setup/emotion.js
  src/components/mark/__snapshots__/mark.test.tsx.snap
  src/components/mark/mark.test.tsx
Labels: bug, test, skip-changelog

#5771 Updating docs site a11y testing with new rules, skip list.
  package.json
  scripts/a11y-testing.js
  wiki/automated-accessibility-testing.md
  yarn.lock
Labels: accessibility, test, skip-changelog, accessibility - automated

#5786 Bumping Cypress and Cypress Real Events to latest.
  package.json
  yarn.lock
Labels: skip-changelog, tech debt

#5794 Attempt to squash flaky EuiDataGridFooterRow tests
  src/components/datagrid/body/data_grid_footer_row.spec.tsx
Labels: skip-changelog

#5800 Use `package.json` `files` entry instead of `.npmignore`
  .npmignore
  package.json
Labels: skip-changelog

#5804 [Dev-only] Release script improvements
  package.json
  scripts/release.js
  scripts/tests/update-changelog.test.js
  scripts/update-changelog.js
  wiki/releasing-versions.md
Labels: skip-changelog, tech debt

#5807 [ci] add an artifact archiving publisher for pr job
  .ci/jobs/elastic+eui+pull-request-test.yml
Labels: skip-changelog

#5803 [Jest] Remove `_isJest` polyfill
  scripts/jest/setup/polyfills.js
  src/utils/is_jest.ts
Labels: skip-changelog

#5802 Adding `describe` block to EuiMark unit test that omits screen reader helper text
  src/components/mark/mark.test.tsx
Labels: test, skip-changelog

#5784 [EuiPopover] Focus on parent popover panel by default, instead of first tabbable child
  src-docs/src/views/popover/initial_focus.js
  src-docs/src/views/popover/popover_example.js
  src-docs/src/views/popover/trap_focus.js
  src/components/context_menu/context_menu_panel.spec.tsx
  src/components/context_menu/context_menu_panel.tsx
  src/components/datagrid/data_grid.spec.tsx
  src/components/popover/popover.spec.tsx
  src/components/popover/popover.tsx
  upcoming_changelogs/5784.md
Labels: breaking change

#5816 [Build] Scope `pegjs-inline-precompile` usage
  .babelrc.js
Labels: skip-changelog

#5820 Remove missing Sass file import
  src/themes/amsterdam/_globals.scss
  upcoming_changelogs/5820.md
Labels: skip-changelog

#5805 [ci] Save Cypress failure screenshots as CI artifacts
  scripts/deploy/build_docs
  scripts/docker-ci/Dockerfile
  scripts/test-docker.js
  src/components/context_menu/__snapshots__/context_menu_panel.test.tsx.snap
  src/components/context_menu/context_menu_panel.test.tsx
Labels: skip-changelog

#5819 [Emotion] Add new test helper for validating custom `className`, `css`, and `style` props
  src/components/avatar/avatar.test.tsx
  src/components/mark/mark.test.tsx
  src/test/internal/index.ts
  src/test/internal/render_custom_styles.tsx
Labels: skip-changelog, tech debt

#5817 [Platform] Force prune local tags on release
  scripts/release.js
Labels: platform, skip-changelog

#5825 [Emotion] Disable `renderWithStyles` test helper
  src/components/avatar/__snapshots__/avatar.test.tsx.snap
  src/components/avatar/avatar.test.tsx
  src/components/mark/mark.test.tsx
  src/test/internal/render_with_styles.ts
Labels: skip-changelog, tech debt

#5733 [Wiki] Update Wiki with Documentation on Creating Component Documentation
  wiki/documentation-guidelines.md
  wiki/eui-documentation-site.md
Labels: skip-changelog

#5815 [EuiHorizontalRule] convert horizontal rule to emotion
  src/components/context_menu/__snapshots__/context_menu.test.tsx.snap
  src/components/horizontal_rule/__snapshots__/horizontal_rule.test.tsx.snap
  src/components/horizontal_rule/_horizontal_rule.scss
  src/components/horizontal_rule/_index.scss
  src/components/horizontal_rule/horizontal_rule.styles.ts
  src/components/horizontal_rule/horizontal_rule.test.tsx
  src/components/horizontal_rule/horizontal_rule.tsx
  src/components/index.scss
  upcoming_changelogs/5815.md
Labels: emotion

#5835 [Emotion] Add internal service for cloning elements with the `css` property
  src/services/theme/clone_element.test.tsx
  src/services/theme/clone_element.tsx
Labels: skip-changelog, emotion

#5839 Updating a const name in the Emotion wiki entry.
  wiki/writing-styles-with-emotion.md
Labels: documentation, skip-changelog, emotion

#5832 [Emotion] Convert EuiHealth
  src/components/health/__snapshots__/health.test.tsx.snap
  src/components/health/_health.scss
  src/components/health/_index.scss
  src/components/health/health.styles.ts
  src/components/health/health.test.tsx
  src/components/health/health.tsx
  src/components/index.scss
  upcoming_changelogs/5832.md
Labels: emotion

#5844 [Emotion Wiki] Adding sections about child element styles
  wiki/writing-styles-with-emotion.md
Labels: skip-changelog

#5842 [Emotion] Convert EuiTitle
  src/components/card/__snapshots__/card.test.tsx.snap
  src/components/collapsible_nav/collapsible_nav_group/__snapshots__/collapsible_nav_group.test.tsx.snap
  src/components/empty_prompt/__snapshots__/empty_prompt.test.tsx.snap
  src/components/index.scss
  src/components/page/page_header/__snapshots__/page_header.test.tsx.snap
  src/components/page/page_header/__snapshots__/page_header_content.test.tsx.snap
  src/components/provider/__snapshots__/provider.test.tsx.snap
  src/components/side_nav/__snapshots__/side_nav.test.tsx.snap
  src/components/stat/__snapshots__/stat.test.tsx.snap
  src/components/steps/__snapshots__/step.test.tsx.snap
  src/components/steps/__snapshots__/steps.test.tsx.snap
  src/components/steps/_steps.scss
  src/components/title/__snapshots__/title.styles.test.ts.snap
  src/components/title/__snapshots__/title.test.tsx.snap
  src/components/title/_index.scss
  src/components/title/_title.scss
  src/components/title/title.styles.test.ts
  src/components/title/title.styles.ts
  src/components/title/title.test.tsx
  src/components/title/title.tsx
  src/components/tour/__snapshots__/tour_step.test.tsx.snap
  src/global_styling/mixins/_typography.ts
  src/global_styling/variables/_title.ts
  src/global_styling/variables/typography.ts
  src/test/internal/render_custom_styles.tsx
  src/themes/amsterdam/global_styling/variables/_typography.ts
  src/themes/amsterdam/global_styling/variables/title.ts
  upcoming_changelogs/5842.md
Labels: emotion

#5851 [CSS-in-JS] Convert `EuiSkipLink`
  src/components/accessibility/_index.scss
  src/components/accessibility/skip_link/__snapshots__/skip_link.test.tsx.snap
  src/components/accessibility/skip_link/_skip_link.scss
  src/components/accessibility/skip_link/skip_link.styles.ts
  src/components/accessibility/skip_link/skip_link.tsx
  src/global_styling/variables/levels.ts
  upcoming_changelogs/5851.md
Labels: emotion

#5852 [Docs] ThemeExample component - tweak `snippetLanguage` logic
  src-docs/src/views/accessibility/accessibility_example.js
  src-docs/src/views/scroll/scroll.tsx
  src-docs/src/views/scroll/scroll_x.tsx
  src-docs/src/views/scroll/scroll_y.tsx
  src-docs/src/views/theme/_components/_theme_example.tsx
  src-docs/src/views/theme/borders/_border_js.tsx
  src-docs/src/views/theme/color/_color_js.tsx
  src-docs/src/views/theme/other/_animation_js.tsx
  src-docs/src/views/theme/other/_shadow_js.tsx
  src-docs/src/views/theme/sizing/_sizing_js.tsx
  src-docs/src/views/theme/typography/_typography_js.tsx
  src-docs/src/views/theme/typography/typography.tsx
  src-docs/src/views/utility_classes/utility_classes_section.tsx
Labels: skip-changelog
