Repository elastic/eui, pull requests merged in 2022-10, with the labels that each got.

#6286 [Docs] fixed EuiThemeProvider links in EuiProvider documentation
  src-docs/src/views/provider/provider_example.js
Labels: skip-changelog

#6290 [EuiOverlayMask] Fix example with duplicate masks & misc cleanup
  src-docs/src/views/overlay_mask/overlay_mask.tsx
  src-docs/src/views/overlay_mask/overlay_mask_example.js
  src-docs/src/views/overlay_mask/overlay_mask_header.js
  src-docs/src/views/overlay_mask/overlay_mask_header.tsx
Labels: skip-changelog

#6296 [EuiOverlayMask] Do not allow the `css` prop
  src-docs/src/views/overlay_mask/props.tsx
  src/components/overlay_mask/overlay_mask.tsx
Labels: skip-changelog

#6295 [EuiToolTip] Improve Emotion CSS
  src/components/tool_tip/__snapshots__/tool_tip.test.tsx.snap
  src/components/tool_tip/__snapshots__/tool_tip_popover.test.tsx.snap
  src/components/tool_tip/tool_tip.styles.ts
  src/components/tool_tip/tool_tip.tsx
  src/components/tool_tip/tool_tip_arrow.tsx
  src/components/tool_tip/tool_tip_popover.tsx
  upcoming_changelogs/6295.md
Labels: emotion

#6294 [Emotion] Improve checklist/QA process
  .github/pull_request_template.md
  generator-eui/changelog/index.js
  generator-eui/changelog/templates/changelog.md
  upcoming_changelogs/_template.md
Labels: skip-changelog, emotion

#6309 [Docs EuiButton] Added vertical spacing in examples
  src-docs/src/views/button/button.js
  src-docs/src/views/button/button_as_link.js
  src-docs/src/views/button/button_empty.js
  src-docs/src/views/button/button_with_icon.js
Labels: documentation, skip-changelog

#6324 Fix EuiSideBar with `css` props not being detected by EuiPageTemplate
  src/components/page_template/__snapshots__/page_template.test.tsx.snap
  src/components/page_template/page_template.test.tsx
  src/components/page_template/page_template.tsx
  upcoming_changelogs/6324.md
Labels: bug

#6265 [Range sliders] Implement new levels design
  src-docs/src/views/range/range_example.js
  src/components/color_picker/color_stops/__snapshots__/color_stops.test.tsx.snap
  src/components/form/range/__snapshots__/dual_range.test.tsx.snap
  src/components/form/range/__snapshots__/range.test.tsx.snap
  src/components/form/range/__snapshots__/range_levels.test.tsx.snap
  src/components/form/range/dual_range.tsx
  src/components/form/range/range.styles.ts
  src/components/form/range/range.tsx
  src/components/form/range/range_highlight.styles.ts
  src/components/form/range/range_highlight.tsx
  src/components/form/range/range_levels.styles.ts
  src/components/form/range/range_levels.tsx
  src/components/form/range/range_levels_colors.ts
  src/components/form/range/range_slider.styles.ts
  src/components/form/range/range_slider.tsx
  src/components/form/range/range_track.tsx
Labels: skip-changelog

#6329 [EuiPopover] Add `hasDragDrop` prop for popovers with draggable contexts
  src/components/datagrid/controls/__snapshots__/column_selector.test.tsx.snap
  src/components/datagrid/controls/__snapshots__/column_sorting.test.tsx.snap
  src/components/datagrid/controls/_data_grid_toolbar.scss
  src/components/datagrid/controls/column_selector.tsx
  src/components/datagrid/controls/column_sorting.tsx
  src/components/popover/__snapshots__/popover.rtl.test.tsx.snap
  src/components/popover/__snapshots__/popover.test.tsx.snap
  src/components/popover/popover.tsx
  src/components/popover/popover_arrow/_popover_arrow.tsx
  src/components/popover/popover_panel/__snapshots__/_popover_panel.test.tsx.snap
  src/components/popover/popover_panel/_popover_panel.styles.ts
  src/components/popover/popover_panel/_popover_panel.test.tsx
  src/components/popover/popover_panel/_popover_panel.tsx
  src/components/tour/__snapshots__/tour_step.test.tsx.snap
  upcoming_changelogs/6329.md
Labels: bug

#6327 [EuiModal] Temporary workaround for scroll-jumping behavior
  src/components/modal/__snapshots__/modal.test.tsx.snap
  src/components/modal/modal.test.tsx
  src/components/modal/modal.tsx
  upcoming_changelogs/6327.md
Labels: bug
