Repository elastic/eui, pull requests merged in 2022-07, with the labels that each got.

#6038 Upgrade Node to v16.16.0 to match Kibana
  .ci/jobs/elastic+eui+pull-request-test.yml
  .nvmrc
  package.json
  scripts/deploy/build_docs
  scripts/deploy/deploy_docs
  scripts/docker-ci/Dockerfile
  scripts/docker-ci/README.md
  scripts/test-docker.js
Labels: skip-changelog, tech debt

#6046 Add new auto-close cron job for `answered` label
  .github/workflows/stale_issues.yml
Labels: skip-changelog

#6042 Expose scrollTo and scrollToItem on imperative ref
  src-docs/src/views/datagrid/advanced/datagrid_advanced_example.js
  src-docs/src/views/datagrid/advanced/ref.tsx
  src/components/datagrid/data_grid.tsx
  src/components/datagrid/data_grid_types.ts
  src/components/datagrid/utils/ref.spec.tsx
  src/components/datagrid/utils/ref.ts
  upcoming_changelogs/6042.md
Labels: data grid

#6051 Fix some Emotion snapshots not being correctly converted to static classNames
  src/components/health/__snapshots__/health.test.tsx.snap
  src/components/loading/__snapshots__/loading_chart.test.tsx.snap
  src/components/stat/__snapshots__/stat.test.tsx.snap
  src/test/emotion-prefix.ts
Labels: skip-changelog, tech debt

#6058 [EuiIcon] Add `keyboard` glyph
  src-docs/src/views/icon/icons.js
  src-docs/src/views/selectable/selectable_sitewide_template_example.js
  src/components/icon/__snapshots__/icon.test.tsx.snap
  src/components/icon/assets/keyboard.tsx
  src/components/icon/icon_map.ts
  src/components/icon/svgs/keyboard.svg
  src/components/icon/svgs/keyboard_shortcut.svg
  upcoming_changelogs/6058.md
Labels: deprecations

#6050 [EuiDataGrid] Fix row height tests and mocks
  src/components/datagrid/body/data_grid_body.test.tsx
  src/components/datagrid/body/data_grid_body.tsx
  src/components/datagrid/body/data_grid_cell.test.tsx
  src/components/datagrid/data_grid_types.ts
  src/components/datagrid/utils/__mocks__/row_heights.ts
  src/components/datagrid/utils/row_heights.test.ts
  src/components/datagrid/utils/row_heights.ts
  src/services/hooks/index.ts
  src/services/hooks/useLatest.test.tsx
  src/services/hooks/useLatest.ts
Labels: data grid, skip-changelog

#6030 [EuiCommentList] Convert to `Emotion`, allow `custom` children and new `event` props
  src-docs/src/views/comment/comment.tsx
  src-docs/src/views/comment/comment_actions.tsx
  src-docs/src/views/comment/comment_avatar.tsx
  src-docs/src/views/comment/comment_example.js
  src-docs/src/views/comment/comment_flexible.tsx
  src-docs/src/views/comment/comment_list.tsx
  src-docs/src/views/comment/comment_props.tsx
  src-docs/src/views/comment/comment_system.tsx
  src-docs/src/views/comment/comment_timelineIcons.tsx
  src-docs/src/views/comment/comment_types.tsx
  src-docs/src/views/copy/copy_to_clipboard.js
  src/components/comment_list/__snapshots__/comment.test.tsx.snap
  src/components/comment_list/__snapshots__/comment_event.test.tsx.snap
  src/components/comment_list/__snapshots__/comment_list.test.tsx.snap
  src/components/comment_list/__snapshots__/comment_timeline.test.tsx.snap
  src/components/comment_list/_comment.scss
  src/components/comment_list/_comment_event.scss
  src/components/comment_list/_comment_timeline.scss
  src/components/comment_list/_index.scss
  src/components/comment_list/comment.test.tsx
  src/components/comment_list/comment.tsx
  src/components/comment_list/comment_event.styles.ts
  src/components/comment_list/comment_event.test.tsx
  src/components/comment_list/comment_event.tsx
  src/components/comment_list/comment_list.test.tsx
  src/components/comment_list/comment_list.tsx
  src/components/comment_list/comment_timeline.test.tsx
  src/components/comment_list/comment_timeline.tsx
  src/components/comment_list/index.ts
  src/components/index.scss
  src/components/markdown_editor/_markdown_editor.scss
  src/components/timeline/timeline_item.tsx
  src/themes/amsterdam/overrides/_comment.scss
  src/themes/amsterdam/overrides/_index.scss
  upcoming_changelogs/6030.md
Labels: breaking change

#6061 [Docs EuiEmptyPrompt] Add new page not found illustration
  src-docs/src/images/empty-prompt/404_rainy_cloud_dark.png
  src-docs/src/images/empty-prompt/404_rainy_cloud_light.png
  src-docs/src/images/empty-prompt/pageNotFound--dark.png
  src-docs/src/images/empty-prompt/pageNotFound--dark@2x.png
  src-docs/src/images/empty-prompt/pageNotFound--light.png
  src-docs/src/images/empty-prompt/pageNotFound--light@2x.png
  src-docs/src/views/empty_prompt/_types_of_empty_states.tsx
  src-docs/src/views/empty_prompt/_types_of_use_cases.tsx
  src-docs/src/views/empty_prompt/prompt_types/page_not_found.tsx
Labels: skip-changelog

#6062 [Docs EuiPortal] Fix CodeSandbox demos
  src-docs/src/views/portal/portal.js
  src-docs/src/views/portal/portal_example.js
  src-docs/src/views/portal/portal_insert.js
Labels: skip-changelog

#6056 [CSS-in-JS] Convert `EuiTextDiff`
  src/components/index.scss
  src/components/text_diff/__snapshots__/text-diff.test.tsx.snap
  src/components/text_diff/_index.scss
  src/components/text_diff/_text_diff.scss
  src/components/text_diff/text-diff.test.tsx
  src/components/text_diff/text_diff.styles.ts
  src/components/text_diff/text_diff.tsx
  upcoming_changelogs/6056.md
Labels: emotion

#6053 [CSS-in-JS] Convert `EuiErrorBoundary`
  src/components/error_boundary/_error_boundary.scss
  src/components/error_boundary/_index.scss
  src/components/error_boundary/error_boundary.styles.ts
  src/components/error_boundary/error_boundary.tsx
  src/components/index.scss
  upcoming_changelogs/6053.md
Labels: emotion

#6044 [EuiPopover] Removed `false` as an option for `initialFocus`, removed unnecessary focus logic
  src/components/context_menu/context_menu_panel.spec.tsx
  src/components/context_menu/context_menu_panel.tsx
  src/components/focus_trap/focus_trap.tsx
  src/components/popover/popover.spec.tsx
  src/components/popover/popover.test.tsx
  src/components/popover/popover.tsx
  upcoming_changelogs/6044.md
Labels: breaking change

#5969 [Emotion] Convert `EuiImage`
  src-docs/src/views/image/float.tsx
  src-docs/src/views/image/image.js
  src-docs/src/views/image/image.tsx
  src-docs/src/views/image/image_example.js
  src-docs/src/views/image/image_size.tsx
  src-docs/src/views/image/image_zoom.js
  src-docs/src/views/image/image_zoom.tsx
  src/components/image/__snapshots__/image.test.tsx.snap
  src/components/image/_image.scss
  src/components/image/_index.scss
  src/components/image/image.styles.ts
  src/components/image/image.test.tsx
  src/components/image/image.tsx
  src/components/image/image_button.styles.ts
  src/components/image/image_button.tsx
  src/components/image/image_caption.styles.ts
  src/components/image/image_caption.tsx
  src/components/image/image_fullscreen_wrapper.styles.ts
  src/components/image/image_fullscreen_wrapper.tsx
  src/components/image/image_types.ts
  src/components/image/image_wrapper.styles.ts
  src/components/image/image_wrapper.tsx
  src/components/image/index.ts
  src/components/index.scss
  src/components/text/text.styles.ts
  src/themes/amsterdam/overrides/_image.scss
  src/themes/amsterdam/overrides/_index.scss
  upcoming_changelogs/5969.md
Labels: breaking change, emotion

#6069 [Emotion] Fix `euiBreakpoint` behavior to match Sass mixin
  scripts/jest/config.json
  src-docs/src/views/theme/breakpoints/_breakpoints_js.tsx
  src/global_styling/mixins/__snapshots__/_responsive.test.ts.snap
  src/global_styling/mixins/_responsive.test.ts
  src/global_styling/mixins/_responsive.ts
  upcoming_changelogs/6057.md
Labels: skip-changelog

#6071 [EuiComment] Revert `username` prop to accept a `ReactNode`
  src-docs/src/views/comment/comment.tsx
  src-docs/src/views/comment/comment_actions.tsx
  src-docs/src/views/comment/comment_avatar.tsx
  src-docs/src/views/comment/comment_example.js
  src-docs/src/views/comment/comment_flexible.tsx
  src-docs/src/views/comment/comment_list.tsx
  src-docs/src/views/comment/comment_props.tsx
  src-docs/src/views/comment/comment_system.tsx
  src-docs/src/views/copy/copy_to_clipboard.js
  src/components/avatar/__snapshots__/avatar.test.tsx.snap
  src/components/avatar/avatar.tsx
  src/components/comment_list/__snapshots__/comment.test.tsx.snap
  src/components/comment_list/__snapshots__/comment_event.test.tsx.snap
  src/components/comment_list/__snapshots__/comment_list.test.tsx.snap
  src/components/comment_list/__snapshots__/comment_timeline.test.tsx.snap
  src/components/comment_list/comment.test.tsx
  src/components/comment_list/comment.tsx
  src/components/comment_list/comment_event.tsx
  src/components/comment_list/comment_timeline.test.tsx
  src/components/comment_list/comment_timeline.tsx
  src/components/timeline/__snapshots__/timeline.test.tsx.snap
  src/components/timeline/__snapshots__/timeline_item.test.tsx.snap
  upcoming_changelogs/6071.md
Labels: breaking change

#6076 [BUG]: Adding `role=marquee` to `EuiFilterButton`
  src/components/filter_group/__snapshots__/filter_button.test.tsx.snap
  src/components/filter_group/filter_button.tsx
  upcoming_changelogs/6076.md
Labels: bug, accessibility, accessibility - automated

#6078 Track changes to json theme files during release
  scripts/release.js
Labels: platform, skip-changelog

#6074 [EuiSelectable] Enable CodeSandbox links and misc documentation improvements
  src-docs/src/routes.js
  src-docs/src/views/_index.scss
  src-docs/src/views/selectable/data.ts
  src-docs/src/views/selectable/props.tsx
  src-docs/src/views/selectable/selectable.tsx
  src-docs/src/views/selectable/selectable_custom_render.js
  src-docs/src/views/selectable/selectable_custom_render.tsx
  src-docs/src/views/selectable/selectable_example.js
  src-docs/src/views/selectable/selectable_exclusion.tsx
  src-docs/src/views/selectable/selectable_messages.tsx
  src-docs/src/views/selectable/selectable_search.tsx
  src-docs/src/views/selectable/selectable_single.tsx
  src-docs/src/views/selectable/selectable_sizing.tsx
  src-docs/src/views/selectable/selectable_templates/_sitewide.scss
  src-docs/src/views/selectable/selectable_templates/sitewide_example.js
  src-docs/src/views/selectable/selectable_templates/sitewide_option.tsx
  src-docs/src/views/selectable/selectable_templates/sitewide_search.tsx
Labels: documentation, skip-changelog

#6082 [Wiki] Add script for running Kibana type checks
  wiki/upgrading-kibana.md
Labels: skip-changelog

#6083 Tweak release script prompt
  scripts/release.js
Labels: skip-changelog

#6068 [EuiToast & Co.] Convert to function component, Emotion styling
  src/components/index.scss
  src/components/toast/__snapshots__/global_toast_list.test.tsx.snap
  src/components/toast/__snapshots__/global_toast_list_item.test.tsx.snap
  src/components/toast/__snapshots__/toast.test.tsx.snap
  src/components/toast/_global_toast_list.scss
  src/components/toast/_index.scss
  src/components/toast/_toast.scss
  src/components/toast/global_toast_list.styles.ts
  src/components/toast/global_toast_list.test.tsx
  src/components/toast/global_toast_list.tsx
  src/components/toast/global_toast_list_item.tsx
  src/components/toast/toast.styles.ts
  src/components/toast/toast.tsx
  src/themes/amsterdam/overrides/_index.scss
  src/themes/amsterdam/overrides/_toast.scss
  upcoming_changelogs/6068.md
Labels: emotion

#5934 Moving EuiBreadcrumb styles to Emotion.
  src-docs/src/views/breadcrumbs/breadcrumbs_example.js
  src-docs/src/views/breadcrumbs/playground.js
  src-docs/src/views/breadcrumbs/props.tsx
  src-docs/src/views/theme/_json/eui_theme_dark.json
  src-docs/src/views/theme/_json/eui_theme_light.json
  src/components/breadcrumbs/__snapshots__/breadcrumbs.test.tsx.snap
  src/components/breadcrumbs/_breadcrumbs.scss
  src/components/breadcrumbs/_index.scss
  src/components/breadcrumbs/_variables.scss
  src/components/breadcrumbs/breadcrumb.styles.ts
  src/components/breadcrumbs/breadcrumb.tsx
  src/components/breadcrumbs/breadcrumbs.styles.ts
  src/components/breadcrumbs/breadcrumbs.test.tsx
  src/components/breadcrumbs/breadcrumbs.tsx
  src/components/breadcrumbs/index.ts
  src/components/control_bar/__snapshots__/control_bar.test.tsx.snap
  src/components/control_bar/_control_bar.scss
  src/components/control_bar/control_bar.test.tsx
  src/components/header/__snapshots__/header.test.tsx.snap
  src/components/header/_index.scss
  src/components/header/header_breadcrumbs/__snapshots__/header_breadcrumbs.test.tsx.snap
  src/components/header/header_breadcrumbs/_header_breadcrumbs.scss
  src/components/header/header_breadcrumbs/_index.scss
  src/components/header/header_breadcrumbs/header_breadcrumbs.styles.ts
  src/components/header/header_breadcrumbs/header_breadcrumbs.test.tsx
  src/components/header/header_breadcrumbs/header_breadcrumbs.tsx
  src/components/index.scss
  src/components/page/page_header/__snapshots__/page_header.test.tsx.snap
  src/components/page/page_header/__snapshots__/page_header_content.test.tsx.snap
  src/themes/amsterdam/overrides/_breadcrumbs.scss
  src/themes/amsterdam/overrides/_header_breadcrumbs.scss
  src/themes/amsterdam/overrides/_index.scss
  upcoming_changelogs/5934.md
Labels: emotion

#6086 [EuiBetaBadge] Change `LabelAsString` from interface to type
  src/components/badge/beta_badge/beta_badge.tsx
Labels: skip-changelog

#6084 [EuiRange sliders Emotion feature] Merge amsterdam and legacy styles
  src/components/form/range/_range_draggable.scss
  src/components/form/range/_range_highlight.scss
  src/components/form/range/_range_levels.scss
  src/components/form/range/_range_slider.scss
  src/components/form/range/_range_thumb.scss
  src/components/form/range/_range_ticks.scss
  src/components/form/range/_range_tooltip.scss
  src/components/form/range/_range_track.scss
  src/global_styling/mixins/_range.scss
  src/global_styling/variables/_form.scss
  src/themes/amsterdam/global_styling/mixins/_index.scss
  src/themes/amsterdam/global_styling/mixins/_range.scss
  src/themes/amsterdam/global_styling/variables/_form.scss
  src/themes/amsterdam/overrides/_index.scss
  src/themes/amsterdam/overrides/_range.scss
  src/themes/amsterdam/overrides/_range_draggable.scss
  src/themes/amsterdam/overrides/_range_highlight.scss
  src/themes/amsterdam/overrides/_range_levels.scss
  src/themes/amsterdam/overrides/_range_slider.scss
  src/themes/amsterdam/overrides/_range_thumb.scss
  src/themes/amsterdam/overrides/_range_ticks.scss
  src/themes/amsterdam/overrides/_range_tooltip.scss
  src/themes/amsterdam/overrides/_range_track.scss
Labels: skip-changelog

#6067 [Emotion] Convert EuiToken
  src-docs/src/views/icon/custom_tokens.tsx
  src-docs/src/views/icon/icon_example.js
  src-docs/src/views/icon/tokens.tsx
  src-docs/src/views/theme/_json/eui_theme_dark.json
  src-docs/src/views/theme/_json/eui_theme_light.json
  src/components/datagrid/controls/__snapshots__/column_sorting.test.tsx.snap
  src/components/icon/__snapshots__/icon.test.tsx.snap
  src/components/icon/assets/tokenStruct.tsx
  src/components/icon/svgs/tokens/tokenStruct.svg
  src/components/index.scss
  src/components/token/__snapshots__/token.test.tsx.snap
  src/components/token/_index.scss
  src/components/token/_token.scss
  src/components/token/_variables.scss
  src/components/token/index.ts
  src/components/token/token.styles.ts
  src/components/token/token.test.tsx
  src/components/token/token.tsx
  src/components/token/token_map.ts
  src/components/token/token_types.ts
  src/themes/amsterdam/overrides/_index.scss
  src/themes/amsterdam/overrides/_token.scss
  upcoming_changelogs/6067.md
Labels: emotion
