Repository elastic/eui, pull requests merged in 2022-08, with the labels that each got.

#6102 [Docs] fix documentation build
  scripts/babel/react-docgen-typescript.js
Labels: skip-changelog

#6103 Fix release script
  scripts/release.js
Labels: skip-changelog

#6112 [Deps] Bump `caniuse-lite`
  yarn.lock
Labels: skip-changelog

#6119 Deprecate static breakpoint services
  src-docs/src/views/theme/breakpoints/_breakpoints_js.tsx
  src-docs/src/views/theme/breakpoints/breakpoint_utilities.tsx
  src/components/collapsible_nav/__snapshots__/collapsible_nav.test.tsx.snap
  src/components/collapsible_nav/collapsible_nav.test.tsx
  src/components/collapsible_nav/collapsible_nav.tsx
  src/components/flyout/__snapshots__/flyout.test.tsx.snap
  src/components/flyout/flyout.tsx
  src/services/breakpoint/breakpoint.test.ts
  src/services/breakpoint/breakpoint.ts
  src/services/breakpoint/current_breakpoint.tsx
  src/services/breakpoint/current_breakpoint_hook.testenv.tsx
  src/services/breakpoint/index.ts
  src/services/breakpoint/is_within_hooks.spec.tsx
  src/services/breakpoint/is_within_hooks.ts
  src/services/breakpoint/useIsWithinBreakpoints.ts
  src/services/index.ts
  upcoming_changelogs/6119.md
Labels: breaking change

#6087 [EuiTour] Convert to Emotion styling
  src/components/index.scss
  src/components/popover/popover.tsx
  src/components/popover/popover_panel/_popover_panel.styles.ts
  src/components/tour/__snapshots__/tour_step.test.tsx.snap
  src/components/tour/__snapshots__/tour_step_indicator.test.tsx.snap
  src/components/tour/_index.scss
  src/components/tour/_tour.scss
  src/components/tour/_tour_step_indicator.scss
  src/components/tour/index.ts
  src/components/tour/tour.styles.ts
  src/components/tour/tour.tsx
  src/components/tour/tour_step.tsx
  src/components/tour/tour_step_indicator.tsx
  src/components/tour/useEuiTour.tsx
  src/services/popover/popover_positioning.ts
  upcoming_changelogs/6087.md
Labels: emotion

#6132 Create screen reader testing matrix MD.
  wiki/screen-reader-testing-matrix.md
Labels: documentation, accessibility, skip-changelog

#6126 [Emotion] Use default cache for consumers who do not pass a cache to EuiProvider
  package.json
  src-docs/src/views/guidelines/getting_started/getting_started.js
  src/components/provider/cache/__snapshots__/cache_provider.test.tsx.snap
  src/components/provider/cache/cache_provider.test.tsx
  src/components/provider/cache/cache_provider.tsx
  upcoming_changelogs/6126.md
  wiki/consuming.md
Labels: breaking change, emotion

#6137 [DOCS] Adding a11y documentation for disabled elements
  src-docs/src/views/guidelines/accessibility.js
Labels: documentation, accessibility, skip-changelog

#6143 [EuiDescriptionList] Export subcomponent prop interfaces
  src/components/description_list/description_list_description.tsx
  src/components/description_list/description_list_title.tsx
Labels: skip-changelog

#6125 [Emotion] Add eslint rule for CSS logical properties
  .eslintplugin.js
  .eslintrc.js
  scripts/eslint-plugin/css_logical_properties.js
  scripts/eslint-plugin/css_logical_properties.test.js
  src-docs/src/views/auto_sizer/auto_sizer.tsx
  src-docs/src/views/comment/comment_props.tsx
  src-docs/src/views/datagrid/_snippets.tsx
  src-docs/src/views/datagrid/schema_columns/datagrid_columns_example.js
  src-docs/src/views/datagrid/styling/row_height_auto.tsx
  src-docs/src/views/datagrid/styling/row_height_fixed.tsx
  src-docs/src/views/datagrid/styling/row_line_height.tsx
  src-docs/src/views/datagrid/toolbar/_props.tsx
  src-docs/src/views/datagrid/toolbar/datagrid_toolbar_example.js
  src-docs/src/views/elastic_charts/category_chart.js
  src-docs/src/views/resize_observer/resize_observer.js
  src-docs/src/views/resize_observer/resize_observer_hook.js
  src-docs/src/views/scroll/scroll.tsx
  src-docs/src/views/scroll/scroll_x.tsx
  src-docs/src/views/scroll/scroll_y.tsx
  src-docs/src/views/tables/mobile/mobile_section.js
  src-docs/src/views/theme/color/_color_js.tsx
  src-docs/src/views/theme/customizing/_border.js
  src-docs/src/views/theme/customizing/_colors.js
  src-docs/src/views/theme/customizing/_size.js
  src-docs/src/views/theme/customizing/_typography.js
  src-docs/src/views/theme/sizing/_sizing_js.tsx
  src/components/accessibility/screen_reader_only/screen_reader_only.styles.ts
  src/components/accordion/accordion.styles.ts
  src/components/accordion/accordion.tsx
  src/components/beacon/beacon.styles.ts
  src/components/button/button_display/_button_display.styles.ts
  src/components/call_out/call_out.styles.ts
  src/components/comment_list/comment_event.styles.ts
  src/components/expression/expression.styles.ts
  src/components/image/image_button.styles.ts
  src/components/image/image_wrapper.styles.ts
  src/components/link/link.styles.ts
  src/components/loading/loading_chart.styles.ts
  src/components/loading/loading_content.styles.ts
  src/components/loading/loading_logo.styles.ts
  src/components/loading/loading_spinner.styles.ts
  src/components/page/page_template.tsx
  src/components/page_template/inner/page_inner.styles.ts
  src/components/page_template/outer/page_outer.styles.ts
  src/components/panel/panel.styles.ts
  src/components/progress/__snapshots__/progress.styles.test.ts.snap
  src/components/progress/progress.styles.ts
  src/components/title/title.styles.ts
  src/components/toast/toast.styles.ts
  src/global_styling/functions/__snapshots__/logicals.test.ts.snap
  src/global_styling/functions/logicals.json
  src/global_styling/functions/logicals.ts
  src/global_styling/functions/typography.ts
  src/global_styling/reset/global_styles.tsx
  src/global_styling/utility/__snapshots__/utility.test.tsx.snap
  tsconfig.json
Labels: skip-changelog

#6155 [Docs] Better docs for color mode
  src-docs/src/views/theme/color_mode/color_mode_example.js
  src-docs/src/views/theme/color_mode/inverse.tsx
  src-docs/src/views/theme/color_mode/inverse_complex.tsx
Labels: skip-changelog, emotion

#6154 Remove IE CSS utilities, mixins, and non-flex/sizing fallbacks
  src/components/basic_table/basic_table.tsx
  src/components/basic_table/table_types.ts
  src/components/card/card.styles.ts
  src/components/datagrid/body/header/_data_grid_header_row.scss
  src/components/description_list/description_list_description.styles.ts
  src/components/description_list/description_list_title.styles.ts
  src/components/filter_group/_filter_group.scss
  src/components/flex/_flex_group.scss
  src/components/flex/_flex_item.scss
  src/components/form/field_search/_field_search.scss
  src/components/list_group/_list_group_item.scss
  src/components/table/_table.scss
  src/components/table/table_row_cell.tsx
  src/global_styling/mixins/__snapshots__/_typography.test.ts.snap
  src/global_styling/mixins/_form.scss
  src/global_styling/mixins/_helpers.scss
  src/global_styling/mixins/_typography.scss
  src/global_styling/mixins/_typography.ts
  src/global_styling/utility/__snapshots__/utility.test.tsx.snap
  src/global_styling/utility/_index.scss
  src/global_styling/utility/_utility.scss
  upcoming_changelogs/6154.md
Labels: breaking change

#6161 Remove IE flex and display CSS fixes & fallbacks
  src/components/badge/_badge.scss
  src/components/card/card.styles.ts
  src/components/flex/_flex_group.scss
  src/components/form/form_control_layout/_form_control_layout_delimited.scss
  src/components/form/form_row/_form_row.scss
  src/components/list_group/_list_group_item.scss
  src/components/modal/__snapshots__/confirm_modal.test.tsx.snap
  src/components/modal/__snapshots__/modal.test.tsx.snap
  src/components/modal/_modal.scss
  src/components/modal/modal.tsx
  src/components/page/page_content/_page_content.scss
  src/components/table/_responsive.scss
  upcoming_changelogs/6161.md
Labels: breaking change

#6176 [EuiFlexItem] Revert flex-basis unitless 0 CSS change
  src/components/flex/_flex_group.scss
Labels: bug, skip-changelog

#6162 Remove all IE JS fallbacks and workarounds
  src/components/combo_box/__snapshots__/combo_box.test.tsx.snap
  src/components/combo_box/combo_box.tsx
  src/components/form/field_search/field_search.tsx
  src/components/form/range/range_input.tsx
  src/components/icon/__snapshots__/icon.test.tsx.snap
  src/components/icon/icon.tsx
  src/components/observer/mutation_observer/mutation_observer.ts
  src/components/tabs/tabbed_content/__snapshots__/tabbed_content.test.tsx.snap
  src/components/tabs/tabbed_content/tabbed_content.tsx
  upcoming_changelogs/6162.md
Labels: breaking change

#6173 Log Cypress a11y violations without test failures.
  cypress/support/a11y/checkAxe.ts
  cypress/support/index.d.ts
  src/test/internal/axe_report_only.spec.tsx
Labels: accessibility, test, skip-changelog, accessibility - automated

#6177 [Docs] Fix sidenav scroll position resetting on every page change + fix nav on mobile
  src-docs/src/components/guide_page/_guide_page.scss
  src-docs/src/components/guide_page/guide_page_chrome.js
  src-docs/src/services/routing/scroll_to_hash.ts
Labels: documentation, skip-changelog

#6178 [Docs] Fix small screen layout in "other" nav popover
  src-docs/src/components/guide_page/guide_page_header.tsx
Labels: skip-changelog

#6188 Expands the guideline for hint text
  src-docs/src/views/form_controls/guidelines.js
Labels: documentation, skip-changelog

#6167 [Docs] Add anchor links to headings with IDs
  src-docs/src/components/guide_section/guide_section_parts/guide_section_example.tsx
  src-docs/src/services/index.js
  src-docs/src/services/routing/heading_anchor_links.tsx
  src-docs/src/services/routing/link_wrapper.ts
  src-docs/src/views/app_view.js
Labels: documentation, skip-changelog

#6109 [EuiPagination & Co.] Convert to Emotion styling
  src/components/basic_table/__snapshots__/in_memory_table.test.tsx.snap
  src/components/datagrid/__snapshots__/data_grid.test.tsx.snap
  src/components/index.scss
  src/components/pagination/__snapshots__/pagination.test.tsx.snap
  src/components/pagination/__snapshots__/pagination_button.test.tsx.snap
  src/components/pagination/_index.scss
  src/components/pagination/_pagination.scss
  src/components/pagination/_pagination_button.scss
  src/components/pagination/pagination.styles.ts
  src/components/pagination/pagination.tsx
  src/components/pagination/pagination_button.styles.ts
  src/components/pagination/pagination_button.tsx
  src/components/pagination/pagination_button_arrow.tsx
  src/components/table/table_pagination/__snapshots__/table_pagination.test.tsx.snap
  upcoming_changelogs/6109.md
Labels: emotion

#6195 Update Kibana upgrade wiki with more tips + section for synthetics E2E tests
  wiki/upgrading-kibana.md
Labels: skip-changelog
