Repository elastic/eui, pull requests merged in 2023-09, with the labels that each got.

#7145 [wiki] Add CSS variables docs to our Emotion wiki
  wiki/contributing-to-eui/developing/writing-styles-with-emotion.md
Labels: documentation, skip-changelog, emotion

#7155 [Storybook] Fix emotion styles being applied twice
  .storybook/main.ts
Labels: skip-changelog, tech debt

#7151 [EuiHeader] Set up CSS variable for fixed header affordance; [Emotion] Set up CSS variable architecture
  src-docs/src/components/guide_page/_guide_page.scss
  src-docs/src/components/guide_page/guide_page_chrome.js
  src-docs/src/views/header/header_elastic_pattern.tsx
  src-docs/src/views/header/header_example.js
  src-docs/src/views/header/header_stacked.tsx
  src/components/collapsible_nav_beta/collapsible_nav_beta.stories.tsx
  src/components/collapsible_nav_beta/collapsible_nav_beta.styles.ts
  src/components/collapsible_nav_beta/collapsible_nav_beta.test.tsx
  src/components/collapsible_nav_beta/collapsible_nav_beta.tsx
  src/components/datagrid/_data_grid.scss
  src/components/flyout/__snapshots__/flyout.test.tsx.snap
  src/components/flyout/flyout.styles.ts
  src/components/header/__snapshots__/header.test.tsx.snap
  src/components/header/header.stories.tsx
  src/components/header/header.styles.ts
  src/components/header/header.test.tsx
  src/components/header/header.tsx
  src/components/overlay_mask/overlay_mask.styles.ts
  src/components/overlay_mask/overlay_mask.test.tsx
  src/components/page/page_sidebar/page_sidebar.test.tsx
  src/components/page/page_sidebar/page_sidebar.tsx
  src/components/page_template/__snapshots__/page_template.test.tsx.snap
  src/components/page_template/page_template.tsx
  src/global_styling/mixins/_header.scss
  src/services/theme/__snapshots__/provider.test.tsx.snap
  src/services/theme/context.ts
  src/services/theme/hooks.test.tsx
  src/services/theme/hooks.tsx
  src/services/theme/index.ts
  src/services/theme/provider.stories.tsx
  src/services/theme/provider.test.tsx
  src/services/theme/provider.tsx
  src/services/theme/types.ts
  upcoming_changelogs/7144.md
  wiki/contributing-to-eui/developing/writing-styles-with-emotion.md
Labels: skip-changelog, emotion

#7164 [CI] Delete previous staging link comment(s) when posting a staging link
  scripts/deploy/deploy_docs
Labels: skip-changelog, infrastructure

#7125 [Snyk] Upgrade @hello-pangea/dnd from 16.2.0 to 16.3.0
  package.json
  upcoming_changelogs/7125.md
  yarn.lock
Labels: tech debt

#7126 [Snyk] Upgrade @types/lodash from 4.14.195 to 4.14.196
  package.json
  upcoming_changelogs/7126.md
  yarn.lock
Labels: tech debt

#7153 [EuiContextMenuItem] Added an example `aria-current` attribute and documentation for a11y
  src-docs/src/views/context_menu/context_menu_example.js
  src-docs/src/views/context_menu/single_panel.js
Labels: documentation, accessibility, skip-changelog

#7172 [Emotion] Convert EuiSplitPanel
  src/components/card/checkable_card/__snapshots__/checkable_card.test.tsx.snap
  src/components/index.scss
  src/components/panel/_index.scss
  src/components/panel/_panel.scss
  src/components/panel/split_panel/__snapshots__/split_panel.test.tsx.snap
  src/components/panel/split_panel/_index.scss
  src/components/panel/split_panel/_split_panel.scss
  src/components/panel/split_panel/split_panel.styles.ts
  src/components/panel/split_panel/split_panel.test.tsx
  src/components/panel/split_panel/split_panel.tsx
  src/components/panel/split_panel/split_panel_inner.stories.tsx
  src/components/panel/split_panel/split_panel_outer.stories.tsx
  upcoming_changelogs/7172.md
Labels: emotion

#7177 [wiki] Include dependency upgrades in changelog
  generator-eui/changelog/index.js
  generator-eui/changelog/templates/changelog.md
  upcoming_changelogs/_template.md
  wiki/contributing-to-eui/documenting/changelogs.md
Labels: skip-changelog, infrastructure

#7178 [GitHub] Add breaking change specific checklist, organize general PR checklist template
  .github/config/label_commenter_config.yml
  .github/pull_request_template.md
  wiki/contributing-to-eui/README.md
Labels: skip-changelog, infrastructure

#7181 [EuiInlineEdit] End Beta Phase
  src-docs/src/views/inline_edit/inline_edit_example.js
Labels: skip-changelog

#7183 [GitHub] Fix `breaking change` PR bot auto-responder
  .github/workflows/label_commenter.yml
Labels: skip-changelog, infrastructure

#7184 [Docs] Update CodeSandbox link in nav to use Typescript
  src-docs/src/components/guide_page/guide_page_header.tsx
Labels: documentation, skip-changelog

#7100 [INFRA] Building GitHub Action to comment on community PRs
  .github/workflows/community_contribution.yml
Labels: skip-changelog

#7191 [BUG] Add write permission to Buildkite community bot.
  .github/workflows/community_contribution.yml
Labels: bug, skip-changelog, infrastructure

#7186 [EuiTablePagination] Add `aria-current` to rows per page menu
  src/components/table/table_pagination/__snapshots__/table_pagination.test.tsx.snap
  src/components/table/table_pagination/table_pagination.tsx
  upcoming_changelogs/7186.md
Labels: accessibility, accessibility - screen reader

#7163 Switch `pre-commit` hook to `pre-push`; fix Jest `--findRelatedTests` behavior
  package.json
  scripts/test-staged.js
  scripts/tests/test-staged.test.js
  src-docs/src/components/guide_section/_utils.test.js
  src/components/card/card.styles.ts
  src/components/card/card.test.tsx
  src/components/card/card.tsx
  src/components/popover/popover.test.tsx
  src/global_styling/functions/typography.test.tsx
  src/services/theme/hooks.test.tsx
  src/test/internal/render_custom_styles.tsx
  src/test/rtl/custom_render.ts
  yarn.lock
Labels: skip-changelog, tech debt

#7028 [EuiComboBox] Update to dogfood `EuiTextTruncate`
  src-docs/src/views/combo_box/combo_box_example.js
  src-docs/src/views/combo_box/truncation.tsx
  src/components/combo_box/__snapshots__/combo_box.test.tsx.snap
  src/components/combo_box/combo_box.spec.tsx
  src/components/combo_box/combo_box.test.tsx
  src/components/combo_box/combo_box.tsx
  src/components/combo_box/combo_box_input/combo_box_input.tsx
  src/components/combo_box/combo_box_options_list/combo_box_options_list.tsx
  src/components/combo_box/types.ts
  upcoming_changelogs/7028.md
Labels: feature request

#7199 [wiki] RTL docs update
  wiki/contributing-to-eui/testing/unit-testing.md
Labels: documentation, skip-changelog

#7207 Revert parallelize the Buildkite `test` job
  .buildkite/pipelines/pipeline_pull_request_test.yml
  .buildkite/scripts/pipeline_test.sh
Labels: skip-changelog, infrastructure

#7216 [tech debt] Address faker deprecation warnings
  src-docs/src/views/datagrid/advanced/custom_renderer.tsx
  src-docs/src/views/datagrid/advanced/in_memory.js
  src-docs/src/views/datagrid/advanced/in_memory_enhancements.js
  src-docs/src/views/datagrid/advanced/in_memory_pagination.js
  src-docs/src/views/datagrid/advanced/in_memory_sorting.js
  src-docs/src/views/datagrid/advanced/ref.tsx
  src-docs/src/views/datagrid/basics/container.js
  src-docs/src/views/datagrid/basics/datagrid.js
  src-docs/src/views/datagrid/basics/flex.js
  src-docs/src/views/datagrid/basics/virtualization.js
  src-docs/src/views/datagrid/basics/virtualization_constrained.js
  src-docs/src/views/datagrid/cells_popovers/cell_popover_is_details.tsx
  src-docs/src/views/datagrid/cells_popovers/cell_popover_is_expandable.tsx
  src-docs/src/views/datagrid/cells_popovers/cell_popover_rendercellpopover.tsx
  src-docs/src/views/datagrid/cells_popovers/column_cell_actions.js
  src-docs/src/views/datagrid/cells_popovers/focus.js
  src-docs/src/views/datagrid/cells_popovers/visible_cell_actions.tsx
  src-docs/src/views/datagrid/schema_columns/column_actions.js
  src-docs/src/views/datagrid/schema_columns/column_widths.js
  src-docs/src/views/datagrid/schema_columns/control_columns.js
  src-docs/src/views/datagrid/schema_columns/footer_row.js
  src-docs/src/views/datagrid/schema_columns/schema.js
  src-docs/src/views/datagrid/styling/display_callbacks.js
  src-docs/src/views/datagrid/styling/row_classes.js
  src-docs/src/views/datagrid/styling/styling_grid.js
  src-docs/src/views/datagrid/toolbar/_grid.js
  src-docs/src/views/datagrid/toolbar/additional_controls.tsx
  src-docs/src/views/pagination/paginated_table.js
  src-docs/src/views/tables/actions/actions.tsx
  src-docs/src/views/tables/auto/auto.tsx
  src-docs/src/views/tables/basic/basic.tsx
  src-docs/src/views/tables/expanding_rows/expanding_rows.tsx
  src-docs/src/views/tables/footer/footer.tsx
  src-docs/src/views/tables/in_memory/in_memory.tsx
  src-docs/src/views/tables/in_memory/in_memory_controlled_pagination.tsx
  src-docs/src/views/tables/in_memory/in_memory_search_callback.tsx
  src-docs/src/views/tables/in_memory/in_memory_search_external.tsx
  src-docs/src/views/tables/in_memory/in_memory_selection.tsx
  src-docs/src/views/tables/mobile/mobile.tsx
  src-docs/src/views/tables/paginated/paginated.tsx
  src-docs/src/views/tables/selection/selection.tsx
  src-docs/src/views/tables/sorting/sorting.tsx
  src/components/basic_table/basic_table.a11y.tsx
  src/components/basic_table/in_memory_table.a11y.tsx
  src/components/datagrid/data_grid.a11y.tsx
Labels: documentation, skip-changelog

#7174 [Storybook] Create Stories for `EuiSideNav`
  .storybook/preview.tsx
  src/components/side_nav/side_nav.stories.tsx
Labels: skip-changelog

#7221 [EuiMarkdownEditor] Fix default processing plugins type
  src/components/markdown_editor/plugins/markdown_default_plugins/processing_plugins.tsx
  upcoming_changelogs/7221.md
Labels: typescript

#7225 Updating docs link and description in release process doc.
  wiki/eui-team-processes/releasing-versions.md
Labels: documentation, skip-changelog

#7224 Fix release script
  scripts/release.js
Labels: skip-changelog, infrastructure

#7231 [wiki] Update upgrading Kibana doc with a FAQ for Kibana teams
  wiki/eui-team-processes/upgrading-kibana.md
Labels: documentation, skip-changelog

#7227 [Tech debt] Fix Jest unit tests on broken on React 17
  .buildkite/scripts/pipeline_test.sh
  package.json
  scripts/test-cypress.js
  scripts/test-unit.js
  src/components/collapsible_nav_beta/__snapshots__/collapsible_nav_beta.test.tsx.snap
  src/components/collapsible_nav_beta/collapsible_nav_beta.test.tsx
  src/components/datagrid/controls/__snapshots__/keyboard_shortcuts.test.tsx.snap
  src/components/datagrid/controls/keyboard_shortcuts.test.tsx
  src/components/text_truncate/text_truncate.tsx
  src/global_styling/functions/typography.test.tsx
  src/services/theme/hooks.test.tsx
  wiki/contributing-to-eui/testing/unit-testing.md
Labels: skip-changelog, tech debt
