Repository elastic/eui, pull requests merged in 2023-01, with the labels that each got.

#6495 A11y specs for EuiImage, EuiTable, EuiKeyPadMenu.
  src/components/basic_table/table.a11y.tsx
  src/components/image/image.a11y.tsx
  src/components/key_pad_menu/key_pad_menu.a11y.tsx
Labels: skip-changelog, accessibility - automated

#6504 [EuiImage] Expose full screen state
  src/components/image/image.tsx
  src/components/image/image_fullscreen_wrapper.tsx
  src/components/image/image_types.ts
  src/components/image/image_wrapper.tsx
  upcoming_changelogs/6504.md
Labels: skip-changelog

#6510 Added NPM login and release steps to releasing-versions.md.
  wiki/releasing-versions.md
Labels: documentation, skip-changelog

#6493 [EuiAccordion] Remove a unnecessary condition statement
  src/components/accordion/accordion.tsx
Labels: skip-changelog, tech debt

#6484 Updating the composition variant in EuiStat Docs
  src-docs/src/views/stat/stat_combos.js
  src-docs/src/views/stat/stat_example.js
Labels: documentation, skip-changelog

#6517 [EuiDataGrid] Fix nested interactive controls axe error
  src/components/datagrid/controls/__snapshots__/column_selector.test.tsx.snap
  src/components/datagrid/controls/__snapshots__/column_sorting.test.tsx.snap
  src/components/datagrid/controls/__snapshots__/column_sorting_draggable.test.tsx.snap
  src/components/datagrid/controls/_data_grid_column_sorting.scss
  src/components/datagrid/controls/column_selector.tsx
  src/components/datagrid/controls/column_sorting_draggable.tsx
  src/components/datagrid/data_grid.a11y.tsx
  upcoming_changelogs/6517.md
Labels: data grid, accessibility - automated

#6518 [Wiki] Improve Kibana upgrade docs
  wiki/upgrading-kibana.md
Labels: documentation, skip-changelog

#6519 [Docs] Update `EuiConfirmModal` examples
  src-docs/src/views/button/guidelines.js
  src-docs/src/views/modal/confirm_modal.tsx
Labels: documentation, skip-changelog

#6520 [EuiToolTip] Enforce only one visible tooltip at a time
  src/components/tool_tip/tool_tip.spec.tsx
  src/components/tool_tip/tool_tip.tsx
  src/components/tool_tip/tool_tip_manager.test.ts
  src/components/tool_tip/tool_tip_manager.ts
  upcoming_changelogs/6520.md
Labels: breaking change

#6522 [EuiToolTip] Unit tests for control of internal tooltip visibility state via `ref`
  src/components/tool_tip/tool_tip.test.tsx
Labels: skip-changelog

#6526 [Docs] Fix code snippet
  src-docs/src/views/guidelines/getting_started/getting_started.js
Labels: skip-changelog

#6524 Added a11y specs for EuiNotificationEvent, EuiPageHeader, EuiPortal
  src/components/notification/notification_event.a11y.tsx
  src/components/page/page_header/page_header.a11y.tsx
  src/components/portal/portal.a11y.tsx
Labels: skip-changelog, accessibility - automated

#6528 Harden release script to check for correct `upstream` remote
  scripts/release.js
Labels: skip-changelog, tech debt

#6497 Adding EuiModal callout for H1 rendering.
  src-docs/src/views/color_picker/containers.js
  src-docs/src/views/combo_box/containers.js
  src-docs/src/views/datagrid/advanced/ref.tsx
  src-docs/src/views/datagrid/basics/datagrid.js
  src-docs/src/views/modal/modal.tsx
  src-docs/src/views/modal/modal_example.js
  src-docs/src/views/modal/modal_form.tsx
  src-docs/src/views/modal/modal_width.tsx
  src-docs/src/views/toast/guidelines.js
  src-docs/src/views/window_event/basic_window_event.js
  src-docs/src/views/window_event/window_event_conflict.js
  src/components/modal/modal.a11y.tsx
  src/components/modal/modal.spec.tsx
  src/components/modal/modal_header_title.tsx
Labels: documentation, accessibility, skip-changelog

#6539 [Emotion] Convert EuiBasicTable
  src/components/basic_table/__snapshots__/basic_table.test.tsx.snap
  src/components/basic_table/__snapshots__/in_memory_table.test.tsx.snap
  src/components/basic_table/_basic_table.scss
  src/components/basic_table/_index.scss
  src/components/basic_table/basic_table.styles.ts
  src/components/basic_table/basic_table.test.tsx
  src/components/basic_table/basic_table.tsx
  src/components/index.scss
  src/services/theme/hooks.test.ts
  src/services/theme/hooks.test.tsx
  src/services/theme/hooks.tsx
  src/services/theme/index.ts
  src/services/theme/provider.tsx
  upcoming_changelogs/6539.md
Labels: emotion

#6534 [EuiResizablePanel] Added tabindex prop to EuiResizablePanel for keyboard accessibility.
  src-docs/src/views/resizable_container/resizable_container_basic.tsx
  src-docs/src/views/resizable_container/resizable_container_callbacks.tsx
  src-docs/src/views/resizable_container/resizable_container_example.js
  src-docs/src/views/resizable_container/resizable_container_reset_values.tsx
  src-docs/src/views/resizable_container/resizable_container_vertical.tsx
  src-docs/src/views/resizable_container/resizable_panel_collapsible.tsx
  src-docs/src/views/resizable_container/resizable_panel_collapsible_options.tsx
  src-docs/src/views/resizable_container/resizable_panels.tsx
  src/components/resizable_container/__snapshots__/resizable_panel.test.tsx.snap
  src/components/resizable_container/resizable_panel.test.tsx
  src/components/resizable_container/resizable_panel.tsx
Labels: documentation, accessibility, skip-changelog, accessibility - keyboard, accessibility - automated

#6548 Added a lang attribute to EUI i18n context EN | FR demo.
  src-docs/src/views/i18n/context.js
Labels: documentation, accessibility, skip-changelog

#6549 [EuiSuperSelect] Updated i18n default instructions string
  i18ntokens.json
  src/components/form/super_select/__snapshots__/super_select.test.tsx.snap
  src/components/form/super_select/super_select.tsx
  upcoming_changelogs/6549.md
Labels: accessibility, accessibility - cognition

#6560 [EuiSkeleton] Design review
  src-docs/src/views/skeleton/skeleton_example.js
  src/components/skeleton/skeleton_text.styles.ts
  src/components/skeleton/skeleton_title.styles.ts
Labels: skip-changelog

#6552 Cypress a11y specs for `EuiProgress`, `EuiResizableContainer`, and `EuiRange`
  src/components/datagrid/data_grid.a11y.tsx
  src/components/form/range/range.a11y.tsx
  src/components/progress/progress.a11y.tsx
  src/components/resizable_container/resizable_container.a11y.tsx
Labels: accessibility, skip-changelog, accessibility - automated

#6558 Add new `EuiSkeleton` components; deprecate `EuiLoadingContent`
  src-docs/src/routes.js
  src-docs/src/views/loading/loading_content.tsx
  src-docs/src/views/loading/loading_example.tsx
  src-docs/src/views/loading/playground.js
  src-docs/src/views/skeleton/playground.js
  src-docs/src/views/skeleton/skeleton_circle.tsx
  src-docs/src/views/skeleton/skeleton_example.js
  src-docs/src/views/skeleton/skeleton_loading.tsx
  src-docs/src/views/skeleton/skeleton_rectangle.tsx
  src-docs/src/views/skeleton/skeleton_text.tsx
  src-docs/src/views/skeleton/skeleton_title.tsx
  src/components/index.ts
  src/components/loading/__snapshots__/loading_content.test.tsx.snap
  src/components/loading/loading_content.styles.ts
  src/components/loading/loading_content.test.tsx
  src/components/loading/loading_content.tsx
  src/components/skeleton/__snapshots__/skeleton_circle.test.tsx.snap
  src/components/skeleton/__snapshots__/skeleton_loading.test.tsx.snap
  src/components/skeleton/__snapshots__/skeleton_rectangle.test.tsx.snap
  src/components/skeleton/__snapshots__/skeleton_text.test.tsx.snap
  src/components/skeleton/__snapshots__/skeleton_title.test.tsx.snap
  src/components/skeleton/index.ts
  src/components/skeleton/skeleton_circle.styles.ts
  src/components/skeleton/skeleton_circle.test.tsx
  src/components/skeleton/skeleton_circle.tsx
  src/components/skeleton/skeleton_loading.test.tsx
  src/components/skeleton/skeleton_loading.tsx
  src/components/skeleton/skeleton_rectangle.styles.ts
  src/components/skeleton/skeleton_rectangle.test.tsx
  src/components/skeleton/skeleton_rectangle.tsx
  src/components/skeleton/skeleton_text.styles.ts
  src/components/skeleton/skeleton_text.test.tsx
  src/components/skeleton/skeleton_text.tsx
  src/components/skeleton/skeleton_title.styles.ts
  src/components/skeleton/skeleton_title.test.tsx
  src/components/skeleton/skeleton_title.tsx
  src/components/skeleton/utils.ts
  src/global_styling/functions/logicals.ts
  src/global_styling/utility/animations.ts
  upcoming_changelogs/6502.md
  upcoming_changelogs/6557.md
  upcoming_changelogs/6562.md
Labels: skip-changelog
