Repository elastic/eui, pull requests merged in 2023-10, with the labels that each got.

#7237 [Tech debt] Fix Jest unit tests to run on React 16
  package.json
  scripts/jest/setup/enzyme.js
  src/components/combo_box/combo_box.test.tsx
  src/components/datagrid/controls/__snapshots__/column_selector.test.tsx.snap
  src/components/datagrid/controls/__snapshots__/column_sorting.test.tsx.snap
  src/components/datagrid/controls/__snapshots__/column_sorting_draggable.test.tsx.snap
  src/components/drag_and_drop/__snapshots__/draggable.test.tsx.snap
  src/components/drag_and_drop/__snapshots__/droppable.test.tsx.snap
  src/components/form/range/dual_range.test.tsx
  yarn.lock
Labels: skip-changelog, tech debt

#7241 [EuiInputPopover] Refactor & clean ups
  src/components/color_picker/color_palette_picker/__snapshots__/color_palette_picker.test.tsx.snap
  src/components/date_picker/auto_refresh/__snapshots__/auto_refresh.test.tsx.snap
  src/components/date_picker/super_date_picker/__snapshots__/super_date_picker.test.tsx.snap
  src/components/form/range/__snapshots__/range.test.tsx.snap
  src/components/form/super_select/__snapshots__/super_select.test.tsx.snap
  src/components/popover/input_popover.spec.tsx
  src/components/popover/input_popover.tsx
  src/components/suggest/__snapshots__/suggest.test.tsx.snap
Labels: skip-changelog, tech debt

#7249 [EuiIcon] Fix silenced test errors
  src/components/icon/__snapshots__/icon.test.tsx.snap
  src/components/icon/icon.test.tsx
Labels: testing, skip-changelog, tech debt

#7245 [Storybook] General consistency pass
  .storybook/preview.tsx
  .storybook/utils.test.ts
  .storybook/utils.ts
  scripts/jest/config.js
  src/components/button/button_empty/button_empty.stories.tsx
  src/components/button/button_group/button_group.stories.tsx
  src/components/button/button_icon/button_icon.stories.tsx
  src/components/collapsible_nav/collapsible_nav.stories.tsx
  src/components/collapsible_nav/collapsible_nav_group/collapsible_nav_group.stories.tsx
  src/components/collapsible_nav_beta/collapsible_nav_beta.stories.tsx
  src/components/empty_prompt/empty_prompt.stories.tsx
  src/components/error_boundary/error_boundary.stories.tsx
  src/components/filter_group/filter_button.stories.tsx
  src/components/header/header.stories.tsx
  src/components/header/header_alert/header_alert.stories.tsx
  src/components/header/header_links/header_links.stories.tsx
  src/components/header/header_logo/header_logo.stories.tsx
  src/components/key_pad_menu/key_pad_menu_item.stories.tsx
  src/components/page/page.stories.tsx
  src/components/page/page_body/page_body.stories.tsx
  src/components/page/page_header/page_header.stories.tsx
  src/components/page/page_section/page_section.stories.tsx
  src/components/page/page_sidebar/page_sidebar.stories.tsx
  src/components/panel/split_panel/split_panel_inner.stories.tsx
  src/components/panel/split_panel/split_panel_outer.stories.tsx
  src/components/resizable_container/resizable_button.stories.tsx
  src/components/resizable_container/resizable_collapse_button.stories.tsx
  src/components/side_nav/side_nav.stories.tsx
  src/components/text_truncate/text_truncate.stories.tsx
Labels: testing, skip-changelog, tech debt

#7242 [INFRA] Parallelize Buildkite test job, take 3
  .buildkite/pipelines/pipeline_pull_request_test.yml
  .buildkite/scripts/pipeline_test.sh
  src/components/icon/icon.test.tsx
Labels: skip-changelog, infrastructure

#7182 Update global EUI font size to use configurable theme units
  .storybook/preview.tsx
  src-docs/src/views/theme/typography/_typography_js.tsx
  src/components/provider/provider.stories.tsx
  src/global_styling/reset/global_styles.tsx
  upcoming_changelogs/7182.md
Labels: breaking change, accessibility

#7256 [Services] Remove unused key services
  src/components/context_menu/context_menu_panel.tsx
  src/components/popover/popover.tsx
  src/services/accessibility/accessible_click_keys.ts
  src/services/accessibility/cascading_menu_keys.ts
  src/services/accessibility/combo_box_keys.ts
  src/services/accessibility/index.ts
  src/services/index.ts
  upcoming_changelogs/7256.md
Labels: breaking change

#7263 Remove deprecated `EuiSuggest` component
  src-docs/src/routes.js
  src-docs/src/views/_index.scss
  src-docs/src/views/description_list/playground.js
  src-docs/src/views/suggest/_global_filter_group.scss
  src-docs/src/views/suggest/_global_filter_item.scss
  src-docs/src/views/suggest/_index.scss
  src-docs/src/views/suggest/_saved_queries.scss
  src-docs/src/views/suggest/global_filter_add.js
  src-docs/src/views/suggest/global_filter_bar.js
  src-docs/src/views/suggest/global_filter_form.js
  src-docs/src/views/suggest/global_filter_item.js
  src-docs/src/views/suggest/global_filter_options.js
  src-docs/src/views/suggest/hashtag_popover.js
  src-docs/src/views/suggest/playground.js
  src-docs/src/views/suggest/saved_queries.js
  src-docs/src/views/suggest/suggest.tsx
  src-docs/src/views/suggest/suggest_example.js
  src-docs/src/views/suggest/suggest_item.tsx
  src-docs/src/views/suggest/suggest_item_example.tsx
  src-docs/src/views/super_date_picker/super_date_picker_example.js
  src-docs/src/views/super_date_picker/super_date_picker_pattern.tsx
  src/components/index.scss
  src/components/index.ts
  src/components/suggest/__snapshots__/suggest.test.tsx.snap
  src/components/suggest/__snapshots__/suggest_item.test.tsx.snap
  src/components/suggest/_index.scss
  src/components/suggest/_suggest_input.scss
  src/components/suggest/_suggest_item.scss
  src/components/suggest/_variables.scss
  src/components/suggest/index.ts
  src/components/suggest/suggest.a11y.tsx
  src/components/suggest/suggest.spec.tsx
  src/components/suggest/suggest.test.tsx
  src/components/suggest/suggest.tsx
  src/components/suggest/suggest_item.test.tsx
  src/components/suggest/suggest_item.tsx
  src/components/suggest/types.ts
  upcoming_changelogs/7263.md
Labels: breaking change

#7260 [Tech debt] Remove `testCustomHook` in favor of RTL `renderHook`
  src/components/datagrid/body/data_grid_row_manager.test.ts
  src/components/datagrid/body/header/__snapshots__/data_grid_header_cell.test.tsx.snap
  src/components/datagrid/body/header/data_grid_header_cell.test.tsx
  src/components/datagrid/body/header/header_is_interactive.test.ts
  src/components/datagrid/controls/display_selector.test.tsx
  src/components/datagrid/controls/fullscreen_selector.test.tsx
  src/components/datagrid/utils/col_widths.test.ts
  src/components/datagrid/utils/focus.test.tsx
  src/components/datagrid/utils/ref.test.ts
  src/components/datagrid/utils/scrolling.test.tsx
  src/components/date_picker/super_date_picker/pretty_duration.test.tsx
  src/components/date_picker/super_date_picker/pretty_interval.test.ts
  src/components/date_picker/super_date_picker/time_options.test.tsx
  src/components/markdown_editor/markdown_format.styles.test.ts
  src/components/progress/progress.styles.test.ts
  src/components/text/text.styles.test.ts
  src/components/title/title.styles.test.ts
  src/global_styling/mixins/_color.test.ts
  src/global_styling/mixins/_padding.test.ts
  src/global_styling/mixins/_responsive.test.ts
  src/global_styling/mixins/_states.test.ts
  src/global_styling/mixins/_typography.test.ts
  src/global_styling/utility/__snapshots__/utility.test.ts.snap
  src/global_styling/utility/utility.test.ts
  src/test/README.md
  src/test/internal/index.ts
  src/test/internal/test_custom_hook.tsx
Labels: testing, skip-changelog, tech debt

#7269 [EuiCollapsibleNavItem] Prevent DOM errors about `accordionProps` being passed to non-accordions
  src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_item.tsx
Labels: skip-changelog

#7271 fix: color errors due to `fillColor` changes in `v54.0.0`
  src-docs/src/views/elastic_charts/accessibility_sunburst.js
  src-docs/src/views/elastic_charts/pie.js
  src-docs/src/views/elastic_charts/pie_example.js
  src-docs/src/views/elastic_charts/pie_slices.js
  src-docs/src/views/elastic_charts/treemap.js
Labels: documentation, skip-changelog

#7255 [EuiDataGrid] Update to use `EuiTextBreakTruncate` + cell DOM & CSS cleanup
  src/components/datagrid/__snapshots__/data_grid.test.tsx.snap
  src/components/datagrid/_data_grid_data_row.scss
  src/components/datagrid/_mixins.scss
  src/components/datagrid/body/__snapshots__/data_grid_body_custom.test.tsx.snap
  src/components/datagrid/body/__snapshots__/data_grid_body_virtualized.test.tsx.snap
  src/components/datagrid/body/__snapshots__/data_grid_cell.test.tsx.snap
  src/components/datagrid/body/data_grid_cell.test.tsx
  src/components/datagrid/body/data_grid_cell.tsx
  src/components/datagrid/body/data_grid_cell_actions.test.tsx
  src/components/datagrid/body/data_grid_cell_actions.tsx
  src/components/datagrid/body/data_grid_cell_popover.spec.tsx
  src/components/datagrid/utils/__mocks__/row_heights.ts
  src/components/datagrid/utils/row_heights.test.ts
  src/components/datagrid/utils/row_heights.ts
Labels: skip-changelog, tech debt

#7272 [Emotion] Reduce CSS browser prefixing to supported browsers only
  package.json
  src-docs/src/components/codesandbox/link.js
  src-docs/src/views/app_context.js
  src-docs/src/views/provider/provider_example.js
  src-docs/src/views/provider/provider_styles.tsx
  src/components/bottom_bar/__snapshots__/bottom_bar.test.tsx.snap
  src/components/button/__snapshots__/button.test.tsx.snap
  src/components/button/button_empty/__snapshots__/button_empty.test.tsx.snap
  src/components/button/button_icon/__snapshots__/button_icon.test.tsx.snap
  src/components/collapsible_nav/collapsible_nav_group/__snapshots__/collapsible_nav_group.test.tsx.snap
  src/components/control_bar/__snapshots__/control_bar.test.tsx.snap
  src/components/overlay_mask/overlay_mask.test.tsx
  src/components/page/__snapshots__/page_template.test.tsx.snap
  src/components/page_template/bottom_bar/__snapshots__/page_bottom_bar.test.tsx.snap
  src/components/portal/__snapshots__/portal.test.tsx.snap
  src/components/provider/provider.test.tsx
  src/components/provider/provider.tsx
  src/services/emotion/css.test.ts
  src/services/emotion/css.ts
  src/services/emotion/index.ts
  src/services/emotion/prefixer.test.tsx
  src/services/emotion/prefixer.ts
  src/services/theme/__snapshots__/provider.test.tsx.snap
  src/services/theme/provider.tsx
  src/services/theme/utils.ts
  upcoming_changelogs/7272.md
  yarn.lock
Labels: tech debt, emotion

#7278 Update contributing README
  wiki/contributing-to-eui/README.md
Labels: documentation, skip-changelog

#7274 Bump Node to `v18.18.1`; Remove puppeteer
  .buildkite/pipelines/pipeline_pull_request_test.yml
  .buildkite/scripts/pipeline_test.sh
  .nvmrc
  package.json
  scripts/a11y-testing.js
  scripts/deploy/build_docs
  scripts/docker-ci/Dockerfile
  scripts/test-a11y-docker.js
  scripts/test-docker.js
  src/components/delay_hide/delay_hide.tsx
  wiki/contributing-to-eui/testing/automated-accessibility-testing.md
  yarn.lock
Labels: chore, skip-changelog, tech debt, infrastructure

#7265 Deprecate previous EuiPage and EuiPageTemplate components
  src-docs/src/views/elastic_charts/sizes.tsx
  src-docs/src/views/page_template/deprecated.tsx
  src-docs/src/views/page_template/examples.tsx
  src-docs/src/views/page_template/playground.js
  src/components/index.scss
  src/components/page/__snapshots__/page_template.test.tsx.snap
  src/components/page/_index.scss
  src/components/page/index.ts
  src/components/page/page_content/__snapshots__/page_content.test.tsx.snap
  src/components/page/page_content/__snapshots__/page_content_body.test.tsx.snap
  src/components/page/page_content/__snapshots__/page_content_header.test.tsx.snap
  src/components/page/page_content/__snapshots__/page_content_header_section.test.tsx.snap
  src/components/page/page_content/_index.scss
  src/components/page/page_content/_page_content.scss
  src/components/page/page_content/_page_content_body.scss
  src/components/page/page_content/_page_content_header.scss
  src/components/page/page_content/_page_content_header_section.scss
  src/components/page/page_content/index.ts
  src/components/page/page_content/page_content.test.tsx
  src/components/page/page_content/page_content.tsx
  src/components/page/page_content/page_content_body.test.tsx
  src/components/page/page_content/page_content_body.tsx
  src/components/page/page_content/page_content_header.test.tsx
  src/components/page/page_content/page_content_header.tsx
  src/components/page/page_content/page_content_header_section.test.tsx
  src/components/page/page_content/page_content_header_section.tsx
  src/components/page/page_side_bar/__snapshots__/page_side_bar.test.tsx.snap
  src/components/page/page_side_bar/_index.scss
  src/components/page/page_side_bar/_page_side_bar.scss
  src/components/page/page_side_bar/index.ts
  src/components/page/page_side_bar/page_side_bar.test.tsx
  src/components/page/page_side_bar/page_side_bar.tsx
  src/components/page/page_template.test.tsx
  src/components/page/page_template.tsx
  upcoming_changelogs/7265.md
Labels: breaking change

#7297 [Tech debt] Remove `defaultProps` from function components
  src-docs/src/components/guide_rule/guide_rule_example.js
  src-docs/src/views/app_context.js
  src-docs/src/views/app_view.js
  src/components/form/field_password/field_password.tsx
  src/components/popover/input_popover.tsx
Labels: skip-changelog, tech debt

#7298 [docs] Create a handy dandy version switcher
  scripts/release.js
  scripts/tests/update-versions-log.test.js
  scripts/update-versions-log.js
  src-docs/src/components/guide_page/guide_page_header.tsx
  src-docs/src/components/guide_page/versions.json
  src/components/list_group/__snapshots__/list_group_item.test.tsx.snap
  src/components/list_group/list_group_item.test.tsx
  src/components/list_group/list_group_item.tsx
  src/components/list_group/list_group_item_extra_action.styles.ts
  upcoming_changelogs/7298.md
Labels: documentation

#7300 Updates capitalization guidelines in Writing doc
  src-docs/src/views/guidelines/writing_guidelines.js
Labels: documentation, skip-changelog

#7296 [EuiButton][EuiButtonEmpty][EuiButtonIcon] Remove `color="ghost"`
  src-docs/src/components/guide_theme_selector/guide_theme_selector.tsx
  src-docs/src/views/bottom_bar/bottom_bar_position.js
  src-docs/src/views/button/button_example.js
  src-docs/src/views/button/button_ghost.js
  src-docs/src/views/page_template/_page_demo.tsx
  src/components/button/__snapshots__/button.test.tsx.snap
  src/components/button/button.tsx
  src/components/button/button_empty/__snapshots__/button_empty.test.tsx.snap
  src/components/button/button_empty/button_empty.test.tsx
  src/components/button/button_empty/button_empty.tsx
  src/components/button/button_icon/__snapshots__/button_icon.test.tsx.snap
  src/components/button/button_icon/button_icon.styles.ts
  src/components/button/button_icon/button_icon.test.tsx
  src/components/button/button_icon/button_icon.tsx
  src/components/control_bar/__snapshots__/control_bar.test.tsx.snap
  src/components/control_bar/control_bar.tsx
  src/components/date_picker/super_date_picker/__snapshots__/super_update_button.test.tsx.snap
  src/components/date_picker/super_date_picker/quick_select_popover/__snapshots__/quick_select.test.tsx.snap
  upcoming_changelogs/7296.md
Labels: breaking change

#7319 [EuiCollapsibleNavBeta] Store mobile overlay open/close state separately from desktop collapsed/expanded state
  src/components/collapsible_nav_beta/__snapshots__/collapsible_nav_beta.test.tsx.snap
  src/components/collapsible_nav_beta/collapsible_nav_beta.test.tsx
  src/components/collapsible_nav_beta/collapsible_nav_beta.tsx
  src/components/collapsible_nav_beta/collapsible_nav_body_footer.test.tsx
  src/components/collapsible_nav_beta/collapsible_nav_button/__snapshots__/collapsible_nav_button.test.tsx.snap
  src/components/collapsible_nav_beta/collapsible_nav_button/collapsible_nav_button.test.tsx
  src/components/collapsible_nav_beta/collapsible_nav_button/collapsible_nav_button.tsx
  src/components/collapsible_nav_beta/collapsible_nav_group/collapsible_nav_group.test.tsx
  src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_item.test.tsx
  src/components/collapsible_nav_beta/context.ts
Labels: skip-changelog

#7317 [EuiCollapsibleNavBeta] Fix accordion open animation bug
  src/components/collapsible_nav_beta/collapsible_nav_beta.stories.tsx
  src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_accordion.styles.ts
Labels: skip-changelog

#7315 [EuiCollapsibleNavItem] Add a non-accordion group component
  src/components/collapsible_nav_beta/collapsible_nav_beta.stories.tsx
  src/components/collapsible_nav_beta/collapsible_nav_item/__snapshots__/collapsible_nav_group.test.tsx.snap
  src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_accordion.tsx
  src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_group.test.tsx
  src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_group.tsx
  src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_item.stories.tsx
  src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_item.tsx
  src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_link.tsx
Labels: skip-changelog

#7323 Add tiers and subscription levels to capitalization rules
  src-docs/src/views/guidelines/writing_guidelines.js
Labels: documentation, skip-changelog

#7326 [EuiAccordion] Add configurable `role` prop and change default role to `group`
  src/components/accordion/__snapshots__/accordion.test.tsx.snap
  src/components/accordion/accordion.test.tsx
  src/components/accordion/accordion.tsx
  src/components/accordion/accordion_children/accordion_children.tsx
  src/components/collapsible_nav/collapsible_nav_group/__snapshots__/collapsible_nav_group.test.tsx.snap
  src/components/collapsible_nav_beta/collapsible_nav_group/__snapshots__/collapsible_nav_group.test.tsx.snap
  src/components/collapsible_nav_beta/collapsible_nav_group/collapsible_nav_group.tsx
  src/components/collapsible_nav_beta/collapsible_nav_item/__snapshots__/collapsible_nav_accordion.test.tsx.snap
  src/components/collapsible_nav_beta/collapsible_nav_item/__snapshots__/collapsible_nav_group.test.tsx.snap
  src/components/collapsible_nav_beta/collapsible_nav_item/__snapshots__/collapsible_nav_item.test.tsx.snap
  src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_group.tsx
  src/components/notification/__snapshots__/notification_event.test.tsx.snap
  upcoming_changelogs/7326.md
Labels: accessibility

#7325 [EuiButtonGroup] Remove radio group markup/behavior
  src/components/button/button_display/_button_display.test.tsx
  src/components/button/button_display/_button_display.tsx
  src/components/button/button_group/__snapshots__/button_group.test.tsx.snap
  src/components/button/button_group/button_group.test.tsx
  src/components/button/button_group/button_group.tsx
  src/components/button/button_group/button_group_button.styles.ts
  src/components/button/button_group/button_group_button.tsx
  src/components/datagrid/controls/__snapshots__/column_sorting.test.tsx.snap
  src/components/datagrid/controls/__snapshots__/column_sorting_draggable.test.tsx.snap
  src/components/datagrid/controls/column_sorting_draggable.test.tsx
  src/components/datagrid/controls/display_selector.test.tsx
  src/components/datagrid/data_grid.test.tsx
  src/global_styling/mixins/__snapshots__/_states.test.ts.snap
  src/global_styling/mixins/_states.test.ts
  src/global_styling/mixins/_states.ts
  upcoming_changelogs/7325.md
Labels: accessibility
