Repository elastic/eui, pull requests merged in 2023-02, with the labels that each got.

#6567 Updating EuiPopover screen reader text to include mobile cues.
  i18ntokens.json
  src/components/datagrid/controls/__snapshots__/column_selector.test.tsx.snap
  src/components/datagrid/controls/__snapshots__/column_sorting.test.tsx.snap
  src/components/datagrid/controls/__snapshots__/keyboard_shortcuts.test.tsx.snap
  src/components/popover/__snapshots__/popover.rtl.test.tsx.snap
  src/components/popover/__snapshots__/popover.test.tsx.snap
  src/components/popover/popover.tsx
  upcoming_changelogs/6567.md
Labels: accessibility, accessibility - screen reader

#6573 Update upgrading-kibana.md
  wiki/upgrading-kibana.md
Labels: skip-changelog

#6447 Metric chart docs
  src-docs/src/images/metric_anatomy.png
  src-docs/src/images/metric_intro.png
  src-docs/src/routes.js
  src-docs/src/views/elastic_charts/metric/metric_chart_example.js
  src-docs/src/views/elastic_charts/metric/metric_chart_grid.tsx
  src-docs/src/views/elastic_charts/metric/metric_chart_grid_column.tsx
  src-docs/src/views/elastic_charts/metric/metric_chart_grid_row.tsx
  src-docs/src/views/elastic_charts/metric/metric_chart_no_data.tsx
  src-docs/src/views/elastic_charts/metric/metric_chart_overview.tsx
  src-docs/src/views/elastic_charts/metric/metric_chart_progress_bar.tsx
  src-docs/src/views/elastic_charts/metric/metric_chart_props.tsx
  src-docs/src/views/elastic_charts/metric/metric_chart_resizing.tsx
  src-docs/src/views/elastic_charts/metric/metric_chart_single_value.tsx
  src-docs/src/views/elastic_charts/metric/metric_chart_snippets.ts
  src-docs/src/views/elastic_charts/metric/metric_chart_trend.tsx
Labels: documentation, Elastic Charts, skip-changelog

#6595 Fixed a bug in EuiCodeBlock docs where import statement example was raised up and evaluated.
  src-docs/src/components/guide_section/_utils.js
  src-docs/src/components/guide_section/_utils.test.js
Labels: bug, documentation, skip-changelog

#6597 fix: broken link within EuiSideNav documentation
  src-docs/src/views/side_nav/side_nav.js
  src-docs/src/views/side_nav/side_nav_heading.js
Labels: documentation, skip-changelog

#6599 Add docs for using EuiImage with SVGs
  src-docs/src/views/image/image_example.js
  src-docs/src/views/image/image_svg.tsx
Labels: documentation, skip-changelog

#6603 Fixing EuiCodeBlock regex for Safari regex support.
  src-docs/src/components/guide_section/_utils.js
  src-docs/src/components/guide_section/_utils.test.js
  upcoming_changelogs/6603.md
Labels: bug, documentation

#6610 Error & warning guides
  src-docs/src/views/call_out/call_out_example.js
  src-docs/src/views/call_out/danger.tsx
  src-docs/src/views/call_out/warning.tsx
  src-docs/src/views/toast/danger.js
  src-docs/src/views/toast/guidelines.js
  src-docs/src/views/toast/toast_example.js
  src-docs/src/views/toast/warning.js
Labels: documentation, skip-changelog
