Repository elastic/eui, pull requests merged in 2023-12, with the labels that each got.

#7390 Better backport and prerelease DX
  catalog-info.yaml
  package.json
  scripts/release.js
  scripts/tests/update-versions-log.test.js
  scripts/update-changelog.js
  scripts/update-token-changelog.js
  scripts/update-versions-log.js
  wiki/eui-team-processes/releasing-versions.md
Labels: chore, skip-changelog, infrastructure

#7397 [CHORE] Adding env var to trigger docs deploy manually from Buildkite UI
  scripts/deploy/deploy_docs
  wiki/eui-team-processes/releasing-versions.md
Labels: chore, skip-changelog, infrastructure

#7413 Fix #7412: Add missing closing quotes on line 110 of `src-docs\src\views\list_group\list_group_example.js`.
  src-docs/src/views/list_group/list_group_example.js
Labels: skip-changelog, community contribution

#7410 [DOCS] Add guidance for `EuiTabs` around higher-order navigation
  src-docs/src/views/breadcrumbs/breadcrumbs_example.js
  src-docs/src/views/tabs/tabs_example.js
  src-docs/src/views/tabs/tabs_guidance.js
Labels: documentation, skip-changelog

#7414 [docs][EuiFlexGroup] Fix example order/organization
  src-docs/src/views/flex/flex_example.js
Labels: documentation, skip-changelog

#7403 [BUG] Buildkite did not pick up new env variable.
  .buildkite/scripts/lifecycle/pre_command.sh
  scripts/deploy/deploy_docs
Labels: bug, skip-changelog, infrastructure

#7419 Fix #7418: Two instances of incorrect 2nd parseFloat parameter
  src-docs/src/views/datagrid/basics/datagrid.js
  src-docs/src/views/datagrid/schema_columns/footer_row.js
Labels: documentation, skip-changelog, community contribution

#7426 [CHORE] Bump nvmrc and Docker to use Node v20.10.0
  .buildkite/scripts/lifecycle/pre_command.sh
  .buildkite/scripts/pipelines/pipeline_test.sh
  .nvmrc
  package.json
  scripts/deploy/build_docs
  scripts/docker-ci/Dockerfile
Labels: chore, skip-changelog, infrastructure

#7435 Remove deprecated `EuiControlBar` component
  changelogs/upcoming/7435.md
  src-docs/src/routes.js
  src-docs/src/views/control_bar/control_bar.js
  src-docs/src/views/control_bar/control_bar_example.js
  src-docs/src/views/control_bar/controls.js
  src-docs/src/views/control_bar/mobile.js
  src-docs/src/views/control_bar/props.tsx
  src-docs/src/views/control_bar/tabs.js
  src/components/control_bar/__snapshots__/control_bar.test.tsx.snap
  src/components/control_bar/_control_bar.scss
  src/components/control_bar/_index.scss
  src/components/control_bar/_variables.scss
  src/components/control_bar/control_bar.a11y.tsx
  src/components/control_bar/control_bar.test.tsx
  src/components/control_bar/control_bar.tsx
  src/components/control_bar/index.ts
  src/components/drag_and_drop/drag_and_drop.a11y.tsx
  src/components/index.scss
  src/components/index.ts
Labels: breaking change

#7434 Remove deprecated `EuiNotificationEvent` component
  changelogs/upcoming/7434.md
  src-docs/src/routes.js
  src-docs/src/views/_index.scss
  src-docs/src/views/notification_event/_notification_event.scss
  src-docs/src/views/notification_event/notification_event.js
  src-docs/src/views/notification_event/notification_event_example.js
  src-docs/src/views/notification_event/notification_event_flexible.js
  src-docs/src/views/notification_event/notification_event_props_methods.js
  src-docs/src/views/notification_event/notifications_feed.js
  src/components/index.scss
  src/components/index.ts
  src/components/notification/__snapshots__/notification_event.test.tsx.snap
  src/components/notification/__snapshots__/notification_event_meta.test.tsx.snap
  src/components/notification/__snapshots__/notification_event_read_button.test.tsx.snap
  src/components/notification/_index.scss
  src/components/notification/_notification_event.scss
  src/components/notification/_notification_event_messages.scss
  src/components/notification/_notification_event_meta.scss
  src/components/notification/_notification_event_read_button.scss
  src/components/notification/_notification_event_read_icon.scss
  src/components/notification/index.ts
  src/components/notification/notification_event.a11y.tsx
  src/components/notification/notification_event.test.tsx
  src/components/notification/notification_event.tsx
  src/components/notification/notification_event_messages.tsx
  src/components/notification/notification_event_meta.test.tsx
  src/components/notification/notification_event_meta.tsx
  src/components/notification/notification_event_read_button.test.tsx
  src/components/notification/notification_event_read_button.tsx
  src/components/notification/notification_event_read_icon.tsx
Labels: breaking change
