Repository elastic/eui, pull requests merged in 2023-03, with the labels that each got.

#6629 [EuiFormControlLayout] Fix `isInvalid` icon
  src/components/form/field_password/__snapshots__/field_password.test.tsx.snap
  src/components/form/form_control_layout/__snapshots__/form_control_layout.test.tsx.snap
  src/components/form/form_control_layout/form_control_layout_icons.tsx
  src/components/form/super_select/__snapshots__/super_select_control.test.tsx.snap
  src/components/suggest/__snapshots__/suggest.test.tsx.snap
  upcoming_changelogs/6629.md
Labels: bug

#6628 [Docs] Remove arrow key page/route navigation
  src-docs/src/routes.js
  src-docs/src/views/app_view.js
Labels: documentation, skip-changelog

#6589 Added SR-only help text to `EuiPopover` and dependent components.
  src-docs/src/views/suggest/suggest_example.js
  src/components/date_picker/auto_refresh/auto_refresh.tsx
  src/components/form/range/dual_range.tsx
  src/components/form/range/range.tsx
  src/components/popover/popover.tsx
  src/components/selectable/__snapshots__/selectable.test.tsx.snap
  src/components/selectable/selectable.test.tsx
  src/components/selectable/selectable.tsx
  src/components/selectable/selectable_list/selectable_list.tsx
  src/components/selectable/selectable_templates/__snapshots__/selectable_template_sitewide.test.tsx.snap
  src/components/suggest/__snapshots__/suggest.test.tsx.snap
  src/components/suggest/suggest.tsx
  upcoming_changelogs/6589.md
Labels: accessibility, accessibility - screen reader

#6632 [EuiDataGrid] Add new `setCellPopoverProps` API to `renderCellPopover`
  src-docs/src/views/datagrid/cells_popovers/cell_popover_rendercellpopover.tsx
  src-docs/src/views/datagrid/cells_popovers/datagrid_cell_popover_example.js
  src/components/datagrid/body/data_grid_cell.test.tsx
  src/components/datagrid/body/data_grid_cell.tsx
  src/components/datagrid/body/data_grid_cell_popover.spec.tsx
  src/components/datagrid/body/data_grid_cell_popover.test.tsx
  src/components/datagrid/body/data_grid_cell_popover.tsx
  src/components/datagrid/body/footer/data_grid_footer_row.test.tsx
  src/components/datagrid/data_grid_types.ts
  upcoming_changelogs/6632.md
Labels: data grid

#6625 Update documentation-guidelines.md
  wiki/documentation-guidelines.md
Labels: skip-changelog

#6644 Remove Emotion conversion checklist from PR template
  .github/pull_request_template.md
Labels: skip-changelog

#6650 [EuiIcon Docs] Add callout with considerations for when importing SVGs as Components
  src-docs/src/views/icon/icon_example.js
Labels: documentation, skip-changelog

#6661 Upgrade `@babel/core` and `@babel/cli` to latest
  package.json
  yarn.lock
Labels: skip-changelog, tech debt

#6660 [EuiInlineEdit] Add Dynamic Font Sizing & Truncation Styling
  src/components/inline_edit/__snapshots__/inline_edit_text.test.tsx.snap
  src/components/inline_edit/__snapshots__/inline_edit_title.test.tsx.snap
  src/components/inline_edit/inline_edit_text.styles.ts
  src/components/inline_edit/inline_edit_text.tsx
  src/components/inline_edit/inline_edit_title.styles.ts
  src/components/inline_edit/inline_edit_title.tsx
Labels: skip-changelog

#6662 Upgrade `@babel/plugin-*` and `@babel/preset-*` packages to latest
  package.json
  scripts/babel/proptypes-from-ts-props/index.test.ts
  yarn.lock
Labels: skip-changelog, tech debt
