Repository elastic/eui, pull requests merged in 2023-08, with the labels that each got.

#7004 Upgrade to Node v18.17.0
  .buildkite/scripts/pipeline_test.sh
  .ci/jobs/elastic+eui+pull-request-test.yml
  .nvmrc
  package.json
  scripts/deploy/build_docs
  scripts/docker-ci/Dockerfile
  scripts/test-a11y-docker.js
  scripts/test-docker.js
Labels: skip-changelog, tech debt

#6990 [CHORE] Upgrading Cypress to version 12.
  package.json
  src/components/code/code_block_copy.spec.tsx
  yarn.lock
Labels: testing, skip-changelog

#7029 [A11y] Fixed two failing Cypress accessibility tests
  src/components/date_picker/super_date_picker/super_date_picker.a11y.tsx
  src/components/filter_group/filter_group.a11y.tsx
Labels: skip-changelog

#7027 [EuiCollapsibleNavBeta] Build out component state and responsive behavior
  src/components/collapsible_nav_beta/__snapshots__/collapsible_nav_beta.test.tsx.snap
  src/components/collapsible_nav_beta/collapsible_nav_beta.stories.tsx
  src/components/collapsible_nav_beta/collapsible_nav_beta.styles.ts
  src/components/collapsible_nav_beta/collapsible_nav_beta.test.tsx
  src/components/collapsible_nav_beta/collapsible_nav_beta.tsx
  src/components/collapsible_nav_beta/collapsible_nav_button/__snapshots__/collapsible_nav_button.test.tsx.snap
  src/components/collapsible_nav_beta/collapsible_nav_button/collapsible_nav_button.styles.ts
  src/components/collapsible_nav_beta/collapsible_nav_button/collapsible_nav_button.test.tsx
  src/components/collapsible_nav_beta/collapsible_nav_button/collapsible_nav_button.tsx
  src/components/collapsible_nav_beta/collapsible_nav_button/index.ts
  src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_item.stories.tsx
  src/components/collapsible_nav_beta/index.ts
  src/components/flyout/flyout.tsx
  src/components/header/header.styles.ts
Labels: skip-changelog

#7030 [INFRA] Fixing the Buildkite release docs job
  scripts/deploy/deploy_docs
Labels: skip-changelog, infrastructure

#7018 [EuiListGroupItem] Adding a `toolTipProps` spread operator to allow tooltip customization
  src-docs/src/views/list_group/list_group_example.js
  src-docs/src/views/list_group/list_group_extra.tsx
  src/components/list_group/list_group_item.test.tsx
  src/components/list_group/list_group_item.tsx
  src/components/tool_tip/tool_tip.tsx
  upcoming_changelogs/7018.md
Labels: feature request

#7036 [Buildkite] Avoid deploying backport and prerelease tags
  scripts/deploy/deploy_docs
Labels: skip-changelog, infrastructure

#7034 [EuiCollapsibleNavBeta] Final collapsed/docked icon & popover behavior
  src/components/collapsible_nav_beta/__snapshots__/collapsible_nav_beta.test.tsx.snap
  src/components/collapsible_nav_beta/collapsible_nav_beta.styles.ts
  src/components/collapsible_nav_beta/collapsible_nav_beta.tsx
  src/components/collapsible_nav_beta/collapsible_nav_button/__snapshots__/collapsible_nav_button.test.tsx.snap
  src/components/collapsible_nav_beta/collapsible_nav_button/collapsible_nav_button.styles.ts
  src/components/collapsible_nav_beta/collapsible_nav_button/collapsible_nav_button.test.tsx
  src/components/collapsible_nav_beta/collapsible_nav_button/collapsible_nav_button.tsx
  src/components/collapsible_nav_beta/collapsible_nav_item/__snapshots__/collapsible_nav_accordion.test.tsx.snap
  src/components/collapsible_nav_beta/collapsible_nav_item/__snapshots__/collapsible_nav_item.test.tsx.snap
  src/components/collapsible_nav_beta/collapsible_nav_item/__snapshots__/collapsible_nav_link.test.tsx.snap
  src/components/collapsible_nav_beta/collapsible_nav_item/collapsed/__snapshots__/collapsed_nav_button.test.tsx.snap
  src/components/collapsible_nav_beta/collapsible_nav_item/collapsed/__snapshots__/collapsed_nav_item.test.tsx.snap
  src/components/collapsible_nav_beta/collapsible_nav_item/collapsed/__snapshots__/collapsed_nav_popover.test.tsx.snap
  src/components/collapsible_nav_beta/collapsible_nav_item/collapsed/collapsed_nav_button.styles.ts
  src/components/collapsible_nav_beta/collapsible_nav_item/collapsed/collapsed_nav_button.test.tsx
  src/components/collapsible_nav_beta/collapsible_nav_item/collapsed/collapsed_nav_button.tsx
  src/components/collapsible_nav_beta/collapsible_nav_item/collapsed/collapsed_nav_item.stories.tsx
  src/components/collapsible_nav_beta/collapsible_nav_item/collapsed/collapsed_nav_item.test.tsx
  src/components/collapsible_nav_beta/collapsible_nav_item/collapsed/collapsed_nav_item.tsx
  src/components/collapsible_nav_beta/collapsible_nav_item/collapsed/collapsed_nav_popover.styles.ts
  src/components/collapsible_nav_beta/collapsible_nav_item/collapsed/collapsed_nav_popover.test.tsx
  src/components/collapsible_nav_beta/collapsible_nav_item/collapsed/collapsed_nav_popover.tsx
  src/components/collapsible_nav_beta/collapsible_nav_item/collapsed/index.ts
  src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_accordion.styles.ts
  src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_item.stories.tsx
  src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_item.test.tsx
  src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_item.tsx
  src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_link.test.tsx
  src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_link.tsx
  src/components/collapsible_nav_beta/context.ts
Labels: skip-changelog

#7026 [BUG] Fixed `isLoading` logic in `EuiConfirmModal` docs
  src-docs/src/views/modal/confirm_modal_loading.tsx
Labels: bug, documentation, skip-changelog

#7040 build: upgrade mdast-util-to-hast to 10.2.0
  package.json
  yarn.lock
Labels: skip-changelog

#7039 build: upgrade chroma-js to 2.4.2
  package.json
  yarn.lock
Labels: skip-changelog

#7037 [INFRA] Updating Jenkins and BK permissions for PR jobs.
  .ci/jobs/elastic+eui+pull-request.yml
  catalog-info.yaml
Labels: skip-changelog, infrastructure

#7050 [Docs] Remove `isNew` flag from `EuiSkeleton` components
  src-docs/src/views/skeleton/skeleton_example.js
Labels: documentation, skip-changelog

#7051 [EuiCollapsibleNavBeta] Add storybook QA test for ensuring flyouts sit above the nav
  src/components/collapsible_nav_beta/collapsible_nav_beta.stories.tsx
Labels: testing, skip-changelog

#7057 [EuiEmptyPrompt] Create Storybook Stories for `EuiEmptyPrompt` & Import Sass Styles for Components Not Using Emotion
  .storybook/preview.tsx
  src/components/empty_prompt/empty_prompt.stories.tsx
  src/components/empty_prompt/empty_prompt.tsx
Labels: documentation, skip-changelog

#7064 [EuiAccordion] Improve keyboard accessibility of tabbable children
  src/components/accordion/__snapshots__/accordion.test.tsx.snap
  src/components/accordion/accordion.test.tsx
  src/components/accordion/accordion.tsx
  src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_item.stories.tsx
  upcoming_changelogs/7064.md
Labels: accessibility

#7066 [wiki] Update Kibana upgrade docs
  wiki/eui-team-processes/upgrading-kibana.md
Labels: documentation, skip-changelog

#7045 [Snyk] Upgrade classnames from 2.2.6 to 2.3.2
  package.json
  yarn.lock
Labels: skip-changelog, tech debt

#6801 [Snyk] Upgrade tabbable from 5.2.1 to 5.3.3
  package.json
  scripts/jest/setup/mocks.js
  yarn.lock
Labels: skip-changelog, tech debt

#7046 [Snyk] Upgrade react-dropzone from 11.5.3 to 11.7.1
  package.json
  src/components/markdown_editor/__snapshots__/markdown_editor.test.tsx.snap
  yarn.lock
Labels: skip-changelog, tech debt

#6798 [Snyk] Upgrade react-virtualized-auto-sizer from 1.0.6 to 1.0.20
  package.json
  src-docs/src/views/auto_sizer/auto_sizer.tsx
  src/components/auto_sizer/auto_sizer.tsx
  src/components/auto_sizer/index.ts
  src/components/code/code_block_virtualized.tsx
  src/components/selectable/selectable_list/selectable_list.tsx
  upcoming_changelogs/6798.md
  yarn.lock
Labels: typescript, tech debt

#7065 [EuiFlyout] Resolve disparity between push flyouts and overlay flyouts
  src-docs/src/views/flyout/flyout_example.js
  src/components/collapsible_nav/__snapshots__/collapsible_nav.test.tsx.snap
  src/components/collapsible_nav_beta/__snapshots__/collapsible_nav_beta.test.tsx.snap
  src/components/collapsible_nav_beta/collapsible_nav_beta.tsx
  src/components/flyout/__snapshots__/flyout.test.tsx.snap
  src/components/flyout/flyout.test.tsx
  src/components/flyout/flyout.tsx
  upcoming_changelogs/7065.md
Labels: accessibility

#7060 fix: docs layout jumping
  src/components/page/page_sidebar/page_sidebar.tsx
  src/components/page_template/page_template.tsx
Labels: skip-changelog

#7067 [BUG] Added `GIT_TAG` env variable for tag and root docs deploy.
  .buildkite/pipelines/pipeline_release_deploy_docs.yml
  scripts/deploy/deploy_docs
Labels: bug, skip-changelog, infrastructure

#7081 [Emotion] Convert `EuiResizableButton`
  src/components/resizable_container/__snapshots__/resizable_button.test.tsx.snap
  src/components/resizable_container/__snapshots__/resizable_container.test.tsx.snap
  src/components/resizable_container/_index.scss
  src/components/resizable_container/_resizable_button.scss
  src/components/resizable_container/_variables.scss
  src/components/resizable_container/resizable_button.styles.ts
  src/components/resizable_container/resizable_button.test.tsx
  src/components/resizable_container/resizable_button.tsx
  upcoming_changelogs/7081.md
Labels: emotion

#7086 [CHORE] Removing last Jenkins blocks from docs deploy script.
  .buildkite/pipelines/pipeline_pull_request_test_and_deploy.yml
  .buildkite/pipelines/pipeline_release_deploy_docs.yml
  scripts/deploy/deploy_docs
Labels: skip-changelog, infrastructure

#7096 [CHORE] Bump Node to `v18.17.1`
  .buildkite/scripts/pipeline_test.sh
  .nvmrc
  package.json
  scripts/deploy/build_docs
  scripts/docker-ci/Dockerfile
  scripts/test-a11y-docker.js
  scripts/test-docker.js
Labels: chore, skip-changelog, infrastructure

#7091 [Emotion] Convert `EuiResizableCollapseButton`
  src/components/index.scss
  src/components/resizable_container/__snapshots__/resizable_container.test.tsx.snap
  src/components/resizable_container/_index.scss
  src/components/resizable_container/_resizable_collapse_button.scss
  src/components/resizable_container/resizable_collapse_button.stories.tsx
  src/components/resizable_container/resizable_collapse_button.styles.ts
  src/components/resizable_container/resizable_collapse_button.tsx
  src/themes/amsterdam/global_styling/mixins/shadow.ts
  upcoming_changelogs/7091.md
Labels: emotion

#7085 [Storybook] Create Playgrounds for `EuiPage`, `EuiPageSidebar`, `EuiPageSection`, `EuiPageBody`, and `EuiPageHeader`
  src/components/page/page.stories.tsx
  src/components/page/page_body/page_body.stories.tsx
  src/components/page/page_header/page_header.stories.tsx
  src/components/page/page_header/page_header_section.stories.tsx
  src/components/page/page_section/page_section.stories.tsx
  src/components/page/page_sidebar/page_sidebar.stories.tsx
Labels: skip-changelog

#7092 [tech debt] Update Storybook + other improvements
  .storybook/main.ts
  .storybook/preview.tsx
  package.json
  yarn.lock
Labels: skip-changelog, tech debt

#7104 [Emotion] Document usage of getters in Emotion style objects
  src/components/steps/step.styles.ts
  wiki/contributing-to-eui/developing/writing-styles-with-emotion.md
Labels: documentation, skip-changelog, tech debt, emotion

#7107 [BUG] Update `catalog-info.yml` to avoid double job starts in Buildkite
  catalog-info.yaml
Labels: bug, skip-changelog, infrastructure

#7113 [DOCS] Updating wiki doc for Buildkite release docs job
  wiki/eui-team-processes/releasing-versions.md
Labels: documentation, skip-changelog

#7115 Update feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: skip-changelog

#7114 Update bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: skip-changelog

#7118 [Emotion] Convert `EuiKeyPadMenuItem`
  src/components/index.scss
  src/components/key_pad_menu/__snapshots__/key_pad_menu_item.test.tsx.snap
  src/components/key_pad_menu/_index.scss
  src/components/key_pad_menu/_key_pad_menu_item.scss
  src/components/key_pad_menu/_variables.scss
  src/components/key_pad_menu/key_pad_menu_item.stories.tsx
  src/components/key_pad_menu/key_pad_menu_item.styles.ts
  src/components/key_pad_menu/key_pad_menu_item.tsx
  src/themes/amsterdam/overrides/_index.scss
  src/themes/amsterdam/overrides/_key_pad_menu.scss
  upcoming_changelogs/7118.md
Labels: emotion

#7074 [Snyk] Upgrade @types/resize-observer-browser from 0.1.5 to 0.1.7
  package.json
  yarn.lock
Labels: skip-changelog

#7075 [Snyk] Upgrade rehype-react from 6.1.0 to 6.2.1
  package.json
  yarn.lock
Labels: skip-changelog

#7072 [Snyk] Upgrade @types/numeral from 0.0.28 to 0.0.30
  package.json
  yarn.lock
Labels: skip-changelog

#7073 [Snyk] Upgrade @types/refractor from 3.0.0 to 3.0.2
  package.json
  yarn.lock
Labels: skip-changelog

#7134 [EuiCollapsibleNavBeta] Add `onCollapseToggle` callback
  src/components/collapsible_nav_beta/collapsible_nav_beta.stories.tsx
  src/components/collapsible_nav_beta/collapsible_nav_beta.test.tsx
  src/components/collapsible_nav_beta/collapsible_nav_beta.tsx
Labels: skip-changelog

#7139 Reorders icon grid to go left to right instead of vertically.
  src-docs/src/views/icon/apps.js
  src-docs/src/views/icon/icons.js
  src-docs/src/views/icon/logos.js
  src-docs/src/views/icon/ml.js
  src-docs/src/views/icon/tokens.tsx
Labels: documentation, skip-changelog

#7142 [docs] Document requirement for using drag & drop components in popovers
  src-docs/src/views/drag_and_drop/drag_and_drop_example.js
  src-docs/src/views/drag_and_drop/in_popover.tsx
Labels: documentation, skip-changelog
