Repository elastic/eui, pull requests merged in 2024-10, with the labels that each got.

#8055 Delete remaining component-specific mixins
  packages/eui/changelogs/upcoming/8055.md
  packages/eui/src/global_styling/mixins/_button.scss
  packages/eui/src/global_styling/mixins/_form.scss
  packages/eui/src/global_styling/mixins/_index.scss
  packages/eui/src/global_styling/mixins/_panel.scss
  packages/eui/src/global_styling/mixins/_tool_tip.scss
  packages/eui/src/themes/amsterdam/global_styling/mixins/_index.scss
Labels: emotion

#8059 github-actions: add missing permissions
  .github/workflows/stale_issues.yml
Labels: skip-changelog, tech debt

#8062 chore: remove EUI from `ci-systems` system
  catalog-info.yaml
Labels: skip-changelog

#8058 Re-add more of a README to `packages/eui/`
  packages/eui/README.md
Labels: documentation, skip-changelog

#8057 [EuiButtonDisplay] Fix missing text-align CSS
  packages/eui/src/components/button/button_display/_button_display.styles.ts
Labels: skip-changelog, emotion

#8028 [EuiDataGrid] Enhance `renderCustomGridBody` to better support consumer virtualization
  packages/eui/changelogs/upcoming/8028.md
  packages/eui/src-docs/src/views/datagrid/advanced/custom_renderer.tsx
  packages/eui/src-docs/src/views/datagrid/advanced/datagrid_advanced_example.js
  packages/eui/src-docs/src/views/datagrid/advanced/render_custom_grid_body/data_columns_cells.tsx
  packages/eui/src-docs/src/views/datagrid/advanced/render_custom_grid_body/data_grid.tsx
  packages/eui/src-docs/src/views/datagrid/advanced/render_custom_grid_body/example.js
  packages/eui/src-docs/src/views/datagrid/advanced/render_custom_grid_body/unvirtualized_body.tsx
  packages/eui/src-docs/src/views/datagrid/advanced/render_custom_grid_body/virtualized_body.tsx
  packages/eui/src/components/datagrid/body/data_grid_body_custom.spec.tsx
  packages/eui/src/components/datagrid/body/data_grid_body_custom.test.tsx
  packages/eui/src/components/datagrid/body/data_grid_body_custom.tsx
  packages/eui/src/components/datagrid/data_grid_types.ts
Labels: breaking change, data grid

#8066 [Cypress] Add static colorMode for test environment
  packages/eui/cypress/support/setup/mount.tsx
Labels: skip-changelog

#8076 Fix stalebot config
  .github/workflows/stale_issues.yml
Labels: skip-changelog, infrastructure

#8074 Fix Loki failures locally with non-cached Docker images
  packages/eui/.loki/reference/chrome_desktop_Layout_EuiInputPopover_Anchor_Position.png
  packages/eui/.loki/reference/chrome_desktop_Layout_EuiInputPopover_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Layout_EuiInputPopover_Anchor_Position.png
  packages/eui/.loki/reference/chrome_mobile_Layout_EuiInputPopover_Playground.png
  packages/eui/loki.config.js
  packages/eui/src/components/popover/input_popover.stories.tsx
Labels: testing, skip-changelog

#8078 ci: update github PAT token secret path
  .buildkite/scripts/lifecycle/pre_command.sh
Labels: skip-changelog, infrastructure

#8085 [EuiDataGrid] Vertically center toolbar `additionalControls` items
  packages/eui/changelogs/upcoming/8085.md
  packages/eui/src/components/datagrid/controls/data_grid_toolbar.styles.ts
Labels: data grid

#8080 [EuiDataGrid] Display selector / toolbar control enhancements
  packages/eui/.loki/reference/chrome_desktop_Tabular_Content_EuiDataGrid_toolbarVisibility_prop_Display_Selector.png
  packages/eui/.loki/reference/chrome_mobile_Tabular_Content_EuiDataGrid_toolbarVisibility_prop_Display_Selector.png
  packages/eui/changelogs/upcoming/8080.md
  packages/eui/src-docs/src/views/datagrid/toolbar/_props.tsx
  packages/eui/src-docs/src/views/datagrid/toolbar/additional_controls.tsx
  packages/eui/src-docs/src/views/datagrid/toolbar/datagrid_toolbar_example.js
  packages/eui/src-docs/src/views/datagrid/toolbar/render_custom_toolbar.tsx
  packages/eui/src/components/datagrid/body/data_grid_body_custom.spec.tsx
  packages/eui/src/components/datagrid/controls/__snapshots__/display_selector.test.tsx.snap
  packages/eui/src/components/datagrid/controls/data_grid_toolbar.stories.tsx
  packages/eui/src/components/datagrid/controls/display_selector.test.tsx
  packages/eui/src/components/datagrid/controls/display_selector.tsx
  packages/eui/src/components/datagrid/data_grid.spec.tsx
  packages/eui/src/components/datagrid/data_grid_types.ts
  packages/eui/src/services/hooks/useDeepEqual.ts
Labels: data grid

#8098 Fix EUI+ search not indexing heading elements
  packages/docusaurus-theme/src/theme/DocItem/Content/index.tsx
  packages/docusaurus-theme/src/theme/MDXContent/index.tsx
  packages/website/src/components/homepage/header/index.tsx
Labels: skip-changelog

#8096 [EuiDataGrid] Add new beta `rowHeightsOptions.autoBelowLineCount` feature flag
  packages/eui/.loki/reference/chrome_desktop_Tabular_Content_EuiDataGrid_rowHeightsOptions_prop_Auto_Below_Line_Count.png
  packages/eui/.loki/reference/chrome_mobile_Tabular_Content_EuiDataGrid_rowHeightsOptions_prop_Auto_Below_Line_Count.png
  packages/eui/changelogs/upcoming/8096.md
  packages/eui/src/components/datagrid/body/cell/data_grid_cell.test.tsx
  packages/eui/src/components/datagrid/body/cell/data_grid_cell.tsx
  packages/eui/src/components/datagrid/body/data_grid_body_custom.tsx
  packages/eui/src/components/datagrid/body/data_grid_body_virtualized.tsx
  packages/eui/src/components/datagrid/controls/display_selector.test.tsx
  packages/eui/src/components/datagrid/controls/display_selector.tsx
  packages/eui/src/components/datagrid/data_grid.styles.ts
  packages/eui/src/components/datagrid/data_grid_row_heights.stories.tsx
  packages/eui/src/components/datagrid/data_grid_types.ts
  packages/eui/src/components/datagrid/utils/__mocks__/row_heights.ts
  packages/eui/src/components/datagrid/utils/grid_height_width.ts
  packages/eui/src/components/datagrid/utils/row_heights.test.ts
  packages/eui/src/components/datagrid/utils/row_heights.ts
Labels: data grid

#8106 docs: fix broken imports in color utilities
  packages/website/docs/components/theming/colors/utilities/use_eui_background_color_css_preview.tsx
  packages/website/docs/components/theming/colors/utilities/use_eui_background_color_preview.tsx
  packages/website/docs/components/theming/colors/utilities/use_eui_background_color_table.tsx
Labels: skip-changelog

#8107 [EUI+] Polish pass on all docs callouts
  packages/docusaurus-theme/src/components/call_out/index.tsx
  packages/website/docs/components/display/aspect_ratio.mdx
  packages/website/docs/components/display/badge.mdx
  packages/website/docs/components/display/card.mdx
  packages/website/docs/components/display/comment_list.mdx
  packages/website/docs/components/display/drag_and_drop.mdx
  packages/website/docs/components/display/icons/overview.mdx
  packages/website/docs/components/display/image.mdx
  packages/website/docs/components/display/progress.mdx
  packages/website/docs/components/display/skeleton.mdx
  packages/website/docs/components/display/text.mdx
  packages/website/docs/components/display/timeline.mdx
  packages/website/docs/components/display/tour/overview.mdx
  packages/website/docs/components/editors_and_syntax/code.mdx
  packages/website/docs/components/elastic_charts/accessibility_features.mdx
  packages/website/docs/components/elastic_charts/metric_chart.mdx
  packages/website/docs/components/forms/combo_box.mdx
  packages/website/docs/components/forms/compressed_forms.mdx
  packages/website/docs/components/forms/date_picker.mdx
  packages/website/docs/components/forms/form_controls/overview.mdx
  packages/website/docs/components/forms/range_sliders.mdx
  packages/website/docs/components/forms/selectable.mdx
  packages/website/docs/components/forms/selection_controls/overview.mdx
  packages/website/docs/components/forms/super_select.mdx
  packages/website/docs/components/guidelines/accessibility.mdx
  packages/website/docs/components/guidelines/writing/guidelines.mdx
  packages/website/docs/components/layout/accordion.mdx
  packages/website/docs/components/layout/bottom_bar.mdx
  packages/website/docs/components/layout/flyout.mdx
  packages/website/docs/components/layout/page_components/overview.mdx
  packages/website/docs/components/layout/popover.mdx
  packages/website/docs/components/layout/resizable_container.mdx
  packages/website/docs/components/navigation/breadcrumbs.mdx
  packages/website/docs/components/navigation/button/overview.mdx
  packages/website/docs/components/navigation/collapsible_nav.mdx
  packages/website/docs/components/navigation/context_menu.mdx
  packages/website/docs/components/navigation/key_pad_menu.mdx
  packages/website/docs/components/navigation/pagination/overview.mdx
  packages/website/docs/components/navigation/side_nav.mdx
  packages/website/docs/components/navigation/tree_view.mdx
  packages/website/docs/components/tabular_content/data_grid.mdx
  packages/website/docs/components/tabular_content/data_grid_advanced.mdx
  packages/website/docs/components/tabular_content/data_grid_cells_and_popovers.mdx
  packages/website/docs/components/tabular_content/in_memory_tables.mdx
  packages/website/docs/components/tabular_content/tables.mdx
  packages/website/docs/components/templates/page_template/overview.mdx
  packages/website/docs/components/templates/sitewide_search.mdx
  packages/website/docs/components/templates/super_date_picker.mdx
Labels: documentation, skip-changelog
