Repository elastic/eui, pull requests merged in 2024-05, with the labels that each got.

#7720 [EuiDatagrid] fix content header styles to ensure text alignment is applied
  .loki/reference/chrome_desktop_Tabular_Content_EuiDataGrid_Playground.png
  .loki/reference/chrome_mobile_Tabular_Content_EuiDataGrid_Playground.png
  changelogs/upcoming/7720.md
  src/components/datagrid/body/header/_data_grid_header_row.scss
  src/components/datagrid/controls/data_grid_toolbar.tsx
  src/components/datagrid/data_grid.stories.tsx
Labels: bug, documentation

#7734 Fix failure of yarn test-unit at 9 hours offset
  src/services/format/format_date.test.ts
Labels: testing, skip-changelog

#7742 [changelogs] Add an accessibility prompt/heading to `yo` generator
  generator-eui/changelog/index.js
  generator-eui/changelog/templates/changelog.md
Labels: skip-changelog, infrastructure

#7729 [Storybook] Add stories for more components (letters R-S) - Part 3
  .loki/reference/chrome_desktop_Display_EuiSkeletonLoading_EuiSkeletonCircle_Playground.png
  .loki/reference/chrome_desktop_Display_EuiSkeletonLoading_EuiSkeletonLoading_Playground.png
  .loki/reference/chrome_desktop_Display_EuiSkeletonLoading_EuiSkeletonRectangle_Playground.png
  .loki/reference/chrome_desktop_Display_EuiSkeletonLoading_EuiSkeletonText_Playground.png
  .loki/reference/chrome_desktop_Display_EuiSkeletonLoading_EuiSkeletonTitle_Playground.png
  .loki/reference/chrome_mobile_Display_EuiSkeletonLoading_EuiSkeletonCircle_Playground.png
  .loki/reference/chrome_mobile_Display_EuiSkeletonLoading_EuiSkeletonLoading_Playground.png
  .loki/reference/chrome_mobile_Display_EuiSkeletonLoading_EuiSkeletonRectangle_Playground.png
  .loki/reference/chrome_mobile_Display_EuiSkeletonLoading_EuiSkeletonText_Playground.png
  .loki/reference/chrome_mobile_Display_EuiSkeletonLoading_EuiSkeletonTitle_Playground.png
  src/components/skeleton/skeleton_circle.stories.tsx
  src/components/skeleton/skeleton_loading.stories.tsx
  src/components/skeleton/skeleton_rectangle.stories.tsx
  src/components/skeleton/skeleton_text.stories.tsx
  src/components/skeleton/skeleton_title.stories.tsx
Labels: documentation, skip-changelog

#7730 [VRT] Add reference images for recently added stories
  .loki/reference/chrome_desktop_Display_EuiProgress_Determinate.png
  .loki/reference/chrome_desktop_Display_EuiProgress_Indeterminate.png
  .loki/reference/chrome_desktop_Display_EuiStat_Playground.png
  .loki/reference/chrome_desktop_Forms_EuiComboBox_Custom_Matcher.png
  .loki/reference/chrome_desktop_Forms_EuiSearchBar_EuiSearchBarFilters_Playground.png
  .loki/reference/chrome_desktop_Forms_EuiSearchBar_EuiSearchBar_Playground.png
  .loki/reference/chrome_desktop_Layout_EuiInputPopover_Anchor_Position.png
  .loki/reference/chrome_desktop_Layout_EuiInputPopover_Playground.png
  .loki/reference/chrome_desktop_Layout_EuiPopover_EuiPopoverFooter_Playground.png
  .loki/reference/chrome_desktop_Layout_EuiPopover_EuiPopoverTitle_Playground.png
  .loki/reference/chrome_desktop_Layout_EuiPopover_EuiPopover_Panel_Padding_Size.png
  .loki/reference/chrome_desktop_Layout_EuiPopover_EuiPopover_Playground.png
  .loki/reference/chrome_desktop_Layout_EuiResizableContainer_EuiResizableContainer_Collapsible_Panels.png
  .loki/reference/chrome_desktop_Layout_EuiResizableContainer_EuiResizableContainer_Playground.png
  .loki/reference/chrome_desktop_Layout_EuiResizableContainer_EuiResizablePanel_Playground.png
  .loki/reference/chrome_desktop_Layout_EuiSpacer_Playground.png
  .loki/reference/chrome_desktop_Layout_EuiWrappingPopover_Playground.png
  .loki/reference/chrome_desktop_Navigation_EuiCollapsibleNav_beta_EuiCollapsibleNavBeta_Collapsed_State_In_Local_Storage.png
  .loki/reference/chrome_desktop_Navigation_EuiCollapsibleNav_beta_EuiCollapsibleNavBeta_Flyout_Overlay.png
  .loki/reference/chrome_desktop_Navigation_EuiCollapsibleNav_beta_EuiCollapsibleNavBeta_Global_CSS_Variable.png
  .loki/reference/chrome_desktop_Navigation_EuiCollapsibleNav_beta_EuiCollapsibleNavBeta_Playground.png
  .loki/reference/chrome_desktop_Navigation_EuiCollapsibleNav_beta_EuiCollapsibleNavItem_Edge_Case_Testing.png
  .loki/reference/chrome_desktop_Navigation_EuiCollapsibleNav_beta_EuiCollapsibleNavItem_EuiCollapsedNavItem_Accordion.png
  .loki/reference/chrome_desktop_Navigation_EuiCollapsibleNav_beta_EuiCollapsibleNavItem_EuiCollapsedNavItem_Link.png
  .loki/reference/chrome_desktop_Navigation_EuiCollapsibleNav_beta_EuiCollapsibleNavItem_Playground.png
  .loki/reference/chrome_desktop_Navigation_EuiCollapsibleNav_beta_KibanaSolution_Playground.png
  .loki/reference/chrome_desktop_Tabular_Content_EuiDataGrid_Playground.png
  .loki/reference/chrome_desktop_Utilities_EuiPortal_Playground.png
  .loki/reference/chrome_mobile_Display_EuiProgress_Determinate.png
  .loki/reference/chrome_mobile_Display_EuiProgress_Indeterminate.png
  .loki/reference/chrome_mobile_Display_EuiStat_Playground.png
  .loki/reference/chrome_mobile_Forms_EuiComboBox_Custom_Matcher.png
  .loki/reference/chrome_mobile_Forms_EuiSearchBar_EuiSearchBarFilters_Playground.png
  .loki/reference/chrome_mobile_Forms_EuiSearchBar_EuiSearchBar_Playground.png
  .loki/reference/chrome_mobile_Layout_EuiInputPopover_Anchor_Position.png
  .loki/reference/chrome_mobile_Layout_EuiInputPopover_Playground.png
  .loki/reference/chrome_mobile_Layout_EuiPopover_EuiPopoverFooter_Playground.png
  .loki/reference/chrome_mobile_Layout_EuiPopover_EuiPopoverTitle_Playground.png
  .loki/reference/chrome_mobile_Layout_EuiPopover_EuiPopover_Panel_Padding_Size.png
  .loki/reference/chrome_mobile_Layout_EuiPopover_EuiPopover_Playground.png
  .loki/reference/chrome_mobile_Layout_EuiResizableContainer_EuiResizableContainer_Collapsible_Panels.png
  .loki/reference/chrome_mobile_Layout_EuiResizableContainer_EuiResizableContainer_Playground.png
  .loki/reference/chrome_mobile_Layout_EuiResizableContainer_EuiResizablePanel_Playground.png
  .loki/reference/chrome_mobile_Layout_EuiSpacer_Playground.png
  .loki/reference/chrome_mobile_Layout_EuiWrappingPopover_Playground.png
  .loki/reference/chrome_mobile_Navigation_EuiCollapsibleNav_beta_EuiCollapsibleNavBeta_Collapsed_State_In_Local_Storage.png
  .loki/reference/chrome_mobile_Navigation_EuiCollapsibleNav_beta_EuiCollapsibleNavBeta_Flyout_Overlay.png
  .loki/reference/chrome_mobile_Navigation_EuiCollapsibleNav_beta_EuiCollapsibleNavBeta_Global_CSS_Variable.png
  .loki/reference/chrome_mobile_Navigation_EuiCollapsibleNav_beta_EuiCollapsibleNavBeta_Playground.png
  .loki/reference/chrome_mobile_Navigation_EuiCollapsibleNav_beta_EuiCollapsibleNavItem_Edge_Case_Testing.png
  .loki/reference/chrome_mobile_Navigation_EuiCollapsibleNav_beta_EuiCollapsibleNavItem_EuiCollapsedNavItem_Accordion.png
  .loki/reference/chrome_mobile_Navigation_EuiCollapsibleNav_beta_EuiCollapsibleNavItem_EuiCollapsedNavItem_Link.png
  .loki/reference/chrome_mobile_Navigation_EuiCollapsibleNav_beta_EuiCollapsibleNavItem_Playground.png
  .loki/reference/chrome_mobile_Navigation_EuiCollapsibleNav_beta_KibanaSolution_Playground.png
  .loki/reference/chrome_mobile_Tabular_Content_EuiDataGrid_Playground.png
  .loki/reference/chrome_mobile_Utilities_EuiPortal_Playground.png
  src/components/datagrid/data_grid.stories.tsx
  src/components/portal/portal.stories.tsx
  src/components/responsive/show_for.stories.tsx
Labels: skip-changelog

#7733 [Storybook] Add stories for more components (letters R-S) - Part 4
  .loki/reference/chrome_desktop_Navigation_EuiSteps_EuiStepNumber_Playground.png
  .loki/reference/chrome_desktop_Navigation_EuiSteps_EuiStepsHorizontal_EuiStepHorizontal_Playground.png
  .loki/reference/chrome_desktop_Navigation_EuiSteps_EuiStepsHorizontal_EuiStepsHorizontal_Playground.png
  .loki/reference/chrome_desktop_Navigation_EuiSteps_EuiSteps_EuiStep_Playground.png
  .loki/reference/chrome_desktop_Navigation_EuiSteps_EuiSteps_Playground.png
  .loki/reference/chrome_desktop_Navigation_EuiSteps_EuiSubSteps_Playground.png
  .loki/reference/chrome_mobile_Navigation_EuiSteps_EuiStepNumber_Playground.png
  .loki/reference/chrome_mobile_Navigation_EuiSteps_EuiStepsHorizontal_EuiStepHorizontal_Playground.png
  .loki/reference/chrome_mobile_Navigation_EuiSteps_EuiStepsHorizontal_EuiStepsHorizontal_Playground.png
  .loki/reference/chrome_mobile_Navigation_EuiSteps_EuiSteps_EuiStep_Playground.png
  .loki/reference/chrome_mobile_Navigation_EuiSteps_EuiSteps_Playground.png
  .loki/reference/chrome_mobile_Navigation_EuiSteps_EuiSubSteps_Playground.png
  src/components/steps/step.stories.tsx
  src/components/steps/step_horizontal.stories.tsx
  src/components/steps/step_number.stories.tsx
  src/components/steps/steps.stories.tsx
  src/components/steps/steps_horizontal.stories.tsx
  src/components/steps/sub_steps.stories.tsx
Labels: documentation, skip-changelog

#7735 [Storybook] Support storybook interactions for VRT
  .loki/reference/chrome_desktop_Forms_EuiComboBox_With_Tooltip.png
  .loki/reference/chrome_mobile_Forms_EuiComboBox_With_Tooltip.png
  .storybook/loki.ts
  .storybook/main.ts
  .storybook/types.d.ts
  package.json
  src/components/combo_box/combo_box.stories.tsx
  tsconfig.json
  wiki/contributing-to-eui/testing/visual-regression-testing.md
  yarn.lock
Labels: documentation, skip-changelog

#7728 [Storybook] Add stories for more components (letters R-S) - Part 2
  .loki/reference/chrome_desktop_Forms_EuiSelectable_EuiSelectableList_EuiSelectableListItem_Playground.png
  .loki/reference/chrome_desktop_Forms_EuiSelectable_EuiSelectableList_EuiSelectableList_Playground.png
  .loki/reference/chrome_desktop_Forms_EuiSelectable_EuiSelectableMessage_Playground.png
  .loki/reference/chrome_desktop_Forms_EuiSelectable_EuiSelectableSearch_Playground.png
  .loki/reference/chrome_desktop_Templates_EuiSelectableTemplateSitewide_Playground.png
  .loki/reference/chrome_mobile_Forms_EuiSelectable_EuiSelectableList_EuiSelectableListItem_Playground.png
  .loki/reference/chrome_mobile_Forms_EuiSelectable_EuiSelectableList_EuiSelectableList_Playground.png
  .loki/reference/chrome_mobile_Forms_EuiSelectable_EuiSelectableMessage_Playground.png
  .loki/reference/chrome_mobile_Forms_EuiSelectable_EuiSelectableSearch_Playground.png
  .loki/reference/chrome_mobile_Templates_EuiSelectableTemplateSitewide_Playground.png
  src/components/selectable/selectable_list/selectable_list.stories.tsx
  src/components/selectable/selectable_list/selectable_list.tsx
  src/components/selectable/selectable_list/selectable_list_item.stories.tsx
  src/components/selectable/selectable_message/selectable_message.stories.tsx
  src/components/selectable/selectable_option.tsx
  src/components/selectable/selectable_search/selectable_search.stories.tsx
  src/components/selectable/selectable_search/selectable_search.tsx
  src/components/selectable/selectable_templates/_selectable_template_sitewide_option.scss
  src/components/selectable/selectable_templates/selectable_template_sidewide.stories.tsx
Labels: documentation, skip-changelog

#7749 build: fix changelog github action
  .github/workflows/changelog.yml
Labels: skip-changelog

#7751 [EuiToolTip] Close tooltips on escape keydown
  packages/eui/changelogs/upcoming/7751.md
  packages/eui/src/components/tool_tip/tool_tip.spec.tsx
  packages/eui/src/components/tool_tip/tool_tip.tsx
Labels: accessibility - keyboard

#7756 [Wiki] Document deprecating/unpublishing releases
  wiki/eui-team-processes/releasing-versions.md
Labels: documentation, skip-changelog

#7750 [EuiFlyoutResizable] Fix `onResize` not appearing in props table
  packages/eui/src/components/flyout/flyout_resizable.tsx
Labels: documentation, skip-changelog

#7757 [Wiki] Add troubleshooting section
  wiki/contributing-to-eui/running-eui-locally.md
Labels: documentation, skip-changelog

#7739 [Storybook] Add stories for more components (letter T) - Part 1
  packages/eui/.loki/reference/chrome_desktop_Display_EuiText_EuiTextAlign_Clone_Element.png
  packages/eui/.loki/reference/chrome_desktop_Display_EuiText_EuiTextAlign_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Display_EuiText_EuiTextColor_Clone_Element.png
  packages/eui/.loki/reference/chrome_desktop_Display_EuiText_EuiTextColor_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Display_EuiText_EuiText_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Display_EuiTitle_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Navigation_EuiTabbedContent_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Navigation_EuiTabs_EuiTab_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Navigation_EuiTabs_EuiTabs_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Utilities_useEuiTextDiff_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Display_EuiText_EuiTextAlign_Clone_Element.png
  packages/eui/.loki/reference/chrome_mobile_Display_EuiText_EuiTextAlign_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Display_EuiText_EuiTextColor_Clone_Element.png
  packages/eui/.loki/reference/chrome_mobile_Display_EuiText_EuiTextColor_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Display_EuiText_EuiText_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Display_EuiTitle_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Navigation_EuiTabbedContent_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Navigation_EuiTabs_EuiTab_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Navigation_EuiTabs_EuiTabs_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Utilities_useEuiTextDiff_Playground.png
  packages/eui/src/components/tabs/tab.stories.tsx
  packages/eui/src/components/tabs/tabbed_content/tabbed_content.stories.tsx
  packages/eui/src/components/tabs/tabbed_content/tabbed_content.tsx
  packages/eui/src/components/tabs/tabs.stories.tsx
  packages/eui/src/components/text/text.stories.tsx
  packages/eui/src/components/text/text_align.stories.tsx
  packages/eui/src/components/text/text_color.stories.tsx
  packages/eui/src/components/text_diff/text_diff.stories.tsx
  packages/eui/src/components/text_diff/text_diff.tsx
  packages/eui/src/components/title/title.stories.tsx
Labels: documentation, skip-changelog

#7763 [VRT] Update more reference images
  packages/eui/.loki/reference/chrome_desktop_Display_EuiTimeline_EuiTimeline_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Display_EuiToast_EuiGlobalToastList_EuiGlobalToastListItem_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Display_EuiToast_EuiGlobalToastList_EuiGlobalToastList_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Editors_Syntax_EuiMarkdownEditor_EuiMarkdownEditor_Errors.png
  packages/eui/.loki/reference/chrome_desktop_Editors_Syntax_EuiMarkdownEditor_EuiMarkdownEditor_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Editors_Syntax_EuiMarkdownEditor_EuiMarkdownEditor_View_Mode.png
  packages/eui/.loki/reference/chrome_desktop_Editors_Syntax_EuiMarkdownEditor_EuiMarkdownFormat_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Navigation_EuiSteps_EuiStepsHorizontal_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Navigation_EuiSteps_Subcomponents_EuiStepNumber_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Navigation_EuiSteps_Subcomponents_EuiSubSteps_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Tabular_Content_EuiDataGrid_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Display_EuiTimeline_EuiTimeline_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Display_EuiToast_EuiGlobalToastList_EuiGlobalToastListItem_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Display_EuiToast_EuiGlobalToastList_EuiGlobalToastList_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Editors_Syntax_EuiMarkdownEditor_EuiMarkdownEditor_Errors.png
  packages/eui/.loki/reference/chrome_mobile_Editors_Syntax_EuiMarkdownEditor_EuiMarkdownEditor_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Editors_Syntax_EuiMarkdownEditor_EuiMarkdownEditor_View_Mode.png
  packages/eui/.loki/reference/chrome_mobile_Editors_Syntax_EuiMarkdownEditor_EuiMarkdownFormat_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Navigation_EuiSteps_EuiStepsHorizontal_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Navigation_EuiSteps_Subcomponents_EuiStepNumber_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Navigation_EuiSteps_Subcomponents_EuiSubSteps_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Tabular_Content_EuiDataGrid_Playground.png
  packages/eui/src/components/datagrid/data_grid.stories.tsx
Labels: documentation, skip-changelog

#7726 [EuiDatePicker][a11y] Fix screen reader announcements on time selection and intermittently broken up/down navigation on NVDA/JAWS
  packages/eui/changelogs/upcoming/7726.md
  packages/eui/src/components/date_picker/react-datepicker/src/time.js
Labels: bug, a11yReviewNeeded

#7768 fix(EuiSelectableList): fix read-after-write on component state
  packages/eui/src/components/selectable/selectable_list/selectable_list.tsx
Labels: testing, skip-changelog, tech debt

#7755 [Storybook] Add stories for more components (EuiTable components)
  packages/eui/.loki/reference/chrome_desktop_Tabular_Content_EuiTable_EuiTableBody_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Tabular_Content_EuiTable_EuiTableFooter_EuiTableFooterCell_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Tabular_Content_EuiTable_EuiTableFooter_EuiTableFooter_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Tabular_Content_EuiTable_EuiTableHeader_EuiTableHeaderCellCheckbox_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Tabular_Content_EuiTable_EuiTableHeader_EuiTableHeaderCell_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Tabular_Content_EuiTable_EuiTableHeader_EuiTableHeader_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Tabular_Content_EuiTable_EuiTablePagination_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Tabular_Content_EuiTable_EuiTableRow_EuiTableRowCellCheckbox_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Tabular_Content_EuiTable_EuiTableRow_EuiTableRowCell_Actions.png
  packages/eui/.loki/reference/chrome_desktop_Tabular_Content_EuiTable_EuiTableRow_EuiTableRowCell_Expander.png
  packages/eui/.loki/reference/chrome_desktop_Tabular_Content_EuiTable_EuiTableRow_EuiTableRowCell_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Tabular_Content_EuiTable_EuiTableRow_EuiTableRow_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Tabular_Content_EuiTable_Mobile_subcomponents_EuiTableHeaderMobile_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Tabular_Content_EuiTable_Mobile_subcomponents_EuiTableSortMobileItem_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Tabular_Content_EuiTable_Mobile_subcomponents_EuiTableSortMobile_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Tabular_Content_EuiTable_EuiTableBody_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Tabular_Content_EuiTable_EuiTableFooter_EuiTableFooterCell_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Tabular_Content_EuiTable_EuiTableFooter_EuiTableFooter_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Tabular_Content_EuiTable_EuiTableHeader_EuiTableHeaderCellCheckbox_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Tabular_Content_EuiTable_EuiTableHeader_EuiTableHeaderCell_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Tabular_Content_EuiTable_EuiTableHeader_EuiTableHeader_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Tabular_Content_EuiTable_EuiTablePagination_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Tabular_Content_EuiTable_EuiTableRow_EuiTableRowCellCheckbox_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Tabular_Content_EuiTable_EuiTableRow_EuiTableRowCell_Actions.png
  packages/eui/.loki/reference/chrome_mobile_Tabular_Content_EuiTable_EuiTableRow_EuiTableRowCell_Expander.png
  packages/eui/.loki/reference/chrome_mobile_Tabular_Content_EuiTable_EuiTableRow_EuiTableRowCell_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Tabular_Content_EuiTable_EuiTableRow_EuiTableRow_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Tabular_Content_EuiTable_Mobile_subcomponents_EuiTableHeaderMobile_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Tabular_Content_EuiTable_Mobile_subcomponents_EuiTableSortMobileItem_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Tabular_Content_EuiTable_Mobile_subcomponents_EuiTableSortMobile_Playground.png
  packages/eui/src/components/table/mobile/table_header_mobile.stories.tsx
  packages/eui/src/components/table/mobile/table_sort_mobile.stories.tsx
  packages/eui/src/components/table/mobile/table_sort_mobile_item.stories.tsx
  packages/eui/src/components/table/table_body.stories.tsx
  packages/eui/src/components/table/table_footer.stories.tsx
  packages/eui/src/components/table/table_footer_cell.stories.tsx
  packages/eui/src/components/table/table_header.stories.tsx
  packages/eui/src/components/table/table_header_cell.stories.tsx
  packages/eui/src/components/table/table_header_cell.tsx
  packages/eui/src/components/table/table_header_cell_checkbox.stories.tsx
  packages/eui/src/components/table/table_header_cell_checkbox.tsx
  packages/eui/src/components/table/table_header_cell_shared.ts
  packages/eui/src/components/table/table_pagination/table_pagination.stories.tsx
  packages/eui/src/components/table/table_row.stories.tsx
  packages/eui/src/components/table/table_row_cell.stories.tsx
  packages/eui/src/components/table/table_row_cell_checkbox.stories.tsx
Labels: documentation, skip-changelog

#7762 [Storybook] Add stories for more components (letter D) - Part 1
  packages/eui/.loki/reference/chrome_desktop_Display_EuiDescriptionList_Column.png
  packages/eui/.loki/reference/chrome_desktop_Display_EuiDescriptionList_Inline.png
  packages/eui/.loki/reference/chrome_desktop_Display_EuiDescriptionList_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Display_EuiDescriptionList_Row.png
  packages/eui/.loki/reference/chrome_desktop_Display_EuiDescriptionList_Subcomponents_EuiDescriptionListDescription_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Display_EuiDescriptionList_Subcomponents_EuiDescriptionListTitle_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Display_EuiDescriptionList_Column.png
  packages/eui/.loki/reference/chrome_mobile_Display_EuiDescriptionList_Inline.png
  packages/eui/.loki/reference/chrome_mobile_Display_EuiDescriptionList_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Display_EuiDescriptionList_Row.png
  packages/eui/.loki/reference/chrome_mobile_Display_EuiDescriptionList_Subcomponents_EuiDescriptionListDescription_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Display_EuiDescriptionList_Subcomponents_EuiDescriptionListTitle_Playground.png
  packages/eui/src/components/delay_hide/delay_hide.stories.tsx
  packages/eui/src/components/delay_render/delay_render.stories.tsx
  packages/eui/src/components/description_list/description_list.stories.tsx
  packages/eui/src/components/description_list/description_list_description.stories.tsx
  packages/eui/src/components/description_list/description_list_title.stories.tsx
Labels: documentation, skip-changelog

#7784 [EuiDatePicker] Handle invalid `selected` moment formats
  packages/eui/changelogs/upcoming/7784.md
  packages/eui/src/components/date_picker/date_picker.test.tsx
  packages/eui/src/components/date_picker/date_picker.tsx
  packages/eui/src/components/date_picker/react-datepicker/src/index.js
Labels: bug

#7779 [Storybook] Add stories for more components (letter D) - Part 2
  packages/eui/.loki/reference/chrome_desktop_Display_EuiDraggable_Interactive.png
  packages/eui/.loki/reference/chrome_desktop_Display_EuiDraggable_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Display_EuiDroppable_Clone_Draggables.png
  packages/eui/.loki/reference/chrome_desktop_Display_EuiDroppable_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Display_EuiDraggable_Interactive.png
  packages/eui/.loki/reference/chrome_mobile_Display_EuiDraggable_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Display_EuiDroppable_Clone_Draggables.png
  packages/eui/.loki/reference/chrome_mobile_Display_EuiDroppable_Playground.png
  packages/eui/src/components/drag_and_drop/drag_drop_context.stories.tsx
  packages/eui/src/components/drag_and_drop/drag_drop_context.tsx
  packages/eui/src/components/drag_and_drop/draggable.stories.tsx
  packages/eui/src/components/drag_and_drop/droppable.stories.tsx
Labels: documentation, skip-changelog

#7745 [Storybook] Add stories for more components (letter T) - Part 3
  packages/eui/.loki/reference/chrome_desktop_Display_EuiIconTip_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Display_EuiToken_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Display_EuiToolTip_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Display_EuiTour_EuiTourStepIndicator_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Display_EuiTour_EuiTourStep_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Display_EuiTour_EuiTour_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Display_EuiIconTip_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Display_EuiToken_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Display_EuiToolTip_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Display_EuiTour_EuiTourStepIndicator_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Display_EuiTour_EuiTourStep_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Display_EuiTour_EuiTour_Playground.png
  packages/eui/src/components/token/token.stories.tsx
  packages/eui/src/components/tool_tip/icon_tip.stories.tsx
  packages/eui/src/components/tool_tip/icon_tip.tsx
  packages/eui/src/components/tool_tip/tool_tip.stories.tsx
  packages/eui/src/components/tour/tour.stories.tsx
  packages/eui/src/components/tour/tour_step.stories.tsx
  packages/eui/src/components/tour/tour_step_indicator.stories.tsx
Labels: documentation, skip-changelog

#7801 Upgrade Node to v20.13.1
  .buildkite/scripts/lifecycle/pre_command.sh
  .nvmrc
  packages/eui/package.json
  packages/eui/scripts/docker-ci/Dockerfile
  wiki/eui-team-processes/upgrading-node.md
Labels: skip-changelog, tech debt

#7781 [Storybook] Add stories for more components (form components) - Part 1
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiCheckboxGroup_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiCheckbox_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiFieldPassword_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiFieldSearch_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiRadioGroup_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiRadio_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiSwitch_Checked.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiSwitch_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiTextArea_Icon_Shape.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiTextArea_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiCheckboxGroup_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiCheckbox_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiFieldPassword_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiFieldSearch_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiRadioGroup_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiRadio_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiSwitch_Checked.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiSwitch_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiTextArea_Icon_Shape.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiTextArea_Playground.png
  packages/eui/.storybook/manager.ts
  packages/eui/package.json
  packages/eui/src/components/form/checkbox/checkbox.stories.tsx
  packages/eui/src/components/form/checkbox/checkbox_group.stories.tsx
  packages/eui/src/components/form/field_number/field_number.stories.tsx
  packages/eui/src/components/form/field_password/field_password.stories.tsx
  packages/eui/src/components/form/field_search/field_search.stories.tsx
  packages/eui/src/components/form/field_text/field_text.stories.tsx
  packages/eui/src/components/form/radio/radio.stories.tsx
  packages/eui/src/components/form/radio/radio_group.stories.tsx
  packages/eui/src/components/form/switch/switch.stories.tsx
  packages/eui/src/components/form/switch/switch.tsx
  packages/eui/src/components/form/text_area/text_area.stories.tsx
  yarn.lock
Labels: documentation, skip-changelog
