Repository elastic/eui, pull requests merged in 2024-07, with the labels that each got.

#7848 [EUI+] Initial typography and doc content updates
  packages/docusaurus-theme/src/components/call_out/index.tsx
  packages/docusaurus-theme/src/components/theme_context/theme_overrides.ts
  packages/docusaurus-theme/src/theme/Admonition/Type/Danger.tsx
  packages/docusaurus-theme/src/theme/Admonition/Type/Info.tsx
  packages/docusaurus-theme/src/theme/Admonition/Type/Note.tsx
  packages/docusaurus-theme/src/theme/Admonition/Type/Tip.tsx
  packages/docusaurus-theme/src/theme/Admonition/Type/Warning.tsx
  packages/docusaurus-theme/src/theme/DocItem/Content/index.tsx
  packages/docusaurus-theme/src/theme/Footer/index.tsx
  packages/docusaurus-theme/src/theme/MDXComponents/A.tsx
  packages/docusaurus-theme/src/theme/MDXComponents/Code.tsx
  packages/docusaurus-theme/src/theme/MDXComponents/Heading.tsx
  packages/docusaurus-theme/src/theme/MDXContent/index.tsx
  packages/docusaurus-theme/src/theme/Root.styles.ts
  packages/docusaurus-theme/src/theme/Root.tsx
  packages/website/docs/01_guidelines/testing/introduction.mdx
  packages/website/docs/01_guidelines/testing/recommendations.mdx
Labels: skip-changelog, New EUI site

#7870 [FIX] prevent errors around fewer/more hooks in Storybook
  packages/eui/.storybook/addons/code-snippet/decorators/utils.ts
Labels: documentation, skip-changelog

#7874 [FIX] Prevent Storybook code-snippet errors crashing the story preview
  packages/eui/.storybook/addons/code-snippet/components/panel.tsx
  packages/eui/.storybook/addons/code-snippet/constants.ts
  packages/eui/.storybook/addons/code-snippet/decorators/jsx_decorator.tsx
  packages/eui/.storybook/addons/code-snippet/types.ts
Labels: documentation, skip-changelog

#7868 Updated Figma instructions in PR template
  .github/pull_request_template.md
Labels: skip-changelog

#7878 feat: add search to the new documentation website
  packages/docusaurus-theme/src/theme/MDXContent/index.tsx
  packages/website/README.md
  packages/website/docusaurus.config.ts
  packages/website/package.json
  yarn.lock
Labels: skip-changelog

#7885 [EUI+] Implement Breadcrumbs design changes
  packages/docusaurus-theme/src/theme/DocBreadcrumbs/Items/Home/index.tsx
  packages/docusaurus-theme/src/theme/DocBreadcrumbs/Items/item.styles.ts
  packages/docusaurus-theme/src/theme/DocBreadcrumbs/index.tsx
  packages/docusaurus-theme/src/theme/DocItem/Layout/index.tsx
  packages/docusaurus-theme/src/theme/DocItem/index.tsx
  packages/docusaurus-theme/src/theme/DocRoot/Layout/Main/index.tsx
  packages/docusaurus-theme/src/theme/DocRoot/Layout/Sidebar/ExpandButton/index.tsx
  packages/docusaurus-theme/src/theme/DocRoot/Layout/Sidebar/index.tsx
  packages/docusaurus-theme/src/theme/DocRoot/Layout/index.tsx
  packages/docusaurus-theme/src/theme/DocRoot/index.tsx
  packages/docusaurus-theme/src/theme/DocVersionBadge/index.tsx
  packages/docusaurus-theme/src/theme/DocVersionBanner/index.tsx
  packages/docusaurus-theme/src/theme/DocVersionRoot/index.tsx
  packages/docusaurus-theme/src/theme/theme.d.ts
Labels: skip-changelog, EUI Plus, New EUI site

#7887 Updated yearDropdownItemNumber prop description
  packages/eui/src/components/date_picker/react-datepicker/src/index.d.ts
Labels: skip-changelog

#7884 feat: add interactive demo component to the new website
  packages/docusaurus-theme/package.json
  packages/docusaurus-theme/src/components/codesandbox_icon/codesandbox_icon.tsx
  packages/docusaurus-theme/src/components/codesandbox_icon/index.ts
  packages/docusaurus-theme/src/components/demo/actions_bar/actions_bar.tsx
  packages/docusaurus-theme/src/components/demo/actions_bar/index.ts
  packages/docusaurus-theme/src/components/demo/context.ts
  packages/docusaurus-theme/src/components/demo/demo.tsx
  packages/docusaurus-theme/src/components/demo/editor/editor.tsx
  packages/docusaurus-theme/src/components/demo/editor/index.ts
  packages/docusaurus-theme/src/components/demo/index.ts
  packages/docusaurus-theme/src/components/demo/preview/index.ts
  packages/docusaurus-theme/src/components/demo/preview/preview.tsx
  packages/docusaurus-theme/src/components/demo/scope.ts
  packages/docusaurus-theme/src/components/demo/source/get_source_from_children.ts
  packages/docusaurus-theme/src/components/demo/source/index.ts
  packages/docusaurus-theme/src/components/demo/source/source.tsx
  packages/docusaurus-theme/src/theme/MDXComponents/index.ts
  packages/docusaurus-theme/src/theme/Root.styles.ts
  packages/website/docs/02_components/navigation/button/overview.mdx
  yarn.lock
Labels: skip-changelog

#7892 fix: patch `@types/jsdom` to work with TypeScript 4.x
  .yarn/patches/@types-jsdom-npm-20.0.1-5bb899e006.patch
  package.json
  yarn.lock
Labels: skip-changelog

#7891 [BUILD] Support dependency hoisting
  .yarnrc.yml
  packages/eui/package.json
Labels: skip-changelog

#7894 feat: add code transformer to `<Demo>` component
  packages/docusaurus-theme/src/components/demo/code_transformer.ts
  packages/docusaurus-theme/src/components/demo/demo.tsx
  packages/docusaurus-theme/src/components/demo/editor/editor.tsx
  packages/docusaurus-theme/src/components/demo/preview/preview.tsx
  packages/docusaurus-theme/src/components/demo/scope.ts
  packages/website/docs/02_components/navigation/button/overview.mdx
Labels: skip-changelog

#7880 [EUI+] Implement sidebar style changes
  packages/docusaurus-theme/src/components/call_out/index.tsx
  packages/docusaurus-theme/src/theme/DocItem/Layout/index.tsx
  packages/docusaurus-theme/src/theme/DocRoot/Layout/Main/index.tsx
  packages/docusaurus-theme/src/theme/DocRoot/Layout/Sidebar/ExpandButton/index.tsx
  packages/docusaurus-theme/src/theme/DocRoot/Layout/Sidebar/index.tsx
  packages/docusaurus-theme/src/theme/DocRoot/Layout/index.tsx
  packages/docusaurus-theme/src/theme/DocRoot/index.tsx
  packages/docusaurus-theme/src/theme/DocSidebarItem/Category/index.tsx
  packages/docusaurus-theme/src/theme/DocSidebarItem/Link/index.tsx
  packages/docusaurus-theme/src/theme/DocSidebarItem/index.tsx
  packages/docusaurus-theme/src/theme/DocSidebarItems/index.tsx
  packages/docusaurus-theme/src/theme/DocVersionBadge/index.tsx
  packages/docusaurus-theme/src/theme/DocVersionBanner/index.tsx
  packages/docusaurus-theme/src/theme/DocVersionRoot/index.tsx
  packages/docusaurus-theme/src/theme/Navbar/MobileSidebar/Layout/index.tsx
  packages/docusaurus-theme/src/theme/NavbarItem/DropdownNavbarItem/index.tsx
  packages/docusaurus-theme/src/theme/Root.styles.ts
  packages/docusaurus-theme/src/theme/Root.tsx
  packages/docusaurus-theme/src/theme/TOCCollapsible/CollapseButton/index.tsx
  packages/docusaurus-theme/src/theme/TOCItems/Tree.tsx
  packages/docusaurus-theme/src/theme/theme.d.ts
Labels: skip-changelog, EUI Plus, New EUI site

#7902 [Docs] Update release docs
  wiki/eui-team-processes/releasing-versions.md
  wiki/eui-team-processes/upgrading-kibana.md
Labels: skip-changelog

#7889 [EUI+] Implement site header design changes
  packages/docusaurus-theme/src/components/navbar_item/index.tsx
  packages/docusaurus-theme/src/theme/ColorModeToggle/index.tsx
  packages/docusaurus-theme/src/theme/Logo/index.tsx
  packages/docusaurus-theme/src/theme/Navbar/Content/index.tsx
  packages/docusaurus-theme/src/theme/Navbar/Layout/index.tsx
  packages/docusaurus-theme/src/theme/Navbar/MobileSidebar/Header/index.tsx
  packages/docusaurus-theme/src/theme/NavbarItem/NavbarNavLink.tsx
  packages/docusaurus-theme/src/theme/Root.styles.ts
  packages/docusaurus-theme/src/theme/theme.d.ts
  packages/website/docusaurus.config.ts
Labels: skip-changelog

#7901 [Docs] Fix EuiFormControlLayoutDelimited examples with broken input styles
  packages/eui/src-docs/src/views/form_controls/form_control_layout_range.tsx
Labels: documentation, skip-changelog

#7904 [EuiSuperDatePicker] Convert form control styles to Emotion
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiSuperDatePicker_EuiSuperDatePicker_Custom_Quick_Select_Panel.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiSuperDatePicker_EuiSuperDatePicker_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiSuperDatePicker_EuiSuperDatePicker_Custom_Quick_Select_Panel.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiSuperDatePicker_EuiSuperDatePicker_Playground.png
  packages/eui/changelogs/upcoming/7904.md
  packages/eui/src/components/date_picker/super_date_picker/__snapshots__/super_date_picker.test.tsx.snap
  packages/eui/src/components/date_picker/super_date_picker/_index.scss
  packages/eui/src/components/date_picker/super_date_picker/_mixins.scss
  packages/eui/src/components/date_picker/super_date_picker/_super_date_picker.scss
  packages/eui/src/components/date_picker/super_date_picker/_variables.scss
  packages/eui/src/components/date_picker/super_date_picker/date_popover/__snapshots__/date_popover_button.test.tsx.snap
  packages/eui/src/components/date_picker/super_date_picker/date_popover/_date_popover_button.scss
  packages/eui/src/components/date_picker/super_date_picker/date_popover/_index.scss
  packages/eui/src/components/date_picker/super_date_picker/date_popover/date_popover_button.styles.ts
  packages/eui/src/components/date_picker/super_date_picker/date_popover/date_popover_button.test.tsx
  packages/eui/src/components/date_picker/super_date_picker/date_popover/date_popover_button.tsx
  packages/eui/src/components/date_picker/super_date_picker/super_date_picker.styles.ts
  packages/eui/src/components/date_picker/super_date_picker/super_date_picker.test.tsx
  packages/eui/src/components/date_picker/super_date_picker/super_date_picker.tsx
Labels: emotion

#7910 [EuiIcon] Run `yarn compile-icons`
  packages/eui/src/components/icon/__snapshots__/icon.test.tsx.snap
  packages/eui/src/components/icon/assets/anomaly_chart.tsx
  packages/eui/src/components/icon/assets/change_point_detection.tsx
  packages/eui/src/components/icon/assets/field_statistics.tsx
  packages/eui/src/components/icon/assets/single_metric_viewer.tsx
Labels: skip-changelog, tech debt

#7908 [EuiSuperDatePicker] Convert date popover styles to Emotion
  packages/eui/changelogs/upcoming/7908.md
  packages/eui/src/components/date_picker/super_date_picker/_index.scss
  packages/eui/src/components/date_picker/super_date_picker/date_popover/_absolute_tab.scss
  packages/eui/src/components/date_picker/super_date_picker/date_popover/_date_popover_content.scss
  packages/eui/src/components/date_picker/super_date_picker/date_popover/_index.scss
  packages/eui/src/components/date_picker/super_date_picker/date_popover/absolute_tab.styles.ts
  packages/eui/src/components/date_picker/super_date_picker/date_popover/absolute_tab.tsx
  packages/eui/src/components/date_picker/super_date_picker/date_popover/date_popover_content.styles.ts
  packages/eui/src/components/date_picker/super_date_picker/date_popover/date_popover_content.tsx
  packages/eui/src/components/date_picker/super_date_picker/date_popover/relative_tab.tsx
Labels: emotion

#7911 [EuiSuperDatePicker] Emotion conversion button fixes
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiSuperDatePicker_EuiSuperDatePicker_Custom_Quick_Select_Panel.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiSuperDatePicker_EuiSuperDatePicker_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiSuperDatePicker_EuiSuperDatePicker_Custom_Quick_Select_Panel.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiSuperDatePicker_EuiSuperDatePicker_Playground.png
  packages/eui/src/components/date_picker/super_date_picker/date_popover/date_popover_button.styles.ts
  packages/eui/src/components/date_picker/super_date_picker/super_date_picker.styles.ts
Labels: skip-changelog

#7914 New pipeline
  .buildkite/pipelines/pipeline_eui_usage_analytics.yml
  catalog-info.yaml
Labels: skip-changelog

#7915 Added missing details to new analytics pipeline
  catalog-info.yaml
Labels: skip-changelog

#7896 [Patterns] Migrate Help content, Pre GA badges, and Confirmation prompt patterns to EUI
  packages/website/docs/patterns/beta_badges.png
  packages/website/docs/patterns/confirmation_prompts.mdx
  packages/website/docs/patterns/help_content.mdx
  packages/website/docs/patterns/pre_ga_badges.mdx
Labels: documentation, skip-changelog, New EUI site, Pattern

#7890 [New site] Content section
  packages/website/docs/content/accessibility.mdx
  packages/website/docs/content/adapt-tone.mdx
  packages/website/docs/content/inclusivity.mdx
  packages/website/docs/content/language.mdx
  packages/website/docs/content/overview.mdx
  packages/website/docs/content/style.mdx
  packages/website/docs/content/word-choice.mdx
  packages/website/docusaurus.config.ts
  packages/website/sidebars.ts
Labels: documentation, skip-changelog, New EUI site

#7913 [EUI+] Add version switcher
  packages/docusaurus-theme/src/components/version_switcher/index.tsx
  packages/docusaurus-theme/src/theme/Navbar/Content/index.tsx
  packages/docusaurus-theme/src/theme/Navbar/Layout/index.tsx
  packages/docusaurus-theme/src/theme/Navbar/MobileSidebar/Header/index.tsx
  packages/docusaurus-theme/src/theme/Navbar/MobileSidebar/Layout/index.tsx
  packages/docusaurus-theme/src/theme/Root.tsx
  packages/docusaurus-theme/src/theme/theme.d.ts
  packages/website/static/versions.json
Labels: skip-changelog

#7917 Upgrade Node version to v20.15.1
  .buildkite/scripts/lifecycle/pre_command.sh
  .nvmrc
  packages/eui/package.json
  packages/eui/scripts/docker-ci/Dockerfile
Labels: skip-changelog, tech debt

#7907 feat: Add support for simplified interactive demo syntax using code blocks
  .yarn/patches/react-live-npm-4.1.7-7b41625faa.patch
  packages/docusaurus-theme/package.json
  packages/docusaurus-theme/src/components/demo/context.ts
  packages/docusaurus-theme/src/components/demo/demo.tsx
  packages/docusaurus-theme/src/components/demo/editor/editor.tsx
  packages/docusaurus-theme/src/components/demo/preview/preview.tsx
  packages/docusaurus-theme/src/components/demo/scope.ts
  packages/docusaurus-theme/src/components/demo/source/get_source_from_children.ts
  packages/docusaurus-theme/src/theme/CodeBlock/index.tsx
  packages/docusaurus-theme/src/theme/MDXComponents/Code.tsx
  packages/docusaurus-theme/src/theme/theme.d.ts
  packages/website/docs/02_components/navigation/button/overview.mdx
  yarn.lock
Labels: skip-changelog

#7925 build: unify website dependencies
  packages/docusaurus-theme/package.json
  packages/website/package.json
  yarn.lock
Labels: skip-changelog

#7909 [EuiSuperDatePicker] Convert quick select styles to Emotion
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiRefreshInterval_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiSuperDatePicker_EuiSuperDatePicker_Custom_Quick_Select_Panel.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiSuperDatePicker_EuiSuperDatePicker_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiRefreshInterval_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiSuperDatePicker_EuiSuperDatePicker_Custom_Quick_Select_Panel.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiSuperDatePicker_EuiSuperDatePicker_Playground.png
  packages/eui/changelogs/upcoming/7909.md
  packages/eui/src/components/date_picker/_index.scss
  packages/eui/src/components/date_picker/auto_refresh/refresh_interval.tsx
  packages/eui/src/components/date_picker/super_date_picker/__snapshots__/super_date_picker.test.tsx.snap
  packages/eui/src/components/date_picker/super_date_picker/_index.scss
  packages/eui/src/components/date_picker/super_date_picker/quick_select_popover/__snapshots__/quick_select.test.tsx.snap
  packages/eui/src/components/date_picker/super_date_picker/quick_select_popover/__snapshots__/quick_select_popover.test.tsx.snap
  packages/eui/src/components/date_picker/super_date_picker/quick_select_popover/_index.scss
  packages/eui/src/components/date_picker/super_date_picker/quick_select_popover/_quick_select.scss
  packages/eui/src/components/date_picker/super_date_picker/quick_select_popover/_quick_select_popover.scss
  packages/eui/src/components/date_picker/super_date_picker/quick_select_popover/_refresh_interval.scss
  packages/eui/src/components/date_picker/super_date_picker/quick_select_popover/commonly_used_time_ranges.tsx
  packages/eui/src/components/date_picker/super_date_picker/quick_select_popover/quick_select.test.tsx
  packages/eui/src/components/date_picker/super_date_picker/quick_select_popover/quick_select.tsx
  packages/eui/src/components/date_picker/super_date_picker/quick_select_popover/quick_select_panel.styles.ts
  packages/eui/src/components/date_picker/super_date_picker/quick_select_popover/quick_select_panel.tsx
  packages/eui/src/components/date_picker/super_date_picker/quick_select_popover/quick_select_popover.styles.ts
  packages/eui/src/components/date_picker/super_date_picker/quick_select_popover/quick_select_popover.test.tsx
  packages/eui/src/components/date_picker/super_date_picker/quick_select_popover/quick_select_popover.tsx
  packages/eui/src/components/date_picker/super_date_picker/quick_select_popover/recently_used.tsx
  packages/eui/src/components/date_picker/super_date_picker/super_date_picker.a11y.tsx
Labels: emotion

#7929 [Docs] Fix EuiMarkdownEditor plugin example polluting other examples
  packages/eui/src-docs/src/views/markdown_editor/markdown_link_validation.js
  packages/eui/src-docs/src/views/markdown_editor/markdown_plugin_example.js
Labels: documentation, skip-changelog

#7927 feat: add JSON docgen generator to feed docusaurus website with accurate prop definitions
  packages/docusaurus-theme/package.json
  packages/docusaurus-theme/src/components/prop_table/index.ts
  packages/docusaurus-theme/src/components/prop_table/prop_table.tsx
  packages/docusaurus-theme/src/theme/MDXComponents/index.ts
  packages/eui-docgen/.gitignore
  packages/eui-docgen/README.md
  packages/eui-docgen/package.json
  packages/eui-docgen/src/filter_prop.ts
  packages/eui-docgen/src/index.ts
  packages/eui-docgen/src/main.ts
  packages/eui-docgen/src/process_component.ts
  packages/eui-docgen/tsconfig.json
  packages/website/docs/docgen_demo.mdx
  packages/website/package.json
  yarn.lock
Labels: skip-changelog

#7932 feat: Add `PropTable` component to EUI docusaurus theme
  .yarn/patches/infima-npm-0.2.0-alpha.43-8d3b77b44d.patch
  package.json
  packages/docusaurus-theme/src/components/prop_table/extended_types.tsx
  packages/docusaurus-theme/src/components/prop_table/extended_types_info.ts
  packages/docusaurus-theme/src/components/prop_table/prop_table.tsx
  packages/docusaurus-theme/src/theme/DocRoot/Layout/index.tsx
  packages/eui-docgen/src/process_component.ts
  packages/website/README.md
  packages/website/docs/docgen_demo.mdx
  yarn.lock
Labels: skip-changelog

#7933 feat(website): setup google tag manager
  .buildkite/scripts/pipelines/pipeline_deploy_new_docs.sh
  packages/website/docusaurus.config.ts
Labels: skip-changelog

#7936 hotfix: update pixel size values in cypress tests to correct for Chrome 127 text rendering changes
  packages/eui/src/components/combo_box/combo_box.spec.tsx
  packages/eui/src/components/datagrid/body/cell/data_grid_cell_popover.spec.tsx
  packages/eui/src/components/form/range/range.spec.tsx
  packages/eui/src/components/selectable/selectable.spec.tsx
  packages/eui/src/components/text_truncate/text_truncate.spec.tsx
  packages/eui/src/components/text_truncate/utils.spec.tsx
Labels: testing, skip-changelog
