Repository elastic/eui, pull requests merged in 2024-02, with the labels that each got.

#7494 [Emotion] Convert EuiEmptyPrompt
  changelogs/upcoming/7494.md
  src/components/comment_list/comment_event.styles.ts
  src/components/comment_list/comment_event.tsx
  src/components/empty_prompt/__snapshots__/empty_prompt.test.tsx.snap
  src/components/empty_prompt/_empty_prompt.scss
  src/components/empty_prompt/_index.scss
  src/components/empty_prompt/empty_prompt.styles.ts
  src/components/empty_prompt/empty_prompt.test.tsx
  src/components/empty_prompt/empty_prompt.tsx
  src/components/index.scss
  src/components/page_template/empty_prompt/__snapshots__/page_empty_prompt.test.tsx.snap
  src/global_styling/mixins/__snapshots__/_color.test.ts.snap
  src/global_styling/mixins/_color.test.ts
  src/global_styling/mixins/_color.ts
Labels: emotion

#7497 [EuiTourStep] `className` consistency with EuiPopover + performance/cleanups
  changelogs/upcoming/7497.md
  src/components/beacon/__snapshots__/beacon.test.tsx.snap
  src/components/beacon/beacon.tsx
  src/components/tour/__snapshots__/tour_step.test.tsx.snap
  src/components/tour/_tour_footer.styles.ts
  src/components/tour/_tour_footer.tsx
  src/components/tour/_tour_header.styles.ts
  src/components/tour/_tour_header.tsx
  src/components/tour/tour.styles.ts
  src/components/tour/tour_step.test.tsx
  src/components/tour/tour_step.tsx
Labels: breaking change

#7490 [Emotion] Convert EuiSearchBar
  changelogs/upcoming/7490.md
  src/components/index.scss
  src/components/search_bar/__snapshots__/search_bar.test.tsx.snap
  src/components/search_bar/_index.scss
  src/components/search_bar/_search_bar.scss
  src/components/search_bar/search_bar.styles.ts
  src/components/search_bar/search_bar.test.tsx
  src/components/search_bar/search_bar.tsx
Labels: emotion

#7491 [EuiBasicTable][EuiInMemoryTable] Remove deprecated internal `setSelection` class methods
  changelogs/upcoming/7491.md
  src/components/basic_table/basic_table.test.tsx
  src/components/basic_table/basic_table.tsx
  src/components/basic_table/in_memory_table.tsx
Labels: breaking change

#7506 [docs] Fix Colors > Contrast docs page
  src-docs/src/views/theme/color/_contrast_js.tsx
  src-docs/src/views/theme/color/_contrast_sass.tsx
  src-docs/src/views/theme/color/_contrast_slider.tsx
  src-docs/src/views/theme/color/contrast.tsx
  src-docs/src/views/theme/color/tokens.tsx
Labels: documentation, skip-changelog

#7513 [Emotion] Convert EuiTreeView
  changelogs/upcoming/7513.md
  src-docs/src/views/tree_view/playground.js
  src/components/index.scss
  src/components/tree_view/__snapshots__/tree_view.test.tsx.snap
  src/components/tree_view/_index.scss
  src/components/tree_view/_tree_view_item.styles.ts
  src/components/tree_view/_tree_view_item.tsx
  src/components/tree_view/tree_view.a11y.tsx
  src/components/tree_view/tree_view.scss
  src/components/tree_view/tree_view.spec.tsx
  src/components/tree_view/tree_view.stories.tsx
  src/components/tree_view/tree_view.styles.ts
  src/components/tree_view/tree_view.test.tsx
  src/components/tree_view/tree_view.tsx
Labels: emotion

#7511 Upgrade Node version to 20.11.0
  .buildkite/scripts/lifecycle/pre_command.sh
  .nvmrc
  package.json
  scripts/docker-ci/Dockerfile
  src/components/selectable/selectable.spec.tsx
Labels: skip-changelog, tech debt, infrastructure

#7518 [useResizeObserver] Fix initial width and height being 0 in docs example
  src-docs/src/views/resize_observer/resize_observer.js
  src-docs/src/views/resize_observer/resize_observer_hook.js
Labels: documentation, skip-changelog, community contribution

#7521 [Emotion] Convert EuiSideNav
  changelogs/upcoming/7521.md
  src-docs/src/components/guide_page/_guide_page.scss
  src-docs/src/views/app_view.js
  src-docs/src/views/side_nav/props.tsx
  src/components/index.scss
  src/components/page/page_sidebar/page_sidebar.stories.tsx
  src/components/page/page_sidebar/page_sidebar.styles.ts
  src/components/page/page_sidebar/page_sidebar.tsx
  src/components/side_nav/__snapshots__/side_nav.test.tsx.snap
  src/components/side_nav/__snapshots__/side_nav_item.test.tsx.snap
  src/components/side_nav/_index.scss
  src/components/side_nav/_mixins.scss
  src/components/side_nav/_side_nav.scss
  src/components/side_nav/_side_nav_heading.tsx
  src/components/side_nav/_side_nav_item.scss
  src/components/side_nav/_variables.scss
  src/components/side_nav/side_nav.stories.tsx
  src/components/side_nav/side_nav.styles.ts
  src/components/side_nav/side_nav.test.tsx
  src/components/side_nav/side_nav.tsx
  src/components/side_nav/side_nav_item.styles.ts
  src/components/side_nav/side_nav_item.test.tsx
  src/components/side_nav/side_nav_item.tsx
  src/themes/amsterdam/overrides/_index.scss
  src/themes/amsterdam/overrides/_side_nav.scss
Labels: emotion

#7530 [CHORE] Update Tooltip and Popover callouts to info style.
  src-docs/src/views/popover/popover_example.js
  src-docs/src/views/tool_tip/tool_tip_example.js
Labels: documentation, chore, skip-changelog

#7529 [Emotion] Create hook utility for memoizing component styles per-theme
  changelogs/upcoming/7529.md
  src/components/beacon/beacon.tsx
  src/components/code/code.styles.ts
  src/components/code/code.tsx
  src/components/code/code_block.styles.ts
  src/components/code/code_block.tsx
  src/components/code/code_block_controls.styles.ts
  src/components/code/code_block_controls.tsx
  src/components/code/code_block_full_screen.tsx
  src/components/code/code_syntax.styles.ts
  src/services/theme/index.ts
  src/services/theme/provider.tsx
  src/services/theme/style_memoization.test.tsx
  src/services/theme/style_memoization.tsx
Labels: emotion, performance

#7539 Upgrade Node to v20.11.1
  .buildkite/scripts/lifecycle/pre_command.sh
  .nvmrc
  package.json
  scripts/docker-ci/Dockerfile
Labels: skip-changelog, tech debt

#7541 [Emotion][perf] Memoize `EuiButton` styles & mixins
  src/components/button/button_display/_button_display.tsx
  src/components/button/button_empty/button_empty.tsx
  src/components/button/button_group/button_group.styles.ts
  src/components/button/button_group/button_group.tsx
  src/components/button/button_icon/button_icon.styles.ts
  src/components/button/button_icon/button_icon.tsx
  src/themes/amsterdam/global_styling/mixins/__snapshots__/button.test.ts.snap
  src/themes/amsterdam/global_styling/mixins/button.test.ts
  src/themes/amsterdam/global_styling/mixins/button.ts
Labels: skip-changelog, emotion, performance
