Repository elastic/eui, pull requests merged in 2024-08, with the labels that each got.

#7938 [Eui+] Fix docusaurus containerId for local environment
  packages/website/docusaurus.config.ts
Labels: skip-changelog, EUI Plus, New EUI site

#7928 [EUI+] Implement Homepage
  packages/docusaurus-theme/src/theme/Footer/index.tsx
  packages/docusaurus-theme/src/theme/Navbar/Content/index.tsx
  packages/docusaurus-theme/src/theme/Navbar/Layout/index.tsx
  packages/docusaurus-theme/src/theme/NavbarItem/NavbarNavLink.tsx
  packages/docusaurus-theme/src/theme/Root.styles.ts
  packages/website/babel.config.js
  packages/website/package.json
  packages/website/src/components/homepage/header/decor_left.tsx
  packages/website/src/components/homepage/header/decor_right.tsx
  packages/website/src/components/homepage/header/index.tsx
  packages/website/src/components/homepage/highlights/index.tsx
  packages/website/src/components/homepage/layout/Container.tsx
  packages/website/src/components/homepage/layout/Section.tsx
  packages/website/src/components/homepage/layout/index.ts
  packages/website/src/components/homepage/users/index.tsx
  packages/website/src/pages/index.tsx
  packages/website/tsconfig.json
  yarn.lock
Labels: skip-changelog, New EUI site

#7937 [Emotion] Convert EuiDatePicker
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiDatePickerRange_Inline.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiDatePickerRange_Restricted_Selection.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiDatePicker_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiDatePicker_Restricted_Day_Select.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiDatePicker_Time_Select.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiDatePicker_Time_Select_Only.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiDatePickerRange_Inline.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiDatePickerRange_Restricted_Selection.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiDatePicker_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiDatePicker_Restricted_Day_Select.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiDatePicker_Time_Select.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiDatePicker_Time_Select_Only.png
  packages/eui/changelogs/upcoming/7937.md
  packages/eui/src/components/date_picker/__snapshots__/date_picker.test.tsx.snap
  packages/eui/src/components/date_picker/__snapshots__/date_picker_range.test.tsx.snap
  packages/eui/src/components/date_picker/_index.scss
  packages/eui/src/components/date_picker/date_picker.spec.tsx
  packages/eui/src/components/date_picker/date_picker.stories.tsx
  packages/eui/src/components/date_picker/date_picker.styles.ts
  packages/eui/src/components/date_picker/date_picker.test.tsx
  packages/eui/src/components/date_picker/date_picker.tsx
  packages/eui/src/components/date_picker/date_picker_range.stories.tsx
  packages/eui/src/components/date_picker/date_picker_range.styles.ts
  packages/eui/src/components/date_picker/date_picker_range.test.tsx
  packages/eui/src/components/date_picker/react-datepicker/src/calendar.js
  packages/eui/src/components/date_picker/react-datepicker/src/month_dropdown.js
  packages/eui/src/components/date_picker/react-datepicker/src/month_year_dropdown.js
  packages/eui/src/components/date_picker/react-datepicker/src/time.js
  packages/eui/src/components/date_picker/react-datepicker/src/year_dropdown.js
  packages/eui/src/components/date_picker/react-datepicker/src/year_dropdown_options.js
  packages/eui/src/components/date_picker/react_date_picker.styles.ts
  packages/eui/src/components/date_picker/super_date_picker/date_popover/date_popover_content.styles.ts
  packages/eui/src/components/index.scss
  packages/eui/src/themes/amsterdam/global_styling/index.scss
  packages/eui/src/themes/amsterdam/global_styling/react_date_picker/_date_picker.scss
  packages/eui/src/themes/amsterdam/global_styling/react_date_picker/_date_picker_days.scss
  packages/eui/src/themes/amsterdam/global_styling/react_date_picker/_date_picker_month_year.scss
  packages/eui/src/themes/amsterdam/global_styling/react_date_picker/_date_picker_navigation.scss
  packages/eui/src/themes/amsterdam/global_styling/react_date_picker/_date_picker_times.scss
  packages/eui/src/themes/amsterdam/global_styling/react_date_picker/_index.scss
  packages/eui/src/themes/amsterdam/global_styling/react_date_picker/_mixins.scss
  packages/eui/src/themes/amsterdam/global_styling/react_date_picker/_variables.scss
Labels: emotion

#7941 Tweak release script to update both `website`'s and `src-docs`'s versions.json
  packages/eui/scripts/release.js
  packages/eui/scripts/update-versions-log.js
  packages/website/static/versions.json
Labels: skip-changelog, tech debt

#7940 [Emotion] Convert EuiSelectable
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiSelectable_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiSelectable_Subcomponents_EuiSelectableListItem_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiSelectable_Subcomponents_EuiSelectableList_Groups.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiSelectable_Subcomponents_EuiSelectableList_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiSelectable_Subcomponents_EuiSelectableMessage_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiSelectable_With_Search.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiSelectable_With_Tooltip.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiSelectable_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiSelectable_Subcomponents_EuiSelectableListItem_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiSelectable_Subcomponents_EuiSelectableList_Groups.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiSelectable_Subcomponents_EuiSelectableList_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiSelectable_Subcomponents_EuiSelectableMessage_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiSelectable_With_Search.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiSelectable_With_Tooltip.png
  packages/eui/changelogs/upcoming/7940.md
  packages/eui/src/components/selectable/__snapshots__/selectable.test.tsx.snap
  packages/eui/src/components/selectable/_index.scss
  packages/eui/src/components/selectable/_selectable.scss
  packages/eui/src/components/selectable/selectable.stories.tsx
  packages/eui/src/components/selectable/selectable.styles.ts
  packages/eui/src/components/selectable/selectable.test.tsx
  packages/eui/src/components/selectable/selectable.tsx
  packages/eui/src/components/selectable/selectable_list/__snapshots__/selectable_list.test.tsx.snap
  packages/eui/src/components/selectable/selectable_list/__snapshots__/selectable_list_item.test.tsx.snap
  packages/eui/src/components/selectable/selectable_list/_index.scss
  packages/eui/src/components/selectable/selectable_list/_selectable_list.scss
  packages/eui/src/components/selectable/selectable_list/_selectable_list_item.scss
  packages/eui/src/components/selectable/selectable_list/_variables.scss
  packages/eui/src/components/selectable/selectable_list/selectable_list.styles.ts
  packages/eui/src/components/selectable/selectable_list/selectable_list.test.tsx
  packages/eui/src/components/selectable/selectable_list/selectable_list.tsx
  packages/eui/src/components/selectable/selectable_list/selectable_list_item.styles.ts
  packages/eui/src/components/selectable/selectable_list/selectable_list_item.test.tsx
  packages/eui/src/components/selectable/selectable_list/selectable_list_item.tsx
  packages/eui/src/components/selectable/selectable_message/__snapshots__/selectable_message.test.tsx.snap
  packages/eui/src/components/selectable/selectable_message/_index.scss
  packages/eui/src/components/selectable/selectable_message/_selectable_message.scss
  packages/eui/src/components/selectable/selectable_message/selectable_message.styles.ts
  packages/eui/src/components/selectable/selectable_message/selectable_message.test.tsx
  packages/eui/src/components/selectable/selectable_message/selectable_message.tsx
  packages/eui/src/components/selectable/selectable_search/_index.scss
  packages/eui/src/components/selectable/selectable_search/_selectable_search.scss
  packages/eui/src/components/selectable/selectable_search/selectable_search.test.tsx
  packages/eui/src/components/selectable/selectable_templates/__snapshots__/selectable_template_sitewide.test.tsx.snap
  packages/eui/src/services/theme/index.ts
  packages/eui/src/services/theme/style_memoization.test.tsx
  packages/eui/src/services/theme/style_memoization.tsx
Labels: emotion

#7944 [Emotion] Convert EuiSelectableTemplateSitewide
  packages/eui/.loki/reference/chrome_desktop_Templates_EuiSelectableTemplateSitewide_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Templates_EuiSelectableTemplateSitewide_VRT.png
  packages/eui/.loki/reference/chrome_mobile_Templates_EuiSelectableTemplateSitewide_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Templates_EuiSelectableTemplateSitewide_VRT.png
  packages/eui/changelogs/upcoming/7944.md
  packages/eui/src-docs/src/views/selectable/selectable_templates/sitewide_option.tsx
  packages/eui/src/components/index.scss
  packages/eui/src/components/selectable/_index.scss
  packages/eui/src/components/selectable/selectable_templates/__snapshots__/selectable_template_sitewide.test.tsx.snap
  packages/eui/src/components/selectable/selectable_templates/__snapshots__/selectable_template_sitewide_option.test.tsx.snap
  packages/eui/src/components/selectable/selectable_templates/_index.scss
  packages/eui/src/components/selectable/selectable_templates/_selectable_template_sitewide_option.scss
  packages/eui/src/components/selectable/selectable_templates/_variables.scss
  packages/eui/src/components/selectable/selectable_templates/selectable_template_sidewide.stories.tsx
  packages/eui/src/components/selectable/selectable_templates/selectable_template_sitewide.styles.ts
  packages/eui/src/components/selectable/selectable_templates/selectable_template_sitewide.tsx
  packages/eui/src/components/selectable/selectable_templates/selectable_template_sitewide_option.test.tsx
  packages/eui/src/components/selectable/selectable_templates/selectable_template_sitewide_option.tsx
Labels: emotion

#7948 [Emotion][microperf] Separate form max-width variable to its own utility
  packages/eui/src/components/date_picker/super_date_picker/quick_select_popover/quick_select_popover.styles.ts
  packages/eui/src/components/flyout/flyout.styles.ts
  packages/eui/src/components/form/form.styles.ts
  packages/eui/src/components/list_group/list_group.styles.ts
  packages/eui/src/components/popover/input_popover.tsx
  packages/eui/src/components/search_bar/search_bar.styles.ts
Labels: skip-changelog, emotion, performance

#7931 [EUI+] Implement welcome banner
  packages/website/src/components/homepage/banner/index.tsx
  packages/website/src/pages/index.tsx
Labels: skip-changelog, EUI Plus, New EUI site

#7949 feat(website): enable legacy openssl provider
  packages/website/docs/patterns/pre_ga_badges.mdx
  packages/website/package.json
  yarn.lock
Labels: skip-changelog

#7918 [Patterns] Migrate dataviz guidelines pages
  packages/website/docs/data_visualization/dashboard_good_practices.mdx
  packages/website/docs/data_visualization/dependancies_among_charts.gif
  packages/website/docs/data_visualization/elastic_charts_design_system.mdx
  packages/website/docusaurus.config.ts
  packages/website/sidebars.ts
Labels: documentation, skip-changelog, New EUI site

#7923 [Patterns] Tables
  packages/website/docs/patterns/elastic_ai_assistant/_category_.yml
  packages/website/docs/patterns/elastic_ai_assistant/elastic_ai_assistant_chat_ui.mdx
  packages/website/docs/patterns/elastic_ai_assistant/elastic_ai_assistant_insight.mdx
  packages/website/docs/patterns/elastic_ai_assistant/overview.mdx
  packages/website/docs/patterns/error_messages/error_banners.mdx
  packages/website/docs/patterns/error_messages/error_examples.mdx
  packages/website/docs/patterns/error_messages/error_help_users_avoid_errors.mdx
  packages/website/docs/patterns/error_messages/error_pages.mdx
  packages/website/docs/patterns/error_messages/error_validation.mdx
  packages/website/docs/patterns/error_messages/error_warning.mdx
  packages/website/docs/patterns/error_messages/error_writing.mdx
  packages/website/docs/patterns/error_messages/help_users_avoid_errors.mdx
  packages/website/docs/patterns/error_messages/images/error-banner.webp
  packages/website/docs/patterns/error_messages/images/error-page-403.webp
  packages/website/docs/patterns/error_messages/images/error-page-404.webp
  packages/website/docs/patterns/error_messages/images/error-summary.webp
  packages/website/docs/patterns/error_messages/images/error-validation-text.webp
  packages/website/docs/patterns/error_messages/images/error-warning.webp
  packages/website/docs/patterns/error_messages/images/validation-errors.webp
  packages/website/docs/patterns/error_messages/overview.mdx
  packages/website/docs/patterns/overview.mdx
  packages/website/docs/patterns/save_buttons.mdx
  packages/website/docs/patterns/tables/_category_.yml
  packages/website/docs/patterns/tables/table_pagination.mdx
  packages/website/docs/patterns/tables/table_selection.mdx
  packages/website/package.json
Labels: documentation, skip-changelog, Pattern

#7952 [EUI+] update homepage component illustrations
  packages/website/src/components/homepage/highlights/index.tsx
  packages/website/src/components/homepage/highlights/svg/button.svg
  packages/website/src/components/homepage/highlights/svg/callout.svg
  packages/website/src/components/homepage/highlights/svg/card.svg
  packages/website/src/components/homepage/highlights/svg/flex.svg
  packages/website/src/components/homepage/highlights/svg/form.svg
  packages/website/src/components/homepage/highlights/svg/link.svg
  packages/website/src/components/homepage/highlights/svg/panel.svg
  packages/website/src/components/homepage/highlights/svg/spacer.svg
  packages/website/src/components/homepage/highlights/svg/table.svg
  packages/website/src/components/homepage/highlights/svg/text.svg
  packages/website/src/components/homepage/highlights/svg/title.svg
  packages/website/src/components/homepage/highlights/svg/tooltip.svg
Labels: skip-changelog, EUI Plus, New EUI site

#7954 [Emotion] Convert EuiFormLayout (1/3)
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiForm_EuiFormControlLayout_Append_Prepend.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiForm_EuiFormControlLayout_Append_Prepend.png
  packages/eui/changelogs/upcoming/7954.md
  packages/eui/src/components/color_picker/__snapshots__/color_picker.test.tsx.snap
  packages/eui/src/components/color_picker/color_palette_picker/__snapshots__/color_palette_picker.test.tsx.snap
  packages/eui/src/components/combo_box/__snapshots__/combo_box.test.tsx.snap
  packages/eui/src/components/combo_box/combo_box.test.tsx
  packages/eui/src/components/combo_box/combo_box_input/combo_box_input.styles.ts
  packages/eui/src/components/combo_box/combo_box_input/combo_box_input.tsx
  packages/eui/src/components/datagrid/controls/__snapshots__/column_selector.test.tsx.snap
  packages/eui/src/components/date_picker/__snapshots__/date_picker.test.tsx.snap
  packages/eui/src/components/date_picker/__snapshots__/date_picker_range.test.tsx.snap
  packages/eui/src/components/date_picker/auto_refresh/__snapshots__/auto_refresh.test.tsx.snap
  packages/eui/src/components/date_picker/date_picker.spec.tsx
  packages/eui/src/components/date_picker/date_picker.test.tsx
  packages/eui/src/components/date_picker/super_date_picker/__snapshots__/super_date_picker.test.tsx.snap
  packages/eui/src/components/date_picker/super_date_picker/quick_select_popover/__snapshots__/quick_select.test.tsx.snap
  packages/eui/src/components/date_picker/super_date_picker/quick_select_popover/__snapshots__/quick_select_popover.test.tsx.snap
  packages/eui/src/components/form/field_password/__snapshots__/field_password.test.tsx.snap
  packages/eui/src/components/form/field_password/field_password.test.tsx
  packages/eui/src/components/form/form.styles.test.tsx
  packages/eui/src/components/form/form.styles.ts
  packages/eui/src/components/form/form_control_layout/__snapshots__/form_control_layout.test.tsx.snap
  packages/eui/src/components/form/form_control_layout/__snapshots__/form_control_layout_delimited.test.tsx.snap
  packages/eui/src/components/form/form_control_layout/_form_control_layout.scss
  packages/eui/src/components/form/form_control_layout/_form_control_layout_delimited.scss
  packages/eui/src/components/form/form_control_layout/_form_control_layout_icons.scss
  packages/eui/src/components/form/form_control_layout/_index.scss
  packages/eui/src/components/form/form_control_layout/_num_icons.test.ts
  packages/eui/src/components/form/form_control_layout/_num_icons.ts
  packages/eui/src/components/form/form_control_layout/form_control_layout.stories.tsx
  packages/eui/src/components/form/form_control_layout/form_control_layout.styles.ts
  packages/eui/src/components/form/form_control_layout/form_control_layout.test.tsx
  packages/eui/src/components/form/form_control_layout/form_control_layout.tsx
  packages/eui/src/components/form/range/__snapshots__/dual_range.test.tsx.snap
  packages/eui/src/components/form/range/__snapshots__/range.test.tsx.snap
  packages/eui/src/components/form/range/__snapshots__/range_input.test.tsx.snap
  packages/eui/src/components/form/super_select/__snapshots__/super_select.test.tsx.snap
  packages/eui/src/components/form/super_select/__snapshots__/super_select_control.test.tsx.snap
  packages/eui/src/components/form/text_area/__snapshots__/text_area.test.tsx.snap
  packages/eui/src/components/form/text_area/text_area.styles.ts
  packages/eui/src/components/inline_edit/__snapshots__/inline_edit_form.test.tsx.snap
  packages/eui/src/components/search_bar/__snapshots__/search_bar.test.tsx.snap
  packages/eui/src/components/search_bar/__snapshots__/search_box.test.tsx.snap
  packages/eui/src/components/selectable/__snapshots__/selectable.test.tsx.snap
  packages/eui/src/components/selectable/selectable_search/__snapshots__/selectable_search.test.tsx.snap
  packages/eui/src/components/selectable/selectable_templates/__snapshots__/selectable_template_sitewide.test.tsx.snap
  packages/eui/src/themes/amsterdam/overrides/_form_control_layout.scss
  packages/eui/src/themes/amsterdam/overrides/_index.scss
Labels: emotion

#7957 [Emotion] Convert EuiFormControlLayoutDelimited (2/3)
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiDualRange_Input_With_Popover.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiForm_EuiFormControlLayoutDelimited_Kitchen_Sink.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiForm_EuiFormControlLayoutDelimited_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiForm_EuiFormControlLayout_Append_Prepend.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiDualRange_Input_With_Popover.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiForm_EuiFormControlLayoutDelimited_Kitchen_Sink.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiForm_EuiFormControlLayoutDelimited_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiForm_EuiFormControlLayout_Append_Prepend.png
  packages/eui/changelogs/upcoming/7957.md
  packages/eui/src-docs/src/views/form_controls/form_control_layout_range.tsx
  packages/eui/src/components/date_picker/__snapshots__/date_picker.test.tsx.snap
  packages/eui/src/components/date_picker/__snapshots__/date_picker_range.test.tsx.snap
  packages/eui/src/components/date_picker/date_picker.spec.tsx
  packages/eui/src/components/date_picker/date_picker.styles.ts
  packages/eui/src/components/date_picker/date_picker.tsx
  packages/eui/src/components/date_picker/date_picker_range.styles.ts
  packages/eui/src/components/date_picker/date_picker_range.tsx
  packages/eui/src/components/date_picker/super_date_picker/__snapshots__/super_date_picker.test.tsx.snap
  packages/eui/src/components/date_picker/super_date_picker/super_date_picker.styles.ts
  packages/eui/src/components/form/field_number/field_number.styles.ts
  packages/eui/src/components/form/form.styles.test.tsx
  packages/eui/src/components/form/form.styles.ts
  packages/eui/src/components/form/form_control_layout/__snapshots__/form_control_layout_delimited.test.tsx.snap
  packages/eui/src/components/form/form_control_layout/_form_control_layout_delimited.scss
  packages/eui/src/components/form/form_control_layout/_index.scss
  packages/eui/src/components/form/form_control_layout/form_control_layout.styles.ts
  packages/eui/src/components/form/form_control_layout/form_control_layout.test.tsx
  packages/eui/src/components/form/form_control_layout/form_control_layout.tsx
  packages/eui/src/components/form/form_control_layout/form_control_layout_delimited.stories.tsx
  packages/eui/src/components/form/form_control_layout/form_control_layout_delimited.styles.ts
  packages/eui/src/components/form/form_control_layout/form_control_layout_delimited.test.tsx
  packages/eui/src/components/form/form_control_layout/form_control_layout_delimited.tsx
  packages/eui/src/components/form/range/range_input.styles.ts
  packages/eui/src/services/emotion/clone_element.test.tsx
  packages/eui/src/services/emotion/clone_element.tsx
  packages/eui/src/themes/amsterdam/overrides/_form_control_layout_delimited.scss
  packages/eui/src/themes/amsterdam/overrides/_index.scss
Labels: emotion

#7959 [Emotion] Convert EuiFormLayoutControl icons (3/3)
  packages/eui/changelogs/upcoming/7959.md
  packages/eui/src/components/color_picker/__snapshots__/color_picker.test.tsx.snap
  packages/eui/src/components/color_picker/color_palette_picker/__snapshots__/color_palette_picker.test.tsx.snap
  packages/eui/src/components/combo_box/__snapshots__/combo_box.test.tsx.snap
  packages/eui/src/components/combo_box/combo_box_input/combo_box_input.tsx
  packages/eui/src/components/date_picker/__snapshots__/date_picker.test.tsx.snap
  packages/eui/src/components/date_picker/__snapshots__/date_picker_range.test.tsx.snap
  packages/eui/src/components/date_picker/date_picker.spec.tsx
  packages/eui/src/components/date_picker/super_date_picker/__snapshots__/super_date_picker.test.tsx.snap
  packages/eui/src/components/date_picker/super_date_picker/quick_select_popover/__snapshots__/quick_select.test.tsx.snap
  packages/eui/src/components/date_picker/super_date_picker/quick_select_popover/__snapshots__/quick_select_popover.test.tsx.snap
  packages/eui/src/components/date_picker/super_date_picker/super_date_picker.tsx
  packages/eui/src/components/form/_index.scss
  packages/eui/src/components/form/field_number/field_number.tsx
  packages/eui/src/components/form/field_password/__snapshots__/field_password.test.tsx.snap
  packages/eui/src/components/form/field_password/field_password.tsx
  packages/eui/src/components/form/field_search/field_search.tsx
  packages/eui/src/components/form/field_text/field_text.tsx
  packages/eui/src/components/form/form_control_layout/__snapshots__/form_control_layout.test.tsx.snap
  packages/eui/src/components/form/form_control_layout/__snapshots__/form_control_layout_clear_button.test.tsx.snap
  packages/eui/src/components/form/form_control_layout/__snapshots__/form_control_layout_custom_icon.test.tsx.snap
  packages/eui/src/components/form/form_control_layout/_form_control_layout_clear_button.scss
  packages/eui/src/components/form/form_control_layout/_form_control_layout_custom_icon.scss
  packages/eui/src/components/form/form_control_layout/_form_control_layout_icons.scss
  packages/eui/src/components/form/form_control_layout/_index.scss
  packages/eui/src/components/form/form_control_layout/form_control_layout.stories.tsx
  packages/eui/src/components/form/form_control_layout/form_control_layout.tsx
  packages/eui/src/components/form/form_control_layout/form_control_layout_clear_button.styles.ts
  packages/eui/src/components/form/form_control_layout/form_control_layout_clear_button.test.tsx
  packages/eui/src/components/form/form_control_layout/form_control_layout_clear_button.tsx
  packages/eui/src/components/form/form_control_layout/form_control_layout_custom_icon.test.tsx
  packages/eui/src/components/form/form_control_layout/form_control_layout_custom_icon.tsx
  packages/eui/src/components/form/form_control_layout/form_control_layout_icons.styles.ts
  packages/eui/src/components/form/form_control_layout/form_control_layout_icons.tsx
  packages/eui/src/components/form/range/__snapshots__/dual_range.test.tsx.snap
  packages/eui/src/components/form/range/__snapshots__/range.test.tsx.snap
  packages/eui/src/components/form/super_select/__snapshots__/super_select.test.tsx.snap
  packages/eui/src/components/form/super_select/__snapshots__/super_select_control.test.tsx.snap
  packages/eui/src/components/form/text_area/text_area.tsx
  packages/eui/src/components/inline_edit/__snapshots__/inline_edit_form.test.tsx.snap
  packages/eui/src/components/search_bar/__snapshots__/search_bar.test.tsx.snap
  packages/eui/src/components/search_bar/__snapshots__/search_box.test.tsx.snap
  packages/eui/src/components/selectable/__snapshots__/selectable.test.tsx.snap
  packages/eui/src/components/selectable/selectable_search/__snapshots__/selectable_search.test.tsx.snap
  packages/eui/src/components/selectable/selectable_templates/__snapshots__/selectable_template_sitewide.test.tsx.snap
  packages/eui/src/global_styling/mixins/_form.scss
Labels: emotion

#7964 [Emotion] Convert EuiDescribedFormGroup
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiForm_EuiDescribedFormGroup_Implicit_Titles.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiForm_EuiDescribedFormGroup_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiForm_EuiDescribedFormGroup_Implicit_Titles.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiForm_EuiDescribedFormGroup_Playground.png
  packages/eui/changelogs/upcoming/7964.md
  packages/eui/src/components/form/_index.scss
  packages/eui/src/components/form/described_form_group/__snapshots__/described_form_group.test.tsx.snap
  packages/eui/src/components/form/described_form_group/_described_form_group.scss
  packages/eui/src/components/form/described_form_group/_index.scss
  packages/eui/src/components/form/described_form_group/described_form_group.stories.tsx
  packages/eui/src/components/form/described_form_group/described_form_group.styles.ts
  packages/eui/src/components/form/described_form_group/described_form_group.test.tsx
  packages/eui/src/components/form/described_form_group/described_form_group.tsx
Labels: emotion

#7967 [Emotion] Convert EuiFormLabel and EuiFormLegend
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiForm_Error.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiForm_EuiDescribedFormGroup_Implicit_Titles.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiForm_EuiDescribedFormGroup_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiForm_EuiFormControlLayoutDelimited_Kitchen_Sink.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiForm_EuiFormControlLayout_Append_Prepend.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiForm_EuiFormFieldset_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiForm_EuiFormFieldset_Subcomponents_EuiFormLegend_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiForm_EuiFormRow_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiForm_EuiFormRow_Subcomponents_EuiFormLabel_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiForm_Error.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiForm_EuiDescribedFormGroup_Implicit_Titles.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiForm_EuiDescribedFormGroup_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiForm_EuiFormControlLayoutDelimited_Kitchen_Sink.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiForm_EuiFormControlLayout_Append_Prepend.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiForm_EuiFormFieldset_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiForm_EuiFormFieldset_Subcomponents_EuiFormLegend_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiForm_EuiFormRow_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiForm_EuiFormRow_Subcomponents_EuiFormLabel_Playground.png
  packages/eui/changelogs/upcoming/7967.md
  packages/eui/src/components/color_picker/__snapshots__/color_picker.test.tsx.snap
  packages/eui/src/components/date_picker/super_date_picker/quick_select_popover/__snapshots__/quick_select_popover.test.tsx.snap
  packages/eui/src/components/form/_index.scss
  packages/eui/src/components/form/checkbox/__snapshots__/checkbox_group.test.tsx.snap
  packages/eui/src/components/form/described_form_group/__snapshots__/described_form_group.test.tsx.snap
  packages/eui/src/components/form/field_password/__snapshots__/field_password.test.tsx.snap
  packages/eui/src/components/form/form_control_layout/__snapshots__/form_control_layout.test.tsx.snap
  packages/eui/src/components/form/form_control_layout/form_control_layout.styles.ts
  packages/eui/src/components/form/form_fieldset/__snapshots__/form_fieldset.test.tsx.snap
  packages/eui/src/components/form/form_fieldset/__snapshots__/form_legend.test.tsx.snap
  packages/eui/src/components/form/form_fieldset/_form_legend.scss
  packages/eui/src/components/form/form_fieldset/_index.scss
  packages/eui/src/components/form/form_fieldset/form_legend.styles.ts
  packages/eui/src/components/form/form_fieldset/form_legend.tsx
  packages/eui/src/components/form/form_label/__snapshots__/form_label.test.tsx.snap
  packages/eui/src/components/form/form_label/_form_label.scss
  packages/eui/src/components/form/form_label/_index.scss
  packages/eui/src/components/form/form_label/form_label.styles.ts
  packages/eui/src/components/form/form_label/form_label.tsx
  packages/eui/src/components/form/form_row/__snapshots__/form_row.test.tsx.snap
  packages/eui/src/components/form/form_row/form_row.test.tsx
  packages/eui/src/components/form/radio/__snapshots__/radio_group.test.tsx.snap
  packages/eui/src/components/form/super_select/__snapshots__/super_select.test.tsx.snap
  packages/eui/src/components/inline_edit/__snapshots__/inline_edit_form.test.tsx.snap
  packages/eui/src/components/key_pad_menu/__snapshots__/key_pad_menu.test.tsx.snap
  packages/eui/src/global_styling/mixins/_form.scss
Labels: emotion

#7972 Update renovate.json
  renovate.json
Labels: dependencies, skip-changelog, tech debt

#7968 [Emotion] Convert EuiFormRow
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiForm_EuiFormRow_Column_Layout.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiForm_EuiFormRow_Inline_Layout.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiForm_EuiFormRow_Column_Layout.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiForm_EuiFormRow_Inline_Layout.png
  packages/eui/changelogs/upcoming/7968.md
  packages/eui/src-docs/src/views/color_picker/color_palette_display.js
  packages/eui/src-docs/src/views/datagrid/toolbar/visibility.js
  packages/eui/src-docs/src/views/form_compressed/form_compressed.js
  packages/eui/src-docs/src/views/form_compressed/form_compressed_example.js
  packages/eui/src-docs/src/views/form_compressed/form_horizontal.js
  packages/eui/src-docs/src/views/selection_controls/switch_label.tsx
  packages/eui/src/components/form/_index.scss
  packages/eui/src/components/form/described_form_group/__snapshots__/described_form_group.test.tsx.snap
  packages/eui/src/components/form/form_control_layout/form_control_layout.styles.ts
  packages/eui/src/components/form/form_row/__snapshots__/form_row.test.tsx.snap
  packages/eui/src/components/form/form_row/_form_row.scss
  packages/eui/src/components/form/form_row/_index.scss
  packages/eui/src/components/form/form_row/form_row.stories.tsx
  packages/eui/src/components/form/form_row/form_row.styles.ts
  packages/eui/src/components/form/form_row/form_row.test.tsx
  packages/eui/src/components/form/form_row/form_row.tsx
  packages/eui/src/components/inline_edit/__snapshots__/inline_edit_form.test.tsx.snap
Labels: emotion

#7973 Revert "Update renovate.json"
  renovate.json
Labels: skip-changelog

#7969 [Emotion] Convert EuiCheckbox, EuiRadio, and EuiSwitch
  packages/eui/.loki/reference/chrome_desktop_Editors_Syntax_EuiMarkdownFormat_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiCheckboxGroup_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiCheckbox_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiRadioGroup_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiRadio_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiSwitch_Kitchen_Sink.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiSwitch_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Editors_Syntax_EuiMarkdownFormat_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiCheckboxGroup_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiCheckbox_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiRadioGroup_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiRadio_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiSwitch_Kitchen_Sink.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiSwitch_Playground.png
  packages/eui/changelogs/upcoming/7969.md
  packages/eui/src-docs/src/views/selection_controls/checkbox.js
  packages/eui/src/components/basic_table/__snapshots__/basic_table.test.tsx.snap
  packages/eui/src/components/basic_table/__snapshots__/in_memory_table.test.tsx.snap
  packages/eui/src/components/card/checkable_card/__snapshots__/checkable_card.test.tsx.snap
  packages/eui/src/components/datagrid/controls/__snapshots__/column_selector.test.tsx.snap
  packages/eui/src/components/datagrid/controls/_data_grid_toolbar.scss
  packages/eui/src/components/datagrid/controls/column_selector.tsx
  packages/eui/src/components/datagrid/data_grid.a11y.tsx
  packages/eui/src/components/date_picker/super_date_picker/quick_select_popover/__snapshots__/quick_select_popover.test.tsx.snap
  packages/eui/src/components/form/_index.scss
  packages/eui/src/components/form/checkbox/__snapshots__/checkbox.test.tsx.snap
  packages/eui/src/components/form/checkbox/_checkbox.scss
  packages/eui/src/components/form/checkbox/_index.scss
  packages/eui/src/components/form/checkbox/checkbox.styles.ts
  packages/eui/src/components/form/checkbox/checkbox.test.tsx
  packages/eui/src/components/form/checkbox/checkbox.tsx
  packages/eui/src/components/form/checkbox/checkbox_group.stories.tsx
  packages/eui/src/components/form/form.styles.test.tsx
  packages/eui/src/components/form/form.styles.ts
  packages/eui/src/components/form/radio/__snapshots__/radio.test.tsx.snap
  packages/eui/src/components/form/radio/__snapshots__/radio_group.test.tsx.snap
  packages/eui/src/components/form/radio/_index.scss
  packages/eui/src/components/form/radio/_radio.scss
  packages/eui/src/components/form/radio/radio.styles.ts
  packages/eui/src/components/form/radio/radio.tsx
  packages/eui/src/components/form/range/range.styles.ts
  packages/eui/src/components/form/range/range_slider.styles.ts
  packages/eui/src/components/form/range/range_thumb.styles.ts
  packages/eui/src/components/form/switch/__snapshots__/switch.test.tsx.snap
  packages/eui/src/components/form/switch/_index.scss
  packages/eui/src/components/form/switch/_switch.scss
  packages/eui/src/components/form/switch/switch.stories.tsx
  packages/eui/src/components/form/switch/switch.styles.ts
  packages/eui/src/components/form/switch/switch.tsx
  packages/eui/src/components/index.scss
  packages/eui/src/components/key_pad_menu/__snapshots__/key_pad_menu_item.test.tsx.snap
  packages/eui/src/global_styling/mixins/_form.scss
  packages/eui/src/global_styling/mixins/_icons.scss
  packages/eui/src/global_styling/mixins/_index.scss
  packages/eui/src/global_styling/variables/_form.scss
  packages/eui/src/themes/amsterdam/global_styling/mixins/_index.scss
  packages/eui/src/themes/amsterdam/overrides/_form_controls.scss
  packages/eui/src/themes/amsterdam/overrides/_index.scss
Labels: emotion

#7974 [EuiSwitch] Re-add `pointer-events: none` to switch button children
  packages/eui/src/components/form/switch/switch.styles.ts
Labels: skip-changelog

#7953 ci: setup buildkite test analytics for cypress and jest tests
  .buildkite/scripts/pipelines/pipeline_test.sh
  packages/eui/cypress.config.ts
  packages/eui/package.json
  packages/eui/scripts/jest/config.js
  yarn.lock
Labels: skip-changelog

#7976 Export EuiFormControlLayoutIcons
  packages/eui/src/components/form/form_control_layout/index.ts
Labels: skip-changelog

#7981 Workaround for `:has` CSS selector that nwsapi/jest can't parse
  packages/eui/src/components/form/checkbox/checkbox.styles.ts
  packages/eui/src/components/form/checkbox/checkbox.tsx
  packages/eui/src/components/form/form.styles.test.tsx
  packages/eui/src/components/form/form.styles.ts
  packages/eui/src/components/form/radio/radio.styles.ts
  packages/eui/src/components/form/radio/radio.test.tsx
  packages/eui/src/components/form/radio/radio.tsx
Labels: testing, skip-changelog

#7986 Updated callout example
  packages/eui/src-docs/src/views/call_out/warning.tsx
Labels: documentation, skip-changelog

#7958 [EuiSearchBar] Allow disabling selection auto sort in `field_value_selection` filters
  packages/eui/changelogs/upcoming/7958.md
  packages/eui/src-docs/src/views/search_bar/props_info.js
  packages/eui/src-docs/src/views/search_bar/search_bar_filters.js
  packages/eui/src/components/search_bar/filters/field_value_selection_filter.spec.tsx
  packages/eui/src/components/search_bar/filters/field_value_selection_filter.tsx
  packages/eui/src/components/search_bar/search_bar.stories.tsx
  packages/eui/src/components/search_bar/search_filters.stories.tsx
Labels: community contribution
