Repository elastic/eui, pull requests merged in 2024-04, with the labels that each got.

#7627 [Docs] Update EUIExpression example
  src-docs/src/views/expression/expression.js
Labels: skip-changelog

#7634 [Emotion][perf] Remaining unmemoized button styles
  src/components/button/button_display/_button_display_content.tsx
  src/components/button/button_group/button_group_button.styles.ts
  src/components/button/button_group/button_group_button.tsx
Labels: skip-changelog, tech debt, emotion, performance

#7639 [EuiTextTruncate] Remove beta status in docs
  src-docs/src/views/text_truncate/text_truncate_example.js
Labels: documentation, skip-changelog

#7635 [Emotion][perf] Memoize low-impact components (A-C)
  src/components/accessibility/screen_reader_only/__snapshots__/screen_reader_only.test.tsx.snap
  src/components/accessibility/screen_reader_only/screen_reader_only.styles.ts
  src/components/accessibility/screen_reader_only/screen_reader_only.tsx
  src/components/accessibility/skip_link/__snapshots__/skip_link.test.tsx.snap
  src/components/accessibility/skip_link/skip_link.tsx
  src/components/aspect_ratio/__snapshots__/aspect_ratio.test.tsx.snap
  src/components/aspect_ratio/aspect_ratio.test.tsx
  src/components/aspect_ratio/aspect_ratio.tsx
  src/components/avatar/__snapshots__/avatar.test.tsx.snap
  src/components/avatar/avatar.styles.ts
  src/components/avatar/avatar.test.tsx
  src/components/avatar/avatar.tsx
  src/components/bottom_bar/__snapshots__/bottom_bar.test.tsx.snap
  src/components/bottom_bar/bottom_bar.styles.ts
  src/components/bottom_bar/bottom_bar.test.tsx
  src/components/bottom_bar/bottom_bar.tsx
  src/components/code/code_block_annotations.style.ts
  src/components/code/code_block_annotations.tsx
  src/components/collapsible_nav/collapsible_nav.tsx
  src/components/collapsible_nav/collapsible_nav_group/collapsible_nav_group.tsx
  src/components/collapsible_nav_beta/collapsible_nav_beta.tsx
  src/components/collapsible_nav_beta/collapsible_nav_body_footer.tsx
  src/components/collapsible_nav_beta/collapsible_nav_button/collapsible_nav_button.tsx
  src/components/collapsible_nav_beta/collapsible_nav_group/collapsible_nav_group.tsx
  src/components/collapsible_nav_beta/collapsible_nav_item/collapsed/collapsed_nav_button.tsx
  src/components/collapsible_nav_beta/collapsible_nav_item/collapsed/collapsed_nav_popover.tsx
  src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_accordion.tsx
  src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_group.tsx
  src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_item.tsx
  src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_link.tsx
  src/components/comment_list/comment_event.tsx
  src/components/context_menu/context_menu_item.tsx
  src/components/resizable_container/__snapshots__/resizable_container.test.tsx.snap
  src/components/resizable_container/resizable_collapse_button.tsx
Labels: skip-changelog, tech debt, emotion, performance

#7640 Convert table actions hover UX/behavior
  changelogs/upcoming/7640.md
  src-docs/src/views/tables/actions/actions.tsx
  src/components/basic_table/__snapshots__/basic_table.test.tsx.snap
  src/components/basic_table/__snapshots__/expanded_item_actions.test.tsx.snap
  src/components/basic_table/action_types.ts
  src/components/basic_table/basic_table.styles.ts
  src/components/basic_table/basic_table.test.tsx
  src/components/basic_table/basic_table.tsx
  src/components/basic_table/expanded_item_actions.test.tsx
  src/components/basic_table/expanded_item_actions.tsx
  src/components/table/__snapshots__/table_row_cell.test.tsx.snap
  src/components/table/_responsive.scss
  src/components/table/_table.scss
  src/components/table/table_row.tsx
  src/components/table/table_row_cell.styles.ts
  src/components/table/table_row_cell.test.tsx
  src/components/table/table_row_cell.tsx
Labels: breaking change, emotion

#7641 DRY out new `EuiTableCellContent` internal subcomponent & convert to Emotion
  changelogs/upcoming/7641.md
  src/components/basic_table/__snapshots__/basic_table.test.tsx.snap
  src/components/basic_table/__snapshots__/in_memory_table.test.tsx.snap
  src/components/basic_table/basic_table.test.tsx
  src/components/basic_table/basic_table.tsx
  src/components/basic_table/in_memory_table.test.tsx
  src/components/basic_table/table_types.ts
  src/components/index.scss
  src/components/table/__snapshots__/table.test.tsx.snap
  src/components/table/__snapshots__/table_footer_cell.test.tsx.snap
  src/components/table/__snapshots__/table_header_cell.test.tsx.snap
  src/components/table/__snapshots__/table_row.test.tsx.snap
  src/components/table/__snapshots__/table_row_cell.test.tsx.snap
  src/components/table/_index.scss
  src/components/table/_responsive.scss
  src/components/table/_table.scss
  src/components/table/_table_cell_content.styles.ts
  src/components/table/_table_cell_content.tsx
  src/components/table/table_cells_shared.styles.ts
  src/components/table/table_footer_cell.tsx
  src/components/table/table_header_cell.tsx
  src/components/table/table_row.tsx
  src/components/table/table_row_cell.styles.ts
  src/components/table/table_row_cell.test.tsx
  src/components/table/table_row_cell.tsx
Labels: tech debt, emotion

#7638 [Emotion][perf] Memoize simpler medium-impact components
  src/components/badge/badge.tsx
  src/components/badge/badge_group/badge_group.tsx
  src/components/badge/beta_badge/beta_badge.tsx
  src/components/badge/notification_badge/badge_notification.tsx
  src/components/call_out/call_out.styles.ts
  src/components/call_out/call_out.tsx
  src/components/context_menu/__snapshots__/context_menu.test.tsx.snap
  src/components/context_menu/context_menu.tsx
  src/components/context_menu/context_menu_panel.tsx
  src/components/description_list/description_list.tsx
  src/components/description_list/description_list_description.tsx
  src/components/description_list/description_list_title.tsx
  src/components/empty_prompt/empty_prompt.tsx
  src/components/horizontal_rule/__snapshots__/horizontal_rule.test.tsx.snap
  src/components/horizontal_rule/horizontal_rule.tsx
  src/components/tabs/tab.tsx
  src/components/tabs/tabs.tsx
Labels: skip-changelog, tech debt, emotion, performance

#7649 [Emotion][perf] Memoize loading components
  src/components/loading/__snapshots__/loading_chart.test.tsx.snap
  src/components/loading/loading_chart.styles.ts
  src/components/loading/loading_chart.tsx
  src/components/loading/loading_elastic.styles.ts
  src/components/loading/loading_elastic.tsx
  src/components/loading/loading_logo.styles.ts
  src/components/loading/loading_logo.tsx
  src/components/loading/loading_spinner.stories.tsx
  src/components/loading/loading_spinner.tsx
Labels: skip-changelog, tech debt, emotion, performance

#7650 [EuiSuperSelect] Fix various focus and accessibility issues: The Sequel, Part Two
  changelogs/upcoming/7650.md
  src-docs/src/views/super_select/super_select_basic.js
  src/components/form/super_select/__snapshots__/super_select.test.tsx.snap
  src/components/form/super_select/super_select.spec.tsx
  src/components/form/super_select/super_select.test.tsx
  src/components/form/super_select/super_select.tsx
  src/components/form/super_select/super_select_control.tsx
Labels: accessibility

#7657 [Docs] Add `noindex` and `nofollow` to dev & staging
  src-docs/src/index.js
Labels: documentation, skip-changelog, infrastructure

#7652 CI: configure `eui-release` pipeline to test merged changes and bump package versions
  .buildkite/pipelines/pipeline_release.yml
  .buildkite/scripts/release/step_update_version.sh
Labels: skip-changelog

#7662 ci: automatic npm releases
  .buildkite/pipelines/pipeline_release.yml
  .buildkite/scripts/release/step_build.sh
  .buildkite/scripts/release/step_commit_and_publish.sh
  .buildkite/scripts/release/step_update_version.sh
Labels: skip-changelog

#7665 Remove unused scripts
  scripts/docker-ci/README.md
  wiki/contributing-to-eui/testing/automated-accessibility-testing.md
  wiki/eui-team-processes/upgrading-node.md
Labels: skip-changelog

#7664 Updated node to 20.12.1
  .buildkite/scripts/lifecycle/pre_command.sh
  .nvmrc
  package.json
  scripts/docker-ci/Dockerfile
Labels: skip-changelog

#7648 [Storybook] Add stories for more components (letter P) - Part 1
  .storybook/utils.test.ts
  .storybook/utils.ts
  changelogs/upcoming/7648.md
  src/components/page/page_header/page_header.stories.tsx
  src/components/page/page_header/page_header_content.stories.tsx
  src/components/page_template/outer/page_outer.tsx
  src/components/page_template/page_template.stories.tsx
  src/components/page_template/page_template.tsx
  src/components/pagination/pagination.stories.tsx
  src/components/pagination/pagination_button.stories.tsx
  src/components/pagination/pagination_button_arrow.stories.tsx
  src/components/panel/panel.stories.tsx
Labels: documentation, skip-changelog

#7680 [CHORE]: Bump axe-core to latest v4.9.0
  package.json
  yarn.lock
Labels: chore, skip-changelog, accessibility - automated

#7681 [EuiTableRowCell] Fix `th scope="row"` text alignment
  changelogs/upcoming/7681.md
  src-docs/src/views/tables/auto/auto.tsx
  src/components/table/table_row_cell.styles.ts
Labels: bug

#7678 [BUG] Fix the `EuiRange` prepend prop CSS
  changelogs/upcoming/7678.md
  src/components/form/range/range_wrapper.styles.ts
Labels: bug, skip-changelog

#7691 [ci] Automatically retry flaky Cypress tests
  .buildkite/pipelines/pipeline_pull_request_test.yml
Labels: skip-changelog, infrastructure

#7659 [Storybook] upgrade Storybook to v8
  .browserslistrc
  .storybook/main.ts
  .storybook/preview.tsx
  package.json
  src/components/selectable/selectable_templates/selectable_template_sitewide.test.tsx
  yarn.lock
Labels: documentation, skip-changelog

#7675 [EuiRange]: Add conditional `aria-valuetext` when `ticks` prop is passed
  changelogs/upcoming/7675.md
  src-docs/src/views/range/range_example.js
  src-docs/src/views/range/ticks.tsx
  src/components/form/range/range.test.tsx
  src/components/form/range/range.tsx
  src/components/form/range/range_slider.tsx
  src/components/form/range/types.ts
Labels: feature request, accessibility, accessibility - screen reader

#7697 fix: `renderHook` imports
  scripts/jest/config.js
  src/components/datagrid/body/data_grid_row_manager.test.ts
  src/components/datagrid/utils/col_widths.test.ts
  src/components/datagrid/utils/ref.test.ts
  src/components/datagrid/utils/sorting.test.ts
  src/components/date_picker/super_date_picker/pretty_interval.test.ts
  src/components/markdown_editor/markdown_format.styles.test.ts
  src/components/progress/progress.styles.test.ts
  src/components/text/text.styles.test.ts
  src/components/title/title.styles.test.ts
  src/global_styling/mixins/_color.test.ts
  src/global_styling/mixins/_padding.test.ts
  src/global_styling/mixins/_responsive.test.ts
  src/global_styling/mixins/_states.test.ts
  src/global_styling/mixins/_typography.test.ts
  src/global_styling/utility/utility.test.ts
  src/services/hooks/useDeepEqual.test.ts
  src/themes/amsterdam/global_styling/mixins/button.test.ts
Labels: skip-changelog

#7693 [EuiCollapsibleNavBeta] `KibanaSolution` component
  src/components/collapsible_nav_beta/_kibana_solution/__snapshots__/collapsible_nav_kibana_solution.test.tsx.snap
  src/components/collapsible_nav_beta/_kibana_solution/collapsible_nav_kibana_solution.stories.tsx
  src/components/collapsible_nav_beta/_kibana_solution/collapsible_nav_kibana_solution.styles.ts
  src/components/collapsible_nav_beta/_kibana_solution/collapsible_nav_kibana_solution.test.tsx
  src/components/collapsible_nav_beta/_kibana_solution/collapsible_nav_kibana_solution.tsx
  src/components/collapsible_nav_beta/_kibana_solution/index.ts
  src/components/collapsible_nav_beta/collapsible_nav_beta.stories.tsx
  src/components/collapsible_nav_beta/collapsible_nav_beta.tsx
  src/components/collapsible_nav_beta/collapsible_nav_group/__snapshots__/collapsible_nav_group.test.tsx.snap
  src/components/collapsible_nav_beta/collapsible_nav_group/collapsible_nav_group.stories.tsx
  src/components/collapsible_nav_beta/collapsible_nav_group/collapsible_nav_group.styles.ts
  src/components/collapsible_nav_beta/collapsible_nav_group/collapsible_nav_group.test.tsx
  src/components/collapsible_nav_beta/collapsible_nav_group/collapsible_nav_group.tsx
  src/components/collapsible_nav_beta/collapsible_nav_item/collapsed/collapsed_nav_item.stories.tsx
  src/components/collapsible_nav_beta/collapsible_nav_item/collapsed/collapsed_nav_popover.tsx
  src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_item.stories.tsx
  src/components/popover/input_popover.spec.tsx
  src/components/popover/input_popover.tsx
Labels: skip-changelog

#7698 [EuiDataGrid] Fix column header move left focus bug
  changelogs/upcoming/7698.md
  src/components/datagrid/body/header/column_actions.test.tsx
  src/components/datagrid/body/header/column_actions.tsx
  src/components/datagrid/body/header/data_grid_header_cell.tsx
Labels: bug, data grid

#7696 [EuiAccordion] Update component logic to retain focus on `<button>` when clicked
  changelogs/upcoming/7696.md
  src/components/accordion/__snapshots__/accordion.test.tsx.snap
  src/components/accordion/accordion.spec.tsx
  src/components/accordion/accordion.test.tsx
  src/components/accordion/accordion.tsx
  src/components/accordion/accordion_children/accordion_children.tsx
  src/components/collapsible_nav/collapsible_nav_group/__snapshots__/collapsible_nav_group.test.tsx.snap
  src/components/collapsible_nav_beta/collapsible_nav_item/__snapshots__/collapsible_nav_accordion.test.tsx.snap
  src/components/collapsible_nav_beta/collapsible_nav_item/__snapshots__/collapsible_nav_item.test.tsx.snap
Labels: chore, accessibility, accessibility - WCAG A, accessibility - keyboard

#7701 [EuiDataGrid][CRA] Fix header cell focus when moving columns left/right
  changelogs/upcoming/7698.md
  src/components/datagrid/body/header/data_grid_header_cell_wrapper.tsx
Labels: bug, data grid, skip-changelog

#7707 [buildkite] Delete all but most recent 50 PR staging subdirs
  .buildkite/scripts/pipelines/pipeline_prune_staging_docs.sh
Labels: skip-changelog, infrastructure

#7674 [Storybook] Add stories for more components (letter P) - Part 2
  src/components/popover/input_popover.stories.tsx
  src/components/popover/popover.stories.tsx
  src/components/popover/popover.tsx
  src/components/popover/popover_footer.stories.tsx
  src/components/popover/popover_title.stories.tsx
  src/components/popover/wrapping_popover.stories.tsx
  src/components/portal/portal.stories.tsx
  src/components/progress/progress.stories.tsx
Labels: documentation, skip-changelog

#7687 [Storybook] Add stories for more components (letters R-S) - Part 1
  src/components/page_template/page_template.stories.tsx
  src/components/resizable_container/resizable_container.stories.tsx
  src/components/resizable_container/resizable_panel.stories.tsx
  src/components/responsive/show_for.stories.tsx
  src/components/search_bar/search_bar.stories.tsx
  src/components/search_bar/search_bar_filters.stories.tsx
  src/components/search_bar/search_filters.tsx
  src/components/side_nav/side_nav.stories.tsx
  src/components/spacer/spacer.stories.tsx
  src/components/stat/stat.stories.tsx
Labels: documentation, skip-changelog

#7713 [EuiTabbedContent] Fix error when updated with a completely new `tabs` prop
  changelogs/upcoming/7713.md
  src/components/tabs/tabbed_content/__snapshots__/tabbed_content.test.tsx.snap
  src/components/tabs/tabbed_content/tabbed_content.test.tsx
  src/components/tabs/tabbed_content/tabbed_content.tsx
Labels: community contribution

#7719 Fix `@storybook/test` - should be in `devDependencies`, not `dependencies`
  changelogs/upcoming/7719.md
  package.json
Labels: dependencies

#7721 [CI] Increase the # of kept PR staging docs to 100
  .buildkite/scripts/pipelines/pipeline_prune_staging_docs.sh
Labels: skip-changelog, infrastructure
