Repository elastic/eui, pull requests merged in 2025-06, with the labels that each got.

#8731 Upgrade and fix @elastic/charts in docs
  packages/docusaurus-theme/src/components/index.ts
  packages/docusaurus-theme/src/components/theme_context/index.tsx
  packages/website/package.json
  packages/website/src/theme/Root.tsx
  yarn.lock
Labels: documentation, skip-changelog

#8741 Add Emotion FAQ to docs
  packages/website/docs/getting-started/accessibility.mdx
  packages/website/docs/getting-started/working-with-emotion/_category_.yml
  packages/website/docs/getting-started/working-with-emotion/introduction.mdx
  packages/website/docs/getting-started/working-with-emotion/migrating-from-sass.mdx
Labels: documentation, skip-changelog

#8749 [Docs] Remove Docusaurus global focus outline styles
  packages/docusaurus-preset/src/index.ts
Labels: skip-changelog

#8766 [Changelog] Update #8725 changelogs
  packages/eui-theme-borealis/changelogs/upcoming/8725.md
  packages/eui/changelogs/upcoming/8725.md
Labels: skip-changelog

#8752 [Docs] Updated colors page with data vis contrast and usage guidance
  packages/website/docs/getting-started/theming/tokens/colors/index.mdx
Labels: documentation, skip-changelog, support-duty-flywheel

#8751 [Docs] Fixed form link on home page
  packages/website/src/components/homepage/highlights/index.tsx
Labels: documentation, skip-changelog

#8714 [Content] Adds relevant content guidelines and examples from obsolete files
  packages/website/docs/content/index.mdx
  packages/website/docs/content/language.mdx
  packages/website/docs/content/style.mdx
Labels: documentation, skip-changelog

#8768 [VRT] Update reference images after #8756
  packages/eui/.loki/reference/chrome_desktop_Display_EuiIconTip_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Display_EuiTour_EuiTourStep_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Display_EuiTour_EuiTour_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Editors_Syntax_EuiMarkdownEditor_View_Mode.png
  packages/eui/.loki/reference/chrome_desktop_Editors_Syntax_EuiMarkdownFormat_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiForm_EuiFormControlLayout_Append_Prepend.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiForm_EuiFormControlLayout_High_Contrast.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiForm_EuiFormControlLayout_High_Contrast_Dark_Mode.png
  packages/eui/.loki/reference/chrome_desktop_Layout_EuiResizableContainer_EuiResizableContainer_Collapsible_Panels.png
  packages/eui/.loki/reference/chrome_desktop_Layout_EuiResizableContainer_Subcomponents_EuiResizableCollapseButton_Production_Usage.png
  packages/eui/.loki/reference/chrome_desktop_Tabular_Content_EuiBasicTable_Expanded_Nested_Table.png
  packages/eui/.loki/reference/chrome_desktop_Tabular_Content_EuiBasicTable_Expanded_Row.png
  packages/eui/.loki/reference/chrome_desktop_Tabular_Content_EuiBasicTable_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Tabular_Content_EuiDataGrid_Custom_Header_Content.png
  packages/eui/.loki/reference/chrome_desktop_Tabular_Content_EuiDataGrid_Draggable_Columns.png
  packages/eui/.loki/reference/chrome_desktop_Tabular_Content_EuiDataGrid_toolbarVisibility_prop_Column_Sorting.png
  packages/eui/.loki/reference/chrome_desktop_Tabular_Content_EuiDataGrid_toolbarVisibility_prop_Display_Selector.png
  packages/eui/.loki/reference/chrome_desktop_Tabular_Content_EuiInMemoryTable_Kitchen_Sink.png
  packages/eui/.loki/reference/chrome_desktop_Tabular_Content_EuiTable_EuiTableHeader_EuiTableHeaderCell_Tooltip.png
  packages/eui/.loki/reference/chrome_mobile_Display_EuiIconTip_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Display_EuiTour_EuiTourStep_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Display_EuiTour_EuiTour_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Editors_Syntax_EuiMarkdownEditor_View_Mode.png
  packages/eui/.loki/reference/chrome_mobile_Editors_Syntax_EuiMarkdownFormat_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiForm_EuiFormControlLayout_Append_Prepend.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiForm_EuiFormControlLayout_High_Contrast.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiForm_EuiFormControlLayout_High_Contrast_Dark_Mode.png
  packages/eui/.loki/reference/chrome_mobile_Layout_EuiResizableContainer_EuiResizableContainer_Collapsible_Panels.png
  packages/eui/.loki/reference/chrome_mobile_Layout_EuiResizableContainer_Subcomponents_EuiResizableCollapseButton_Production_Usage.png
  packages/eui/.loki/reference/chrome_mobile_Tabular_Content_EuiDataGrid_Custom_Header_Content.png
  packages/eui/.loki/reference/chrome_mobile_Tabular_Content_EuiDataGrid_toolbarVisibility_prop_Column_Sorting.png
  packages/eui/.loki/reference/chrome_mobile_Tabular_Content_EuiDataGrid_toolbarVisibility_prop_Display_Selector.png
  packages/eui/.loki/reference/chrome_mobile_Tabular_Content_EuiInMemoryTable_Kitchen_Sink.png
  packages/eui/.loki/reference/chrome_mobile_Tabular_Content_EuiTable_EuiTableHeader_EuiTableHeaderCell_Tooltip.png
Labels: skip-changelog

#8759 chore: update pre-release link for breaking changes
  .github/config/label_commenter_config.yml
Labels: skip-changelog

#8794 [Amsterdam] Update values for `border-strong-*` tokens
  packages/eui/src/themes/amsterdam/_colors_dark.scss
  packages/eui/src/themes/amsterdam/_colors_light.scss
  packages/eui/src/themes/amsterdam/global_styling/variables/_colors.ts
  packages/eui/src/themes/json/eui_theme_amsterdam_dark.json
  packages/eui/src/themes/json/eui_theme_amsterdam_light.json
  packages/website/docs/getting-started/theming/tokens/colors/border_colors_table.tsx
Labels: skip-changelog, visual refresh

#8799 New buttons guidelines
  packages/website/docs/components/containers/_category_.yml
  packages/website/docs/components/navigation/buttons/_category_.yml
  packages/website/docs/components/navigation/buttons/button.mdx
  packages/website/docs/components/navigation/buttons/button_empty.svg
  packages/website/docs/components/navigation/buttons/button_left.svg
  packages/website/docs/components/navigation/buttons/button_placement.svg
  packages/website/docs/components/navigation/buttons/button_popover.svg
  packages/website/docs/components/navigation/buttons/button_right.svg
  packages/website/docs/components/navigation/buttons/button_table.svg
  packages/website/docs/components/navigation/buttons/button_types.svg
  packages/website/docs/components/navigation/buttons/button_types_bad.svg
  packages/website/docs/components/navigation/buttons/empty.mdx
  packages/website/docs/components/navigation/buttons/filter-group.mdx
  packages/website/docs/components/navigation/buttons/group.mdx
  packages/website/docs/components/navigation/buttons/guidelines.mdx
  packages/website/docs/components/navigation/buttons/icon.mdx
  packages/website/docs/components/navigation/buttons/img/button_apply.svg
  packages/website/docs/components/navigation/buttons/img/button_bar.svg
  packages/website/docs/components/navigation/buttons/img/button_empty.svg
  packages/website/docs/components/navigation/buttons/img/button_left.svg
  packages/website/docs/components/navigation/buttons/img/button_login.svg
  packages/website/docs/components/navigation/buttons/img/button_placement.svg
  packages/website/docs/components/navigation/buttons/img/button_popover.svg
  packages/website/docs/components/navigation/buttons/img/button_right.svg
  packages/website/docs/components/navigation/buttons/img/button_save.svg
  packages/website/docs/components/navigation/buttons/img/button_table.svg
  packages/website/docs/components/navigation/buttons/img/button_types.svg
  packages/website/docs/components/navigation/buttons/img/button_types_bad.svg
  packages/website/docs/components/navigation/buttons/img/button_wide.svg
  packages/website/docs/components/navigation/buttons/key-pad-menu.mdx
  packages/website/docs/components/navigation/buttons/patterns.mdx
Labels: skip-changelog

#8806 [Visual Refresh][EuiSelectableTemplateSitewide] Add `theme` prop
  packages/eui/.loki/reference/chrome_desktop_Layout_EuiHeader_EuiHeader_Dark_Theme_With_Sitewide_Search.png
  packages/eui/.loki/reference/chrome_desktop_Layout_EuiHeader_EuiHeader_Elastic_Navigation_Pattern.png
  packages/eui/changelogs/upcoming/8806.md
  packages/eui/src/components/header/header.stories.tsx
  packages/eui/src/components/header/header.styles.ts
  packages/eui/src/components/selectable/selectable_templates/__snapshots__/selectable_template_sitewide.test.tsx.snap
  packages/eui/src/components/selectable/selectable_templates/index.ts
  packages/eui/src/components/selectable/selectable_templates/selectable_template_sidewide.stories.tsx
  packages/eui/src/components/selectable/selectable_templates/selectable_template_sitewide.styles.ts
  packages/eui/src/components/selectable/selectable_templates/selectable_template_sitewide.tsx
  packages/eui/src/components/selectable/selectable_templates/selectable_template_sitewide_popover.tsx
  packages/website/docs/components/templates/sitewide-search/index.mdx
Labels: visual refresh

#8758 feat(eui): add tooltipProps prop to EuiCopy
  packages/eui/changelogs/upcoming/8758.md
  packages/eui/src/components/copy/copy.test.tsx
  packages/eui/src/components/copy/copy.tsx
  packages/website/docs/components/display/icons/index.mdx
  packages/website/docs/components/navigation/buttons/guidelines_context_menu.tsx
  packages/website/docs/components/navigation/context-menu.mdx
Labels: breaking change

#8757 feat(website): add a supported environments section
  packages/website/docs/getting-started/setup.mdx
Labels: skip-changelog, support-duty-flywheel

#8813 [Visual Refresh][EuiCode] Update background color
  packages/eui-theme-borealis/changelogs/upcoming/8813.md
  packages/eui-theme-borealis/src/variables/_components.ts
  packages/eui-theme-common/changelogs/upcoming/8813.md
  packages/eui-theme-common/src/global_styling/variables/components.ts
  packages/eui/.loki/reference/chrome_desktop_Editors_Syntax_EuiCode_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Editors_Syntax_EuiMarkdownFormat_High_Contrast.png
  packages/eui/.loki/reference/chrome_desktop_Editors_Syntax_EuiMarkdownFormat_Kitchen_Sink.png
  packages/eui/.loki/reference/chrome_desktop_Editors_Syntax_EuiMarkdownFormat_Text_Props.png
  packages/eui/.loki/reference/chrome_desktop_Forms_EuiComboBox_Custom_Matcher.png
  packages/eui/.loki/reference/chrome_desktop_Navigation_EuiCollapsibleNav_EuiCollapsibleNav_Full_Header_Pattern.png
  packages/eui/.loki/reference/chrome_desktop_Theming_EuiProvider_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Theming_EuiProvider_System_Defaults.png
  packages/eui/.loki/reference/chrome_desktop_Utilities_EuiInnerText_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Utilities_EuiResizeObserver_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Editors_Syntax_EuiCode_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Editors_Syntax_EuiMarkdownFormat_High_Contrast.png
  packages/eui/.loki/reference/chrome_mobile_Editors_Syntax_EuiMarkdownFormat_Kitchen_Sink.png
  packages/eui/.loki/reference/chrome_mobile_Editors_Syntax_EuiMarkdownFormat_Text_Props.png
  packages/eui/.loki/reference/chrome_mobile_Forms_EuiComboBox_Custom_Matcher.png
  packages/eui/.loki/reference/chrome_mobile_Theming_EuiProvider_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Theming_EuiProvider_System_Defaults.png
  packages/eui/.loki/reference/chrome_mobile_Utilities_EuiInnerText_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Utilities_EuiResizeObserver_Playground.png
  packages/eui/changelogs/upcoming/8813.md
  packages/eui/src/components/code/code.styles.ts
  packages/eui/src/components/code/code_syntax.styles.ts
  packages/eui/src/themes/amsterdam/global_styling/variables/_components.ts
Labels: visual refresh

#8807 [Docs] Fix page jump for Empty Prompt page
  packages/website/docs/components/display/empty-prompt/index.mdx
  packages/website/docs/components/tables/in-memory.mdx
Labels: documentation, skip-changelog, support-duty-flywheel

#8812 feat(eui): add noItemsMessage prop to EuiInMemoryTable
  packages/eui/changelogs/upcoming/8812.md
  packages/eui/src/components/basic_table/in_memory_table.stories.tsx
  packages/eui/src/components/basic_table/in_memory_table.test.tsx
  packages/eui/src/components/basic_table/in_memory_table.tsx
  packages/website/docs/components/tables/table_selection.tsx
Labels: support-duty-flywheel
