Repository elastic/eui, pull requests merged in 2025-08, with the labels that each got.

#8913 feat(website): add typography utilities documentation
  packages/website/docs/getting-started/theming/utilities/preview_utilities.tsx
  packages/website/docs/getting-started/theming/utilities/typography.mdx
Labels: skip-changelog, support-duty-flywheel

#8950 fix(EuiInputPopover): close popover on Tab, not Shift Tab
  packages/eui/changelogs/upcoming/8950.md
  packages/eui/src/components/form/range/types.ts
  packages/eui/src/components/popover/input_popover.spec.tsx
  packages/eui/src/components/popover/input_popover.stories.tsx
  packages/eui/src/components/popover/input_popover.tsx
Labels: accessibility, support-duty-flywheel

#8972 Convert most of the remaining Enzyme tests to RTL
  packages/eui/src/components/datagrid/body/cell/data_grid_cell_wrapper.test.tsx
  packages/eui/src/components/datagrid/body/data_grid_body_virtualized.test.tsx
  packages/eui/src/components/delay_hide/delay_hide.test.tsx
  packages/eui/src/components/expression/expression.test.tsx
  packages/eui/src/components/facet/facet_button.test.tsx
  packages/eui/src/components/flyout/__snapshots__/flyout.test.tsx.snap
  packages/eui/src/components/flyout/flyout.test.tsx
  packages/eui/src/components/form/checkbox/checkbox_group.behavior.test.tsx
  packages/eui/src/components/form/radio/radio_group.test.tsx
  packages/eui/src/components/header/header_breadcrumbs/header_breadcrumbs.test.tsx
  packages/eui/src/components/i18n/__snapshots__/i18n.test.tsx.snap
  packages/eui/src/components/i18n/i18n.test.tsx
  packages/eui/src/components/inner_text/inner_text.test.tsx
  packages/eui/src/components/key_pad_menu/key_pad_menu_item.test.tsx
  packages/eui/src/components/link/link.test.tsx
  packages/eui/src/components/modal/__snapshots__/confirm_modal.test.tsx.snap
  packages/eui/src/components/modal/confirm_modal.test.tsx
  packages/eui/src/components/observer/mutation_observer/mutation_observer.test.tsx
  packages/eui/src/components/observer/resize_observer/resize_observer.test.tsx
  packages/eui/src/components/outside_click_detector/outside_click_detector.test.tsx
  packages/eui/src/components/page/page_sidebar/page_sidebar.test.tsx
  packages/eui/src/components/provider/cache/__snapshots__/cache_provider.test.tsx.snap
  packages/eui/src/components/provider/cache/cache_provider.test.tsx
  packages/eui/src/components/resizable_container/resizable_container.test.tsx
  packages/eui/src/components/steps/step_horizontal.test.tsx
  packages/eui/src/components/tabs/__snapshots__/tab.test.tsx.snap
  packages/eui/src/components/tabs/tab.test.tsx
  packages/eui/src/components/toast/global_toast_list.test.tsx
  packages/eui/src/components/toast/toast.test.tsx
  packages/eui/src/components/tool_tip/tool_tip.test.tsx
Labels: testing, skip-changelog, tech debt

#8970 Fixes: #7824 : refactor(avatar,badge,color): centralize contrast warning via services util and add Avatar parity
  packages/eui/src/components/avatar/avatar.tsx
  packages/eui/src/components/badge/badge.tsx
  packages/eui/src/services/color/contrast.ts
Labels: skip-changelog, community contribution
