Repository elastic/eui, pull requests merged in 2025-02, with the labels that each got.

#8294 Fixing styles for `euiKeyPadMenu`
  packages/eui/src/components/key_pad_menu/key_pad_menu_item.styles.ts
Labels: skip-changelog

#8316 [Visual Refresh] Fix incorrect backgroundLight json tokens
  packages/eui-theme-borealis/src/eui_theme_borealis_light.json
  packages/eui/src-docs/src/views/theme/_json/eui_theme_borealis_light.json
Labels: skip-changelog, visual refresh

#8326 [EUI+] Adjust styles for `EuiHorizontalRule` snippets
  packages/website/docs/components/layout/horizontal_rule.mdx
Labels: skip-changelog

#8320 chore: update yarn to v4.6.0
  .yarn/releases/yarn-4.2.2.cjs
  .yarn/releases/yarn-4.6.0.cjs
  .yarnrc.yml
  package.json
  yarn.lock
Labels: skip-changelog

#8309 [EUI+] Add missing guidelines
  packages/website/docs/components/display/empty_prompt/guidelines.mdx
  packages/website/docs/components/display/empty_prompt/multiple_types.tsx
  packages/website/docs/components/display/empty_prompt/overview.mdx
  packages/website/docs/components/display/empty_prompt/types_of_empty_states/colors.tsx
  packages/website/docs/components/display/empty_prompt/types_of_empty_states/component.tsx
  packages/website/docs/components/display/empty_prompt/types_of_empty_states/empty_snippet.tsx
  packages/website/docs/components/display/empty_prompt/types_of_empty_states/index.ts
  packages/website/docs/components/display/empty_prompt/types_of_empty_states/multiple_snippet.tsx
  packages/website/docs/components/display/empty_prompt/types_of_empty_states/sidebar_snippet.tsx
  packages/website/docs/components/display/empty_prompt/types_of_empty_states/use_cases.tsx
  packages/website/docs/components/display/empty_prompt/types_of_empty_states/utils.ts
  packages/website/docs/components/display/toast/guidelines.mdx
  packages/website/docs/components/display/toast/overview.mdx
  packages/website/docs/components/display/tour/guidelines.mdx
  packages/website/docs/components/display/tour/tour_1_do.svg
  packages/website/docs/components/display/tour/tour_1_dont.svg
  packages/website/docs/components/display/tour/tour_6.gif
  packages/website/docs/components/forms/form_controls/guidelines.mdx
  packages/website/docs/components/forms/selection_controls/guidelines.mdx
  packages/website/docs/components/forms/selection_controls/single.svg
  packages/website/static/images/empty_prompt/accessDenied--dark.png
  packages/website/static/images/empty_prompt/accessDenied--light.png
  packages/website/static/images/empty_prompt/content_center.svg
  packages/website/static/images/empty_prompt/illustration.svg
  packages/website/static/images/empty_prompt/no-results--dark.svg
  packages/website/static/images/empty_prompt/no-results--light.svg
  packages/website/static/images/empty_prompt/pageNotFound--dark.png
  packages/website/static/images/empty_prompt/pageNotFound--dark@2x.png
  packages/website/static/images/empty_prompt/pageNotFound--light.png
  packages/website/static/images/empty_prompt/pageNotFound--light@2x.png
  packages/website/static/images/empty_prompt/side_nav.svg
  packages/website/static/images/empty_prompt/thumbnail_dark_empty_content.svg
  packages/website/static/images/empty_prompt/thumbnail_dark_page-empty.svg
  packages/website/static/images/empty_prompt/thumbnail_dark_page-multiple.svg
  packages/website/static/images/empty_prompt/thumbnail_dark_page-sidebar.svg
  packages/website/static/images/empty_prompt/thumbnail_footer-link.svg
  packages/website/static/images/empty_prompt/thumbnail_horizontal.svg
  packages/website/static/images/empty_prompt/thumbnail_icon-do.svg
  packages/website/static/images/empty_prompt/thumbnail_icon-dont.svg
  packages/website/static/images/empty_prompt/thumbnail_inline-link.svg
  packages/website/static/images/empty_prompt/thumbnail_light_empty_content.svg
  packages/website/static/images/empty_prompt/thumbnail_light_page-empty.svg
  packages/website/static/images/empty_prompt/thumbnail_light_page-multiple.svg
  packages/website/static/images/empty_prompt/thumbnail_light_page-sidebar.svg
  packages/website/static/images/empty_prompt/thumbnail_multiple-do.svg
  packages/website/static/images/empty_prompt/thumbnail_multiple-dont.svg
  packages/website/static/images/empty_prompt/thumbnail_vertical.svg
  packages/website/static/images/single.svg
Labels: skip-changelog

#8333 [EuiComboBox] Improve accessibility of virtualized listbox
  packages/eui/changelogs/upcoming/8333.md
  packages/eui/src/components/combo_box/__snapshots__/combo_box.test.tsx.snap
  packages/eui/src/components/combo_box/combo_box.stories.tsx
  packages/eui/src/components/combo_box/combo_box.tsx
  packages/eui/src/components/combo_box/combo_box_input/combo_box_input.tsx
  packages/eui/src/components/combo_box/combo_box_options_list/combo_box_options_list.tsx
  packages/eui/src/components/filter_group/__snapshots__/filter_select_item.test.tsx.snap
  packages/eui/src/components/filter_group/filter_select_item.tsx
  packages/eui/src/components/popover/popover.tsx
Labels: accessibility

#8343 [EuiBasicTable] Better document `columns.nameTooltip`
  packages/eui/src-docs/src/views/tables/basic/basic.tsx
  packages/eui/src-docs/src/views/tables/basic/basic_section.js
  packages/eui/src/components/basic_table/table_types.ts
  packages/website/docs/components/tabular_content/tables/basic_tables.mdx
Labels: skip-changelog

#8308 Add CLI for monorepo releases
  package.json
  packages/eui-docgen/package.json
  packages/release-cli/.gitignore
  packages/release-cli/package.json
  packages/release-cli/src/cli.ts
  packages/release-cli/src/errors.ts
  packages/release-cli/src/git_utils.ts
  packages/release-cli/src/index.ts
  packages/release-cli/src/logger.ts
  packages/release-cli/src/npm_utils.ts
  packages/release-cli/src/release.ts
  packages/release-cli/src/steps/build_packages.ts
  packages/release-cli/src/steps/check_workspaces.ts
  packages/release-cli/src/steps/init_checks.ts
  packages/release-cli/src/steps/publish.ts
  packages/release-cli/src/steps/run_pre_post_scripts.ts
  packages/release-cli/src/steps/update_versions.ts
  packages/release-cli/src/update_changelog.ts
  packages/release-cli/src/version.ts
  packages/release-cli/src/workspace.ts
  packages/release-cli/src/yarn_utils.ts
  packages/release-cli/tsconfig.json
  scripts/release.js
  yarn.lock
Labels: skip-changelog

#8372 feat(website): add Utilities > Beacon page
  packages/website/docs/components/utilities/beacon.mdx
Labels: skip-changelog

#8368 feat(website): add Utilities > Error Boundary page
  packages/website/docs/components/utilities/error_boundary.mdx
Labels: skip-changelog

#8367 feat(website): add Utilities > Highlight and Mark page
  packages/website/docs/components/utilities/highlight_and_mark.mdx
Labels: skip-changelog

#8365 feat(website): add Utilities > i18n page
  packages/website/docs/components/utilities/i18n.mdx
Labels: skip-changelog
