Repository elastic/eui, pull requests merged in 2025-07, with the labels that each got.

#8834 [EuiBasicTable][EuiDataGrid] Add marked row styling
  packages/eui-theme-borealis/changelogs/upcoming/8834.md
  packages/eui-theme-borealis/src/variables/_components.ts
  packages/eui-theme-common/changelogs/upcoming/8834.md
  packages/eui-theme-common/src/global_styling/variables/components.ts
  packages/eui/.loki/reference/chrome_desktop_Tabular_Content_EuiBasicTable_Marked_Row.png
  packages/eui/.loki/reference/chrome_desktop_Tabular_Content_EuiDataGrid_gridStyle_prop_Marked_Row.png
  packages/eui/.loki/reference/chrome_mobile_Tabular_Content_EuiBasicTable_Marked_Row.png
  packages/eui/.loki/reference/chrome_mobile_Tabular_Content_EuiDataGrid_gridStyle_prop_Marked_Row.png
  packages/eui/changelogs/upcoming/8834.md
  packages/eui/src/components/basic_table/basic_table.stories.tsx
  packages/eui/src/components/datagrid/body/cell/data_grid_cell.styles.ts
  packages/eui/src/components/datagrid/data_grid.styles.ts
  packages/eui/src/components/datagrid/data_grid_styles.stories.tsx
  packages/eui/src/components/table/table_row.styles.ts
  packages/eui/src/themes/amsterdam/global_styling/variables/_components.ts
  packages/website/docs/components/data-grid/style-and-display.mdx
  packages/website/docs/components/tables/basic.mdx
Labels: visual refresh

#8839 [EuiProgress][A11y] Announce determinate progress update to screen readers
  packages/eui/changelogs/upcoming/8839.md
  packages/eui/src/components/progress/__snapshots__/progress.test.tsx.snap
  packages/eui/src/components/progress/progress.stories.tsx
  packages/eui/src/components/progress/progress.tsx
Labels: accessibility

#8694 Fix i18ntokens generation
  packages/eui/i18ntokens.json
  packages/eui/i18ntokens_changelog.json
  packages/eui/package.json
  packages/eui/scripts/build_copy_assets.js
  packages/eui/scripts/build_i18ntokens.mjs
  packages/eui/scripts/compile-clean.js
  packages/eui/scripts/compile-eui.js
  packages/eui/scripts/compile-i18n-strings.js
  packages/eui/scripts/compile-scss.js
  packages/eui/scripts/i18ntokens/diff.mjs
  packages/eui/scripts/i18ntokens/traverse.mjs
  packages/eui/scripts/prerelease.mjs
  packages/eui/scripts/update-token-changelog.js
  yarn.lock
Labels: skip-changelog

#8852 [VRT] Add missing reference images for #8847
  packages/eui/.loki/reference/chrome_desktop_Layout_EuiFlyout_EuiFlyoutBody_Playground.png
  packages/eui/.loki/reference/chrome_desktop_Layout_EuiFlyout_EuiFlyoutChild_Child_Background_Styles.png
  packages/eui/.loki/reference/chrome_mobile_Layout_EuiFlyout_EuiFlyoutBody_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Layout_EuiFlyout_EuiFlyoutChild_Child_Background_Styles.png
  packages/eui/changelogs/upcoming/8847.md
Labels: skip-changelog

#8833 chore: build deployment folders for tags
  scripts/build_docs_versions.sh
Labels: skip-changelog

#8858 [Fix] Ensure correct file paths in `compile-icons`
  packages/eui/scripts/compile-icons.js
Labels: skip-changelog

#8856 [EuiProgress] Handle nodes in label prop
  packages/eui/changelogs/upcoming/8856.md
  packages/eui/src/components/progress/__snapshots__/progress.test.tsx.snap
  packages/eui/src/components/progress/progress.a11y.tsx
  packages/eui/src/components/progress/progress.test.tsx
  packages/eui/src/components/progress/progress.tsx
Labels: support-duty-flywheel

#8838 chore: deploy both to root and version subfolder
  .buildkite/scripts/pipelines/pipeline_deploy_new_docs.sh
  packages/website/package.json
Labels: skip-changelog

#8863 build: fix dts-generator directory paths
  packages/eui/scripts/compile-eui.js
Labels: skip-changelog

#8862 feat(docusaurus-theme): Support markdown tables
  packages/docusaurus-theme/src/theme/MDXComponents/Table.tsx
  packages/docusaurus-theme/src/theme/MDXComponents/TableBody.tsx
  packages/docusaurus-theme/src/theme/MDXComponents/TableDataCell.tsx
  packages/docusaurus-theme/src/theme/MDXComponents/TableHeader.tsx
  packages/docusaurus-theme/src/theme/MDXComponents/TableHeaderCell.tsx
  packages/docusaurus-theme/src/theme/MDXComponents/TableRow.tsx
  packages/docusaurus-theme/src/theme/MDXComponents/index.ts
  packages/website/docs/components/forms/selection/overview.mdx
  wiki/contributing-to-eui/documenting/writing-documentation.md
Labels: documentation, skip-changelog

#8870 [Wiki] Update local Kibana testing guide with missing information about `eui-theme-common`
  wiki/contributing-to-eui/testing/testing-in-kibana.md
Labels: skip-changelog, support-duty-flywheel

#8864 [EuiTreeView] Fix support for `css` key in Node
  packages/eui/changelogs/upcoming/8864.md
  packages/eui/src/components/tree_view/tree_view.stories.tsx
  packages/eui/src/components/tree_view/tree_view.tsx
Labels: support-duty-flywheel

#8890 chore: move changelog to eslint plugin
  packages/eslint-plugin/changelogs/upcoming/8888.md
Labels: skip-changelog

#8899 [Wiki] Update guideline for cloud deployments
  wiki/contributing-to-eui/testing/testing-in-kibana.md
Labels: skip-changelog

#8887 [EuiCodeBlock] Add accessible labels for virtualized code blocks
  packages/eui/changelogs/upcoming/8887.md
  packages/eui/src/components/code/__snapshots__/code_block.test.tsx.snap
  packages/eui/src/components/code/code_block.tsx
  packages/eui/src/components/code/code_block_virtualized.tsx
Labels: accessibility

#8901 fix(website): update the button icon to align with the guideline
  packages/website/docs/components/navigation/buttons/button.mdx
Labels: skip-changelog, support-duty-flywheel

#8905 fix(website): improve modal overview wording
  packages/website/docs/components/containers/modal/index.mdx
Labels: skip-changelog, support-duty-flywheel

#8908 feat(website): add a warning admonition for unique identifiers
  packages/website/docs/components/tables/basic.mdx
Labels: skip-changelog, support-duty-flywheel

#8917 chore(eui): improve EuiCallout `size` prop type
  packages/eui/src/components/call_out/call_out.tsx
Labels: skip-changelog, support-duty-flywheel

#8921 feat(website): move checkbox, radio and switch pages up
  packages/website/docs/components/forms/layouts/label.mdx
  packages/website/docs/components/forms/selection/basic-select.mdx
  packages/website/docs/components/forms/selection/checkbox-and-checkbox-group.mdx
  packages/website/docs/components/forms/selection/checkboxes-and-radios/index.mdx
  packages/website/docs/components/forms/selection/checkboxes-and-radios/switch.mdx
  packages/website/docs/components/forms/selection/combo-box.mdx
  packages/website/docs/components/forms/selection/guidelines.mdx
  packages/website/docs/components/forms/selection/overview.mdx
  packages/website/docs/components/forms/selection/radio-and-radio-group.mdx
  packages/website/docs/components/forms/selection/selectable.mdx
  packages/website/docs/components/forms/selection/super-select.mdx
  packages/website/docs/components/forms/selection/switch.mdx
Labels: skip-changelog
