Repository elastic/eui, pull requests merged in 2025-05, with the labels that each got.

#8675 docs: blockquotes in MDX / `border.radius.medium` info
  packages/docusaurus-theme/src/theme/MDXComponents/Blockquote.tsx
  packages/docusaurus-theme/src/theme/MDXComponents/index.ts
  packages/website/docs/getting-started/theming/tokens/borders/border_radii_table.tsx
  packages/website/docs/getting-started/theming/tokens/borders/border_widths_table.tsx
  packages/website/docs/getting-started/theming/tokens/borders/borders_table.tsx
  packages/website/docs/getting-started/theming/tokens/borders/index.mdx
Labels: skip-changelog

#8543 feat(docusaurus-theme): redirect to GH using types definition
  packages/docusaurus-theme/package.json
  packages/docusaurus-theme/src/components/demo/code_transformer.ts
  packages/docusaurus-theme/src/components/prop_table/prop_table.tsx
  packages/eui-docgen/package.json
  packages/eui-docgen/typedoc.json
  packages/eui-theme-common/src/global_styling/variables/typography.ts
  packages/eui-theme-common/src/services/theme/types.ts
  packages/eui/.storybook/main.ts
  packages/eui/changelogs/upcoming/8626.md
  packages/eui/src/components/basic_table/basic_table.tsx
  packages/eui/src/components/basic_table/in_memory_table.tsx
  packages/eui/src/components/basic_table/table_types.ts
  packages/eui/src/components/breadcrumbs/types.ts
  packages/eui/src/components/button/button_group/button_group.tsx
  packages/eui/src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_item.tsx
  packages/eui/src/components/color_picker/color_palette_display/color_palette_display.tsx
  packages/eui/src/components/color_picker/color_palette_picker/color_palette_picker.tsx
  packages/eui/src/components/combo_box/combo_box_options_list/combo_box_options_list.tsx
  packages/eui/src/components/comment_list/comment_list.tsx
  packages/eui/src/components/datagrid/data_grid_types.ts
  packages/eui/src/components/date_picker/super_date_picker/super_date_picker.tsx
  packages/eui/src/components/form/range/types.ts
  packages/eui/src/components/header/header.tsx
  packages/eui/src/components/key_pad_menu/key_pad_menu.tsx
  packages/eui/src/components/list_group/list_group.tsx
  packages/eui/src/components/list_group/list_group_item.tsx
  packages/eui/src/components/list_group/pinnable_list_group/pinnable_list_group.tsx
  packages/eui/src/components/loading/loading_spinner.tsx
  packages/eui/src/components/markdown_editor/plugins/markdown_default_plugins/parsing_plugins.ts
  packages/eui/src/components/popover/popover.tsx
  packages/eui/src/components/resizable_container/resizable_panel.tsx
  packages/eui/src/components/responsive/hide_for.tsx
  packages/eui/src/components/responsive/show_for.tsx
  packages/eui/src/components/search_bar/filters/field_value_selection_filter.tsx
  packages/eui/src/components/search_bar/filters/field_value_toggle_group_filter.tsx
  packages/eui/src/components/search_bar/search_bar.tsx
  packages/eui/src/components/selectable/selectable.tsx
  packages/eui/src/components/selectable/selectable_templates/selectable_template_sitewide.tsx
  packages/eui/src/components/selectable/selectable_templates/selectable_template_sitewide_option.tsx
  packages/eui/src/components/side_nav/side_nav.tsx
  packages/eui/src/components/table/table_row_cell.tsx
  packages/eui/src/components/timeline/timeline.tsx
  packages/eui/typedoc.json
  yarn.lock
Labels: skip-changelog

#8683 Removed writing guidelines from docs
  packages/website/docs/content/index.mdx
  packages/website/docs/content/writing/_category_.yml
  packages/website/docs/content/writing/examples.mdx
  packages/website/docs/content/writing/guidelines.mdx
  packages/website/docs/getting-started/theming/tokens/colors/_forced_colors_warning.mdx
  packages/website/docs/patterns/save-buttons.mdx
Labels: documentation, skip-changelog

#8686 [EuiSuperDatePicker] Improve a11y of quick select `Next/Previous time window` buttons
  packages/eui/changelogs/upcoming/8686.md
  packages/eui/src/components/date_picker/super_date_picker/quick_select_popover/quick_select.tsx
Labels: accessibility

#8687 Update secondary icon fill to match brand
  packages/eui/.loki/reference/chrome_desktop_Navigation_EuiKeyPadMenu_EuiKeyPadMenu_Checkable_Multi.png
  packages/eui/.loki/reference/chrome_desktop_Navigation_EuiKeyPadMenu_EuiKeyPadMenu_Checkable_Single.png
  packages/eui/.loki/reference/chrome_desktop_Navigation_EuiKeyPadMenu_EuiKeyPadMenu_High_Contrast.png
  packages/eui/.loki/reference/chrome_desktop_Navigation_EuiKeyPadMenu_EuiKeyPadMenu_Playground.png
  packages/eui/.loki/reference/chrome_mobile_Navigation_EuiKeyPadMenu_EuiKeyPadMenu_Checkable_Multi.png
  packages/eui/.loki/reference/chrome_mobile_Navigation_EuiKeyPadMenu_EuiKeyPadMenu_Checkable_Single.png
  packages/eui/.loki/reference/chrome_mobile_Navigation_EuiKeyPadMenu_EuiKeyPadMenu_High_Contrast.png
  packages/eui/.loki/reference/chrome_mobile_Navigation_EuiKeyPadMenu_EuiKeyPadMenu_Playground.png
  packages/eui/changelogs/upcoming/8687.md
  packages/eui/src/components/icon/icon.styles.ts
Labels: design decision, icons

#8688 [EuiDataGrid] Pass scroll position data as args in onScroll
  packages/eui/changelogs/upcoming/8688.md
  packages/eui/src/components/datagrid/body/data_grid_body_virtualized.test.tsx
  packages/eui/src/components/datagrid/body/data_grid_body_virtualized.tsx
  packages/eui/src/components/datagrid/data_grid.stories.tsx
  packages/eui/src/components/datagrid/data_grid_types.ts
  packages/website/docs/components/tabular-content/data-grid/container-constraints.mdx
Labels: data grid

#8676 Added Images to writing-documentation.md
  wiki/contributing-to-eui/documenting/writing-documentation.md
Labels: skip-changelog

#8712 docs: fix typo in eui token docs
  packages/website/docs/components/display/icons/index.mdx
Labels: skip-changelog

#8709 Update running-eui-locally.md
  wiki/contributing-to-eui/running-eui-locally.md
Labels: documentation, skip-changelog, support-duty-flywheel

#8716 [EuiFlyout] Support `returnFocus` prop
  packages/eui/.loki/reference/chrome_desktop_Layout_EuiFlyout_EuiFlyout_Manual_Return_Focus.png
  packages/eui/.loki/reference/chrome_mobile_Layout_EuiFlyout_EuiFlyout_Manual_Return_Focus.png
  packages/eui/changelogs/upcoming/8716.md
  packages/eui/src/components/flyout/flyout.spec.tsx
  packages/eui/src/components/flyout/flyout.stories.tsx
  packages/eui/src/components/flyout/flyout.tsx
Labels: accessibility

#8726 [Wiki] Update local testing documentation
  wiki/contributing-to-eui/testing/testing-in-kibana.md
Labels: skip-changelog
